// huffman_data.s — Generated by huff_encoder.py
// Source: data/insult_strings.txt
// 15 strings, 367 bytes uncompressed
// 204 bytes compressed (55.6%)
// Tree: 52 bytes, Index: 30 bytes
// Total data: 286 bytes

.const HUFF_STR_COUNT = 15

// Huffman tree: 26 internal nodes
// Children: $00-$7E = node index, $80+ = leaf (& $7F = screencode)
huff_tree_left:
    .byte $01, $03, $05, $07, $08, $0a, $a0, $8e, $85, $0e, $8f, $10, $94, $13, $97, $15, $84, $93, $99, $bf, $82, $17, $a1, $ac, $83, $90
huff_tree_right:
    .byte $02, $04, $06, $81, $09, $0b, $0c, $0d, $88, $89, $0f, $11, $12, $87, $14, $95, $16, $92, $80, $96, $8d, $ae, $18, $19, $8c, $8b

// String index: 16-bit byte offsets into huff_str_data
huff_str_index:
    .word $0000  // [0] "YOU WILL HAVE TO DO BETTER THA"
    .word $0014  // [1] "THAT IS AN INSULT!"
    .word $001e  // [2] "DO YOU WISH TO DO BUSINESS OR "
    .word $0031  // [3] "HAH! TRY AGAIN."
    .word $003a  // [4] "RIDICULOUS!"
    .word $0042  // [5] "YOU HAVE GOT TO BE KIDDING!"
    .word $0052  // [6] "YOU HAD BETTER BE KIDDING!"
    .word $0062  // [7] "YOU TRY MY PATIENCE."
    .word $006f  // [8] "I DO NOT HEAR YOU."
    .word $0079  // [9] "HMMM, NICE WEATHER WE ARE HAVI"
    .word $008c  // [10] "I MUST HAVE HEARD YOU WRONG."
    .word $009c  // [11] "WHAT WAS THAT?"
    .word $00a4  // [12] "I AM SORRY, SAY THAT AGAIN."
    .word $00b3  // [13] "WHAT DID YOU SAY?"
    .word $00bd  // [14] "SORRY, WHAT WAS THAT AGAIN?"

// Compressed string data (204 bytes)
huff_str_data:
    // [0] "YOU WILL HAVE TO DO BETTER THAN THAT!" (38→20 bytes)
    .byte $f4, $4f, $31, $eb, $d7, $ca, $45, $4d, $d1, $a9, $19, $a4, $ee, $4b, $ee, $52, $1b, $94, $f5, $5f
    // [1] "THAT IS AN INSULT!" (19→10 bytes)
    .byte $e5, $3d, $9e, $d8, $86, $70, $b4, $eb, $f5, $5f
    // [2] "DO YOU WISH TO DO BUSINESS OR NOT?" (35→19 bytes)
    .byte $a4, $6f, $44, $f3, $1e, $cb, $ba, $35, $23, $35, $3b, $38, $25, $ad, $a2, $f8, $23, $84, $f8
    // [3] "HAH! TRY AGAIN." (16→9 bytes)
    .byte $52, $b5, $6e, $bf, $b1, $19, $70, $97, $e0
    // [4] "RIDICULOUS!" (12→8 bytes)
    .byte $bb, $d1, $eb, $4e, $bc, $4e, $d5, $7c
    // [5] "YOU HAVE GOT TO BE KIDDING!" (28→16 bytes)
    .byte $f4, $4f, $29, $15, $30, $e3, $b7, $46, $69, $34, $9b, $d2, $8e, $03, $ab, $e0
    // [6] "YOU HAD BETTER BE KIDDING!" (27→16 bytes)
    .byte $f4, $4f, $29, $a6, $69, $3b, $92, $f9, $a4, $d2, $6f, $4a, $38, $0e, $af, $80
    // [7] "YOU TRY MY PATIENCE." (21→13 bytes)
    .byte $f4, $4f, $75, $fd, $9b, $f6, $92, $3c, $e8, $15, $92, $5f, $80
    // [8] "I DO NOT HEAR YOU." (19→10 bytes)
    .byte $7d, $48, $c1, $1d, $95, $0d, $f7, $a2, $72, $fc
    // [9] "HMMM, NICE WEATHER WE ARE HAVING." (34→19 bytes)
    .byte $56, $db, $6e, $46, $07, $ac, $99, $88, $79, $52, $f9, $89, $8d, $d3, $29, $15, $c0, $72, $fc
    // [10] "I MUST HAVE HEARD YOU WRONG." (29→16 bytes)
    .byte $7c, $dc, $ed, $d9, $48, $a9, $95, $0d, $e9, $bd, $13, $cc, $bc, $00, $e5, $f8
    // [11] "WHAT WAS THAT?" (15→8 bytes)
    .byte $62, $9e, $cc, $36, $dc, $a7, $84, $f8
    // [12] "I AM SORRY, SAY THAT AGAIN." (28→15 bytes)
    .byte $7c, $5b, $d6, $8b, $df, $d2, $35, $8f, $b7, $29, $ec, $46, $5c, $25, $f8
    // [13] "WHAT DID YOU SAY?" (18→10 bytes)
    .byte $62, $9e, $d4, $7a, $6f, $44, $f5, $8f, $84, $f8
    // [14] "SORRY, WHAT WAS THAT AGAIN?" (28→15 bytes)
    .byte $b4, $5e, $fe, $91, $98, $a7, $b3, $0d, $b7, $29, $ec, $46, $5c, $04, $f8

// Huffman code table:
//   NULL   =        11111 (5 bits, freq=15)
//   A      =          001 (3 bits, freq=32)
//   B      =       011010 (6 bits, freq=5)
//   C      =      1010110 (7 bits, freq=3)
//   D      =        10100 (5 bits, freq=13)
//   E      =         0100 (4 bits, freq=19)
//   G      =        00011 (5 bits, freq=8)
//   H      =         0101 (4 bits, freq=21)
//   I      =         0111 (4 bits, freq=21)
//   K      =     10010011 (8 bits, freq=2)
//   L      =      1010111 (7 bits, freq=4)
//   M      =       011011 (6 bits, freq=6)
//   N      =         0000 (4 bits, freq=15)
//   O      =         1000 (4 bits, freq=23)
//   P      =     10010010 (8 bits, freq=1)
//   R      =        10111 (5 bits, freq=15)
//   S      =        10110 (5 bits, freq=14)
//   T      =         1110 (4 bits, freq=30)
//   U      =        10011 (5 bits, freq=13)
//   V      =       000101 (6 bits, freq=4)
//   W      =        01100 (5 bits, freq=10)
//   Y      =        11110 (5 bits, freq=15)
//   SPACE  =          110 (3 bits, freq=59)
//   $21    =       101010 (6 bits, freq=6)
//   $2c    =      1001000 (7 bits, freq=3)
//   $2e    =       100101 (6 bits, freq=6)
//   $3f    =       000100 (6 bits, freq=4)
