// Tier 1 (Shallow) — creature data
// Generated by parse_creatures.py — DO NOT EDIT
// 24 creatures, dlvl 1-8
//
// Creature index map (tier-local → name):
//     0: [ 16] DL 1 Kobold
//     1: [ 17] DL 1 White Worm mass
//     2: [ 18] DL 1 Floating Eye
//     3: [ 24] DL 2 Novice Priest
//     4: [ 25] DL 2 Novice Mage
//     5: [ 29] DL 2 Giant Black Ant
//     6: [ 34] DL 3 Poltergeist
//     7: [ 37] DL 3 Black Naga
//     8: [ 39] DL 3 Yellow Jelly
//     9: [ 52] DL 4 Creeping Copper Coins
//    10: [ 56] DL 4 Blue Worm mass
//    11: [ 58] DL 4 Jackal
//    12: [ 59] DL 5 Green Naga
//    13: [ 61] DL 5 White Mushroom patch
//    14: [ 63] DL 5 Skeleton Kobold
//    15: [ 74] DL 6 Brown Mold
//    16: [ 77] DL 6 Orc
//    17: [ 80] DL 6 Rattlesnake
//    18: [ 81] DL 7 Bloodshot Eye
//    19: [ 86] DL 7 Zombie Kobold
//    20: [ 87] DL 7 Lost Soul
//    21: [ 91] DL 8 Green Mold
//    22: [ 92] DL 8 Skeleton Orc
//    23: [ 95] DL 8 Bandit

.const TIER_COUNT = 24
.const TIER_MIN_DLVL = 1
.const TIER_MAX_DLVL = 8

// Display character (screen code)
tier1_cr_display:
    .byte $0b, $17, $05, $10, $10, $01, $07, $0e, $0a, $24, $17, $0a, $0e, $2c, $13, $0d
    .byte $0f, $12, $05, $1a, $07, $0d, $13, $10

// Color code
tier1_cr_color:
    .byte $01, $01, $01, $01, $01, $0b, $01, $0b, $07, $07, $06, $01, $05, $01, $0f, $09
    .byte $09, $01, $01, $0f, $01, $05, $0f, $03

// Speed (0=slow, 1=normal, 2=fast)
tier1_cr_speed:
    .byte $01, $00, $01, $01, $01, $01, $02, $01, $02, $00, $00, $01, $01, $01, $01, $01
    .byte $01, $01, $01, $01, $01, $01, $01, $01

// Monster flags
tier1_cr_mflags:
    .byte $00, $00, $01, $00, $00, $00, $06, $00, $01, $00, $00, $00, $00, $01, $02, $01
    .byte $00, $00, $01, $02, $06, $01, $02, $00

// Dungeon level
tier1_cr_level:
    .byte $01, $01, $01, $02, $02, $02, $03, $03, $03, $04, $04, $04, $05, $05, $05, $06
    .byte $06, $06, $07, $07, $07, $08, $08, $08

// Hit dice count
tier1_cr_hd_num:
    .byte $03, $04, $03, $07, $06, $03, $02, $06, $0a, $07, $05, $03, $09, $01, $05, $0f
    .byte $09, $06, $04, $06, $02, $15, $0a, $08

// Hit dice sides
tier1_cr_hd_sides:
    .byte $07, $04, $06, $04, $04, $06, $05, $08, $08, $08, $08, $08, $08, $01, $08, $08
    .byte $08, $07, $08, $08, $08, $08, $08, $08

// Armor class
tier1_cr_ac:
    .byte $10, $01, $06, $0a, $06, $14, $0f, $28, $01, $18, $0c, $10, $28, $01, $1a, $0c
    .byte $20, $18, $06, $0e, $0a, $0e, $24, $18

// Sleep counter
tier1_cr_sleep:
    .byte $0a, $0a, $0a, $05, $05, $50, $0a, $78, $63, $0a, $0a, $1e, $78, $00, $28, $63
    .byte $1e, $01, $0a, $1e, $0a, $4b, $28, $0a

// Area affect radius
tier1_cr_aaf:
    .byte $14, $07, $02, $14, $14, $08, $08, $10, $02, $03, $07, $0c, $12, $02, $14, $02
    .byte $14, $06, $02, $14, $0c, $02, $14, $14

// XP low byte
tier1_cr_xp_lo:
    .byte $05, $02, $01, $07, $07, $08, $06, $14, $0c, $09, $05, $08, $1e, $05, $0c, $14
    .byte $10, $14, $0f, $0e, $12, $1c, $1a, $1a

// XP high byte
tier1_cr_xp_hi:
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00

// Attack 0 type
tier1_cr_atk0_type:
    .byte $00, $01, $02, $00, $00, $00, $03, $00, $01, $00, $0b, $00, $00, $02, $00, $04
    .byte $00, $01, $07, $00, $00, $03, $00, $00

// Attack 0 dice count
tier1_cr_atk0_dice:
    .byte $01, $01, $00, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $02, $01, $01
    .byte $01, $02, $02, $01, $02, $01, $02, $02

// Attack 0 dice sides
tier1_cr_atk0_sides:
    .byte $06, $02, $00, $05, $04, $04, $01, $08, $03, $04, $04, $06, $08, $04, $06, $04
    .byte $08, $05, $06, $02, $02, $04, $05, $04

// Attack 1 type
tier1_cr_atk1_type:
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $01, $00, $00, $05, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $08

// Attack 1 dice count
tier1_cr_atk1_dice:
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $02, $00, $00, $02, $00, $00, $00
    .byte $00, $00, $00, $01, $00, $00, $00, $00

// Attack 1 dice sides
tier1_cr_atk1_sides:
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $04, $00, $00, $06, $00, $00, $00
    .byte $00, $00, $00, $02, $00, $00, $00, $00

// Spell chance (0-100)
tier1_cr_spell_chance:
    .byte $00, $00, $07, $08, $08, $00, $06, $00, $06, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $0e, $00, $06, $00, $00, $00

// Spell flags bitmask
tier1_cr_spell_flags:
    .byte $00, $00, $00, $81, $21, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00

// Name string pointers
tier1_cr_name_lo:
    .byte <tier1_crn_0, <tier1_crn_1, <tier1_crn_2, <tier1_crn_3, <tier1_crn_4, <tier1_crn_5, <tier1_crn_6, <tier1_crn_7
    .byte <tier1_crn_8, <tier1_crn_9, <tier1_crn_10, <tier1_crn_11, <tier1_crn_12, <tier1_crn_13, <tier1_crn_14, <tier1_crn_15
    .byte <tier1_crn_16, <tier1_crn_17, <tier1_crn_18, <tier1_crn_19, <tier1_crn_20, <tier1_crn_21, <tier1_crn_22, <tier1_crn_23
tier1_cr_name_hi:
    .byte >tier1_crn_0, >tier1_crn_1, >tier1_crn_2, >tier1_crn_3, >tier1_crn_4, >tier1_crn_5, >tier1_crn_6, >tier1_crn_7
    .byte >tier1_crn_8, >tier1_crn_9, >tier1_crn_10, >tier1_crn_11, >tier1_crn_12, >tier1_crn_13, >tier1_crn_14, >tier1_crn_15
    .byte >tier1_crn_16, >tier1_crn_17, >tier1_crn_18, >tier1_crn_19, >tier1_crn_20, >tier1_crn_21, >tier1_crn_22, >tier1_crn_23

.encoding "screencode_upper"
// Name strings (screen codes, null-terminated)
tier1_crn_0: .text "KOBOLD" ; .byte 0
tier1_crn_1: .text "WHITE WORM MASS" ; .byte 0
tier1_crn_2: .text "FLOATING EYE" ; .byte 0
tier1_crn_3: .text "NOVICE PRIEST" ; .byte 0
tier1_crn_4: .text "NOVICE MAGE" ; .byte 0
tier1_crn_5: .text "GIANT BLACK ANT" ; .byte 0
tier1_crn_6: .text "POLTERGEIST" ; .byte 0
tier1_crn_7: .text "BLACK NAGA" ; .byte 0
tier1_crn_8: .text "YELLOW JELLY" ; .byte 0
tier1_crn_9: .text "CREEPING COPPER COINS" ; .byte 0
tier1_crn_10: .text "BLUE WORM MASS" ; .byte 0
tier1_crn_11: .text "JACKAL" ; .byte 0
tier1_crn_12: .text "GREEN NAGA" ; .byte 0
tier1_crn_13: .text "WHITE MUSHROOM PATCH" ; .byte 0
tier1_crn_14: .text "SKELETON KOBOLD" ; .byte 0
tier1_crn_15: .text "BROWN MOLD" ; .byte 0
tier1_crn_16: .text "ORC" ; .byte 0
tier1_crn_17: .text "RATTLESNAKE" ; .byte 0
tier1_crn_18: .text "BLOODSHOT EYE" ; .byte 0
tier1_crn_19: .text "ZOMBIE KOBOLD" ; .byte 0
tier1_crn_20: .text "LOST SOUL" ; .byte 0
tier1_crn_21: .text "GREEN MOLD" ; .byte 0
tier1_crn_22: .text "SKELETON ORC" ; .byte 0
tier1_crn_23: .text "BANDIT" ; .byte 0

// End marker for size calculation
tier1_data_end:
.print "Tier 1 (Shallow): " + (tier1_data_end - tier1_cr_display) + " bytes"
