// Tier 0 (Town) — creature data
// Generated by parse_creatures.py — DO NOT EDIT
// 8 creatures, dlvl 0-0
//
// Creature index map (tier-local → name):
//     0: [  0] DL 0 Filthy Street Urchin
//     1: [  1] DL 0 Blubbering Idiot
//     2: [  2] DL 0 Pitiful-Looking Beggar
//     3: [  3] DL 0 Mangy-Looking Leper
//     4: [  4] DL 0 Squint-Eyed Rogue
//     5: [  5] DL 0 Singing, Happy Drunk
//     6: [  6] DL 0 Mean-Looking Mercenary
//     7: [  7] DL 0 Battle-Scarred Veteran

.const TIER_COUNT = 8
.const TIER_MIN_DLVL = 0
.const TIER_MAX_DLVL = 0

// Display character (screen code)
tier0_cr_display:
    .byte $10, $10, $10, $10, $10, $10, $10, $10

// Color code
tier0_cr_color:
    .byte $0f, $0f, $0f, $0f, $03, $0f, $03, $02

// Speed (0=slow, 1=normal, 2=fast)
tier0_cr_speed:
    .byte $01, $01, $01, $01, $01, $01, $01, $01

// Monster flags
tier0_cr_mflags:
    .byte $0c, $08, $08, $08, $0c, $08, $0c, $08

// Dungeon level
tier0_cr_level:
    .byte $00, $00, $00, $00, $00, $00, $00, $00

// Hit dice count
tier0_cr_hd_num:
    .byte $01, $01, $01, $01, $02, $02, $05, $07

// Hit dice sides
tier0_cr_hd_sides:
    .byte $04, $02, $04, $01, $08, $03, $08, $08

// Armor class
tier0_cr_ac:
    .byte $01, $01, $01, $01, $08, $01, $14, $1e

// Sleep counter
tier0_cr_sleep:
    .byte $28, $00, $28, $32, $63, $00, $fa, $fa

// Area affect radius
tier0_cr_aaf:
    .byte $04, $06, $0a, $0a, $0a, $0a, $0a, $0a

// XP low byte
tier0_cr_xp_lo:
    .byte $00, $00, $00, $00, $00, $00, $00, $00

// XP high byte
tier0_cr_xp_hi:
    .byte $00, $00, $00, $00, $00, $00, $00, $00

// Attack 0 type
tier0_cr_atk0_type:
    .byte $01, $01, $01, $01, $01, $01, $01, $01

// Attack 0 dice count
tier0_cr_atk0_dice:
    .byte $00, $00, $00, $00, $01, $00, $01, $02

// Attack 0 dice sides
tier0_cr_atk0_sides:
    .byte $00, $00, $00, $00, $06, $00, $0a, $06

// Attack 1 type
tier0_cr_atk1_type:
    .byte $01, $00, $00, $00, $01, $00, $00, $00

// Attack 1 dice count
tier0_cr_atk1_dice:
    .byte $00, $00, $00, $00, $00, $00, $00, $00

// Attack 1 dice sides
tier0_cr_atk1_sides:
    .byte $00, $00, $00, $00, $00, $00, $00, $00

// Spell chance (0-100)
tier0_cr_spell_chance:
    .byte $00, $00, $00, $00, $00, $00, $00, $00

// Spell flags bitmask
tier0_cr_spell_flags:
    .byte $00, $00, $00, $00, $00, $00, $00, $00

// Name string pointers
tier0_cr_name_lo:
    .byte <tier0_crn_0, <tier0_crn_1, <tier0_crn_2, <tier0_crn_3, <tier0_crn_4, <tier0_crn_5, <tier0_crn_6, <tier0_crn_7
tier0_cr_name_hi:
    .byte >tier0_crn_0, >tier0_crn_1, >tier0_crn_2, >tier0_crn_3, >tier0_crn_4, >tier0_crn_5, >tier0_crn_6, >tier0_crn_7

.encoding "screencode_upper"
// Name strings (screen codes, null-terminated)
tier0_crn_0: .text "FILTHY STREET URCHIN" ; .byte 0
tier0_crn_1: .text "BLUBBERING IDIOT" ; .byte 0
tier0_crn_2: .text "PITIFUL-LOOKING BEGGAR" ; .byte 0
tier0_crn_3: .text "MANGY-LOOKING LEPER" ; .byte 0
tier0_crn_4: .text "SQUINT-EYED ROGUE" ; .byte 0
tier0_crn_5: .text "SINGING, HAPPY DRUNK" ; .byte 0
tier0_crn_6: .text "MEAN-LOOKING MERCENARY" ; .byte 0
tier0_crn_7: .text "BATTLE-SCARRED VETERAN" ; .byte 0

// End marker for size calculation
tier0_data_end:
.print "Tier 0 (Town): " + (tier0_data_end - tier0_cr_display) + " bytes"
