// Tier 2 (Early) — creature data
// Generated by parse_creatures.py — DO NOT EDIT
// 32 creatures, dlvl 5-15
//
// Creature index map (tier-local → name):
//     0: [ 59] DL 5 Green Naga
//     1: [ 61] DL 5 White Mushroom patch
//     2: [ 63] DL 5 Skeleton Kobold
//     3: [ 74] DL 6 Brown Mold
//     4: [ 77] DL 6 Orc
//     5: [ 80] DL 6 Rattlesnake
//     6: [ 81] DL 7 Bloodshot Eye
//     7: [ 86] DL 7 Zombie Kobold
//     8: [ 87] DL 7 Lost Soul
//     9: [ 91] DL 8 Green Mold
//    10: [ 92] DL 8 Skeleton Orc
//    11: [ 95] DL 8 Bandit
//    12: [102] DL 9 Orc Shaman
//    13: [103] DL 9 Giant Red Ant
//    14: [104] DL 9 King Cobra
//    15: [106] DL10 Giant White Tick
//    16: [108] DL10 Disenchanter Mold
//    17: [110] DL10 Creeping Gold Coins
//    18: [113] DL11 Orc Zombie
//    19: [116] DL11 Nasty Little Gnome
//    20: [117] DL11 Hobgoblin
//    21: [118] DL12 Black Mamba
//    22: [121] DL12 Priest
//    23: [124] DL12 Skeleton Human
//    24: [129] DL13 Ogre
//    25: [131] DL13 Magic User
//    26: [132] DL13 Black Orc
//    27: [137] DL14 Giant White Dragon Fly
//    28: [138] DL14 Hill Giant
//    29: [140] DL14 Flesh Golem
//    30: [148] DL15 Frost Giant
//    31: [152] DL15 Violet Mold

.const TIER_COUNT = 32
.const TIER_MIN_DLVL = 5
.const TIER_MAX_DLVL = 15

// Display character (screen code)
tier2_cr_display:
    .byte $0e, $2c, $13, $0d, $0f, $12, $05, $1a, $07, $0d, $13, $10, $0f, $01, $12, $14
    .byte $0d, $24, $1a, $10, $08, $12, $10, $13, $0f, $10, $0f, $06, $10, $07, $10, $0d

// Color code
tier2_cr_color:
    .byte $05, $01, $0f, $09, $09, $01, $01, $0f, $01, $05, $0f, $03, $09, $02, $01, $01
    .byte $0d, $07, $0f, $01, $01, $0b, $03, $0f, $05, $01, $0b, $01, $01, $0c, $01, $04

// Speed (0=slow, 1=normal, 2=fast)
tier2_cr_speed:
    .byte $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $00
    .byte $01, $00, $01, $01, $01, $02, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01

// Monster flags
tier2_cr_mflags:
    .byte $04, $41, $26, $41, $2c, $18, $01, $26, $06, $41, $26, $2c, $2c, $10, $18, $10
    .byte $41, $00, $26, $0c, $2c, $18, $08, $26, $0c, $08, $2c, $10, $0c, $08, $04, $41

// Dungeon level
tier2_cr_level:
    .byte $05, $05, $05, $06, $06, $06, $07, $07, $07, $08, $08, $08, $09, $09, $09, $0a
    .byte $0a, $0a, $0b, $0b, $0b, $0c, $0c, $0c, $0d, $0d, $0d, $0e, $0e, $0e, $0f, $0f

// Hit dice count
tier2_cr_hd_num:
    .byte $09, $01, $05, $0f, $09, $06, $04, $06, $02, $15, $0a, $08, $07, $04, $08, $0f
    .byte $10, $12, $0b, $04, $0c, $0a, $07, $0c, $0d, $07, $0c, $05, $10, $0c, $11, $11

// Hit dice sides
tier2_cr_hd_sides:
    .byte $08, $01, $08, $08, $08, $07, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08
    .byte $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08

// Armor class
tier2_cr_ac:
    .byte $28, $01, $1a, $0c, $20, $18, $06, $0e, $0a, $0e, $24, $18, $0f, $22, $1e, $28
    .byte $14, $24, $18, $0a, $26, $20, $16, $1e, $20, $0a, $24, $14, $24, $0a, $26, $0f

// Sleep counter
tier2_cr_sleep:
    .byte $78, $00, $28, $63, $1e, $01, $0a, $1e, $0a, $4b, $28, $0a, $14, $3c, $01, $14
    .byte $46, $0a, $19, $0a, $1e, $01, $28, $1e, $1e, $0a, $14, $32, $32, $0a, $32, $46

// Area affect radius
tier2_cr_aaf:
    .byte $12, $02, $14, $02, $14, $06, $02, $14, $0c, $02, $14, $14, $14, $0c, $08, $0c
    .byte $02, $05, $14, $12, $14, $0a, $14, $14, $14, $14, $14, $14, $14, $0c, $14, $02

// XP low byte
tier2_cr_xp_lo:
    .byte $1e, $05, $0c, $14, $10, $14, $0f, $0e, $12, $1c, $1a, $1a, $1e, $16, $1c, $1b
    .byte $28, $20, $1e, $20, $26, $28, $24, $26, $2a, $23, $28, $36, $34, $30, $36, $32

// XP high byte
tier2_cr_xp_hi:
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00

// Attack 0 type
tier2_cr_atk0_type:
    .byte $01, $0b, $01, $03, $01, $0e, $01, $01, $01, $04, $01, $01, $01, $01, $01, $0e
    .byte $01, $01, $01, $01, $01, $0e, $01, $01, $01, $01, $01, $01, $01, $01, $01, $0b

// Attack 0 dice count
tier2_cr_atk0_dice:
    .byte $01, $02, $01, $01, $01, $02, $02, $01, $02, $01, $02, $02, $01, $01, $01, $02
    .byte $01, $02, $01, $01, $01, $04, $02, $01, $02, $02, $03, $01, $03, $01, $03, $01

// Attack 0 dice sides
tier2_cr_atk0_sides:
    .byte $08, $04, $06, $04, $08, $05, $06, $02, $02, $04, $05, $04, $06, $04, $02, $06
    .byte $06, $05, $04, $05, $0a, $04, $03, $08, $08, $02, $04, $06, $06, $06, $06, $02

// Attack 1 type
tier2_cr_atk1_type:
    .byte $06, $00, $00, $00, $00, $00, $00, $01, $01, $00, $00, $01, $00, $0e, $0e, $00
    .byte $00, $0e, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $01, $00, $00

// Attack 1 dice count
tier2_cr_atk1_dice:
    .byte $02, $00, $00, $00, $00, $00, $00, $01, $00, $00, $00, $00, $00, $01, $03, $00
    .byte $00, $03, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $01, $00, $00

// Attack 1 dice sides
tier2_cr_atk1_sides:
    .byte $06, $00, $00, $00, $00, $00, $00, $02, $00, $00, $00, $00, $00, $04, $04, $00
    .byte $00, $05, $04, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $06, $00, $00

// Spell chance (0-100)
tier2_cr_spell_chance:
    .byte $00, $00, $00, $00, $00, $00, $0e, $00, $06, $00, $00, $00, $14, $00, $00, $00
    .byte $09, $00, $00, $14, $00, $00, $14, $00, $00, $21, $00, $0a, $00, $00, $00, $0b

// Spell flags bitmask
tier2_cr_spell_flags:
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $01, $00, $00, $00
    .byte $00, $00, $00, $05, $00, $00, $01, $00, $00, $14, $00, $02, $00, $00, $00, $00

// Name string pointers
tier2_cr_name_lo:
    .byte <tier2_crn_0, <tier2_crn_1, <tier2_crn_2, <tier2_crn_3, <tier2_crn_4, <tier2_crn_5, <tier2_crn_6, <tier2_crn_7
    .byte <tier2_crn_8, <tier2_crn_9, <tier2_crn_10, <tier2_crn_11, <tier2_crn_12, <tier2_crn_13, <tier2_crn_14, <tier2_crn_15
    .byte <tier2_crn_16, <tier2_crn_17, <tier2_crn_18, <tier2_crn_19, <tier2_crn_20, <tier2_crn_21, <tier2_crn_22, <tier2_crn_23
    .byte <tier2_crn_24, <tier2_crn_25, <tier2_crn_26, <tier2_crn_27, <tier2_crn_28, <tier2_crn_29, <tier2_crn_30, <tier2_crn_31
tier2_cr_name_hi:
    .byte >tier2_crn_0, >tier2_crn_1, >tier2_crn_2, >tier2_crn_3, >tier2_crn_4, >tier2_crn_5, >tier2_crn_6, >tier2_crn_7
    .byte >tier2_crn_8, >tier2_crn_9, >tier2_crn_10, >tier2_crn_11, >tier2_crn_12, >tier2_crn_13, >tier2_crn_14, >tier2_crn_15
    .byte >tier2_crn_16, >tier2_crn_17, >tier2_crn_18, >tier2_crn_19, >tier2_crn_20, >tier2_crn_21, >tier2_crn_22, >tier2_crn_23
    .byte >tier2_crn_24, >tier2_crn_25, >tier2_crn_26, >tier2_crn_27, >tier2_crn_28, >tier2_crn_29, >tier2_crn_30, >tier2_crn_31

.encoding "screencode_upper"
// Name strings (screen codes, null-terminated)
tier2_crn_0: .text "GREEN NAGA" ; .byte 0
tier2_crn_1: .text "WHITE MUSHROOM PATCH" ; .byte 0
tier2_crn_2: .text "SKELETON KOBOLD" ; .byte 0
tier2_crn_3: .text "BROWN MOLD" ; .byte 0
tier2_crn_4: .text "ORC" ; .byte 0
tier2_crn_5: .text "RATTLESNAKE" ; .byte 0
tier2_crn_6: .text "BLOODSHOT EYE" ; .byte 0
tier2_crn_7: .text "ZOMBIE KOBOLD" ; .byte 0
tier2_crn_8: .text "LOST SOUL" ; .byte 0
tier2_crn_9: .text "GREEN MOLD" ; .byte 0
tier2_crn_10: .text "SKELETON ORC" ; .byte 0
tier2_crn_11: .text "BANDIT" ; .byte 0
tier2_crn_12: .text "ORC SHAMAN" ; .byte 0
tier2_crn_13: .text "GIANT RED ANT" ; .byte 0
tier2_crn_14: .text "KING COBRA" ; .byte 0
tier2_crn_15: .text "GIANT WHITE TICK" ; .byte 0
tier2_crn_16: .text "DISENCHANTER MOLD" ; .byte 0
tier2_crn_17: .text "CREEPING GOLD COINS" ; .byte 0
tier2_crn_18: .text "ORC ZOMBIE" ; .byte 0
tier2_crn_19: .text "NASTY LITTLE GNOME" ; .byte 0
tier2_crn_20: .text "HOBGOBLIN" ; .byte 0
tier2_crn_21: .text "BLACK MAMBA" ; .byte 0
tier2_crn_22: .text "PRIEST" ; .byte 0
tier2_crn_23: .text "SKELETON HUMAN" ; .byte 0
tier2_crn_24: .text "OGRE" ; .byte 0
tier2_crn_25: .text "MAGIC USER" ; .byte 0
tier2_crn_26: .text "BLACK ORC" ; .byte 0
tier2_crn_27: .text "GIANT WHITE DRAGON FLY" ; .byte 0
tier2_crn_28: .text "HILL GIANT" ; .byte 0
tier2_crn_29: .text "FLESH GOLEM" ; .byte 0
tier2_crn_30: .text "FROST GIANT" ; .byte 0
tier2_crn_31: .text "VIOLET MOLD" ; .byte 0

// End marker for size calculation
tier2_data_end:
.print "Tier 2 (Early): " + (tier2_data_end - tier2_cr_display) + " bytes"
