// huffman_data.s — Generated by huff_encoder.py
// Source: data/huffman_strings.txt
// 160 strings, 3242 bytes uncompressed
// 1883 bytes compressed (58.1%)
// Tree: 68 bytes, Index: 320 bytes
// Total data: 2271 bytes

.const HUFF_STR_COUNT = 160
.const HSTR_INSULT_COUNT = 15

// Named string constants
.const HSTR_MAT_HITS = 15
.const HSTR_MAT_MISS = 16
.const HSTR_MAT_POISON = 17
.const HSTR_MAT_CONFUSE = 18
.const HSTR_MAT_PARALYZE = 19
.const HSTR_MAT_ACID = 20
.const HSTR_MAT_FEAR = 21
.const HSTR_MAT_SHRIEK = 22
.const HSTR_MAT_DEAD = 23
.const HSTR_MM_BOLT = 24
.const HSTR_MM_BREATH = 25
.const HSTR_MM_SUMMON = 26
.const HSTR_MM_TELEPORT = 27
.const HSTR_MM_BLIND = 28
.const HSTR_MM_CONFUSE = 29
.const HSTR_MM_HEAL = 30
.const HSTR_RF_NO_WEAPON = 31
.const HSTR_RF_NO_AMMO = 32
.const HSTR_RF_FLIES = 33
.const HSTR_RF_MISSES = 34
.const HSTR_RF_HITS = 35
.const HSTR_EB_SPELL_HITS = 36
.const HSTR_EB_FIZZLE = 37
.const HSTR_TW_PROMPT = 38
.const HSTR_TW_SHATTERS = 39
.const HSTR_EFF_POISON_END = 40
.const HSTR_EFF_BLIND_END = 41
.const HSTR_EFF_CONFUSE_END = 42
.const HSTR_EFF_PARALYZE_END = 43
.const HSTR_EFF_FEAR_END = 44
.const HSTR_TTL_DIM = 45
.const HSTR_TTL_OUT = 46
.const HSTR_RECALL_ARRIVE = 47
.const HSTR_DL_YOU_SEE = 48
.const HSTR_DL_OPEN_DOOR = 49
.const HSTR_DL_CLOSED_DOOR = 50
.const HSTR_DL_STAIRS_DN = 51
.const HSTR_DL_STAIRS_UP = 52
.const HSTR_DL_TRAP = 53
.const HSTR_DL_RUBBLE = 54
.const HSTR_DL_WALL = 55
.const HSTR_DL_NOTHING = 56
.const HSTR_PTM_AFRAID = 57
.const HSTR_DF_TRAP_0 = 58
.const HSTR_DF_TRAP_1 = 59
.const HSTR_DF_TRAP_2 = 60
.const HSTR_DF_TRAP_3 = 61
.const HSTR_DF_TRAP_4 = 62
.const HSTR_DF_TRAP_5 = 63
.const HSTR_DF_DIRECTION = 64
.const HSTR_DF_DOOR_STUCK = 65
.const HSTR_DF_FOUND_TRAP = 66
.const HSTR_DF_FOUND_SECRET = 67
.const HSTR_DF_FOUND_NOTHING = 68
.const HSTR_DF_NO_DOOR = 69
.const HSTR_DF_ALREADY_OPEN = 70
.const HSTR_DF_ALREADY_CLOSED = 71
.const HSTR_DF_DOOR_OPENED = 72
.const HSTR_DF_DOOR_CLOSED = 73
.const HSTR_DF_YOU_FELL = 74
.const HSTR_DF_ARROW_HITS = 75
.const HSTR_DF_POISON_GAS = 76
.const HSTR_DF_TELEPORTED = 77
.const HSTR_DF_DART_HITS = 78
.const HSTR_DF_ROCKFALL = 79
.const HSTR_DF_DAMAGE_PRE = 80
.const HSTR_DF_DAMAGE_POST = 81
.const HSTR_DF_CON_DRAIN = 82
.const HSTR_DF_POISONED = 83
.const HSTR_PM_NO_CAST = 84
.const HSTR_PM_NO_PRAY = 85
.const HSTR_PM_NOT_KNOWN = 86
.const HSTR_PM_NO_MANA = 87
.const HSTR_PM_NO_EXP = 88
.const HSTR_PM_FAIL = 89
.const HSTR_PM_YOU_CAST = 90
.const HSTR_PM_YOU_PRAY = 91
.const HSTR_PM_TITLE_MAGE = 92
.const HSTR_PM_TITLE_PRAY = 93
.const HSTR_PM_FOOTER_CAST = 94
.const HSTR_PM_FOOTER_PRAY = 95
.const HSTR_PM_LEARNED = 96
.const HSTR_PIW_WEAR_PROMPT = 97
.const HSTR_PIW_TAKEOFF_PROMPT = 98
.const HSTR_PIW_NOTHING = 99
.const HSTR_PIW_CANT_WEAR = 100
.const HSTR_PIW_NEVERMIND = 101
.const HSTR_PIW_CURSED = 102
.const HSTR_PIW_NO_FOOD = 103
.const HSTR_PIW_WIELD = 104
.const HSTR_PIW_WEARING = 105
.const HSTR_PIW_TAKEOFF = 106
.const HSTR_PIW_EAT = 107
.const HSTR_PIW_DELICIOUS = 108
.const HSTR_PIW_YUCK = 109
.const HSTR_PIQ_QUAFF_PROMPT = 110
.const HSTR_PIQ_READ_PROMPT = 111
.const HSTR_PIQ_NOT_POTION = 112
.const HSTR_PIQ_NOT_SCROLL = 113
.const HSTR_PIQ_FEEL_BETTER = 114
.const HSTR_PIQ_SPEED = 115
.const HSTR_PIQ_TERRIBLE = 116
.const HSTR_PIQ_NOTHING = 117
.const HSTR_PIQ_LIGHT = 118
.const HSTR_PIQ_IDENTIFY_PROMPT = 119
.const HSTR_PIQ_THISIS = 120
.const HSTR_PIQ_TELEPORT = 121
.const HSTR_PIQ_MUCH_BETTER = 122
.const HSTR_PIQ_MIND_CLEAR = 123
.const HSTR_PIQ_HEROIC = 124
.const HSTR_PIQ_CANT_SEE = 125
.const HSTR_PIQ_DIZZY = 126
.const HSTR_PIQ_SENSE = 127
.const HSTR_PIQ_EYES_TINGLE = 128
.const HSTR_PIQ_AIR_CRACKLE = 129
.const HSTR_PIQ_CLEANSED = 130
.const HSTR_PIQ_WPN_GLOW = 131
.const HSTR_PIQ_ARM_GLOW = 132
.const HSTR_PIQ_HANDS_GLOW = 133
.const HSTR_PIQ_HUMMING = 134
.const HSTR_PIQ_PROTECTED = 135
.const HSTR_PIQ_VIBRATION = 136
.const HSTR_PIW_AIM_PROMPT = 137
.const HSTR_PIW_USE_PROMPT = 138
.const HSTR_PIW_NOT_WAND = 139
.const HSTR_PIW_NOT_STAFF = 140
.const HSTR_PIW_NO_CHARGES = 141
.const HSTR_PIW_STAFF_EMPTY = 142
.const HSTR_PIW_WAND_BOLT = 143
.const HSTR_PIW_WAND_FROST = 144
.const HSTR_PIW_WAND_CLOUD = 145
.const HSTR_PIW_WAND_MISS = 146
.const HSTR_PIQ_CANT_READ = 147
.const HSTR_IGS_PROMPT = 148
.const HSTR_IGS_NO_MAGIC = 149
.const HSTR_IGS_NOT_BOOK = 150
.const HSTR_IGS_WRONG_TYPE = 151
.const HSTR_IGS_SUCCESS = 152
.const HSTR_IGS_NO_NEW = 153
.const HSTR_PIR_NOT_LAMP = 154
.const HSTR_PIR_NO_OIL = 155
.const HSTR_PIR_OVERFLOW = 156
.const HSTR_PIR_FULL = 157
.const HSTR_PIR_REFUELED = 158
.const HSTR_CMB_LVLUP = 159

// Huffman tree: 34 internal nodes
// Children: $00-$7E = node index, $80+ = leaf (& $7F = screencode)
huff_tree_left:
    .byte $01, $03, $05, $07, $09, $0b, $0c, $95, $0e, $80, $94, $81, $12, $13, $14, $15, $16, $8c, $99, $8e, $a1, $8d, $1a, $90, $86, $1c, $1d, $82, $1f, $a9, $ad, $21, $9a, $91
huff_tree_right:
    .byte $02, $04, $06, $08, $0a, $a0, $0d, $92, $93, $0f, $10, $11, $85, $8f, $84, $ae, $17, $88, $18, $89, $19, $87, $97, $1b, $83, $8b, $96, $1e, $a8, $20, $bf, $a7, $ac, $98

// String index: 16-bit byte offsets into huff_str_data
huff_str_index:
    .word $0000  // [0] "YOU WILL HAVE TO DO BETTER THA"
    .word $0015  // [1] "THAT IS AN INSULT!"
    .word $0020  // [2] "DO YOU WISH TO DO BUSINESS OR "
    .word $0033  // [3] "HAH! TRY AGAIN."
    .word $003c  // [4] "RIDICULOUS!"
    .word $0043  // [5] "YOU HAVE GOT TO BE KIDDING!"
    .word $0054  // [6] "YOU HAD BETTER BE KIDDING!"
    .word $0064  // [7] "YOU TRY MY PATIENCE."
    .word $0070  // [8] "I DO NOT HEAR YOU."
    .word $007a  // [9] "HMMM, NICE WEATHER WE ARE HAVI"
    .word $008f  // [10] "I MUST HAVE HEARD YOU WRONG."
    .word $009f  // [11] "WHAT WAS THAT?"
    .word $00a8  // [12] "I AM SORRY, SAY THAT AGAIN."
    .word $00b8  // [13] "WHAT DID YOU SAY?"
    .word $00c3  // [14] "SORRY, WHAT WAS THAT AGAIN?"
    .word $00d3  // [15] @MAT_HITS " HITS YOU."
    .word $00d9  // [16] @MAT_MISS " MISSES YOU."
    .word $00e0  // [17] @MAT_POISON " POISONS YOU."
    .word $00e8  // [18] @MAT_CONFUSE " CONFUSES YOU."
    .word $00f1  // [19] @MAT_PARALYZE " PARALYZES YOU."
    .word $00fb  // [20] @MAT_ACID " SPITS ACID ON YOU."
    .word $0106  // [21] @MAT_FEAR " FRIGHTENS YOU."
    .word $010f  // [22] @MAT_SHRIEK "YOU HEAR A HORRIBLE SHRIEK!"
    .word $011f  // [23] @MAT_DEAD "YOU HAVE BEEN SLAIN."
    .word $012b  // [24] @MM_BOLT " CASTS A BOLT!"
    .word $0134  // [25] @MM_BREATH " BREATHES FIRE!"
    .word $013d  // [26] @MM_SUMMON " SUMMONS HELP!"
    .word $0146  // [27] @MM_TELEPORT " TELEPORTS YOU!"
    .word $014f  // [28] @MM_BLIND " BLINDS YOU!"
    .word $0157  // [29] @MM_CONFUSE " CONFUSES YOU!"
    .word $0160  // [30] @MM_HEAL " HEALS ITSELF."
    .word $0169  // [31] @RF_NO_WEAPON "NO RANGED WEAPON."
    .word $0174  // [32] @RF_NO_AMMO "NO AMMO."
    .word $017a  // [33] @RF_FLIES " FLIES AWAY."
    .word $0182  // [34] @RF_MISSES " MISSES"
    .word $0187  // [35] @RF_HITS " HITS"
    .word $018b  // [36] @EB_SPELL_HITS "YOUR SPELL HITS"
    .word $0194  // [37] @EB_FIZZLE "YOUR SPELL FIZZLES OUT."
    .word $01a3  // [38] @TW_PROMPT "THROW WHICH ITEM (A-V)?"
    .word $01b3  // [39] @TW_SHATTERS " SHATTERS!"
    .word $01b9  // [40] @EFF_POISON_END "YOU FEEL BETTER."
    .word $01c3  // [41] @EFF_BLIND_END "YOU CAN SEE AGAIN."
    .word $01ce  // [42] @EFF_CONFUSE_END "YOU FEEL LESS CONFUSED."
    .word $01dc  // [43] @EFF_PARALYZE_END "YOU CAN MOVE AGAIN."
    .word $01e8  // [44] @EFF_FEAR_END "YOU FEEL BOLDER NOW."
    .word $01f4  // [45] @TTL_DIM "YOUR LIGHT IS GROWING DIM."
    .word $0204  // [46] @TTL_OUT "YOUR LIGHT HAS GONE OUT."
    .word $0212  // [47] @RECALL_ARRIVE "YOU FEEL YOURSELF YANKED AWAY!"
    .word $0224  // [48] @DL_YOU_SEE "YOU SEE A "
    .word $022a  // [49] @DL_OPEN_DOOR "YOU SEE AN OPEN DOOR."
    .word $0236  // [50] @DL_CLOSED_DOOR "YOU SEE A CLOSED DOOR."
    .word $0242  // [51] @DL_STAIRS_DN "YOU SEE A STAIRCASE DOWN."
    .word $0250  // [52] @DL_STAIRS_UP "YOU SEE A STAIRCASE UP."
    .word $025d  // [53] @DL_TRAP "YOU SEE A TRAP."
    .word $0266  // [54] @DL_RUBBLE "YOU SEE RUBBLE."
    .word $026f  // [55] @DL_WALL "YOU SEE A WALL."
    .word $0278  // [56] @DL_NOTHING "YOU SEE NOTHING SPECIAL."
    .word $0286  // [57] @PTM_AFRAID "YOU ARE TOO AFRAID!"
    .word $0291  // [58] @DF_TRAP_0 "AN OPEN PIT"
    .word $0298  // [59] @DF_TRAP_1 "AN ARROW TRAP"
    .word $02a0  // [60] @DF_TRAP_2 "A POISON GAS TRAP"
    .word $02aa  // [61] @DF_TRAP_3 "A TELEPORT TRAP"
    .word $02b3  // [62] @DF_TRAP_4 "A POISON DART"
    .word $02bb  // [63] @DF_TRAP_5 "A ROCKFALL TRAP"
    .word $02c5  // [64] @DF_DIRECTION "DIRECTION?"
    .word $02cc  // [65] @DF_DOOR_STUCK "THE DOOR IS STUCK."
    .word $02d7  // [66] @DF_FOUND_TRAP "YOU FOUND A TRAP!"
    .word $02e1  // [67] @DF_FOUND_SECRET "YOU FOUND A SECRET DOOR!"
    .word $02ef  // [68] @DF_FOUND_NOTHING "YOU FOUND NOTHING."
    .word $02fa  // [69] @DF_NO_DOOR "NO DOOR THERE."
    .word $0302  // [70] @DF_ALREADY_OPEN "THE DOOR IS ALREADY OPEN."
    .word $0310  // [71] @DF_ALREADY_CLOSED "IT IS ALREADY CLOSED."
    .word $031c  // [72] @DF_DOOR_OPENED "YOU OPEN THE DOOR."
    .word $0326  // [73] @DF_DOOR_CLOSED "YOU CLOSE THE DOOR."
    .word $0331  // [74] @DF_YOU_FELL "YOU FELL INTO A PIT!"
    .word $033d  // [75] @DF_ARROW_HITS "AN ARROW HITS YOU!"
    .word $0348  // [76] @DF_POISON_GAS "A CLOUD OF GAS SURROUNDS YOU!"
    .word $0358  // [77] @DF_TELEPORTED "YOU ARE TELEPORTED!"
    .word $0363  // [78] @DF_DART_HITS "A DART HITS YOU!"
    .word $036c  // [79] @DF_ROCKFALL "ROCKS FALL ON YOU!"
    .word $0377  // [80] @DF_DAMAGE_PRE "YOU TAKE "
    .word $037d  // [81] @DF_DAMAGE_POST " DAMAGE."
    .word $0383  // [82] @DF_CON_DRAIN "YOU FEEL WEAKENED."
    .word $038e  // [83] @DF_POISONED "YOU FEEL POISONED."
    .word $0399  // [84] @PM_NO_CAST "YOU CANNOT CAST SPELLS."
    .word $03a7  // [85] @PM_NO_PRAY "YOU CANNOT PRAY."
    .word $03b1  // [86] @PM_NOT_KNOWN "YOU DON'T KNOW THAT SPELL."
    .word $03c1  // [87] @PM_NO_MANA "NOT ENOUGH MANA."
    .word $03cb  // [88] @PM_NO_EXP "YOU'RE NOT EXPERIENCED ENOUGH."
    .word $03de  // [89] @PM_FAIL "YOUR SPELL FAILS."
    .word $03e8  // [90] @PM_YOU_CAST "YOU CAST "
    .word $03ee  // [91] @PM_YOU_PRAY "YOU PRAY "
    .word $03f4  // [92] @PM_TITLE_MAGE "MAGE SPELLS"
    .word $03fb  // [93] @PM_TITLE_PRAY "PRAYERS"
    .word $0400  // [94] @PM_FOOTER_CAST "CAST WHICH? (A-P, ESC)"
    .word $0410  // [95] @PM_FOOTER_PRAY "PRAY WHICH? (A-P, ESC)"
    .word $0420  // [96] @PM_LEARNED "YOU HAVE LEARNED "
    .word $042a  // [97] @PIW_WEAR_PROMPT "WEAR WHICH ITEM (A-V)?"
    .word $0439  // [98] @PIW_TAKEOFF_PROMPT "TAKE OFF WHICH ITEM (A-H)?"
    .word $044b  // [99] @PIW_NOTHING "YOU HAVE NOTHING THERE."
    .word $0459  // [100] @PIW_CANT_WEAR "YOU CANNOT WEAR THAT."
    .word $0465  // [101] @PIW_NEVERMIND "NEVER MIND."
    .word $046d  // [102] @PIW_CURSED "YOU CANNOT REMOVE IT, IT IS CU"
    .word $0482  // [103] @PIW_NO_FOOD "YOU HAVE NO FOOD."
    .word $048c  // [104] @PIW_WIELD "YOU ARE WIELDING A "
    .word $0497  // [105] @PIW_WEARING "YOU ARE WEARING A "
    .word $04a1  // [106] @PIW_TAKEOFF "YOU TAKE OFF THE "
    .word $04ab  // [107] @PIW_EAT "YOU EAT THE "
    .word $04b2  // [108] @PIW_DELICIOUS ". DELICIOUS!"
    .word $04ba  // [109] @PIW_YUCK ". YUCK!"
    .word $04bf  // [110] @PIQ_QUAFF_PROMPT "QUAFF WHICH POTION (A-V)?"
    .word $04d1  // [111] @PIQ_READ_PROMPT "READ WHICH SCROLL (A-V)?"
    .word $04e1  // [112] @PIQ_NOT_POTION "THAT IS NOT A POTION."
    .word $04ed  // [113] @PIQ_NOT_SCROLL "THAT IS NOT A SCROLL."
    .word $04f9  // [114] @PIQ_FEEL_BETTER "YOU FEEL BETTER."
    .word $0503  // [115] @PIQ_SPEED "YOU FEEL YOURSELF MOVING FASTE"
    .word $0516  // [116] @PIQ_TERRIBLE "THAT TASTED TERRIBLE!"
    .word $0522  // [117] @PIQ_NOTHING "NOTHING SEEMS TO HAPPEN."
    .word $0530  // [118] @PIQ_LIGHT "THE AREA FILLS WITH LIGHT."
    .word $053f  // [119] @PIQ_IDENTIFY_PROMPT "IDENTIFY WHICH ITEM (A-V)?"
    .word $0551  // [120] @PIQ_THISIS "THIS IS A "
    .word $0557  // [121] @PIQ_TELEPORT "YOU FEEL DISORIENTED."
    .word $0563  // [122] @PIQ_MUCH_BETTER "YOU FEEL MUCH BETTER."
    .word $0570  // [123] @PIQ_MIND_CLEAR "YOUR MIND FEELS CLEAR."
    .word $057d  // [124] @PIQ_HEROIC "YOU FEEL HEROIC!"
    .word $0587  // [125] @PIQ_CANT_SEE "YOU CAN'T SEE!"
    .word $0590  // [126] @PIQ_DIZZY "YOU FEEL DIZZY."
    .word $059a  // [127] @PIQ_SENSE "YOU SENSE NEARBY CREATURES."
    .word $05a9  // [128] @PIQ_EYES_TINGLE "YOUR EYES TINGLE."
    .word $05b3  // [129] @PIQ_AIR_CRACKLE "THE AIR CRACKLES AROUND YOU."
    .word $05c3  // [130] @PIQ_CLEANSED "YOU FEEL CLEANSED."
    .word $05ce  // [131] @PIQ_WPN_GLOW "YOUR WEAPON GLOWS BRIEFLY."
    .word $05de  // [132] @PIQ_ARM_GLOW "YOUR ARMOR GLOWS BRIEFLY."
    .word $05ed  // [133] @PIQ_HANDS_GLOW "YOUR HANDS BEGIN TO GLOW."
    .word $05fc  // [134] @PIQ_HUMMING "YOU HEAR A HIGH-PITCHED HUMMIN"
    .word $0610  // [135] @PIQ_PROTECTED "YOU FEEL PROTECTED."
    .word $061b  // [136] @PIQ_VIBRATION "YOU FEEL A STRANGE VIBRATION."
    .word $062c  // [137] @PIW_AIM_PROMPT "AIM WHICH WAND (A-V)?"
    .word $063b  // [138] @PIW_USE_PROMPT "USE WHICH STAFF (A-V)?"
    .word $064a  // [139] @PIW_NOT_WAND "THAT IS NOT A WAND."
    .word $0655  // [140] @PIW_NOT_STAFF "THAT IS NOT A STAFF."
    .word $0660  // [141] @PIW_NO_CHARGES "NO CHARGES LEFT."
    .word $066a  // [142] @PIW_STAFF_EMPTY "THE STAFF IS EMPTY."
    .word $0676  // [143] @PIW_WAND_BOLT "A BOLT OF LIGHTNING SHOOTS FOR"
    .word $068a  // [144] @PIW_WAND_FROST "A BOLT OF FROST SHOOTS FORTH!"
    .word $069b  // [145] @PIW_WAND_CLOUD "THE MONSTER LOOKS CONFUSED."
    .word $06ab  // [146] @PIW_WAND_MISS "THE CLOUD DISSIPATES."
    .word $06b8  // [147] @PIQ_CANT_READ "YOU CAN'T SEE TO READ!"
    .word $06c5  // [148] @IGS_PROMPT "STUDY WHICH BOOK (A-V)?"
    .word $06d5  // [149] @IGS_NO_MAGIC "YOU CANNOT USE MAGIC."
    .word $06e2  // [150] @IGS_NOT_BOOK "THAT IS NOT A BOOK."
    .word $06ed  // [151] @IGS_WRONG_TYPE "YOU CANNOT READ THAT BOOK."
    .word $06fc  // [152] @IGS_SUCCESS "YOU LEARN FROM THE BOOK!"
    .word $070a  // [153] @IGS_NO_NEW "NO NEW SPELLS TO LEARN."
    .word $0717  // [154] @PIR_NOT_LAMP "NOT USING A LAMP."
    .word $0721  // [155] @PIR_NO_OIL "YOU HAVE NO OIL."
    .word $072b  // [156] @PIR_OVERFLOW "YOUR LAMP OVERFLOWS."
    .word $0738  // [157] @PIR_FULL "YOUR LAMP IS FULL."
    .word $0743  // [158] @PIR_REFUELED "YOUR LAMP IS REFUELED."
    .word $0750  // [159] @CMB_LVLUP "WELCOME TO LEVEL "

// Compressed string data (1883 bytes)
huff_str_data:
    // [0] "YOU WILL HAVE TO DO BETTER THAN THAT!" (38→21 bytes)
    .byte $c7, $85, $77, $b2, $95, $9c, $39, $da, $df, $4b, $f5, $f6, $b3, $68, $d6, $9c, $72, $b4, $e1, $88, $40
    // [1] "THAT IS AN INSULT!" (19→11 bytes)
    .byte $69, $c3, $5e, $9d, $8e, $5e, $f0, $c2, $4c, $42, $00
    // [2] "DO YOU WISH TO DO BUSINESS OR NOT?" (35→19 bytes)
    .byte $2f, $dc, $78, $57, $7a, $73, $ad, $f4, $bf, $5f, $01, $f7, $9a, $67, $7c, $6f, $3d, $9f, $d0
    // [3] "HAH! TRY AGAIN." (16→9 bytes)
    .byte $9c, $4c, $8a, $c3, $8b, $0a, $c7, $78, $b4
    // [4] "RIDICULOUS!" (12→7 bytes)
    .byte $1e, $97, $b9, $84, $bc, $0c, $84
    // [5] "YOU HAVE GOT TO BE KIDDING!" (28→17 bytes)
    .byte $c7, $85, $9c, $39, $da, $af, $b5, $6f, $af, $b6, $93, $e9, $4b, $de, $2a, $42, $00
    // [6] "YOU HAD BETTER BE KIDDING!" (27→16 bytes)
    .byte $c7, $85, $9c, $16, $be, $d6, $6d, $1a, $fb, $69, $3e, $94, $bd, $e2, $a4, $20
    // [7] "YOU TRY MY PATIENCE." (21→12 bytes)
    .byte $c7, $85, $61, $c5, $53, $15, $e8, $6e, $ef, $33, $d5, $a0
    // [8] "I DO NOT HEAR YOU." (19→10 bytes)
    .byte $ed, $2f, $de, $7b, $59, $ec, $0d, $c7, $82, $d0
    // [9] "HMMM, NICE WEATHER WE ARE HAVING." (34→21 bytes)
    .byte $9a, $8a, $28, $e3, $bc, $ee, $7b, $5d, $d8, $69, $e8, $d7, $76, $c0, $ed, $9c, $39, $ef, $15, $5a, $00
    // [10] "I MUST HAVE HEARD YOU WRONG." (29→16 bytes)
    .byte $ed, $50, $0d, $ac, $e1, $ce, $d9, $ec, $09, $6e, $3c, $2b, $a3, $fc, $55, $68
    // [11] "WHAT WAS THAT?" (15→9 bytes)
    .byte $76, $70, $d5, $d8, $3a, $d3, $86, $7f, $40
    // [12] "I AM SORRY, SAY THAT AGAIN." (28→16 bytes)
    .byte $ed, $85, $29, $f8, $8e, $1c, $74, $e3, $15, $a7, $0d, $61, $58, $ef, $16, $80
    // [13] "WHAT DID YOU SAY?" (18→11 bytes)
    .byte $76, $70, $d4, $bd, $2d, $c7, $85, $38, $c3, $fa, $00
    // [14] "SORRY, WHAT WAS THAT AGAIN?" (28→16 bytes)
    .byte $3f, $11, $c3, $8e, $bb, $38, $6a, $ec, $1d, $69, $c3, $58, $56, $3b, $c7, $f4
    // [15] " HITS YOU." (11→6 bytes)
    .byte $b3, $eb, $1d, $c7, $82, $d0
    // [16] " MISSES YOU." (13→7 bytes)
    .byte $aa, $74, $cf, $4e, $e3, $c1, $68
    // [17] " POISONS YOU." (14→8 bytes)
    .byte $af, $7f, $4f, $f8, $77, $1e, $0b, $40
    // [18] " CONFUSES YOU." (15→9 bytes)
    .byte $b9, $ff, $32, $03, $d3, $b8, $f0, $5a, $00
    // [19] " PARALYZES YOU." (16→10 bytes)
    .byte $af, $40, $c4, $b0, $e2, $d3, $b8, $f0, $5a, $00
    // [20] " SPITS ACID ON YOU." (20→11 bytes)
    .byte $a6, $f7, $58, $ec, $67, $d2, $df, $e5, $c7, $82, $d0
    // [21] " FRIGHTENS YOU." (16→9 bytes)
    .byte $b9, $0f, $55, $9b, $6f, $0e, $e3, $c1, $68
    // [22] "YOU HEAR A HORRIBLE SHRIEK!" (28→16 bytes)
    .byte $c7, $85, $9e, $c0, $d8, $b3, $f1, $1e, $be, $96, $d3, $98, $f7, $49, $90, $80
    // [23] "YOU HAVE BEEN SLAIN." (21→12 bytes)
    .byte $c7, $85, $9c, $39, $da, $fb, $77, $94, $e5, $1d, $e2, $d0
    // [24] " CASTS A BOLT!" (15→9 bytes)
    .byte $b9, $c1, $b1, $d8, $af, $be, $4c, $42, $00
    // [25] " BREATHES FIRE!" (16→9 bytes)
    .byte $af, $87, $61, $a7, $a7, $72, $e8, $e9, $08
    // [26] " SUMMONS HELP!" (15→9 bytes)
    .byte $a6, $0a, $29, $fc, $3b, $3d, $93, $c4, $20
    // [27] " TELEPORTS YOU!" (16→9 bytes)
    .byte $ad, $b2, $d7, $bc, $58, $ee, $3c, $08, $40
    // [28] " BLINDS YOU!" (13→8 bytes)
    .byte $af, $a5, $de, $14, $ee, $3c, $08, $40
    // [29] " CONFUSES YOU!" (15→9 bytes)
    .byte $b9, $ff, $32, $03, $d3, $b8, $f0, $21, $00
    // [30] " HEALS ITSELF." (15→9 bytes)
    .byte $b3, $d8, $91, $de, $b1, $ec, $b2, $5a, $00
    // [31] "NO RANGED WEAPON." (18→11 bytes)
    .byte $e7, $d1, $8e, $2b, $a5, $ae, $ec, $3d, $fc, $5a, $00
    // [32] "NO AMMO." (9→6 bytes)
    .byte $e7, $d8, $51, $4f, $5a, $00
    // [33] " FLIES AWAY." (13→8 bytes)
    .byte $b9, $4b, $ba, $76, $1d, $8c, $2d, $00
    // [34] " MISSES" (8→5 bytes)
    .byte $aa, $74, $cf, $4d, $00
    // [35] " HITS" (6→4 bytes)
    .byte $b3, $eb, $1a, $00
    // [36] "YOUR SPELL HITS" (16→9 bytes)
    .byte $c7, $80, $d3, $7b, $65, $2b, $3e, $b1, $a0
    // [37] "YOUR SPELL FIZZLES OUT." (24→15 bytes)
    .byte $c7, $80, $d3, $7b, $65, $2b, $97, $5c, $4e, $29, $69, $df, $06, $5a, $00
    // [38] "THROW WHICH ITEM (A-V)?" (24→16 bytes)
    .byte $69, $8f, $bb, $5d, $9f, $73, $9d, $eb, $6a, $94, $96, $1f, $9c, $b8, $3f, $a0
    // [39] " SHATTERS!" (11→6 bytes)
    .byte $a7, $38, $66, $d1, $32, $10
    // [40] "YOU FEEL BETTER." (17→10 bytes)
    .byte $c7, $85, $cb, $76, $55, $f6, $b3, $68, $ad, $00
    // [41] "YOU CAN SEE AGAIN." (19→11 bytes)
    .byte $c7, $85, $ce, $39, $4f, $76, $c2, $b1, $de, $2d, $00
    // [42] "YOU FEEL LESS CONFUSED." (24→14 bytes)
    .byte $c7, $85, $cb, $76, $56, $5a, $67, $73, $fe, $64, $07, $a5, $5a, $00
    // [43] "YOU CAN MOVE AGAIN." (20→12 bytes)
    .byte $c7, $85, $ce, $39, $54, $f7, $3b, $61, $58, $ef, $16, $80
    // [44] "YOU FEEL BOLDER NOW." (21→12 bytes)
    .byte $c7, $85, $cb, $76, $55, $f7, $c8, $ba, $37, $9e, $ea, $d0
    // [45] "YOUR LIGHT IS GROWING DIM." (27→16 bytes)
    .byte $c7, $80, $d9, $75, $59, $b5, $e9, $d5, $47, $dd, $ef, $15, $a5, $ea, $8b, $40
    // [46] "YOUR LIGHT HAS GONE OUT." (25→14 bytes)
    .byte $c7, $80, $d9, $75, $59, $b5, $9c, $1d, $57, $f9, $b7, $c1, $96, $80
    // [47] "YOU FEEL YOURSELF YANKED AWAY!" (31→18 bytes)
    .byte $c7, $85, $cb, $76, $57, $1e, $02, $7b, $2c, $ae, $23, $84, $f4, $b6, $1d, $8c, $10, $80
    // [48] "YOU SEE A " (11→6 bytes)
    .byte $c7, $85, $3d, $db, $15, $00
    // [49] "YOU SEE AN OPEN DOOR." (22→12 bytes)
    .byte $c7, $85, $3d, $db, $1c, $be, $f6, $f2, $97, $fc, $56, $80
    // [50] "YOU SEE A CLOSED DOOR." (23→12 bytes)
    .byte $c7, $85, $3d, $db, $17, $39, $79, $e9, $69, $7f, $c5, $68
    // [51] "YOU SEE A STAIRCASE DOWN." (26→14 bytes)
    .byte $c7, $85, $3d, $db, $14, $da, $3a, $39, $c1, $ed, $2f, $bb, $c5, $a0
    // [52] "YOU SEE A STAIRCASE UP." (24→13 bytes)
    .byte $c7, $85, $3d, $db, $14, $da, $3a, $39, $c1, $ed, $07, $96, $80
    // [53] "YOU SEE A TRAP." (16→9 bytes)
    .byte $c7, $85, $3d, $db, $15, $86, $1e, $5a, $00
    // [54] "YOU SEE RUBBLE." (16→9 bytes)
    .byte $c7, $85, $3d, $da, $20, $f9, $f4, $b5, $68
    // [55] "YOU SEE A WALL." (16→9 bytes)
    .byte $c7, $85, $3d, $db, $15, $d8, $94, $96, $80
    // [56] "YOU SEE NOTHING SPECIAL." (25→14 bytes)
    .byte $c7, $85, $3d, $db, $cf, $69, $f7, $8a, $d3, $7b, $73, $ec, $49, $68
    // [57] "YOU ARE TOO AFRAID!" (20→11 bytes)
    .byte $c7, $85, $81, $da, $df, $f6, $32, $18, $e9, $48, $40
    // [58] "AN OPEN PIT" (12→7 bytes)
    .byte $8e, $5f, $7b, $79, $5e, $eb, $20
    // [59] "AN ARROW TRAP" (14→8 bytes)
    .byte $8e, $58, $11, $f7, $6b, $0c, $3c, $80
    // [60] "A POISON GAS TRAP" (18→10 bytes)
    .byte $8a, $f7, $f4, $ff, $95, $58, $3a, $c3, $0f, $20
    // [61] "A TELEPORT TRAP" (16→9 bytes)
    .byte $8a, $db, $2d, $7b, $c5, $ab, $0c, $3c, $80
    // [62] "A POISON DART" (14→8 bytes)
    .byte $8a, $f7, $f4, $ff, $94, $b0, $2c, $80
    // [63] "A ROCKFALL TRAP" (16→10 bytes)
    .byte $8a, $3f, $99, $3c, $a2, $52, $ac, $30, $f2, $00
    // [64] "DIRECTION?" (11→7 bytes)
    .byte $2f, $47, $73, $6e, $ff, $1f, $d0
    // [65] "THE DOOR IS STUCK." (19→11 bytes)
    .byte $69, $ed, $2f, $f8, $de, $9d, $36, $0c, $c9, $ad, $00
    // [66] "YOU FOUND A TRAP!" (18→10 bytes)
    .byte $c7, $85, $cb, $c3, $85, $b1, $58, $61, $e2, $10
    // [67] "YOU FOUND A SECRET DOOR!" (25→14 bytes)
    .byte $c7, $85, $cb, $c3, $85, $b1, $4f, $73, $1d, $6a, $5f, $f1, $21, $00
    // [68] "YOU FOUND NOTHING." (19→11 bytes)
    .byte $c7, $85, $cb, $c3, $85, $bc, $f6, $9f, $78, $aa, $d0
    // [69] "NO DOOR THERE." (15→8 bytes)
    .byte $e7, $d2, $ff, $8d, $69, $e8, $ea, $d0
    // [70] "THE DOOR IS ALREADY OPEN." (26→14 bytes)
    .byte $69, $ed, $2f, $f8, $de, $9d, $89, $0e, $c1, $71, $7d, $ed, $e2, $d0
    // [71] "IT IS ALREADY CLOSED." (22→12 bytes)
    .byte $eb, $5e, $9d, $89, $0e, $c1, $71, $73, $97, $9e, $95, $68
    // [72] "YOU OPEN THE DOOR." (19→10 bytes)
    .byte $c7, $85, $f7, $b7, $95, $a7, $b4, $bf, $e2, $b4
    // [73] "YOU CLOSE THE DOOR." (20→11 bytes)
    .byte $c7, $85, $ce, $5e, $7b, $5a, $7b, $4b, $fe, $2b, $40
    // [74] "YOU FELL INTO A PIT!" (21→12 bytes)
    .byte $c7, $85, $cb, $65, $2b, $de, $37, $d8, $af, $75, $88, $40
    // [75] "AN ARROW HITS YOU!" (19→11 bytes)
    .byte $8e, $58, $11, $f7, $6c, $fa, $c7, $71, $e0, $42, $00
    // [76] "A CLOUD OF GAS SURROUNDS YOU!" (30→16 bytes)
    .byte $8b, $9c, $bc, $0b, $7f, $2a, $ac, $1d, $30, $11, $f0, $e1, $4e, $e3, $c0, $84
    // [77] "YOU ARE TELEPORTED!" (20→11 bytes)
    .byte $c7, $85, $81, $da, $db, $2d, $7b, $c5, $b4, $a4, $20
    // [78] "A DART HITS YOU!" (17→9 bytes)
    .byte $8a, $58, $16, $b3, $eb, $1d, $c7, $81, $08
    // [79] "ROCKS FALL ON YOU!" (19→11 bytes)
    .byte $1f, $cc, $99, $dc, $a2, $52, $bf, $cb, $8f, $02, $10
    // [80] "YOU TAKE " (10→6 bytes)
    .byte $c7, $85, $68, $27, $b5, $00
    // [81] " DAMAGE." (9→6 bytes)
    .byte $a5, $85, $21, $5d, $5a, $00
    // [82] "YOU FEEL WEAKENED." (19→11 bytes)
    .byte $c7, $85, $cb, $76, $55, $dd, $82, $7b, $cd, $2a, $d0
    // [83] "YOU FEEL POISONED." (19→11 bytes)
    .byte $c7, $85, $cb, $76, $55, $ef, $e9, $ff, $34, $ab, $40
    // [84] "YOU CANNOT CAST SPELLS." (24→14 bytes)
    .byte $c7, $85, $ce, $39, $cf, $6b, $9c, $1b, $53, $7b, $65, $23, $5a, $00
    // [85] "YOU CANNOT PRAY." (17→10 bytes)
    .byte $c7, $85, $ce, $39, $cf, $6a, $f0, $c6, $16, $80
    // [86] "YOU DON'T KNOW THAT SPELL." (27→16 bytes)
    .byte $c7, $85, $2f, $f0, $92, $d4, $9f, $3d, $da, $d3, $86, $a6, $f6, $ca, $4b, $40
    // [87] "NOT ENOUGH MANA." (17→10 bytes)
    .byte $e7, $b5, $de, $78, $2b, $3a, $a4, $72, $16, $80
    // [88] "YOU'RE NOT EXPERIENCED ENOUGH." (31→19 bytes)
    .byte $c7, $81, $24, $76, $f3, $da, $e9, $22, $f6, $8f, $77, $99, $e9, $6e, $f3, $c1, $59, $ad, $00
    // [89] "YOUR SPELL FAILS." (18→10 bytes)
    .byte $c7, $80, $d3, $7b, $65, $2b, $94, $76, $46, $b4
    // [90] "YOU CAST " (10→6 bytes)
    .byte $c7, $85, $ce, $0d, $aa, $00
    // [91] "YOU PRAY " (10→6 bytes)
    .byte $c7, $85, $78, $63, $15, $00
    // [92] "MAGE SPELLS" (12→7 bytes)
    .byte $52, $15, $da, $6f, $6c, $a4, $68
    // [93] "PRAYERS" (8→5 bytes)
    .byte $78, $63, $1a, $26, $80
    // [94] "CAST WHICH? (A-P, ESC)" (23→16 bytes)
    .byte $ce, $0d, $ab, $b3, $ee, $73, $7f, $a4, $b0, $fc, $f3, $8e, $e9, $e6, $e0, $80
    // [95] "PRAY WHICH? (A-P, ESC)" (23→16 bytes)
    .byte $78, $63, $15, $d9, $f7, $39, $bf, $d2, $58, $7e, $79, $c7, $74, $f3, $70, $40
    // [96] "YOU HAVE LEARNED " (18→10 bytes)
    .byte $c7, $85, $9c, $39, $db, $2d, $81, $e6, $96, $a0
    // [97] "WEAR WHICH ITEM (A-V)?" (23→15 bytes)
    .byte $77, $60, $6b, $b3, $ee, $73, $bd, $6d, $52, $92, $c3, $f3, $97, $07, $f4
    // [98] "TAKE OFF WHICH ITEM (A-H)?" (27→18 bytes)
    .byte $68, $27, $b7, $f2, $ca, $bb, $3e, $e7, $3b, $d6, $d5, $29, $2c, $3f, $4d, $c1, $fd, $00
    // [99] "YOU HAVE NOTHING THERE." (24→14 bytes)
    .byte $c7, $85, $9c, $39, $db, $cf, $69, $f7, $8a, $d6, $9e, $8e, $ad, $00
    // [100] "YOU CANNOT WEAR THAT." (22→12 bytes)
    .byte $c7, $85, $ce, $39, $cf, $6a, $ee, $c0, $d6, $9c, $32, $d0
    // [101] "NEVER MIND." (12→8 bytes)
    .byte $e6, $b9, $d1, $aa, $77, $85, $5a, $00
    // [102] "YOU CANNOT REMOVE IT, IT IS CURSED!" (36→21 bytes)
    .byte $c7, $85, $ce, $39, $cf, $6a, $3a, $a7, $b9, $db, $d6, $71, $de, $b5, $e9, $dc, $c0, $4f, $4a, $42, $00
    // [103] "YOU HAVE NO FOOD." (18→10 bytes)
    .byte $c7, $85, $9c, $39, $db, $cf, $b9, $7f, $95, $68
    // [104] "YOU ARE WIELDING A " (20→11 bytes)
    .byte $c7, $85, $81, $da, $ef, $76, $45, $ef, $15, $b1, $50
    // [105] "YOU ARE WEARING A " (19→10 bytes)
    .byte $c7, $85, $81, $da, $ee, $c0, $f7, $8a, $d8, $a8
    // [106] "YOU TAKE OFF THE " (18→10 bytes)
    .byte $c7, $85, $68, $27, $b7, $f2, $ca, $b4, $f6, $a0
    // [107] "YOU EAT THE " (13→7 bytes)
    .byte $c7, $85, $d8, $6a, $d3, $da, $80
    // [108] ". DELICIOUS!" (13→8 bytes)
    .byte $5d, $2e, $cb, $b9, $f7, $c0, $c8, $40
    // [109] ". YUCK!" (8→5 bytes)
    .byte $5d, $c0, $66, $4c, $84
    // [110] "QUAFF WHICH POTION (A-V)?" (26→18 bytes)
    .byte $24, $02, $32, $ca, $bb, $3e, $e7, $3a, $f7, $b7, $7f, $94, $96, $1f, $9c, $b8, $3f, $a0
    // [111] "READ WHICH SCROLL (A-V)?" (25→16 bytes)
    .byte $1d, $82, $d7, $67, $dc, $e7, $4f, $31, $f9, $4a, $92, $c3, $f3, $97, $07, $f4
    // [112] "THAT IS NOT A POTION." (22→12 bytes)
    .byte $69, $c3, $5e, $9d, $e7, $b5, $8a, $f7, $b7, $7f, $8b, $40
    // [113] "THAT IS NOT A SCROLL." (22→12 bytes)
    .byte $69, $c3, $5e, $9d, $e7, $b5, $8a, $79, $8f, $ca, $4b, $40
    // [114] "YOU FEEL BETTER." (17→10 bytes)
    .byte $c7, $85, $cb, $76, $55, $f6, $b3, $68, $ad, $00
    // [115] "YOU FEEL YOURSELF MOVING FASTER." (33→19 bytes)
    .byte $c7, $85, $cb, $76, $57, $1e, $02, $7b, $2c, $aa, $9e, $e7, $bc, $56, $e5, $06, $da, $2b, $40
    // [116] "THAT TASTED TERRIBLE!" (22→12 bytes)
    .byte $69, $c3, $56, $83, $6d, $2d, $6d, $11, $eb, $e9, $69, $08
    // [117] "NOTHING SEEMS TO HAPPEN." (25→14 bytes)
    .byte $e7, $b4, $fb, $c5, $69, $ee, $a8, $75, $be, $ce, $1e, $7b, $78, $b4
    // [118] "THE AREA FILLS WITH LIGHT." (27→15 bytes)
    .byte $69, $ed, $81, $d8, $b9, $76, $52, $3a, $ef, $5a, $76, $5d, $56, $6c, $b4
    // [119] "IDENTIFY WHICH ITEM (A-V)?" (27→18 bytes)
    .byte $e9, $77, $8d, $dc, $b1, $5d, $9f, $73, $9d, $eb, $6a, $94, $96, $1f, $9c, $b8, $3f, $a0
    // [120] "THIS IS A " (11→6 bytes)
    .byte $69, $f4, $ef, $4e, $c5, $40
    // [121] "YOU FEEL DISORIENTED." (22→12 bytes)
    .byte $c7, $85, $cb, $76, $54, $bd, $3f, $1e, $ef, $1b, $4a, $b4
    // [122] "YOU FEEL MUCH BETTER." (22→13 bytes)
    .byte $c7, $85, $cb, $76, $55, $40, $ce, $75, $f6, $b3, $68, $ad, $00
    // [123] "YOUR MIND FEELS CLEAR." (23→13 bytes)
    .byte $c7, $80, $d5, $3b, $c2, $dc, $b7, $64, $77, $39, $6c, $0a, $d0
    // [124] "YOU FEEL HEROIC!" (17→10 bytes)
    .byte $c7, $85, $cb, $76, $56, $7a, $3f, $dc, $c8, $40
    // [125] "YOU CAN'T SEE!" (15→9 bytes)
    .byte $c7, $85, $ce, $38, $49, $6a, $7b, $a4, $20
    // [126] "YOU FEEL DIZZY." (16→10 bytes)
    .byte $c7, $85, $cb, $76, $54, $bd, $71, $38, $b0, $b4
    // [127] "YOU SENSE NEARBY CREATURES." (28→15 bytes)
    .byte $c7, $85, $3d, $e1, $ed, $e6, $c0, $be, $c5, $cc, $76, $18, $07, $4d, $68
    // [128] "YOUR EYES TINGLE." (18→10 bytes)
    .byte $c7, $80, $dd, $c6, $9d, $6e, $f1, $59, $6a, $d0
    // [129] "THE AIR CRACKLES AROUND YOU." (29→16 bytes)
    .byte $69, $ed, $8e, $8d, $cc, $63, $32, $72, $d3, $b0, $3e, $1c, $2d, $c7, $82, $d0
    // [130] "YOU FEEL CLEANSED." (19→11 bytes)
    .byte $c7, $85, $cb, $76, $57, $39, $6c, $70, $f4, $ab, $40
    // [131] "YOUR WEAPON GLOWS BRIEFLY." (27→16 bytes)
    .byte $c7, $80, $d7, $76, $1e, $fe, $55, $65, $ee, $9d, $7c, $3d, $dc, $a5, $85, $a0
    // [132] "YOUR ARMOR GLOWS BRIEFLY." (26→15 bytes)
    .byte $c7, $80, $d8, $15, $3c, $6a, $b2, $f7, $4e, $be, $1e, $ee, $52, $c2, $d0
    // [133] "YOUR HANDS BEGIN TO GLOW." (26→15 bytes)
    .byte $c7, $80, $d9, $c7, $0a, $75, $f6, $ab, $de, $56, $fa, $ac, $bd, $d5, $a0
    // [134] "YOU HEAR A HIGH-PITCHED HUMMING." (33→20 bytes)
    .byte $c7, $85, $9e, $c0, $d8, $b3, $ea, $b3, $7e, $7b, $ad, $9c, $f4, $b6, $60, $a2, $9d, $e2, $ab, $40
    // [135] "YOU FEEL PROTECTED." (20→11 bytes)
    .byte $c7, $85, $cb, $76, $55, $e1, $f6, $dc, $db, $4a, $b4
    // [136] "YOU FEEL A STRANGE VIBRATION." (30→17 bytes)
    .byte $c7, $85, $cb, $76, $56, $29, $b0, $c7, $15, $da, $e7, $af, $86, $1b, $bf, $c5, $a0
    // [137] "AIM WHICH WAND (A-V)?" (22→15 bytes)
    .byte $8e, $a9, $5d, $9f, $73, $9d, $76, $38, $5a, $4b, $0f, $ce, $5c, $1f, $d0
    // [138] "USE WHICH STAFF (A-V)?" (23→15 bytes)
    .byte $03, $da, $ec, $fb, $9c, $e9, $b4, $65, $95, $25, $87, $e7, $2e, $0f, $e8
    // [139] "THAT IS NOT A WAND." (20→11 bytes)
    .byte $69, $c3, $5e, $9d, $e7, $b5, $8a, $ec, $70, $ab, $40
    // [140] "THAT IS NOT A STAFF." (21→11 bytes)
    .byte $69, $c3, $5e, $9d, $e7, $b5, $8a, $6d, $19, $64, $b4
    // [141] "NO CHARGES LEFT." (17→10 bytes)
    .byte $e7, $dc, $e7, $02, $ae, $9d, $96, $e4, $cb, $40
    // [142] "THE STAFF IS EMPTY." (20→12 bytes)
    .byte $69, $ed, $36, $8c, $b2, $bd, $3b, $aa, $3c, $d8, $5a, $00
    // [143] "A BOLT OF LIGHTNING SHOOTS FORTH!" (34→20 bytes)
    .byte $8a, $fb, $e4, $d7, $f2, $b2, $ea, $b3, $6e, $77, $8a, $d3, $9f, $fb, $1d, $cb, $c5, $a6, $42, $00
    // [144] "A BOLT OF FROST SHOOTS FORTH!" (30→17 bytes)
    .byte $8a, $fb, $e4, $d7, $f2, $b9, $0f, $9b, $53, $9f, $fb, $1d, $cb, $c5, $a6, $42, $00
    // [145] "THE MONSTER LOOKS CONFUSED." (28→16 bytes)
    .byte $69, $ed, $53, $f8, $6d, $a3, $65, $fe, $4c, $ee, $7f, $cc, $80, $f4, $ab, $40
    // [146] "THE CLOUD DISSIPATES." (22→13 bytes)
    .byte $69, $ed, $ce, $5e, $05, $a5, $e9, $9f, $5e, $86, $d3, $5a, $00
    // [147] "YOU CAN'T SEE TO READ!" (23→13 bytes)
    .byte $c7, $85, $ce, $38, $49, $6a, $7b, $b5, $be, $8e, $c1, $48, $40
    // [148] "STUDY WHICH BOOK (A-V)?" (24→16 bytes)
    .byte $36, $02, $e2, $bb, $3e, $e7, $3a, $fb, $fc, $9d, $25, $87, $e7, $2e, $0f, $e8
    // [149] "YOU CANNOT USE MAGIC." (22→13 bytes)
    .byte $c7, $85, $ce, $39, $cf, $6a, $07, $b5, $48, $57, $b9, $ad, $00
    // [150] "THAT IS NOT A BOOK." (20→11 bytes)
    .byte $69, $c3, $5e, $9d, $e7, $b5, $8a, $fb, $fc, $9a, $d0
    // [151] "YOU CANNOT READ THAT BOOK." (27→15 bytes)
    .byte $c7, $85, $ce, $39, $cf, $6a, $3b, $05, $ad, $38, $6a, $fb, $fc, $9a, $d0
    // [152] "YOU LEARN FROM THE BOOK!" (25→14 bytes)
    .byte $c7, $85, $96, $c0, $f2, $e4, $3e, $a5, $69, $ed, $7d, $fe, $4c, $84
    // [153] "NO NEW SPELLS TO LEARN." (24→13 bytes)
    .byte $e7, $de, $6b, $b4, $de, $d9, $48, $eb, $7d, $96, $c0, $f1, $68
    // [154] "NOT USING A LAMP." (18→10 bytes)
    .byte $e7, $b5, $03, $ef, $15, $b1, $65, $0a, $3c, $b4
    // [155] "YOU HAVE NO OIL." (17→10 bytes)
    .byte $c7, $85, $9c, $39, $db, $cf, $bf, $d9, $2d, $00
    // [156] "YOUR LAMP OVERFLOWS." (21→13 bytes)
    .byte $c7, $80, $d9, $42, $8f, $5f, $73, $a3, $94, $bd, $d3, $5a, $00
    // [157] "YOUR LAMP IS FULL." (19→11 bytes)
    .byte $c7, $80, $d9, $42, $8f, $5e, $9d, $c8, $25, $25, $a0
    // [158] "YOUR LAMP IS REFUELED." (23→13 bytes)
    .byte $c7, $80, $d9, $42, $8f, $5e, $9d, $1d, $c8, $36, $5a, $55, $a0
    // [159] "WELCOME TO LEVEL " (18→11 bytes)
    .byte $77, $65, $9f, $a9, $b5, $be, $cb, $5c, $ec, $aa, $00

// Huffman code table:
//   NULL   =         0100 (4 bits, freq=160)
//   A      =         1000 (4 bits, freq=212)
//   B      =      0111110 (7 bits, freq=28)
//   C      =       110011 (6 bits, freq=66)
//   D      =        00101 (5 bits, freq=75)
//   E      =         1101 (4 bits, freq=258)
//   F      =       110010 (6 bits, freq=64)
//   G      =       010101 (6 bits, freq=44)
//   H      =        10011 (5 bits, freq=113)
//   I      =        11101 (5 bits, freq=135)
//   K      =      0010011 (7 bits, freq=19)
//   L      =        10010 (5 bits, freq=110)
//   M      =       010100 (6 bits, freq=40)
//   N      =        11100 (5 bits, freq=131)
//   O      =         1111 (4 bits, freq=266)
//   P      =       011110 (6 bits, freq=53)
//   Q      =   0010010000 (10 bits, freq=1)
//   R      =         0001 (4 bits, freq=137)
//   S      =         0011 (4 bits, freq=159)
//   T      =         0110 (4 bits, freq=183)
//   U      =         0000 (4 bits, freq=136)
//   V      =      0111001 (7 bits, freq=24)
//   W      =       011101 (6 bits, freq=47)
//   X      =   0010010001 (10 bits, freq=1)
//   Y      =        11000 (5 bits, freq=124)
//   Z      =    011100010 (9 bits, freq=5)
//   SPACE  =          101 (3 bits, freq=466)
//   $21    =       001000 (6 bits, freq=34)
//   $27    =    001001001 (9 bits, freq=4)
//   $28    =     00100101 (8 bits, freq=11)
//   $29    =     01110000 (8 bits, freq=11)
//   $2c    =    011100011 (9 bits, freq=6)
//   $2d    =     01111110 (8 bits, freq=12)
//   $2e    =        01011 (5 bits, freq=91)
//   $3f    =     01111111 (8 bits, freq=16)
