// huffman_data.s — Generated by huff_encoder.py
// Source: data/huffman_strings.txt
// 210 strings, 4103 bytes uncompressed
// 2507 bytes compressed (61.1%)
// Tree: 120 bytes, Index: 420 bytes
// Total data: 3047 bytes

.const HUFF_STR_COUNT = 210
.const HSTR_INSULT_COUNT = 15

// Named string constants
.const HSTR_MAT_HITS = 15
.const HSTR_MAT_MISS = 16
.const HSTR_MAT_POISON = 17
.const HSTR_MAT_CONFUSE = 18
.const HSTR_MAT_PARALYZE = 19
.const HSTR_MAT_ACID = 20
.const HSTR_MAT_FEAR = 21
.const HSTR_MAT_SHRIEK = 22
.const HSTR_MM_BOLT = 23
.const HSTR_MM_BREATH = 24
.const HSTR_MM_SUMMON = 25
.const HSTR_MM_TELEPORT = 26
.const HSTR_MM_BLIND = 27
.const HSTR_MM_CONFUSE = 28
.const HSTR_MM_HEAL = 29
.const HSTR_RF_NO_WEAPON = 30
.const HSTR_RF_NO_AMMO = 31
.const HSTR_RF_FLIES = 32
.const HSTR_RF_MISSES = 33
.const HSTR_RF_HITS = 34
.const HSTR_EB_SPELL_HITS = 35
.const HSTR_EB_FIZZLE = 36
.const HSTR_TW_PROMPT = 37
.const HSTR_TW_SHATTERS = 38
.const HSTR_EFF_POISON_END = 39
.const HSTR_EFF_BLIND_END = 40
.const HSTR_EFF_CONFUSE_END = 41
.const HSTR_EFF_PARALYZE_END = 42
.const HSTR_EFF_FEAR_END = 43
.const HSTR_TTL_DIM = 44
.const HSTR_TTL_OUT = 45
.const HSTR_RECALL_ARRIVE = 46
.const HSTR_DL_YOU_SEE = 47
.const HSTR_DL_OPEN_DOOR = 48
.const HSTR_DL_CLOSED_DOOR = 49
.const HSTR_DL_STAIRS_DN = 50
.const HSTR_DL_STAIRS_UP = 51
.const HSTR_DL_TRAP = 52
.const HSTR_DL_RUBBLE = 53
.const HSTR_DL_WALL = 54
.const HSTR_DL_NOTHING = 55
.const HSTR_PTM_AFRAID = 56
.const HSTR_DF_TRAP_0 = 57
.const HSTR_DF_TRAP_1 = 58
.const HSTR_DF_TRAP_2 = 59
.const HSTR_DF_TRAP_3 = 60
.const HSTR_DF_TRAP_4 = 61
.const HSTR_DF_TRAP_5 = 62
.const HSTR_DF_DIRECTION = 63
.const HSTR_DF_DOOR_STUCK = 64
.const HSTR_DF_FOUND_TRAP = 65
.const HSTR_DF_FOUND_SECRET = 66
.const HSTR_DF_FOUND_NOTHING = 67
.const HSTR_DF_NO_DOOR = 68
.const HSTR_DF_ALREADY_OPEN = 69
.const HSTR_DF_ALREADY_CLOSED = 70
.const HSTR_DF_DOOR_OPENED = 71
.const HSTR_DF_DOOR_CLOSED = 72
.const HSTR_DF_YOU_FELL = 73
.const HSTR_DF_ARROW_HITS = 74
.const HSTR_DF_POISON_GAS = 75
.const HSTR_DF_TELEPORTED = 76
.const HSTR_DF_DART_HITS = 77
.const HSTR_DF_ROCKFALL = 78
.const HSTR_DF_DAMAGE_PRE = 79
.const HSTR_DF_DAMAGE_POST = 80
.const HSTR_DF_CON_DRAIN = 81
.const HSTR_DF_POISONED = 82
.const HSTR_PM_NO_CAST = 83
.const HSTR_PM_NO_PRAY = 84
.const HSTR_PM_NOT_KNOWN = 85
.const HSTR_PM_NO_MANA = 86
.const HSTR_PM_NO_EXP = 87
.const HSTR_PM_FAIL = 88
.const HSTR_PM_YOU_CAST = 89
.const HSTR_PM_YOU_PRAY = 90
.const HSTR_PM_TITLE_MAGE = 91
.const HSTR_PM_TITLE_PRAY = 92
.const HSTR_PM_FOOTER_CAST = 93
.const HSTR_PM_FOOTER_PRAY = 94
.const HSTR_PM_LEARNED = 95
.const HSTR_PIW_WEAR_PROMPT = 96
.const HSTR_PIW_TAKEOFF_PROMPT = 97
.const HSTR_PIW_NOTHING = 98
.const HSTR_PIW_NEVERMIND = 99
.const HSTR_PIW_CURSED = 100
.const HSTR_PIW_NO_FOOD = 101
.const HSTR_PIW_WIELD = 102
.const HSTR_PIW_WEARING = 103
.const HSTR_PIW_TAKEOFF = 104
.const HSTR_PIW_EAT = 105
.const HSTR_PIW_DELICIOUS = 106
.const HSTR_PIW_YUCK = 107
.const HSTR_PIQ_QUAFF_PROMPT = 108
.const HSTR_PIQ_READ_PROMPT = 109
.const HSTR_PIQ_FEEL_BETTER = 110
.const HSTR_PIQ_SPEED = 111
.const HSTR_PIQ_TERRIBLE = 112
.const HSTR_PIQ_NOTHING = 113
.const HSTR_PIQ_LIGHT = 114
.const HSTR_PIQ_IDENTIFY_PROMPT = 115
.const HSTR_PIQ_THISIS = 116
.const HSTR_PIQ_TELEPORT = 117
.const HSTR_PIQ_MUCH_BETTER = 118
.const HSTR_PIQ_MIND_CLEAR = 119
.const HSTR_PIQ_HEROIC = 120
.const HSTR_PIQ_CANT_SEE = 121
.const HSTR_PIQ_DIZZY = 122
.const HSTR_PIQ_SENSE = 123
.const HSTR_PIQ_EYES_TINGLE = 124
.const HSTR_PIQ_AIR_CRACKLE = 125
.const HSTR_PIQ_CLEANSED = 126
.const HSTR_PIQ_WPN_GLOW = 127
.const HSTR_PIQ_ARM_GLOW = 128
.const HSTR_PIQ_HANDS_GLOW = 129
.const HSTR_PIQ_HUMMING = 130
.const HSTR_PIQ_PROTECTED = 131
.const HSTR_PIQ_VIBRATION = 132
.const HSTR_PIW_AIM_PROMPT = 133
.const HSTR_PIW_USE_PROMPT = 134
.const HSTR_PIW_NO_CHARGES = 135
.const HSTR_PIW_STAFF_EMPTY = 136
.const HSTR_PIW_WAND_BOLT = 137
.const HSTR_PIW_WAND_FROST = 138
.const HSTR_PIW_WAND_CLOUD = 139
.const HSTR_PIW_WAND_MISS = 140
.const HSTR_PIQ_CANT_READ = 141
.const HSTR_IGS_PROMPT = 142
.const HSTR_IGS_NO_MAGIC = 143
.const HSTR_IGS_WRONG_TYPE = 144
.const HSTR_IGS_SUCCESS = 145
.const HSTR_IGS_NO_NEW = 146
.const HSTR_PIR_NOT_LAMP = 147
.const HSTR_PIR_NO_OIL = 148
.const HSTR_PIR_OVERFLOW = 149
.const HSTR_PIR_FULL = 150
.const HSTR_PIR_REFUELED = 151
.const HSTR_CMB_LVLUP = 152
.const HSTR_UIS_GOLD = 153
.const HSTR_UIS_BIG_GOLD = 154
.const HSTR_UIS_MENU = 155
.const HSTR_UIS_BUY_WHICH = 156
.const HSTR_UIS_PRICE = 157
.const HSTR_UIS_GP_BUY = 158
.const HSTR_UIS_BOUGHT = 159
.const HSTR_UIS_NO_AFFORD = 160
.const HSTR_UIS_PACK_FULL = 161
.const HSTR_UIS_SELL_TITLE = 162
.const HSTR_UIS_SELL_WHICH = 163
.const HSTR_UIS_OFFER = 164
.const HSTR_UIS_GP_SELL = 165
.const HSTR_UIS_SOLD = 166
.const HSTR_UIS_NO_BUY = 167
.const HSTR_UIS_WORTHLESS = 168
.const HSTR_UIS_STORE_FULL = 169
.const HSTR_UIS_CURSED = 170
.const HSTR_HG_ASKS = 171
.const HSTR_HG_OFFERS = 172
.const HSTR_HG_GP = 173
.const HSTR_HG_YOUR_OFFER = 174
.const HSTR_HG_YOUR_PRICE = 175
.const HSTR_HG_COUNTER = 176
.const HSTR_HG_QMARK = 177
.const HSTR_HG_FINAL = 178
.const HSTR_HG_TAKE = 179
.const HSTR_HG_KICKED = 180
.const HSTR_HG_AGREED = 181
.const HSTR_TUN_DIG_GRANITE = 182
.const HSTR_TUN_DIG_MAGMA = 183
.const HSTR_TUN_DIG_QUARTZ = 184
.const HSTR_TUN_FINISHED = 185
.const HSTR_TUN_FOUND = 186
.const HSTR_TUN_PERMANENT = 187
.const HSTR_TUN_NOTHING = 188
.const HSTR_TUN_RUBBLE = 189
.const HSTR_TUN_NO_TOOL = 190
.const HSTR_IPU_NOTHING = 191
.const HSTR_IPU_FOUND = 192
.const HSTR_IPU_GOLD = 193
.const HSTR_IPU_PICKED = 194
.const HSTR_IDR_PROMPT = 195
.const HSTR_IDR_DROP = 196
.const HSTR_IDR_FLOOR_FULL = 197
.const HSTR_PID_TERRIBLE = 198
.const HSTR_PID_BAD = 199
.const HSTR_PID_AVERAGE = 200
.const HSTR_PID_GOOD = 201
.const HSTR_PID_EXCELLENT = 202
.const HSTR_BASH_SMASH = 203
.const HSTR_BASH_CRASH = 204
.const HSTR_BASH_HOLDS = 205
.const HSTR_BASH_OFFBAL = 206
.const HSTR_BASH_EMPTY = 207
.const HSTR_BASH_STUNNED = 208
.const HSTR_BASH_IGNORES = 209

// Huffman tree: 60 internal nodes
// Children: $00-$7E = node index, $80+ = leaf (& $7F = screencode)
huff_tree_left:
    .byte $01, $03, $05, $07, $09, $0b, $0c, $0e, $0f, $80, $81, $12, $8f, $85, $16, $84, $18, $19, $8c, $88, $1c, $95, $a1, $1e, $1f, $20, $21, $90, $83, $a8, $d4, $24, $bf, $96, $27, $28, $2a, $ce, $d3, $ad, $a7, $9a, $2f, $31, $ac, $34, $c1, $af, $b5, $c3, $c8, $36, $38, $c4, $bd, $cf, $3b, $91, $b3, $be
huff_tree_right:
    .byte $02, $04, $06, $08, $0a, $a0, $0d, $93, $94, $10, $11, $13, $14, $15, $d9, $17, $ae, $1a, $1b, $8e, $89, $92, $1d, $97, $99, $8d, $87, $22, $86, $23, $a9, $8b, $25, $26, $82, $29, $2b, $2c, $2d, $2e, $d7, $c9, $30, $32, $33, $ba, $35, $d2, $c7, $d0, $c5, $37, $d1, $c2, $39, $3a, $98, $c6, $b6, $d5

// String index: 16-bit byte offsets into huff_str_data
huff_str_index:
    .word $0000  // [0] "You will have to do better tha"
    .word $0015  // [1] "That is an insult!"
    .word $0020  // [2] "Do you wish to do business or "
    .word $0034  // [3] "Hah! Try again."
    .word $003f  // [4] "Ridiculous!"
    .word $0047  // [5] "You have got to be kidding!"
    .word $0058  // [6] "You had better be kidding!"
    .word $0068  // [7] "You try my patience."
    .word $0075  // [8] "I do not hear you."
    .word $0080  // [9] "Hmmm, nice weather we are havi"
    .word $0095  // [10] "I must have heard you wrong."
    .word $00a6  // [11] "What was that?"
    .word $00af  // [12] "I am sorry, say that again."
    .word $00c0  // [13] "What did you say?"
    .word $00cb  // [14] "Sorry, what was that again?"
    .word $00dc  // [15] @MAT_HITS " hits you."
    .word $00e2  // [16] @MAT_MISS " misses you."
    .word $00ea  // [17] @MAT_POISON " poisons you."
    .word $00f2  // [18] @MAT_CONFUSE " confuses you."
    .word $00fb  // [19] @MAT_PARALYZE " paralyzes you."
    .word $0105  // [20] @MAT_ACID " spits acid on you."
    .word $0110  // [21] @MAT_FEAR " frightens you."
    .word $011a  // [22] @MAT_SHRIEK "You hear a horrible shriek!"
    .word $012a  // [23] @MM_BOLT " casts a bolt!"
    .word $0133  // [24] @MM_BREATH " breathes fire!"
    .word $013d  // [25] @MM_SUMMON " summons help!"
    .word $0146  // [26] @MM_TELEPORT " teleports you!"
    .word $014f  // [27] @MM_BLIND " blinds you!"
    .word $0157  // [28] @MM_CONFUSE " confuses you!"
    .word $0160  // [29] @MM_HEAL " heals itself."
    .word $0169  // [30] @RF_NO_WEAPON "No ranged weapon."
    .word $0174  // [31] @RF_NO_AMMO "No ammo."
    .word $017a  // [32] @RF_FLIES " flies away."
    .word $0182  // [33] @RF_MISSES " misses"
    .word $0187  // [34] @RF_HITS " hits"
    .word $018b  // [35] @EB_SPELL_HITS "Your spell hits"
    .word $0194  // [36] @EB_FIZZLE "Your spell fizzles out."
    .word $01a3  // [37] @TW_PROMPT "Throw which item (a-v)?"
    .word $01b3  // [38] @TW_SHATTERS " shatters!"
    .word $01b9  // [39] @EFF_POISON_END "You feel better."
    .word $01c3  // [40] @EFF_BLIND_END "You can see again."
    .word $01ce  // [41] @EFF_CONFUSE_END "You feel less confused."
    .word $01dc  // [42] @EFF_PARALYZE_END "You can move again."
    .word $01e8  // [43] @EFF_FEAR_END "You feel bolder now."
    .word $01f4  // [44] @TTL_DIM "Your light is growing dim."
    .word $0204  // [45] @TTL_OUT "Your light has gone out."
    .word $0212  // [46] @RECALL_ARRIVE "You feel yourself yanked away!"
    .word $0225  // [47] @DL_YOU_SEE "You see a "
    .word $022b  // [48] @DL_OPEN_DOOR "You see an open door."
    .word $0237  // [49] @DL_CLOSED_DOOR "You see a closed door."
    .word $0244  // [50] @DL_STAIRS_DN "You see a staircase down."
    .word $0252  // [51] @DL_STAIRS_UP "You see a staircase up."
    .word $025f  // [52] @DL_TRAP "You see a trap."
    .word $0268  // [53] @DL_RUBBLE "You see rubble."
    .word $0272  // [54] @DL_WALL "You see a wall."
    .word $027b  // [55] @DL_NOTHING "You see nothing special."
    .word $0289  // [56] @PTM_AFRAID "You are too afraid!"
    .word $0294  // [57] @DF_TRAP_0 "an open pit"
    .word $029b  // [58] @DF_TRAP_1 "an arrow trap"
    .word $02a3  // [59] @DF_TRAP_2 "a poison gas trap"
    .word $02ad  // [60] @DF_TRAP_3 "a teleport trap"
    .word $02b6  // [61] @DF_TRAP_4 "a poison dart"
    .word $02be  // [62] @DF_TRAP_5 "a rockfall trap"
    .word $02c8  // [63] @DF_DIRECTION "Direction?"
    .word $02d0  // [64] @DF_DOOR_STUCK "The door is stuck."
    .word $02db  // [65] @DF_FOUND_TRAP "You found a trap!"
    .word $02e6  // [66] @DF_FOUND_SECRET "You found a secret door!"
    .word $02f4  // [67] @DF_FOUND_NOTHING "You found nothing."
    .word $02ff  // [68] @DF_NO_DOOR "No door there."
    .word $0308  // [69] @DF_ALREADY_OPEN "The door is already open."
    .word $0317  // [70] @DF_ALREADY_CLOSED "It is already closed."
    .word $0324  // [71] @DF_DOOR_OPENED "You open the door."
    .word $032f  // [72] @DF_DOOR_CLOSED "You close the door."
    .word $033a  // [73] @DF_YOU_FELL "You fell into a pit!"
    .word $0346  // [74] @DF_ARROW_HITS "An arrow hits you!"
    .word $0352  // [75] @DF_POISON_GAS "A cloud of gas surrounds you!"
    .word $0364  // [76] @DF_TELEPORTED "You are teleported!"
    .word $036f  // [77] @DF_DART_HITS "A dart hits you!"
    .word $0379  // [78] @DF_ROCKFALL "Rocks fall on you!"
    .word $0385  // [79] @DF_DAMAGE_PRE "You take "
    .word $038b  // [80] @DF_DAMAGE_POST " damage."
    .word $0391  // [81] @DF_CON_DRAIN "You feel weakened."
    .word $039c  // [82] @DF_POISONED "You feel poisoned."
    .word $03a7  // [83] @PM_NO_CAST "You cannot cast spells."
    .word $03b5  // [84] @PM_NO_PRAY "You cannot pray."
    .word $03bf  // [85] @PM_NOT_KNOWN "You don't know that spell."
    .word $03cf  // [86] @PM_NO_MANA "Not enough mana."
    .word $03d9  // [87] @PM_NO_EXP "You're not experienced enough."
    .word $03ec  // [88] @PM_FAIL "Your spell fails."
    .word $03f7  // [89] @PM_YOU_CAST "Spell book (a-v)?"
    .word $0404  // [90] @PM_YOU_PRAY "Prayer book (a-v)?"
    .word $0412  // [91] @PM_TITLE_MAGE "."
    .word $0414  // [92] @PM_TITLE_PRAY "."
    .word $0416  // [93] @PM_FOOTER_CAST "Cast which? (a-p, ESC)"
    .word $0428  // [94] @PM_FOOTER_PRAY "Pray which? (a-p, ESC)"
    .word $043a  // [95] @PM_LEARNED "."
    .word $043c  // [96] @PIW_WEAR_PROMPT "Wear which item (a-v)?"
    .word $044c  // [97] @PIW_TAKEOFF_PROMPT "Take off which item (a-h)?"
    .word $045e  // [98] @PIW_NOTHING "You have nothing there."
    .word $046c  // [99] @PIW_NEVERMIND "Never mind."
    .word $0474  // [100] @PIW_CURSED "You cannot remove it, it is cu"
    .word $0489  // [101] @PIW_NO_FOOD "You have no food."
    .word $0493  // [102] @PIW_WIELD "You are wielding a "
    .word $049e  // [103] @PIW_WEARING "You are wearing a "
    .word $04a9  // [104] @PIW_TAKEOFF "You take off the "
    .word $04b3  // [105] @PIW_EAT "You eat the "
    .word $04ba  // [106] @PIW_DELICIOUS ". Delicious!"
    .word $04c3  // [107] @PIW_YUCK ". Yuck!"
    .word $04c9  // [108] @PIQ_QUAFF_PROMPT "Quaff which potion (a-v)?"
    .word $04db  // [109] @PIQ_READ_PROMPT "Read which scroll (a-v)?"
    .word $04ec  // [110] @PIQ_FEEL_BETTER "You feel better."
    .word $04f6  // [111] @PIQ_SPEED "You feel yourself moving faste"
    .word $050a  // [112] @PIQ_TERRIBLE "That tasted terrible!"
    .word $0517  // [113] @PIQ_NOTHING "Nothing seems to happen."
    .word $0526  // [114] @PIQ_LIGHT "The area fills with light."
    .word $0536  // [115] @PIQ_IDENTIFY_PROMPT "Identify which item (a-v)?"
    .word $0548  // [116] @PIQ_THISIS "This is a "
    .word $054e  // [117] @PIQ_TELEPORT "You feel disoriented."
    .word $055b  // [118] @PIQ_MUCH_BETTER "You feel much better."
    .word $0568  // [119] @PIQ_MIND_CLEAR "Your mind feels clear."
    .word $0576  // [120] @PIQ_HEROIC "You feel heroic!"
    .word $0580  // [121] @PIQ_CANT_SEE "You can't see!"
    .word $0589  // [122] @PIQ_DIZZY "You feel dizzy."
    .word $0594  // [123] @PIQ_SENSE "You sense nearby creatures."
    .word $05a4  // [124] @PIQ_EYES_TINGLE "Your eyes tingle."
    .word $05af  // [125] @PIQ_AIR_CRACKLE "The air crackles around you."
    .word $05c0  // [126] @PIQ_CLEANSED "You feel cleansed."
    .word $05cb  // [127] @PIQ_WPN_GLOW "Your weapon glows briefly."
    .word $05dc  // [128] @PIQ_ARM_GLOW "Your armor glows briefly."
    .word $05ec  // [129] @PIQ_HANDS_GLOW "Your hands begin to glow."
    .word $05fb  // [130] @PIQ_HUMMING "You hear a high-pitched hummin"
    .word $060f  // [131] @PIQ_PROTECTED "You feel protected."
    .word $061b  // [132] @PIQ_VIBRATION "You feel a strange vibration."
    .word $062c  // [133] @PIW_AIM_PROMPT "Aim which wand (a-v)?"
    .word $063b  // [134] @PIW_USE_PROMPT "Use which staff (a-v)?"
    .word $064b  // [135] @PIW_NO_CHARGES "No charges left."
    .word $0655  // [136] @PIW_STAFF_EMPTY "The staff is empty."
    .word $0661  // [137] @PIW_WAND_BOLT "A bolt of lightning shoots for"
    .word $0675  // [138] @PIW_WAND_FROST "A bolt of frost shoots forth!"
    .word $0686  // [139] @PIW_WAND_CLOUD "The monster looks confused."
    .word $0697  // [140] @PIW_WAND_MISS "The cloud dissipates."
    .word $06a4  // [141] @PIQ_CANT_READ "You can't see to read!"
    .word $06b1  // [142] @IGS_PROMPT "Study which book (a-v)?"
    .word $06c2  // [143] @IGS_NO_MAGIC "You cannot use magic."
    .word $06cf  // [144] @IGS_WRONG_TYPE "You cannot read that book."
    .word $06de  // [145] @IGS_SUCCESS "You learn from the book!"
    .word $06ed  // [146] @IGS_NO_NEW "No new spells to learn."
    .word $06fb  // [147] @PIR_NOT_LAMP "Not using a lamp."
    .word $0706  // [148] @PIR_NO_OIL "You have no oil."
    .word $0710  // [149] @PIR_OVERFLOW "Your lamp overflows."
    .word $071d  // [150] @PIR_FULL "Your lamp is full."
    .word $0728  // [151] @PIR_REFUELED "Your lamp is refueled."
    .word $0736  // [152] @CMB_LVLUP "Welcome to level "
    .word $0741  // [153] @UIS_GOLD "Gold: "
    .word $0746  // [154] @UIS_BIG_GOLD ">65535"
    .word $074f  // [155] @UIS_MENU "B)uy  S)ell  Q)uit"
    .word $075c  // [156] @UIS_BUY_WHICH "Buy which item? (a-l)"
    .word $076b  // [157] @UIS_PRICE "Price: "
    .word $0771  // [158] @UIS_GP_BUY " gp. Buy? (Y/N)"
    .word $077d  // [159] @UIS_BOUGHT "Bought!"
    .word $0783  // [160] @UIS_NO_AFFORD "You cannot afford that."
    .word $0791  // [161] @UIS_PACK_FULL "Your pack is full."
    .word $079d  // [162] @UIS_SELL_TITLE "Sell Items"
    .word $07a4  // [163] @UIS_SELL_WHICH "Sell which item? (a-v)"
    .word $07b4  // [164] @UIS_OFFER "Offer: "
    .word $07ba  // [165] @UIS_GP_SELL " gp. Sell? (Y/N)"
    .word $07c6  // [166] @UIS_SOLD "Sold!"
    .word $07ca  // [167] @UIS_NO_BUY "We don't buy that."
    .word $07d6  // [168] @UIS_WORTHLESS "That is worthless."
    .word $07e1  // [169] @UIS_STORE_FULL "The store is full."
    .word $07ec  // [170] @UIS_CURSED "That item is cursed."
    .word $07f8  // [171] @HG_ASKS "Asks "
    .word $07fc  // [172] @HG_OFFERS "Offers "
    .word $0802  // [173] @HG_GP " gp."
    .word $0805  // [174] @HG_YOUR_OFFER "Your offer? (Q=cancel)"
    .word $0815  // [175] @HG_YOUR_PRICE "Your price? (Q=cancel)"
    .word $0825  // [176] @HG_COUNTER "How about "
    .word $082c  // [177] @HG_QMARK " gp?"
    .word $0830  // [178] @HG_FINAL "Final offer: "
    .word $083a  // [179] @HG_TAKE "Take it? (Y/N)"
    .word $0845  // [180] @HG_KICKED "Get out of my store!"
    .word $0851  // [181] @HG_AGREED "Agreed!"
    .word $0857  // [182] @TUN_DIG_GRANITE "You dig in the granite wall."
    .word $0868  // [183] @TUN_DIG_MAGMA "You dig in the magma."
    .word $0875  // [184] @TUN_DIG_QUARTZ "You dig in the quartz vein."
    .word $0887  // [185] @TUN_FINISHED "You have finished the tunnel."
    .word $0898  // [186] @TUN_FOUND "You have found something!"
    .word $08a8  // [187] @TUN_PERMANENT "This seems to be permanent roc"
    .word $08bb  // [188] @TUN_NOTHING "There is nothing to tunnel her"
    .word $08ce  // [189] @TUN_RUBBLE "The rubble crumbles."
    .word $08dc  // [190] @TUN_NO_TOOL "You dig with your hands, makin"
    .word $08f7  // [191] @IPU_NOTHING "You see nothing here."
    .word $0903  // [192] @IPU_FOUND "You found "
    .word $090a  // [193] @IPU_GOLD " gold pieces."
    .word $0912  // [194] @IPU_PICKED "You picked up a "
    .word $091c  // [195] @IDR_PROMPT "Drop which item (a-v)?"
    .word $092c  // [196] @IDR_DROP "You drop a "
    .word $0933  // [197] @IDR_FLOOR_FULL "No room on the floor."
    .word $0940  // [198] @PID_TERRIBLE "Sense: Terrible"
    .word $094b  // [199] @PID_BAD "Sense: Bad"
    .word $0953  // [200] @PID_AVERAGE "Sense: Average"
    .word $095d  // [201] @PID_GOOD "Sense: Good"
    .word $0965  // [202] @PID_EXCELLENT "Sense: Excellent"
    .word $0971  // [203] @BASH_SMASH "You smash into the door!"
    .word $097f  // [204] @BASH_CRASH "The door crashes open!"
    .word $098c  // [205] @BASH_HOLDS "The door holds firm."
    .word $0999  // [206] @BASH_OFFBAL "You are off balance."
    .word $09a5  // [207] @BASH_EMPTY "You bash at empty space."
    .word $09b4  // [208] @BASH_STUNNED " appears stunned!"
    .word $09bf  // [209] @BASH_IGNORES " ignores your bash!"

// Compressed string data (2507 bytes)
huff_str_data:
    // [0] "You will have to do better than that!" (38→21 bytes)
    .byte $0e, $7a, $97, $b8, $42, $c9, $9e, $75, $3c, $a4, $cb, $1f, $8c, $fb, $f4, $e4, $d3, $a7, $26, $30, $10
    // [1] "That is an insult!" (19→11 bytes)
    .byte $29, $26, $3b, $b1, $ad, $3b, $b9, $8f, $a0, $60, $20
    // [2] "Do you wish to do business or not?" (35→20 bytes)
    .byte $8d, $b2, $ab, $9e, $a5, $ec, $65, $4f, $29, $32, $c7, $f0, $ee, $7c, $23, $73, $f6, $78, $6e, $10
    // [3] "Hah! Try again." (16→11 bytes)
    .byte $51, $9a, $40, $52, $9f, $56, $b3, $ed, $b9, $ad, $00
    // [4] "Ridiculous!" (12→8 bytes)
    .byte $50, $76, $4d, $e9, $e8, $67, $84, $04
    // [5] "You have got to be kidding!" (28→17 bytes)
    .byte $0e, $7a, $c9, $9e, $75, $7f, $0e, $9e, $58, $fd, $54, $ec, $84, $dc, $df, $01, $00
    // [6] "You had better be kidding!" (27→16 bytes)
    .byte $0e, $7a, $c9, $89, $63, $f1, $9f, $7e, $c7, $ea, $a7, $64, $26, $e6, $f8, $08
    // [7] "You try my patience." (21→13 bytes)
    .byte $0e, $7a, $9f, $d5, $ae, $ab, $62, $63, $df, $4f, $4e, $5a, $00
    // [8] "I do not hear you." (19→11 bytes)
    .byte $07, $d2, $65, $9e, $1d, $97, $37, $ea, $b9, $e5, $a0
    // [9] "Hmmm, nice weather we are having." (34→21 bytes)
    .byte $51, $9d, $75, $d7, $35, $9e, $f4, $ea, $5f, $31, $cb, $bf, $4b, $ea, $df, $eb, $26, $79, $b9, $be, $b4
    // [10] "I must have heard you wrong." (29→17 bytes)
    .byte $07, $d7, $7c, $27, $64, $cf, $3a, $cb, $9b, $e4, $aa, $e7, $a9, $7f, $c9, $be, $b4
    // [11] "What was that?" (15→9 bytes)
    .byte $06, $c9, $8e, $96, $c3, $4e, $4c, $6e, $10
    // [12] "I am sorry, say that again." (28→17 bytes)
    .byte $07, $d6, $76, $8e, $7f, $ea, $b9, $a8, $b2, $b4, $e4, $c7, $59, $f6, $dc, $d6, $80
    // [13] "What did you say?" (18→11 bytes)
    .byte $06, $c9, $8e, $93, $64, $aa, $e7, $a8, $b2, $ae, $10
    // [14] "Sorry, what was that again?" (28→17 bytes)
    .byte $7a, $cf, $fd, $57, $35, $2e, $4c, $74, $b6, $1a, $72, $63, $ac, $fb, $6e, $6e, $10
    // [15] " hits you." (11→6 bytes)
    .byte $b2, $d9, $8d, $57, $3c, $b4
    // [16] " misses you." (13→8 bytes)
    .byte $ae, $ec, $47, $86, $ab, $9e, $5a, $00
    // [17] " poisons you." (14→8 bytes)
    .byte $b1, $66, $c7, $26, $35, $5c, $f2, $d0
    // [18] " confuses you." (15→9 bytes)
    .byte $ba, $64, $f5, $f0, $f0, $d5, $73, $cb, $40
    // [19] " paralyzes you." (16→10 bytes)
    .byte $b1, $37, $da, $0a, $83, $b8, $6a, $b9, $e5, $a0
    // [20] " spits acid on you." (20→11 bytes)
    .byte $a3, $16, $cc, $6b, $69, $b2, $5c, $9d, $57, $3c, $b4
    // [21] " frightens you." (16→10 bytes)
    .byte $ba, $ff, $6f, $c8, $fa, $63, $55, $cf, $2d, $00
    // [22] "You hear a horrible shriek!" (28→16 bytes)
    .byte $0e, $7a, $cb, $9b, $f5, $ac, $b3, $ff, $dc, $78, $75, $19, $7f, $7c, $a4, $04
    // [23] " casts a bolt!" (15→9 bytes)
    .byte $ba, $30, $98, $d6, $b1, $f2, $06, $02, $00
    // [24] " breathes fire!" (16→10 bytes)
    .byte $b1, $ff, $cc, $72, $e1, $ba, $ef, $fc, $02, $00
    // [25] " summons help!" (15→9 bytes)
    .byte $a3, $e7, $5d, $c9, $8d, $97, $42, $20, $10
    // [26] " teleports you!" (16→9 bytes)
    .byte $a7, $d0, $e8, $b3, $e6, $35, $5c, $f0, $08
    // [27] " blinds you!" (13→8 bytes)
    .byte $b1, $e1, $b9, $90, $6a, $b9, $e0, $10
    // [28] " confuses you!" (15→9 bytes)
    .byte $ba, $64, $f5, $f0, $f0, $d5, $73, $c0, $20
    // [29] " heals itself." (15→9 bytes)
    .byte $b2, $e6, $80, $dd, $98, $f4, $35, $5a, $00
    // [30] "No ranged weapon." (18→11 bytes)
    .byte $72, $cb, $f6, $9b, $fc, $4a, $5f, $34, $59, $35, $a0
    // [31] "No ammo." (9→6 bytes)
    .byte $72, $ca, $ce, $bb, $8b, $40
    // [32] " flies away." (13→8 bytes)
    .byte $ba, $c3, $7c, $35, $8b, $65, $56, $80
    // [33] " misses" (8→5 bytes)
    .byte $ae, $ec, $47, $85, $00
    // [34] " hits" (6→4 bytes)
    .byte $b2, $d9, $8a, $00
    // [35] "Your spell hits" (16→9 bytes)
    .byte $0e, $7b, $f4, $62, $e8, $42, $cb, $66, $28
    // [36] "Your spell fizzles out." (24→15 bytes)
    .byte $0e, $7b, $f4, $62, $e8, $42, $eb, $b0, $70, $3a, $1c, $37, $3c, $6b, $40
    // [37] "Throw which item (a-v)?" (24→16 bytes)
    .byte $29, $2f, $e1, $74, $b9, $6f, $49, $5d, $9f, $3b, $41, $34, $63, $c2, $ae, $10
    // [38] " shatters!" (11→6 bytes)
    .byte $a3, $26, $33, $ef, $88, $08
    // [39] "You feel better." (17→10 bytes)
    .byte $0e, $7a, $eb, $dd, $0b, $1f, $8c, $fb, $eb, $40
    // [40] "You can see again." (19→11 bytes)
    .byte $0e, $7a, $e8, $d3, $a3, $dd, $59, $f6, $dc, $d6, $80
    // [41] "You feel less confused." (24→14 bytes)
    .byte $0e, $7a, $eb, $dd, $0b, $0e, $11, $ba, $64, $f5, $f0, $f1, $16, $80
    // [42] "You can move again." (20→12 bytes)
    .byte $0e, $7a, $e8, $d3, $ae, $e3, $ce, $ac, $fb, $6e, $6b, $40
    // [43] "You feel bolder now." (21→12 bytes)
    .byte $0e, $7a, $eb, $dd, $0b, $1f, $20, $4e, $fd, $9e, $16, $b4
    // [44] "Your light is growing dim." (27→16 bytes)
    .byte $0e, $7b, $f6, $1b, $7e, $47, $76, $35, $ff, $e1, $7b, $9b, $f4, $9b, $75, $68
    // [45] "Your light has gone out." (25→14 bytes)
    .byte $0e, $7b, $f6, $1b, $7e, $47, $64, $c3, $5f, $c9, $f5, $cf, $1a, $d0
    // [46] "You feel yourself yanked away!" (31→19 bytes)
    .byte $0e, $7a, $eb, $dd, $0a, $ae, $7b, $e3, $d0, $d6, $aa, $d3, $53, $c4, $ac, $5b, $2a, $02, $00
    // [47] "You see a " (11→6 bytes)
    .byte $0e, $7a, $8f, $75, $6a, $80
    // [48] "You see an open door." (22→12 bytes)
    .byte $0e, $7a, $8f, $75, $69, $dc, $8b, $a7, $49, $99, $f5, $a0
    // [49] "You see a closed door." (23→13 bytes)
    .byte $0e, $7a, $8f, $75, $6b, $a4, $30, $78, $94, $99, $9f, $5a, $00
    // [50] "You see a staircase down." (26→14 bytes)
    .byte $0e, $7a, $8f, $75, $6a, $26, $db, $fe, $8c, $3d, $49, $85, $cd, $68
    // [51] "You see a staircase up." (24→13 bytes)
    .byte $0e, $7a, $8f, $75, $6a, $26, $db, $fe, $8c, $3d, $7d, $12, $d0
    // [52] "You see a trap." (16→9 bytes)
    .byte $0e, $7a, $8f, $75, $6a, $7f, $68, $96, $80
    // [53] "You see rubble." (16→10 bytes)
    .byte $0e, $7a, $8f, $75, $ff, $a3, $c7, $87, $2d, $00
    // [54] "You see a wall." (16→9 bytes)
    .byte $0e, $7a, $8f, $75, $6a, $5b, $42, $0b, $40
    // [55] "You see nothing special." (25→14 bytes)
    .byte $0e, $7a, $8f, $75, $9e, $1c, $b7, $37, $e8, $c5, $da, $6d, $a0, $b4
    // [56] "You are too afraid!" (20→11 bytes)
    .byte $0e, $7a, $b7, $fa, $9e, $65, $6d, $7e, $db, $20, $08
    // [57] "an open pit" (12→7 bytes)
    .byte $69, $dc, $8b, $a7, $62, $d9, $a0
    // [58] "an arrow trap" (14→8 bytes)
    .byte $69, $d6, $ff, $f0, $ba, $7f, $68, $90
    // [59] "a poison gas trap" (18→10 bytes)
    .byte $6b, $16, $6c, $72, $75, $f6, $1a, $7f, $68, $90
    // [60] "a teleport trap" (16→9 bytes)
    .byte $6a, $7d, $0e, $8b, $3e, $74, $fe, $d1, $20
    // [61] "a poison dart" (14→8 bytes)
    .byte $6b, $16, $6c, $72, $74, $8d, $f3, $40
    // [62] "a rockfall trap" (16→10 bytes)
    .byte $6b, $fc, $d1, $4e, $ad, $08, $53, $fb, $44, $80
    // [63] "Direction?" (11→8 bytes)
    .byte $8d, $b7, $fe, $d0, $f7, $93, $70, $80
    // [64] "The door is stuck." (19→11 bytes)
    .byte $29, $2e, $a4, $cc, $fd, $d8, $d1, $3f, $68, $a5, $68
    // [65] "You found a trap!" (18→11 bytes)
    .byte $0e, $7a, $eb, $9e, $99, $2b, $53, $fb, $44, $02, $00
    // [66] "You found a secret door!" (25→14 bytes)
    .byte $0e, $7a, $eb, $9e, $99, $2b, $51, $ed, $3f, $c7, $49, $99, $f0, $10
    // [67] "You found nothing." (19→11 bytes)
    .byte $0e, $7a, $eb, $9e, $99, $2c, $f0, $e5, $b9, $be, $b4
    // [68] "No door there." (15→9 bytes)
    .byte $72, $ca, $4c, $cf, $d3, $97, $7f, $96, $80
    // [69] "The door is already open." (26→15 bytes)
    .byte $29, $2e, $a4, $cc, $fd, $d8, $d6, $87, $f9, $88, $ad, $c8, $ba, $6b, $40
    // [70] "It is already closed." (22→13 bytes)
    .byte $07, $9d, $d8, $d6, $87, $f9, $88, $ad, $d2, $18, $3c, $45, $a0
    // [71] "You open the door." (19→11 bytes)
    .byte $0e, $7a, $e4, $5d, $3a, $72, $ea, $4c, $cf, $ad, $00
    // [72] "You close the door." (20→11 bytes)
    .byte $0e, $7a, $e9, $0c, $1e, $a7, $2e, $a4, $cc, $fa, $d0
    // [73] "You fell into a pit!" (21→12 bytes)
    .byte $0e, $7a, $eb, $d0, $85, $dc, $cf, $2b, $58, $b6, $60, $20
    // [74] "An arrow hits you!" (19→12 bytes)
    .byte $8d, $4e, $b7, $ff, $85, $d9, $6c, $c6, $ab, $9e, $01, $00
    // [75] "A cloud of gas surrounds you!" (30→18 bytes)
    .byte $8d, $5d, $21, $9e, $25, $cd, $6b, $ec, $34, $7d, $ff, $e7, $a6, $41, $aa, $e7, $80, $40
    // [76] "You are teleported!" (20→11 bytes)
    .byte $0e, $7a, $b7, $fa, $9f, $43, $a2, $cf, $9f, $10, $04
    // [77] "A dart hits you!" (17→10 bytes)
    .byte $8d, $52, $37, $ce, $cb, $66, $35, $5c, $f0, $08
    // [78] "Rocks fall on you!" (19→12 bytes)
    .byte $50, $73, $45, $23, $75, $68, $42, $e4, $ea, $b9, $e0, $10
    // [79] "You take " (10→6 bytes)
    .byte $0e, $7a, $9b, $29, $ea, $80
    // [80] " damage." (9→6 bytes)
    .byte $a4, $67, $59, $fe, $5a, $00
    // [81] "You feel weakened." (19→11 bytes)
    .byte $0e, $7a, $eb, $dd, $0a, $5f, $32, $9e, $9f, $11, $68
    // [82] "You feel poisoned." (19→11 bytes)
    .byte $0e, $7a, $eb, $dd, $0b, $16, $6c, $72, $7c, $45, $a0
    // [83] "You cannot cast spells." (24→14 bytes)
    .byte $0e, $7a, $e8, $d3, $9e, $1d, $d1, $84, $e8, $c5, $d0, $80, $ad, $00
    // [84] "You cannot pray." (17→10 bytes)
    .byte $0e, $7a, $e8, $d3, $9e, $1d, $8b, $ec, $aa, $d0
    // [85] "You don't know that spell." (27→16 bytes)
    .byte $0e, $7a, $93, $26, $0c, $3a, $a6, $78, $5d, $39, $31, $d1, $8b, $a1, $05, $a0
    // [86] "Not enough mana." (17→10 bytes)
    .byte $72, $c3, $bd, $3c, $f3, $f2, $ae, $b4, $d9, $68
    // [87] "You're not experienced enough." (31→19 bytes)
    .byte $0e, $78, $19, $fe, $b3, $c3, $bc, $f6, $62, $ef, $ef, $a7, $a7, $12, $f4, $f3, $cf, $c9, $68
    // [88] "Your spell fails." (18→11 bytes)
    .byte $0e, $7b, $f4, $62, $e8, $42, $ea, $db, $80, $ad, $00
    // [89] "Spell book (a-v)?" (18→13 bytes)
    .byte $7a, $8b, $a1, $0b, $1f, $31, $4d, $04, $d1, $8f, $0a, $b8, $40
    // [90] "Prayer book (a-v)?" (19→14 bytes)
    .byte $51, $7e, $ca, $f7, $ec, $7c, $c5, $34, $13, $46, $3c, $2a, $e1, $00
    // [91] "." (2→2 bytes)
    .byte $5a, $00
    // [92] "." (2→2 bytes)
    .byte $5a, $00
    // [93] "Cast which? (a-p, ESC)" (23→18 bytes)
    .byte $51, $18, $4e, $97, $2d, $e9, $27, $14, $13, $46, $44, $e6, $aa, $3b, $d2, $88, $55, $00
    // [94] "Pray which? (a-p, ESC)" (23→18 bytes)
    .byte $51, $7e, $ca, $d2, $e5, $bd, $24, $e2, $82, $68, $c8, $9c, $d5, $47, $7a, $51, $0a, $a0
    // [95] "." (2→2 bytes)
    .byte $5a, $00
    // [96] "Wear which item (a-v)?" (23→16 bytes)
    .byte $06, $f3, $7e, $97, $2d, $e9, $2b, $b3, $e7, $68, $26, $8c, $78, $55, $c2, $00
    // [97] "Take off which item (a-h)?" (27→18 bytes)
    .byte $28, $ca, $7a, $e6, $ba, $d2, $e5, $bd, $25, $76, $7c, $ed, $04, $d1, $92, $2a, $e1, $00
    // [98] "You have nothing there." (24→14 bytes)
    .byte $0e, $7a, $c9, $9e, $75, $9e, $1c, $b7, $37, $e9, $cb, $bf, $cb, $40
    // [99] "Never mind." (12→8 bytes)
    .byte $72, $e7, $9d, $fa, $ee, $e6, $45, $a0
    // [100] "You cannot remove it, it is cursed!" (36→21 bytes)
    .byte $0e, $7a, $e8, $d3, $9e, $1d, $ff, $3b, $8f, $3a, $ec, $dc, $d7, $67, $76, $37, $4f, $7c, $78, $80, $20
    // [101] "You have no food." (18→10 bytes)
    .byte $0e, $7a, $c9, $9e, $75, $9e, $5d, $73, $08, $b4
    // [102] "You are wielding a " (20→11 bytes)
    .byte $0e, $7a, $b7, $fa, $97, $be, $81, $37, $37, $eb, $54
    // [103] "You are wearing a " (19→11 bytes)
    .byte $0e, $7a, $b7, $fa, $97, $cd, $fd, $cd, $fa, $d5, $00
    // [104] "You take off the " (18→10 bytes)
    .byte $0e, $7a, $9b, $29, $eb, $9a, $eb, $4e, $5d, $50
    // [105] "You eat the " (13→7 bytes)
    .byte $0e, $7a, $f3, $1d, $39, $75, $40
    // [106] ". Delicious!" (13→9 bytes)
    .byte $5d, $8d, $ba, $1b, $d3, $79, $e1, $01, $00
    // [107] ". Yuck!" (8→6 bytes)
    .byte $5d, $0f, $b4, $52, $02, $00
    // [108] "Quaff which potion (a-v)?" (26→18 bytes)
    .byte $7b, $7c, $da, $eb, $4b, $96, $f4, $95, $8b, $0f, $79, $3a, $09, $a3, $1e, $15, $70, $80
    // [109] "Read which scroll (a-v)?" (25→17 bytes)
    .byte $50, $79, $89, $4b, $96, $f4, $95, $1d, $3f, $90, $85, $04, $d1, $8f, $0a, $b8, $40
    // [110] "You feel better." (17→10 bytes)
    .byte $0e, $7a, $eb, $dd, $0b, $1f, $8c, $fb, $eb, $40
    // [111] "You feel yourself moving faster." (33→20 bytes)
    .byte $0e, $7a, $eb, $dd, $0a, $ae, $7b, $e3, $d0, $d6, $bb, $8f, $37, $37, $ee, $ac, $27, $df, $5a, $00
    // [112] "That tasted terrible!" (22→13 bytes)
    .byte $29, $26, $3a, $6c, $27, $c4, $a7, $df, $fe, $e3, $c3, $80, $40
    // [113] "Nothing seems to happen." (25→15 bytes)
    .byte $72, $c3, $96, $e6, $fd, $1e, $e7, $46, $9e, $59, $34, $51, $74, $d6, $80
    // [114] "The area fills with light." (27→16 bytes)
    .byte $29, $2e, $ad, $fe, $6b, $ae, $e1, $01, $a5, $ec, $e5, $61, $b7, $e4, $6b, $40
    // [115] "Identify which item (a-v)?" (27→18 bytes)
    .byte $07, $93, $a6, $7b, $d5, $5a, $5c, $b7, $a4, $ae, $cf, $9d, $a0, $9a, $31, $e1, $57, $08
    // [116] "This is a " (11→6 bytes)
    .byte $29, $2d, $8d, $d8, $d6, $a8
    // [117] "You feel disoriented." (22→13 bytes)
    .byte $0e, $7a, $eb, $dd, $0a, $4d, $8e, $7f, $7d, $33, $e2, $2d, $00
    // [118] "You feel much better." (22→13 bytes)
    .byte $0e, $7a, $eb, $dd, $0a, $ef, $b4, $95, $8f, $c6, $7d, $f5, $a0
    // [119] "Your mind feels clear." (23→14 bytes)
    .byte $0e, $7b, $f5, $dd, $cc, $97, $5e, $e8, $0d, $d2, $1c, $df, $5a, $00
    // [120] "You feel heroic!" (17→10 bytes)
    .byte $0e, $7a, $eb, $dd, $0b, $2e, $fe, $6f, $40, $10
    // [121] "You can't see!" (15→9 bytes)
    .byte $0e, $7a, $e8, $d3, $06, $1d, $1e, $e0, $10
    // [122] "You feel dizzy." (16→11 bytes)
    .byte $0e, $7a, $eb, $dd, $0a, $4d, $83, $81, $ca, $ad, $00
    // [123] "You sense nearby creatures." (28→16 bytes)
    .byte $0e, $7a, $8f, $4c, $7a, $cf, $9b, $f1, $d5, $ba, $7f, $98, $fd, $fe, $15, $a0
    // [124] "Your eyes tingle." (18→11 bytes)
    .byte $0e, $7b, $f7, $95, $e1, $a7, $b9, $bf, $0e, $5a, $00
    // [125] "The air crackles around you." (29→17 bytes)
    .byte $29, $2e, $ad, $bf, $dd, $3e, $da, $29, $87, $0d, $6f, $e7, $a6, $4a, $ae, $79, $68
    // [126] "You feel cleansed." (19→11 bytes)
    .byte $0e, $7a, $eb, $dd, $0b, $a4, $39, $a6, $3c, $45, $a0
    // [127] "Your weapon glows briefly." (27→17 bytes)
    .byte $0e, $7b, $f4, $be, $68, $b2, $75, $f8, $61, $63, $63, $ff, $7d, $ac, $15, $5a, $00
    // [128] "Your armor glows briefly." (26→16 bytes)
    .byte $0e, $7b, $f5, $be, $ee, $7e, $bf, $0c, $2c, $6c, $7f, $ef, $b5, $82, $ab, $40
    // [129] "Your hands begin to glow." (26→15 bytes)
    .byte $0e, $7b, $f6, $4d, $32, $0d, $8f, $cf, $ee, $74, $f2, $bf, $0c, $2d, $68
    // [130] "You hear a high-pitched humming." (33→20 bytes)
    .byte $0e, $7a, $cb, $9b, $f5, $ac, $b6, $fc, $a3, $22, $d9, $e9, $2e, $25, $97, $9d, $77, $73, $7d, $68
    // [131] "You feel protected." (20→12 bytes)
    .byte $0e, $7a, $eb, $dd, $0b, $17, $f0, $fb, $43, $e2, $2d, $00
    // [132] "You feel a strange vibration." (30→17 bytes)
    .byte $0e, $7a, $eb, $dd, $0a, $d4, $4f, $ed, $37, $fa, $bc, $dc, $7f, $b1, $ef, $26, $b4
    // [133] "Aim which wand (a-v)?" (22→15 bytes)
    .byte $8d, $6d, $da, $5c, $b7, $a4, $a9, $6d, $32, $50, $4d, $18, $f0, $ab, $84
    // [134] "Use which staff (a-v)?" (23→16 bytes)
    .byte $7b, $11, $ea, $5c, $b7, $a4, $a8, $9b, $6b, $ad, $04, $d1, $8f, $0a, $b8, $40
    // [135] "No charges left." (17→10 bytes)
    .byte $72, $cb, $a4, $9b, $ef, $f0, $d8, $76, $a6, $b4
    // [136] "The staff is empty." (20→12 bytes)
    .byte $29, $2e, $a2, $6d, $ae, $b7, $63, $79, $d8, $8d, $55, $a0
    // [137] "A bolt of lightning shoots forth!" (34→20 bytes)
    .byte $8d, $58, $f9, $03, $b9, $ad, $86, $df, $91, $cf, $73, $7e, $8c, $b3, $0c, $6e, $b9, $f3, $90, $08
    // [138] "A bolt of frost shoots forth!" (30→17 bytes)
    .byte $8d, $58, $f9, $03, $b9, $ad, $d7, $f8, $27, $46, $59, $86, $37, $5c, $f9, $c8, $04
    // [139] "The monster looks confused." (28→17 bytes)
    .byte $29, $2e, $ae, $e4, $c4, $fb, $f6, $19, $8a, $46, $e9, $93, $d7, $c3, $c4, $5a, $00
    // [140] "The cloud dissipates." (22→13 bytes)
    .byte $29, $2e, $ba, $43, $3c, $4a, $4d, $88, $ee, $26, $3e, $15, $a0
    // [141] "You can't see to read!" (23→13 bytes)
    .byte $0e, $7a, $e8, $d3, $06, $1d, $1e, $ea, $79, $7f, $cc, $40, $10
    // [142] "Study which book (a-v)?" (24→17 bytes)
    .byte $7a, $3f, $11, $5a, $5c, $b7, $a4, $ac, $7c, $c5, $34, $13, $46, $3c, $2a, $e1, $00
    // [143] "You cannot use magic." (22→13 bytes)
    .byte $0e, $7a, $e8, $d3, $9e, $1d, $f0, $f5, $75, $9f, $de, $8b, $40
    // [144] "You cannot read that book." (27→15 bytes)
    .byte $0e, $7a, $e8, $d3, $9e, $1d, $ff, $31, $29, $c9, $8e, $c7, $cc, $52, $b4
    // [145] "You learn from the book!" (25→15 bytes)
    .byte $0e, $7a, $c3, $9b, $f3, $ba, $ff, $1d, $a7, $2e, $b1, $f3, $14, $80, $80
    // [146] "No new spells to learn." (24→14 bytes)
    .byte $72, $cb, $3e, $2e, $8c, $5d, $08, $0d, $3c, $b0, $e6, $fc, $d6, $80
    // [147] "Not using a lamp." (18→11 bytes)
    .byte $72, $c3, $be, $1d, $cd, $fa, $d6, $0c, $ec, $4b, $40
    // [148] "You have no oil." (17→10 bytes)
    .byte $0e, $7a, $c9, $9e, $75, $9e, $5c, $dc, $16, $80
    // [149] "Your lamp overflows." (21→13 bytes)
    .byte $0e, $7b, $f6, $0c, $ec, $57, $1e, $77, $f5, $86, $16, $2b, $40
    // [150] "Your lamp is full." (19→11 bytes)
    .byte $0e, $7b, $f6, $0c, $ec, $57, $63, $75, $f4, $20, $b4
    // [151] "Your lamp is refueled." (23→14 bytes)
    .byte $0e, $7b, $f6, $0c, $ec, $57, $63, $7f, $da, $fb, $a1, $c4, $5a, $00
    // [152] "Welcome to level " (18→11 bytes)
    .byte $06, $f4, $34, $c7, $7a, $9e, $58, $73, $ce, $85, $40
    // [153] "Gold: " (7→5 bytes)
    .byte $50, $f2, $04, $7b, $d4
    // [154] ">65535" (7→9 bytes)
    .byte $7b, $07, $3f, $50, $94, $27, $3e, $50, $90
    // [155] "B)uy  S)ell  Q)uit" (19→13 bytes)
    .byte $8d, $ca, $f9, $5b, $5e, $8a, $f4, $21, $6b, $da, $57, $db, $34
    // [156] "Buy which item? (a-l)" (22→15 bytes)
    .byte $8d, $fc, $ad, $2e, $5b, $d2, $57, $67, $ce, $b8, $a0, $9a, $32, $05, $50
    // [157] "Price: " (8→6 bytes)
    .byte $51, $7f, $bd, $39, $ef, $50
    // [158] " gp. Buy? (Y/N)" (16→12 bytes)
    .byte $af, $c4, $bb, $1b, $f9, $57, $14, $10, $54, $07, $22, $a8
    // [159] "Bought!" (8→6 bytes)
    .byte $8d, $f3, $cf, $c8, $c0, $40
    // [160] "You cannot afford that." (24→14 bytes)
    .byte $0e, $7a, $e8, $d3, $9e, $1d, $6d, $75, $cf, $92, $9c, $98, $d6, $80
    // [161] "Your pack is full." (19→12 bytes)
    .byte $0e, $7b, $f6, $26, $d1, $4d, $d8, $dd, $7d, $08, $2d, $00
    // [162] "Sell Items" (11→7 bytes)
    .byte $7a, $e8, $42, $83, $cf, $9d, $14
    // [163] "Sell which item? (a-v)" (23→16 bytes)
    .byte $7a, $e8, $42, $97, $2d, $e9, $2b, $b3, $e7, $5c, $50, $4d, $18, $f0, $aa, $00
    // [164] "Offer: " (8→6 bytes)
    .byte $73, $da, $eb, $df, $7b, $d4
    // [165] " gp. Sell? (Y/N)" (17→12 bytes)
    .byte $af, $c4, $ba, $f5, $d0, $83, $8a, $08, $2a, $03, $91, $54
    // [166] "Sold!" (6→4 bytes)
    .byte $7a, $c8, $10, $04
    // [167] "We don't buy that." (19→12 bytes)
    .byte $06, $f5, $26, $4c, $18, $76, $3f, $95, $a7, $26, $35, $a0
    // [168] "That is worthless." (19→11 bytes)
    .byte $29, $26, $3b, $b1, $a5, $e7, $ce, $50, $e1, $15, $a0
    // [169] "The store is full." (19→11 bytes)
    .byte $29, $2e, $a2, $79, $fe, $bb, $1b, $af, $a1, $05, $a0
    // [170] "That item is cursed." (21→12 bytes)
    .byte $29, $26, $3b, $b3, $e7, $6e, $c6, $e9, $ef, $8f, $11, $68
    // [171] "Asks " (6→4 bytes)
    .byte $8d, $0a, $91, $a8
    // [172] "Offers " (8→6 bytes)
    .byte $73, $da, $eb, $df, $1a, $80
    // [173] " gp." (5→3 bytes)
    .byte $af, $c4, $b4
    // [174] "Your offer? (Q=cancel)" (23→16 bytes)
    .byte $0e, $7b, $f7, $35, $d7, $be, $e2, $82, $7b, $5c, $e6, $8d, $3d, $3a, $05, $50
    // [175] "Your price? (Q=cancel)" (23→16 bytes)
    .byte $0e, $7b, $f6, $2f, $ef, $4e, $71, $41, $3d, $ae, $73, $46, $9e, $9d, $02, $a8
    // [176] "How about " (11→7 bytes)
    .byte $51, $b0, $ba, $d1, $f3, $c7, $50
    // [177] " gp?" (5→4 bytes)
    .byte $af, $c4, $e1, $00
    // [178] "Final offer: " (14→10 bytes)
    .byte $73, $bd, $cd, $a1, $73, $5d, $7b, $ef, $7a, $80
    // [179] "Take it? (Y/N)" (15→11 bytes)
    .byte $28, $ca, $7a, $ec, $dc, $50, $41, $50, $1c, $8a, $a0
    // [180] "Get out of my store!" (21→12 bytes)
    .byte $50, $f8, $ee, $78, $ee, $6b, $5d, $56, $89, $e7, $f8, $04
    // [181] "Agreed!" (8→6 bytes)
    .byte $8d, $3f, $fe, $e2, $00, $80
    // [182] "You dig in the granite wall." (29→17 bytes)
    .byte $0e, $7a, $93, $6f, $dd, $ce, $9c, $ba, $bf, $f6, $9e, $cf, $a9, $6d, $08, $2d, $00
    // [183] "You dig in the magma." (22→13 bytes)
    .byte $0e, $7a, $93, $6f, $dd, $ce, $9c, $ba, $ba, $cf, $ba, $cb, $40
    // [184] "You dig in the quartz vein." (28→18 bytes)
    .byte $0e, $7a, $93, $6f, $dd, $ce, $9c, $ba, $b9, $d7, $9b, $e6, $0e, $af, $3b, $73, $5a, $00
    // [185] "You have finished the tunnel." (30→17 bytes)
    .byte $0e, $7a, $c9, $9e, $75, $d7, $73, $d8, $cb, $89, $4e, $5d, $4f, $d3, $9f, $41, $68
    // [186] "You have found something!" (26→16 bytes)
    .byte $0e, $7a, $c9, $9e, $75, $d7, $3d, $32, $51, $c7, $78, $e5, $b9, $be, $02, $00
    // [187] "This seems to be permanent rock." (33→19 bytes)
    .byte $29, $2d, $8d, $1e, $e7, $46, $9e, $58, $fd, $62, $ef, $ba, $d3, $e9, $9d, $fe, $68, $a5, $68
    // [188] "There is nothing to tunnel here." (33→19 bytes)
    .byte $29, $2e, $ff, $5d, $8d, $9e, $1c, $b7, $37, $e9, $e5, $3f, $4e, $7d, $0b, $2e, $ff, $2d, $00
    // [189] "The rubble crumbles." (21→14 bytes)
    .byte $29, $2e, $bf, $f4, $78, $f0, $eb, $a7, $fc, $ec, $78, $70, $ad, $00
    // [190] "You dig with your hands, making no progress." (45→27 bytes)
    .byte $0e, $7a, $93, $6f, $d2, $f6, $72, $aa, $e7, $bf, $64, $d3, $20, $b9, $ab, $ac, $a7, $73, $7e, $cf, $2c, $5f, $c7, $ff, $c2, $2b, $40
    // [191] "You see nothing here." (22→12 bytes)
    .byte $0e, $7a, $8f, $75, $9e, $1c, $b7, $37, $ec, $bb, $fc, $b4
    // [192] "You found " (11→7 bytes)
    .byte $0e, $7a, $eb, $9e, $99, $2a, $00
    // [193] " gold pieces." (14→8 bytes)
    .byte $af, $e4, $09, $62, $df, $69, $c2, $b4
    // [194] "You picked up a " (17→10 bytes)
    .byte $0e, $7a, $c5, $bd, $14, $f1, $2f, $a2, $ad, $50
    // [195] "Drop which item (a-v)?" (23→16 bytes)
    .byte $8d, $bf, $91, $52, $e5, $bd, $25, $76, $7c, $ed, $04, $d1, $8f, $0a, $b8, $40
    // [196] "You drop a " (12→7 bytes)
    .byte $0e, $7a, $93, $f9, $15, $6a, $80
    // [197] "No room on the floor." (22→13 bytes)
    .byte $72, $cb, $fc, $c7, $6e, $4e, $9c, $ba, $eb, $0c, $cf, $ad, $00
    // [198] "Sense: Terrible" (16→11 bytes)
    .byte $7a, $e9, $8f, $3d, $e9, $4e, $ff, $f7, $1e, $1c, $80
    // [199] "Sense: Bad" (11→8 bytes)
    .byte $7a, $e9, $8f, $3d, $ec, $6e, $c4, $40
    // [200] "Sense: Average" (15→10 bytes)
    .byte $7a, $e9, $8f, $3d, $ec, $69, $e7, $7d, $9f, $e4
    // [201] "Sense: Good" (12→8 bytes)
    .byte $7a, $e9, $8f, $3d, $ea, $87, $98, $44
    // [202] "Sense: Excellent" (17→12 bytes)
    .byte $7a, $e9, $8f, $3d, $ea, $8e, $f6, $74, $e8, $43, $a6, $68
    // [203] "You smash into the door!" (25→14 bytes)
    .byte $0e, $7a, $8b, $ac, $32, $bb, $99, $e5, $39, $75, $26, $67, $c0, $40
    // [204] "The door crashes open!" (23→13 bytes)
    .byte $29, $2e, $a4, $cc, $fd, $d3, $ec, $32, $e1, $b9, $17, $4c, $04
    // [205] "The door holds firm." (21→13 bytes)
    .byte $29, $2e, $a4, $cc, $fd, $96, $40, $83, $75, $df, $dd, $5a, $00
    // [206] "You are off balance." (21→12 bytes)
    .byte $0e, $7a, $b7, $fa, $e6, $ba, $d8, $ed, $06, $9e, $9c, $b4
    // [207] "You bash at empty space." (25→15 bytes)
    .byte $0e, $7a, $c7, $61, $95, $63, $bc, $ec, $46, $ad, $18, $9b, $4e, $5a, $00
    // [208] " appears stunned!" (18→11 bytes)
    .byte $ad, $14, $5c, $df, $1a, $27, $e9, $cf, $88, $02, $00
    // [209] " ignores your bash!" (20→12 bytes)
    .byte $bb, $7e, $79, $fe, $1a, $ae, $7b, $f6, $3b, $0c, $80, $40

// Huffman code table:
//   NULL   =         0100 (4 bits, freq=210)
//   a      =         0110 (4 bits, freq=226)
//   b      =      1000111 (7 bits, freq=38)
//   c      =       110100 (6 bits, freq=80)
//   d      =        00100 (5 bits, freq=94)
//   e      =         1110 (4 bits, freq=336)
//   f      =       110101 (6 bits, freq=82)
//   g      =       011111 (6 bits, freq=63)
//   h      =        10010 (5 bits, freq=142)
//   i      =        11011 (5 bits, freq=163)
//   k      =      0101001 (7 bits, freq=26)
//   l      =        10000 (5 bits, freq=138)
//   m      =       011101 (6 bits, freq=56)
//   n      =        10011 (5 bits, freq=151)
//   o      =         1100 (4 bits, freq=320)
//   p      =       100010 (6 bits, freq=67)
//   q      = 011100111010 (12 bits, freq=1)
//   r      =        11111 (5 bits, freq=173)
//   s      =         0001 (4 bits, freq=184)
//   t      =         0011 (4 bits, freq=193)
//   u      =        11110 (5 bits, freq=169)
//   v      =      0111100 (7 bits, freq=30)
//   w      =       001011 (6 bits, freq=48)
//   x      =  01111011001 (11 bits, freq=2)
//   y      =       010101 (6 bits, freq=53)
//   z      =    000001110 (9 bits, freq=6)
//   SPACE  =          101 (3 bits, freq=579)
//   $21    =       000000 (6 bits, freq=43)
//   $27    =    000001100 (9 bits, freq=5)
//   $28    =      0000010 (7 bits, freq=21)
//   $29    =      0010101 (7 bits, freq=24)
//   $2c    =    011100110 (9 bits, freq=7)
//   $2d    =     10001100 (8 bits, freq=17)
//   $2e    =        01011 (5 bits, freq=110)
//   $2f    =   0101000000 (10 bits, freq=3)
//   $33    = 011100111110 (12 bits, freq=1)
//   $35    =   0101000010 (10 bits, freq=3)
//   $36    = 011100111111 (12 bits, freq=1)
//   $3a    =    011110111 (9 bits, freq=9)
//   $3d    =  01110011100 (11 bits, freq=2)
//   $3e    = 011110110000 (12 bits, freq=1)
//   $3f    =      0111000 (7 bits, freq=27)
//   A      =    100011010 (9 bits, freq=9)
//   B      =   1000110111 (10 bits, freq=5)
//   C      =   0101000100 (10 bits, freq=3)
//   D      =   1000110110 (10 bits, freq=4)
//   E      =   0101000111 (10 bits, freq=3)
//   F      = 011100111011 (12 bits, freq=1)
//   G      =   0101000011 (10 bits, freq=3)
//   H      =   0101000110 (10 bits, freq=3)
//   I      =    000001111 (9 bits, freq=6)
//   N      =     01110010 (8 bits, freq=13)
//   O      =  01110011110 (11 bits, freq=2)
//   P      =   0101000101 (10 bits, freq=3)
//   Q      =   0111101101 (10 bits, freq=4)
//   R      =   0101000001 (10 bits, freq=3)
//   S      =     01111010 (8 bits, freq=15)
//   T      =      0010100 (7 bits, freq=23)
//   U      = 011110110001 (12 bits, freq=1)
//   W      =    000001101 (9 bits, freq=5)
//   Y      =        00001 (5 bits, freq=93)
