// huffman.s — Huffman string decoder for compressed text
//
// Decodes variable-length Huffman-coded strings into screen codes.
// Tree tables and compressed data generated by tools/huff_encoder.py.

// ============================================================
// Decoder scratch (static RAM)
// ============================================================
hd_cur_byte:   .byte 0        // Current byte being read
hd_bit_mask:   .byte 0        // Bits remaining in current byte (counter)

// Decode output buffer (42 bytes, matches combat_msg_buf size)
hd_decode_buf: .fill 42, 0
.assert "hd_decode_buf same page", (hd_decode_buf >> 8) == ((hd_decode_buf + 7) >> 8), true

// ============================================================
// huff_decode_string — Decode a Huffman-compressed string
//
// Input:  X = string ID (0-based, 0..HUFF_STR_COUNT-1)
// Output: hd_decode_buf filled with null-terminated screen codes
//         zp_ptr0/zp_ptr0_hi → hd_decode_buf
// Clobbers: A, X, Y, zp_ptr0/zp_ptr0_hi
// ============================================================
huff_decode_string:
    // Look up 16-bit byte offset from index table
    // X*2 may exceed 255 for string IDs >= 128, so branch on carry
    txa
    asl                        // X*2 for word index (carry set if >= 128)
    tax
    bcs !hds_hi+
    lda huff_str_index,x
    clc
    adc #<huff_str_data
    sta zp_ptr0                // Source pointer lo (ZP for indirect)
    lda huff_str_index+1,x
    adc #>huff_str_data
    sta zp_ptr0_hi             // Source pointer hi
    jmp huff_decode_from_ptr
!hds_hi:
    lda huff_str_index+256,x
    clc
    adc #<huff_str_data
    sta zp_ptr0
    lda huff_str_index+257,x
    adc #>huff_str_data
    sta zp_ptr0_hi
    // Fall through

// ============================================================
// huff_decode_from_ptr — Decode Huffman stream from pointer
//
// Input:  zp_ptr0/zp_ptr0_hi = pointer to compressed data
// Output: hd_decode_buf filled with null-terminated screen codes
//         zp_ptr0/zp_ptr0_hi → hd_decode_buf
// Clobbers: A, X, Y
// ============================================================
huff_decode_from_ptr:
    // C128: KERNAL/IRQ can clobber low ZP pointer bytes during decode.
    // Lock IRQs for the short decode window to keep pointer traversal stable.
    lda zp_machine_type
    cmp #MACHINE_C128
    bne !hdfp_no_lock+
    php
    sei
!hdfp_no_lock:
    // Initialize bit reader
    lda #0
    sta hd_bit_mask            // Force load of first byte
    ldx #0                     // Output buffer index

!decode_loop:
    // Start at tree root (node 0)
    lda #0
!walk_tree:
    sta hd_cur_node_smc+1      // Self-mod: store current node index

    // Read one bit
    dec hd_bit_mask
    bpl !have_bit+
    // Load next byte — use Y=0, advance src pointer
    ldy #0
    lda (zp_ptr0),y
    sta hd_cur_byte
    inc zp_ptr0
    bne !no_page+
    inc zp_ptr0_hi
!no_page:
    lda #7
    sta hd_bit_mask
!have_bit:
    lda hd_cur_byte            // C128 silicon bug workaround:
    asl                        // DO NOT use RMW "asl hd_cur_byte" on C128.
    sta hd_cur_byte            // The 8502 can corrupt RAM if VIC-II cycle
                               // steals between 2MHz/1MHz on a RMW instruction.

    // Follow tree: carry clear = left, carry set = right
hd_cur_node_smc:
    lda #0                     // Self-modified: current node index
    tay
    bcs !go_right+
    lda huff_tree_left,y
    jmp !check_leaf+
!go_right:
    lda huff_tree_right,y

!check_leaf:
    bmi !leaf+                 // Bit 7 set = leaf node
    // Internal node — continue walking
    jmp !walk_tree-

!leaf:
    and #$7f                   // Extract screencode
    beq !done+                 // Null terminator = end of string
    sta hd_decode_buf,x
    inx
    cpx #41                    // Safety: don't overflow buffer
    bcc !decode_loop-

!done:
    lda #0
    sta hd_decode_buf,x        // Null-terminate

    // Set zp_ptr0 → decode buffer for screen_put_string
    lda #<hd_decode_buf
    sta zp_ptr0
    lda #>hd_decode_buf
    sta zp_ptr0_hi

    // Restore prior IRQ state if we locked on C128.
    lda zp_machine_type
    cmp #MACHINE_C128
    bne !hdfp_no_unlock+
    plp
!hdfp_no_unlock:
    rts

// ============================================================
// huff_decode_to_ptr2 — Decode and set zp_ptr2 (for mon_atk_build_effect_msg)
// Input: X = string ID
// Output: zp_ptr2/hi → hd_decode_buf (decoded string)
// Clobbers: A, X, Y, zp_ptr0/hi, zp_ptr2/hi
// ============================================================
huff_decode_to_ptr2:
    jsr huff_decode_string
    lda zp_ptr0
    sta zp_ptr2
    lda zp_ptr0_hi
    sta zp_ptr2_hi
    rts

// ============================================================
// huff_append_combat — Decode and append to combat_msg_buf
// Input: X = string ID
// Output: string appended to combat_msg_buf at cmb_buf_idx
// Clobbers: A, X, Y, zp_ptr0/hi, zp_ptr1/hi
// ============================================================
huff_append_combat:
    jsr huff_decode_string
    lda #<hd_decode_buf
    ldy #>hd_decode_buf
    jmp combat_append_str

// ============================================================
// huff_print_msg — Decode Huffman string and print to message area
// Input: X = string ID (HSTR_*)
// Clobbers: A, X, Y, zp_ptr0/hi
// ============================================================
huff_print_msg:
    // C128 hotfix: two prompt IDs are intermittently corrupted in the
    // Huffman path. Bypass decode for these IDs with static strings.
    lda zp_machine_type
    cmp #MACHINE_C128
    bne !hpm_normal+
    cpx #64                   // HSTR_DF_DIRECTION
    bne !hpm_not_dir+
    lda #<hpm_df_direction_str
    sta zp_ptr0
    lda #>hpm_df_direction_str
    sta zp_ptr0_hi
    jmp msg_print
!hpm_not_dir:
    cpx #98                   // HSTR_PIW_TAKEOFF_PROMPT
    bne !hpm_normal+
    lda #<hpm_takeoff_prompt_str
    sta zp_ptr0
    lda #>hpm_takeoff_prompt_str
    sta zp_ptr0_hi
    jmp msg_print
!hpm_normal:
    jsr huff_decode_string
    jmp msg_print              // Tail call — 6 bytes total

hpm_df_direction_str:
    .text "Direction?" ; .byte 0
hpm_takeoff_prompt_str:
    .text "Take off which item (a-h)?" ; .byte 0

// ============================================================
// Compressed string data (generated)
// ============================================================
#import "huffman_data.s"
