#importonce
// huffman_data.s — Generated by huff_encoder.py
// Source: data/huffman_strings.txt
// 218 strings, 4295 bytes uncompressed
// 2611 bytes compressed (60.8%)
// Tree: 122 bytes, Index: 436 bytes
// Total data: 3169 bytes

.const HUFF_STR_COUNT = 218
.const HSTR_INSULT_COUNT = 15

// Named string constants
.const HSTR_MAT_HITS = 15
.const HSTR_MAT_MISS = 16
.const HSTR_MAT_POISON = 17
.const HSTR_MAT_CONFUSE = 18
.const HSTR_MAT_PARALYZE = 19
.const HSTR_MAT_ACID = 20
.const HSTR_MAT_FEAR = 21
.const HSTR_MAT_SHRIEK = 22
.const HSTR_MAT_DEAD = 23
.const HSTR_MM_BOLT = 24
.const HSTR_MM_BREATH = 25
.const HSTR_MM_SUMMON = 26
.const HSTR_MM_TELEPORT = 27
.const HSTR_MM_BLIND = 28
.const HSTR_MM_CONFUSE = 29
.const HSTR_MM_HEAL = 30
.const HSTR_RF_NO_WEAPON = 31
.const HSTR_RF_NO_AMMO = 32
.const HSTR_RF_FLIES = 33
.const HSTR_RF_MISSES = 34
.const HSTR_RF_HITS = 35
.const HSTR_EB_SPELL_HITS = 36
.const HSTR_EB_FIZZLE = 37
.const HSTR_TW_PROMPT = 38
.const HSTR_TW_SHATTERS = 39
.const HSTR_EFF_POISON_END = 40
.const HSTR_EFF_BLIND_END = 41
.const HSTR_EFF_CONFUSE_END = 42
.const HSTR_EFF_PARALYZE_END = 43
.const HSTR_EFF_FEAR_END = 44
.const HSTR_TTL_DIM = 45
.const HSTR_TTL_OUT = 46
.const HSTR_RECALL_ARRIVE = 47
.const HSTR_DL_YOU_SEE = 48
.const HSTR_DL_OPEN_DOOR = 49
.const HSTR_DL_CLOSED_DOOR = 50
.const HSTR_DL_STAIRS_DN = 51
.const HSTR_DL_STAIRS_UP = 52
.const HSTR_DL_TRAP = 53
.const HSTR_DL_RUBBLE = 54
.const HSTR_DL_WALL = 55
.const HSTR_DL_NOTHING = 56
.const HSTR_PTM_AFRAID = 57
.const HSTR_DF_TRAP_0 = 58
.const HSTR_DF_TRAP_1 = 59
.const HSTR_DF_TRAP_2 = 60
.const HSTR_DF_TRAP_3 = 61
.const HSTR_DF_TRAP_4 = 62
.const HSTR_DF_TRAP_5 = 63
.const HSTR_DF_DIRECTION = 64
.const HSTR_DF_DOOR_STUCK = 65
.const HSTR_DF_FOUND_TRAP = 66
.const HSTR_DF_FOUND_SECRET = 67
.const HSTR_DF_FOUND_NOTHING = 68
.const HSTR_DF_NO_DOOR = 69
.const HSTR_DF_ALREADY_OPEN = 70
.const HSTR_DF_ALREADY_CLOSED = 71
.const HSTR_DF_DOOR_OPENED = 72
.const HSTR_DF_DOOR_CLOSED = 73
.const HSTR_DF_YOU_FELL = 74
.const HSTR_DF_ARROW_HITS = 75
.const HSTR_DF_POISON_GAS = 76
.const HSTR_DF_TELEPORTED = 77
.const HSTR_DF_DART_HITS = 78
.const HSTR_DF_ROCKFALL = 79
.const HSTR_DF_DAMAGE_PRE = 80
.const HSTR_DF_DAMAGE_POST = 81
.const HSTR_DF_CON_DRAIN = 82
.const HSTR_DF_POISONED = 83
.const HSTR_PM_NO_CAST = 84
.const HSTR_PM_NO_PRAY = 85
.const HSTR_PM_NOT_KNOWN = 86
.const HSTR_PM_NO_MANA = 87
.const HSTR_PM_NO_EXP = 88
.const HSTR_PM_FAIL = 89
.const HSTR_PM_YOU_CAST = 90
.const HSTR_PM_YOU_PRAY = 91
.const HSTR_PM_TITLE_MAGE = 92
.const HSTR_PM_TITLE_PRAY = 93
.const HSTR_PM_FOOTER_CAST = 94
.const HSTR_PM_FOOTER_PRAY = 95
.const HSTR_PM_LEARNED = 96
.const HSTR_PIW_WEAR_PROMPT = 97
.const HSTR_PIW_TAKEOFF_PROMPT = 98
.const HSTR_PIW_NOTHING = 99
.const HSTR_PIW_CANT_WEAR = 100
.const HSTR_PIW_NEVERMIND = 101
.const HSTR_PIW_CURSED = 102
.const HSTR_PIW_NO_FOOD = 103
.const HSTR_PIW_WIELD = 104
.const HSTR_PIW_WEARING = 105
.const HSTR_PIW_TAKEOFF = 106
.const HSTR_PIW_EAT = 107
.const HSTR_PIW_DELICIOUS = 108
.const HSTR_PIW_YUCK = 109
.const HSTR_PIQ_QUAFF_PROMPT = 110
.const HSTR_PIQ_READ_PROMPT = 111
.const HSTR_PIQ_NOT_POTION = 112
.const HSTR_PIQ_NOT_SCROLL = 113
.const HSTR_PIQ_FEEL_BETTER = 114
.const HSTR_PIQ_SPEED = 115
.const HSTR_PIQ_TERRIBLE = 116
.const HSTR_PIQ_NOTHING = 117
.const HSTR_PIQ_LIGHT = 118
.const HSTR_PIQ_IDENTIFY_PROMPT = 119
.const HSTR_PIQ_THISIS = 120
.const HSTR_PIQ_TELEPORT = 121
.const HSTR_PIQ_MUCH_BETTER = 122
.const HSTR_PIQ_MIND_CLEAR = 123
.const HSTR_PIQ_HEROIC = 124
.const HSTR_PIQ_CANT_SEE = 125
.const HSTR_PIQ_DIZZY = 126
.const HSTR_PIQ_SENSE = 127
.const HSTR_PIQ_EYES_TINGLE = 128
.const HSTR_PIQ_AIR_CRACKLE = 129
.const HSTR_PIQ_CLEANSED = 130
.const HSTR_PIQ_WPN_GLOW = 131
.const HSTR_PIQ_ARM_GLOW = 132
.const HSTR_PIQ_HANDS_GLOW = 133
.const HSTR_PIQ_HUMMING = 134
.const HSTR_PIQ_PROTECTED = 135
.const HSTR_PIQ_VIBRATION = 136
.const HSTR_PIW_AIM_PROMPT = 137
.const HSTR_PIW_USE_PROMPT = 138
.const HSTR_PIW_NOT_WAND = 139
.const HSTR_PIW_NOT_STAFF = 140
.const HSTR_PIW_NO_CHARGES = 141
.const HSTR_PIW_STAFF_EMPTY = 142
.const HSTR_PIW_WAND_BOLT = 143
.const HSTR_PIW_WAND_FROST = 144
.const HSTR_PIW_WAND_CLOUD = 145
.const HSTR_PIW_WAND_MISS = 146
.const HSTR_PIQ_CANT_READ = 147
.const HSTR_IGS_PROMPT = 148
.const HSTR_IGS_NO_MAGIC = 149
.const HSTR_IGS_NOT_BOOK = 150
.const HSTR_IGS_WRONG_TYPE = 151
.const HSTR_IGS_SUCCESS = 152
.const HSTR_IGS_NO_NEW = 153
.const HSTR_PIR_NOT_LAMP = 154
.const HSTR_PIR_NO_OIL = 155
.const HSTR_PIR_OVERFLOW = 156
.const HSTR_PIR_FULL = 157
.const HSTR_PIR_REFUELED = 158
.const HSTR_CMB_LVLUP = 159
.const HSTR_UIS_GOLD = 160
.const HSTR_UIS_BIG_GOLD = 161
.const HSTR_UIS_MENU = 162
.const HSTR_UIS_BUY_WHICH = 163
.const HSTR_UIS_PRICE = 164
.const HSTR_UIS_GP_BUY = 165
.const HSTR_UIS_BOUGHT = 166
.const HSTR_UIS_NO_AFFORD = 167
.const HSTR_UIS_PACK_FULL = 168
.const HSTR_UIS_SELL_TITLE = 169
.const HSTR_UIS_SELL_WHICH = 170
.const HSTR_UIS_OFFER = 171
.const HSTR_UIS_GP_SELL = 172
.const HSTR_UIS_SOLD = 173
.const HSTR_UIS_NO_BUY = 174
.const HSTR_UIS_WORTHLESS = 175
.const HSTR_UIS_STORE_FULL = 176
.const HSTR_UIS_CURSED = 177
.const HSTR_HG_ASKS = 178
.const HSTR_HG_OFFERS = 179
.const HSTR_HG_GP = 180
.const HSTR_HG_YOUR_OFFER = 181
.const HSTR_HG_YOUR_PRICE = 182
.const HSTR_HG_COUNTER = 183
.const HSTR_HG_QMARK = 184
.const HSTR_HG_FINAL = 185
.const HSTR_HG_TAKE = 186
.const HSTR_HG_KICKED = 187
.const HSTR_HG_AGREED = 188
.const HSTR_TUN_DIG_GRANITE = 189
.const HSTR_TUN_DIG_MAGMA = 190
.const HSTR_TUN_DIG_QUARTZ = 191
.const HSTR_TUN_FINISHED = 192
.const HSTR_TUN_FOUND = 193
.const HSTR_TUN_PERMANENT = 194
.const HSTR_TUN_NOTHING = 195
.const HSTR_TUN_RUBBLE = 196
.const HSTR_TUN_NO_TOOL = 197
.const HSTR_IPU_NOTHING = 198
.const HSTR_IPU_FOUND = 199
.const HSTR_IPU_GOLD = 200
.const HSTR_IPU_PICKED = 201
.const HSTR_IDR_PROMPT = 202
.const HSTR_IDR_DROP = 203
.const HSTR_IDR_FLOOR_FULL = 204
.const HSTR_PID_TERRIBLE = 205
.const HSTR_PID_BAD = 206
.const HSTR_PID_AVERAGE = 207
.const HSTR_PID_GOOD = 208
.const HSTR_PID_EXCELLENT = 209
.const HSTR_BASH_SMASH = 210
.const HSTR_BASH_CRASH = 211
.const HSTR_BASH_HOLDS = 212
.const HSTR_BASH_OFFBAL = 213
.const HSTR_BASH_NOTHING = 214
.const HSTR_BASH_EMPTY = 215
.const HSTR_BASH_STUNNED = 216
.const HSTR_BASH_IGNORES = 217

// Huffman tree: 61 internal nodes
// Children: $00-$7E = node index, $80+ = leaf (& $7F = screencode)
huff_tree_left:
    .byte $01, $03, $05, $07, $09, $0b, $0c, $0e, $93, $10, $11, $12, $8f, $85, $86, $16, $17, $ae, $8c, $88, $8e, $95, $1c, $1d, $8d, $1f, $90, $83, $22, $8b, $d4, $96, $26, $27, $28, $2a, $ce, $ad, $2d, $a8, $c2, $9a, $30, $32, $ac, $35, $ba, $98, $37, $d2, $c3, $c5, $38, $d1, $a7, $cd, $3a, $cf, $91, $b3, $be
huff_tree_right:
    .byte $02, $04, $06, $08, $0a, $a0, $0d, $0f, $94, $80, $81, $13, $14, $15, $84, $d9, $18, $19, $1a, $1b, $89, $92, $97, $99, $1e, $87, $20, $21, $23, $bf, $24, $25, $82, $a1, $29, $2b, $2c, $d3, $2e, $a9, $2f, $c9, $31, $33, $34, $c1, $36, $af, $b5, $c7, $d0, $c8, $39, $c4, $d7, $bd, $3b, $3c, $c6, $b6, $d5

// String index: 16-bit byte offsets into huff_str_data
huff_str_index:
    .word $0000  // [0] "You will have to do better tha"
    .word $0015  // [1] "That is an insult!"
    .word $0020  // [2] "Do you wish to do business or "
    .word $0034  // [3] "Hah! Try again."
    .word $003f  // [4] "Ridiculous!"
    .word $0048  // [5] "You have got to be kidding!"
    .word $0059  // [6] "You had better be kidding!"
    .word $0069  // [7] "You try my patience."
    .word $0076  // [8] "I do not hear you."
    .word $0081  // [9] "Hmmm, nice weather we are havi"
    .word $0096  // [10] "I must have heard you wrong."
    .word $00a7  // [11] "What was that?"
    .word $00b0  // [12] "I am sorry, say that again."
    .word $00c1  // [13] "What did you say?"
    .word $00cc  // [14] "Sorry, what was that again?"
    .word $00dd  // [15] @MAT_HITS " hits you."
    .word $00e3  // [16] @MAT_MISS " misses you."
    .word $00eb  // [17] @MAT_POISON " poisons you."
    .word $00f3  // [18] @MAT_CONFUSE " confuses you."
    .word $00fc  // [19] @MAT_PARALYZE " paralyzes you."
    .word $0106  // [20] @MAT_ACID " spits acid on you."
    .word $0111  // [21] @MAT_FEAR " frightens you."
    .word $011b  // [22] @MAT_SHRIEK "You hear a horrible shriek!"
    .word $012c  // [23] @MAT_DEAD "You have been slain."
    .word $0138  // [24] @MM_BOLT " casts a bolt!"
    .word $0141  // [25] @MM_BREATH " breathes fire!"
    .word $014b  // [26] @MM_SUMMON " summons help!"
    .word $0154  // [27] @MM_TELEPORT " teleports you!"
    .word $015d  // [28] @MM_BLIND " blinds you!"
    .word $0165  // [29] @MM_CONFUSE " confuses you!"
    .word $016e  // [30] @MM_HEAL " heals itself."
    .word $0176  // [31] @RF_NO_WEAPON "No ranged weapon."
    .word $0181  // [32] @RF_NO_AMMO "No ammo."
    .word $0187  // [33] @RF_FLIES " flies away."
    .word $018f  // [34] @RF_MISSES " misses"
    .word $0194  // [35] @RF_HITS " hits"
    .word $0198  // [36] @EB_SPELL_HITS "Your spell hits"
    .word $01a1  // [37] @EB_FIZZLE "Your spell fizzles out."
    .word $01b0  // [38] @TW_PROMPT "Throw which item (a-v)?"
    .word $01c0  // [39] @TW_SHATTERS " shatters!"
    .word $01c6  // [40] @EFF_POISON_END "You feel better."
    .word $01d0  // [41] @EFF_BLIND_END "You can see again."
    .word $01db  // [42] @EFF_CONFUSE_END "You feel less confused."
    .word $01e9  // [43] @EFF_PARALYZE_END "You can move again."
    .word $01f5  // [44] @EFF_FEAR_END "You feel bolder now."
    .word $0201  // [45] @TTL_DIM "Your light is growing dim."
    .word $0211  // [46] @TTL_OUT "Your light has gone out."
    .word $021f  // [47] @RECALL_ARRIVE "You feel yourself yanked away!"
    .word $0231  // [48] @DL_YOU_SEE "You see a "
    .word $0237  // [49] @DL_OPEN_DOOR "You see an open door."
    .word $0243  // [50] @DL_CLOSED_DOOR "You see a closed door."
    .word $0250  // [51] @DL_STAIRS_DN "You see a staircase down."
    .word $025e  // [52] @DL_STAIRS_UP "You see a staircase up."
    .word $026b  // [53] @DL_TRAP "You see a trap."
    .word $0274  // [54] @DL_RUBBLE "You see rubble."
    .word $027e  // [55] @DL_WALL "You see a wall."
    .word $0287  // [56] @DL_NOTHING "You see nothing special."
    .word $0295  // [57] @PTM_AFRAID "You are too afraid!"
    .word $02a0  // [58] @DF_TRAP_0 "an open pit"
    .word $02a7  // [59] @DF_TRAP_1 "an arrow trap"
    .word $02af  // [60] @DF_TRAP_2 "a poison gas trap"
    .word $02b9  // [61] @DF_TRAP_3 "a teleport trap"
    .word $02c2  // [62] @DF_TRAP_4 "a poison dart"
    .word $02ca  // [63] @DF_TRAP_5 "a rockfall trap"
    .word $02d4  // [64] @DF_DIRECTION "Direction?"
    .word $02dc  // [65] @DF_DOOR_STUCK "The door is stuck."
    .word $02e7  // [66] @DF_FOUND_TRAP "You found a trap!"
    .word $02f2  // [67] @DF_FOUND_SECRET "You found a secret door!"
    .word $0300  // [68] @DF_FOUND_NOTHING "You found nothing."
    .word $030b  // [69] @DF_NO_DOOR "No door there."
    .word $0314  // [70] @DF_ALREADY_OPEN "The door is already open."
    .word $0323  // [71] @DF_ALREADY_CLOSED "It is already closed."
    .word $0330  // [72] @DF_DOOR_OPENED "You open the door."
    .word $033b  // [73] @DF_DOOR_CLOSED "You close the door."
    .word $0346  // [74] @DF_YOU_FELL "You fell into a pit!"
    .word $0352  // [75] @DF_ARROW_HITS "An arrow hits you!"
    .word $035e  // [76] @DF_POISON_GAS "A cloud of gas surrounds you!"
    .word $0370  // [77] @DF_TELEPORTED "You are teleported!"
    .word $037c  // [78] @DF_DART_HITS "A dart hits you!"
    .word $0386  // [79] @DF_ROCKFALL "Rocks fall on you!"
    .word $0392  // [80] @DF_DAMAGE_PRE "You take "
    .word $0398  // [81] @DF_DAMAGE_POST " damage."
    .word $039e  // [82] @DF_CON_DRAIN "You feel weakened."
    .word $03a9  // [83] @DF_POISONED "You feel poisoned."
    .word $03b4  // [84] @PM_NO_CAST "You cannot cast spells."
    .word $03c2  // [85] @PM_NO_PRAY "You cannot pray."
    .word $03cc  // [86] @PM_NOT_KNOWN "You don't know that spell."
    .word $03dc  // [87] @PM_NO_MANA "Not enough mana."
    .word $03e6  // [88] @PM_NO_EXP "You're not experienced enough."
    .word $03f9  // [89] @PM_FAIL "Your spell fails."
    .word $0404  // [90] @PM_YOU_CAST "You cast "
    .word $040a  // [91] @PM_YOU_PRAY "You pray "
    .word $0410  // [92] @PM_TITLE_MAGE "Mage Spells"
    .word $0418  // [93] @PM_TITLE_PRAY "Prayers"
    .word $041e  // [94] @PM_FOOTER_CAST "Cast which? (a-p, ESC)"
    .word $0430  // [95] @PM_FOOTER_PRAY "Pray which? (a-p, ESC)"
    .word $0442  // [96] @PM_LEARNED "You have learned "
    .word $044c  // [97] @PIW_WEAR_PROMPT "Wear which item (a-v)?"
    .word $045c  // [98] @PIW_TAKEOFF_PROMPT "Take off which item (a-h)?"
    .word $046e  // [99] @PIW_NOTHING "You have nothing there."
    .word $047c  // [100] @PIW_CANT_WEAR "You cannot wear that."
    .word $0488  // [101] @PIW_NEVERMIND "Never mind."
    .word $0490  // [102] @PIW_CURSED "You cannot remove it, it is cu"
    .word $04a5  // [103] @PIW_NO_FOOD "You have no food."
    .word $04af  // [104] @PIW_WIELD "You are wielding a "
    .word $04ba  // [105] @PIW_WEARING "You are wearing a "
    .word $04c5  // [106] @PIW_TAKEOFF "You take off the "
    .word $04cf  // [107] @PIW_EAT "You eat the "
    .word $04d6  // [108] @PIW_DELICIOUS ". Delicious!"
    .word $04df  // [109] @PIW_YUCK ". Yuck!"
    .word $04e5  // [110] @PIQ_QUAFF_PROMPT "Quaff which potion (a-v)?"
    .word $04f7  // [111] @PIQ_READ_PROMPT "Read which scroll (a-v)?"
    .word $0508  // [112] @PIQ_NOT_POTION "That is not a potion."
    .word $0514  // [113] @PIQ_NOT_SCROLL "That is not a scroll."
    .word $0520  // [114] @PIQ_FEEL_BETTER "You feel better."
    .word $052a  // [115] @PIQ_SPEED "You feel yourself moving faste"
    .word $053d  // [116] @PIQ_TERRIBLE "That tasted terrible!"
    .word $054a  // [117] @PIQ_NOTHING "Nothing seems to happen."
    .word $0559  // [118] @PIQ_LIGHT "The area fills with light."
    .word $0569  // [119] @PIQ_IDENTIFY_PROMPT "Identify which item (a-v)?"
    .word $057b  // [120] @PIQ_THISIS "This is a "
    .word $0581  // [121] @PIQ_TELEPORT "You feel disoriented."
    .word $058e  // [122] @PIQ_MUCH_BETTER "You feel much better."
    .word $059b  // [123] @PIQ_MIND_CLEAR "Your mind feels clear."
    .word $05a8  // [124] @PIQ_HEROIC "You feel heroic!"
    .word $05b2  // [125] @PIQ_CANT_SEE "You can't see!"
    .word $05bb  // [126] @PIQ_DIZZY "You feel dizzy."
    .word $05c6  // [127] @PIQ_SENSE "You sense nearby creatures."
    .word $05d6  // [128] @PIQ_EYES_TINGLE "Your eyes tingle."
    .word $05e1  // [129] @PIQ_AIR_CRACKLE "The air crackles around you."
    .word $05f2  // [130] @PIQ_CLEANSED "You feel cleansed."
    .word $05fd  // [131] @PIQ_WPN_GLOW "Your weapon glows briefly."
    .word $060d  // [132] @PIQ_ARM_GLOW "Your armor glows briefly."
    .word $061d  // [133] @PIQ_HANDS_GLOW "Your hands begin to glow."
    .word $062c  // [134] @PIQ_HUMMING "You hear a high-pitched hummin"
    .word $0640  // [135] @PIQ_PROTECTED "You feel protected."
    .word $064c  // [136] @PIQ_VIBRATION "You feel a strange vibration."
    .word $065d  // [137] @PIW_AIM_PROMPT "Aim which wand (a-v)?"
    .word $066d  // [138] @PIW_USE_PROMPT "Use which staff (a-v)?"
    .word $067d  // [139] @PIW_NOT_WAND "That is not a wand."
    .word $0688  // [140] @PIW_NOT_STAFF "That is not a staff."
    .word $0694  // [141] @PIW_NO_CHARGES "No charges left."
    .word $069e  // [142] @PIW_STAFF_EMPTY "The staff is empty."
    .word $06aa  // [143] @PIW_WAND_BOLT "A bolt of lightning shoots for"
    .word $06be  // [144] @PIW_WAND_FROST "A bolt of frost shoots forth!"
    .word $06cf  // [145] @PIW_WAND_CLOUD "The monster looks confused."
    .word $06df  // [146] @PIW_WAND_MISS "The cloud dissipates."
    .word $06ec  // [147] @PIQ_CANT_READ "You can't see to read!"
    .word $06f9  // [148] @IGS_PROMPT "Study which book (a-v)?"
    .word $070a  // [149] @IGS_NO_MAGIC "You cannot use magic."
    .word $0717  // [150] @IGS_NOT_BOOK "That is not a book."
    .word $0723  // [151] @IGS_WRONG_TYPE "You cannot read that book."
    .word $0732  // [152] @IGS_SUCCESS "You learn from the book!"
    .word $0741  // [153] @IGS_NO_NEW "No new spells to learn."
    .word $074f  // [154] @PIR_NOT_LAMP "Not using a lamp."
    .word $075a  // [155] @PIR_NO_OIL "You have no oil."
    .word $0764  // [156] @PIR_OVERFLOW "Your lamp overflows."
    .word $0771  // [157] @PIR_FULL "Your lamp is full."
    .word $077c  // [158] @PIR_REFUELED "Your lamp is refueled."
    .word $0789  // [159] @CMB_LVLUP "Welcome to level "
    .word $0794  // [160] @UIS_GOLD "Gold: "
    .word $0799  // [161] @UIS_BIG_GOLD ">65535"
    .word $07a2  // [162] @UIS_MENU "B)uy  S)ell  Q)uit"
    .word $07b0  // [163] @UIS_BUY_WHICH "Buy which item? (a-l)"
    .word $07bf  // [164] @UIS_PRICE "Price: "
    .word $07c5  // [165] @UIS_GP_BUY " gp. Buy? (Y/N)"
    .word $07d1  // [166] @UIS_BOUGHT "Bought!"
    .word $07d7  // [167] @UIS_NO_AFFORD "You cannot afford that."
    .word $07e5  // [168] @UIS_PACK_FULL "Your pack is full."
    .word $07f1  // [169] @UIS_SELL_TITLE "Sell Items"
    .word $07f8  // [170] @UIS_SELL_WHICH "Sell which item? (a-v)"
    .word $0808  // [171] @UIS_OFFER "Offer: "
    .word $080e  // [172] @UIS_GP_SELL " gp. Sell? (Y/N)"
    .word $081b  // [173] @UIS_SOLD "Sold!"
    .word $0820  // [174] @UIS_NO_BUY "We don't buy that."
    .word $082c  // [175] @UIS_WORTHLESS "That is worthless."
    .word $0837  // [176] @UIS_STORE_FULL "The store is full."
    .word $0842  // [177] @UIS_CURSED "That item is cursed."
    .word $084e  // [178] @HG_ASKS "Asks "
    .word $0852  // [179] @HG_OFFERS "Offers "
    .word $0858  // [180] @HG_GP " gp."
    .word $085b  // [181] @HG_YOUR_OFFER "Your offer? (Q=cancel)"
    .word $086b  // [182] @HG_YOUR_PRICE "Your price? (Q=cancel)"
    .word $087c  // [183] @HG_COUNTER "How about "
    .word $0883  // [184] @HG_QMARK " gp?"
    .word $0887  // [185] @HG_FINAL "Final offer: "
    .word $0891  // [186] @HG_TAKE "Take it? (Y/N)"
    .word $089c  // [187] @HG_KICKED "Get out of my store!"
    .word $08a8  // [188] @HG_AGREED "Agreed!"
    .word $08ae  // [189] @TUN_DIG_GRANITE "You dig in the granite wall."
    .word $08bf  // [190] @TUN_DIG_MAGMA "You dig in the magma."
    .word $08cc  // [191] @TUN_DIG_QUARTZ "You dig in the quartz vein."
    .word $08de  // [192] @TUN_FINISHED "You have finished the tunnel."
    .word $08ef  // [193] @TUN_FOUND "You have found something!"
    .word $08ff  // [194] @TUN_PERMANENT "This seems to be permanent roc"
    .word $0912  // [195] @TUN_NOTHING "There is nothing to tunnel her"
    .word $0925  // [196] @TUN_RUBBLE "The rubble crumbles."
    .word $0933  // [197] @TUN_NO_TOOL "You dig with your hands, makin"
    .word $094e  // [198] @IPU_NOTHING "You see nothing here."
    .word $095a  // [199] @IPU_FOUND "You found "
    .word $0960  // [200] @IPU_GOLD " gold pieces."
    .word $0968  // [201] @IPU_PICKED "You picked up a "
    .word $0972  // [202] @IDR_PROMPT "Drop which item (a-v)?"
    .word $0982  // [203] @IDR_DROP "You drop a "
    .word $0989  // [204] @IDR_FLOOR_FULL "No room on the floor."
    .word $0996  // [205] @PID_TERRIBLE "Sense: Terrible"
    .word $09a1  // [206] @PID_BAD "Sense: Bad"
    .word $09a9  // [207] @PID_AVERAGE "Sense: Average"
    .word $09b3  // [208] @PID_GOOD "Sense: Good"
    .word $09bb  // [209] @PID_EXCELLENT "Sense: Excellent"
    .word $09c7  // [210] @BASH_SMASH "You smash into the door!"
    .word $09d5  // [211] @BASH_CRASH "The door crashes open!"
    .word $09e3  // [212] @BASH_HOLDS "The door holds firm."
    .word $09ef  // [213] @BASH_OFFBAL "You are off balance."
    .word $09fb  // [214] @BASH_NOTHING "Nothing interesting happens."
    .word $0a0d  // [215] @BASH_EMPTY "You bash at empty space."
    .word $0a1c  // [216] @BASH_STUNNED " appears stunned!"
    .word $0a27  // [217] @BASH_IGNORES " ignores your bash!"

// Compressed string data (2611 bytes)
huff_str_data:
    // [0] "You will have to do better than that!" (38→21 bytes)
    .byte $1e, $7a, $8b, $b8, $42, $c9, $da, $75, $3c, $a1, $cb, $1f, $8c, $fb, $f4, $e4, $fa, $a7, $27, $39, $ea
    // [1] "That is an insult!" (19→11 bytes)
    .byte $4d, $27, $3b, $b2, $af, $ab, $bd, $17, $a0, $73, $d4
    // [2] "Do you wish to do business or not?" (35→20 bytes)
    .byte $8c, $72, $a3, $9e, $a2, $ec, $a5, $4f, $28, $72, $c7, $f1, $6f, $5c, $45, $73, $f7, $58, $68, $54
    // [3] "Hah! Try again." (16→11 bytes)
    .byte $13, $de, $53, $ea, $6f, $a3, $5d, $b7, $de, $98, $a0
    // [4] "Ridiculous!" (12→9 bytes)
    .byte $12, $b6, $1d, $cd, $e8, $67, $8a, $7a, $80
    // [5] "You have got to be kidding!" (28→17 bytes)
    .byte $1e, $7a, $c9, $da, $75, $6f, $0e, $9e, $58, $fd, $50, $6c, $21, $de, $9b, $9e, $a0
    // [6] "You had better be kidding!" (27→16 bytes)
    .byte $1e, $7a, $c9, $c3, $63, $f1, $9f, $7e, $c7, $ea, $83, $61, $0e, $f4, $dc, $f5
    // [7] "You try my patience." (21→13 bytes)
    .byte $1e, $7a, $9f, $d1, $a9, $23, $62, $73, $df, $6a, $6e, $62, $80
    // [8] "I do not hear you." (19→11 bytes)
    .byte $11, $d0, $e5, $d6, $1d, $97, $3f, $ea, $39, $e6, $28
    // [9] "Hmmm, nice weather we are having." (34→21 bytes)
    .byte $13, $d2, $49, $24, $f5, $d6, $e6, $ea, $2f, $39, $cb, $bf, $45, $ea, $ff, $eb, $27, $69, $bd, $36, $c5
    // [10] "I must have heard you wrong." (29→17 bytes)
    .byte $11, $d4, $bc, $47, $64, $ed, $3a, $cb, $9f, $e1, $a8, $e7, $a8, $bf, $cd, $36, $c5
    // [11] "What was that?" (15→9 bytes)
    .byte $8d, $e4, $e7, $45, $72, $a7, $27, $34, $2a
    // [12] "I am sorry, say that again." (28→17 bytes)
    .byte $11, $d7, $4a, $96, $7f, $e8, $a7, $a9, $3a, $34, $e4, $e7, $5d, $b7, $de, $98, $a0
    // [13] "What did you say?" (18→11 bytes)
    .byte $8d, $e4, $e7, $43, $b0, $d4, $73, $d4, $9d, $14, $2a
    // [14] "Sorry, what was that again?" (28→17 bytes)
    .byte $6b, $cf, $fd, $14, $f5, $16, $4e, $74, $57, $2a, $72, $73, $ae, $db, $ef, $48, $54
    // [15] " hits you." (11→6 bytes)
    .byte $b2, $d9, $95, $47, $3c, $c5
    // [16] " misses you." (13→8 bytes)
    .byte $a9, $6c, $8b, $8a, $a3, $9e, $62, $80
    // [17] " poisons you." (14→8 bytes)
    .byte $b1, $66, $cb, $34, $55, $1c, $f3, $14
    // [18] " confuses you." (15→9 bytes)
    .byte $b3, $66, $81, $e2, $e2, $a8, $e7, $98, $a0
    // [19] " paralyzes you." (16→10 bytes)
    .byte $b1, $3f, $de, $08, $88, $b8, $aa, $39, $e6, $28
    // [20] " spits acid on you." (20→11 bytes)
    .byte $a5, $16, $cc, $ab, $cd, $b0, $dc, $d5, $47, $3c, $c5
    // [21] " frightens you." (16→10 bytes)
    .byte $a0, $fe, $db, $91, $f6, $8a, $a3, $9e, $62, $80
    // [22] "You hear a horrible shriek!" (28→17 bytes)
    .byte $1e, $7a, $cb, $9f, $f5, $ec, $b3, $ff, $dc, $78, $75, $29, $7f, $7c, $82, $7a, $80
    // [23] "You have been slain." (21→12 bytes)
    .byte $1e, $7a, $c9, $da, $75, $8f, $dd, $aa, $50, $7d, $e9, $8a
    // [24] " casts a bolt!" (15→9 bytes)
    .byte $b3, $39, $19, $57, $b1, $f2, $07, $3d, $40
    // [25] " breathes fire!" (16→10 bytes)
    .byte $b1, $ff, $ce, $72, $e2, $a0, $df, $fa, $7a, $80
    // [26] " summons help!" (15→9 bytes)
    .byte $a5, $e4, $92, $cd, $15, $97, $42, $29, $ea
    // [27] " teleports you!" (16→9 bytes)
    .byte $a7, $d0, $e8, $b3, $e6, $55, $1c, $f4, $f5
    // [28] " blinds you!" (13→8 bytes)
    .byte $b1, $e1, $bd, $04, $aa, $39, $e9, $ea
    // [29] " confuses you!" (15→9 bytes)
    .byte $b3, $66, $81, $e2, $e2, $a8, $e7, $a7, $a8
    // [30] " heals itself." (15→8 bytes)
    .byte $b2, $e7, $81, $5d, $99, $74, $00, $c5
    // [31] "No ranged weapon." (18→11 bytes)
    .byte $4e, $cb, $f7, $d3, $7c, $1a, $2f, $3c, $59, $a6, $28
    // [32] "No ammo." (9→6 bytes)
    .byte $4e, $ca, $e9, $25, $8c, $50
    // [33] " flies away." (13→8 bytes)
    .byte $a0, $86, $f8, $ab, $8a, $e8, $b1, $40
    // [34] " misses" (8→5 bytes)
    .byte $a9, $6c, $8b, $89, $40
    // [35] " hits" (6→4 bytes)
    .byte $b2, $d9, $92, $80
    // [36] "Your spell hits" (16→9 bytes)
    .byte $1e, $7b, $f4, $a2, $e8, $42, $cb, $66, $4a
    // [37] "Your spell fizzles out." (24→15 bytes)
    .byte $1e, $7b, $f4, $a2, $e8, $42, $83, $62, $21, $14, $38, $ae, $78, $d8, $a0
    // [38] "Throw which item (a-v)?" (24→16 bytes)
    .byte $4d, $2f, $e0, $b4, $59, $6e, $69, $5d, $9f, $25, $67, $1d, $a9, $a4, $ea, $15
    // [39] " shatters!" (11→6 bytes)
    .byte $a5, $27, $33, $ef, $94, $f5
    // [40] "You feel better." (17→10 bytes)
    .byte $1e, $7a, $83, $ba, $16, $3f, $19, $f7, $d8, $a0
    // [41] "You can see again." (19→11 bytes)
    .byte $1e, $7a, $cc, $fa, $a5, $dd, $5d, $b7, $de, $98, $a0
    // [42] "You feel less confused." (24→14 bytes)
    .byte $1e, $7a, $83, $ba, $16, $1c, $45, $66, $cd, $03, $c5, $c1, $62, $80
    // [43] "You can move again." (20→12 bytes)
    .byte $1e, $7a, $cc, $fa, $a9, $63, $4e, $ae, $db, $ef, $4c, $50
    // [44] "You feel bolder now." (21→12 bytes)
    .byte $1e, $7a, $83, $ba, $16, $3e, $40, $3d, $fb, $ac, $15, $8a
    // [45] "Your light is growing dim." (27→16 bytes)
    .byte $1e, $7b, $f6, $1b, $6e, $47, $76, $55, $bf, $e0, $bb, $d3, $74, $3b, $49, $8a
    // [46] "Your light has gone out." (25→14 bytes)
    .byte $1e, $7b, $f6, $1b, $6e, $47, $64, $e5, $5b, $cd, $75, $cf, $1b, $14
    // [47] "You feel yourself yanked away!" (31→18 bytes)
    .byte $1e, $7a, $83, $ba, $15, $1c, $f7, $cb, $a0, $0a, $8b, $e9, $07, $06, $b8, $ae, $8c, $f5
    // [48] "You see a " (11→6 bytes)
    .byte $1e, $7a, $97, $75, $7a, $a0
    // [49] "You see an open door." (22→12 bytes)
    .byte $1e, $7a, $97, $75, $7d, $5c, $8b, $b5, $43, $99, $f6, $28
    // [50] "You see a closed door." (23→13 bytes)
    .byte $1e, $7a, $97, $75, $7b, $34, $30, $b8, $34, $39, $9f, $62, $80
    // [51] "You see a staircase down." (26→14 bytes)
    .byte $1e, $7a, $97, $75, $7a, $46, $fb, $fc, $ce, $5d, $43, $82, $e9, $8a
    // [52] "You see a staircase up." (24→13 bytes)
    .byte $1e, $7a, $97, $75, $7a, $46, $fb, $fc, $ce, $5d, $7d, $13, $14
    // [53] "You see a trap." (16→9 bytes)
    .byte $1e, $7a, $97, $75, $7a, $7f, $78, $98, $a0
    // [54] "You see rubble." (16→10 bytes)
    .byte $1e, $7a, $97, $75, $ff, $a3, $c7, $87, $31, $40
    // [55] "You see a wall." (16→9 bytes)
    .byte $1e, $7a, $97, $75, $7a, $2b, $c2, $0c, $50
    // [56] "You see nothing special." (25→14 bytes)
    .byte $1e, $7a, $97, $75, $d6, $1c, $b7, $a6, $e9, $45, $d3, $6d, $e0, $c5
    // [57] "You are too afraid!" (20→11 bytes)
    .byte $1e, $7a, $bf, $fa, $9e, $65, $70, $7d, $f6, $19, $ea
    // [58] "an open pit" (12→7 bytes)
    .byte $7d, $5c, $8b, $b5, $62, $d9, $a8
    // [59] "an arrow trap" (14→8 bytes)
    .byte $7d, $57, $ff, $f0, $5a, $7f, $78, $94
    // [60] "a poison gas trap" (18→10 bytes)
    .byte $7b, $16, $6c, $b3, $55, $b7, $2a, $7f, $78, $94
    // [61] "a teleport trap" (16→9 bytes)
    .byte $7a, $7d, $0e, $8b, $3e, $74, $fe, $f1, $28
    // [62] "a poison dart" (14→8 bytes)
    .byte $7b, $16, $6c, $b3, $54, $2f, $f3, $50
    // [63] "a rockfall trap" (16→10 bytes)
    .byte $7b, $fc, $99, $00, $1e, $10, $a7, $f7, $89, $40
    // [64] "Direction?" (11→8 bytes)
    .byte $8c, $77, $fe, $98, $f7, $9a, $42, $a0
    // [65] "The door is stuck." (19→11 bytes)
    .byte $4d, $2e, $a1, $cc, $fd, $d9, $52, $3f, $4c, $81, $8a
    // [66] "You found a trap!" (18→11 bytes)
    .byte $1e, $7a, $83, $3d, $a0, $d7, $a7, $f7, $8a, $7a, $80
    // [67] "You found a secret door!" (25→14 bytes)
    .byte $1e, $7a, $83, $3d, $a0, $d7, $a5, $d3, $7f, $8e, $87, $33, $f3, $d4
    // [68] "You found nothing." (19→11 bytes)
    .byte $1e, $7a, $83, $3d, $a0, $dd, $61, $cb, $7a, $6d, $8a
    // [69] "No door there." (15→9 bytes)
    .byte $4e, $ca, $1c, $cf, $d3, $97, $7f, $98, $a0
    // [70] "The door is already open." (26→15 bytes)
    .byte $4d, $2e, $a1, $cc, $fd, $d9, $57, $87, $f9, $c2, $8d, $c8, $bb, $4c, $50
    // [71] "It is already closed." (22→13 bytes)
    .byte $11, $9d, $d9, $57, $87, $f9, $c2, $8d, $9a, $18, $5c, $16, $28
    // [72] "You open the door." (19→11 bytes)
    .byte $1e, $7a, $e4, $5d, $aa, $72, $ea, $1c, $cf, $b1, $40
    // [73] "You close the door." (20→11 bytes)
    .byte $1e, $7a, $cd, $0c, $2e, $a7, $2e, $a1, $cc, $fb, $14
    // [74] "You fell into a pit!" (21→12 bytes)
    .byte $1e, $7a, $83, $a1, $0b, $bd, $1e, $57, $b1, $6c, $e7, $a8
    // [75] "An arrow hits you!" (19→12 bytes)
    .byte $8c, $ea, $bf, $ff, $82, $d9, $6c, $ca, $a3, $9e, $9e, $a0
    // [76] "A cloud of gas surrounds you!" (30→18 bytes)
    .byte $8c, $d9, $a1, $9e, $0d, $c0, $56, $dc, $a9, $7b, $ff, $cf, $68, $25, $51, $cf, $4f, $50
    // [77] "You are teleported!" (20→12 bytes)
    .byte $1e, $7a, $bf, $fa, $9f, $43, $a2, $cf, $9f, $06, $7a, $80
    // [78] "A dart hits you!" (17→10 bytes)
    .byte $8c, $d0, $bf, $ce, $cb, $66, $55, $1c, $f4, $f5
    // [79] "Rocks fall on you!" (19→12 bytes)
    .byte $12, $b2, $64, $05, $40, $f0, $85, $cd, $54, $73, $d3, $d4
    // [80] "You take " (10→6 bytes)
    .byte $1e, $7a, $9b, $a0, $ea, $a0
    // [81] " damage." (9→6 bytes)
    .byte $a1, $74, $9d, $be, $62, $80
    // [82] "You feel weakened." (19→11 bytes)
    .byte $1e, $7a, $83, $ba, $14, $5e, $74, $1d, $ae, $0b, $14
    // [83] "You feel poisoned." (19→11 bytes)
    .byte $1e, $7a, $83, $ba, $16, $2c, $d9, $66, $b8, $2c, $50
    // [84] "You cannot cast spells." (24→14 bytes)
    .byte $1e, $7a, $cc, $fa, $d6, $1d, $99, $c8, $e9, $45, $d0, $81, $31, $40
    // [85] "You cannot pray." (17→10 bytes)
    .byte $1e, $7a, $cc, $fa, $d6, $1d, $8b, $ee, $8b, $14
    // [86] "You don't know that spell." (27→16 bytes)
    .byte $1e, $7a, $87, $35, $1b, $1d, $41, $ac, $16, $9c, $9c, $e9, $45, $d0, $83, $14
    // [87] "Not enough mana." (17→10 bytes)
    .byte $4e, $c3, $bd, $ac, $f3, $72, $a9, $3e, $9d, $8a
    // [88] "You're not experienced enough." (31→19 bytes)
    .byte $1e, $7a, $36, $ff, $5d, $61, $de, $10, $a2, $ef, $ef, $b5, $37, $06, $f6, $b3, $cd, $c9, $8a
    // [89] "Your spell fails." (18→11 bytes)
    .byte $1e, $7b, $f4, $a2, $e8, $42, $81, $f7, $02, $62, $80
    // [90] "You cast " (10→6 bytes)
    .byte $1e, $7a, $cc, $e4, $75, $40
    // [91] "You pray " (10→6 bytes)
    .byte $1e, $7a, $c5, $f7, $46, $a8
    // [92] "Mage Spells" (12→8 bytes)
    .byte $12, $0e, $df, $56, $b8, $ba, $10, $25
    // [93] "Prayers" (8→6 bytes)
    .byte $13, $7e, $e8, $f7, $c9, $40
    // [94] "Cast which? (a-p, ESC)" (23→18 bytes)
    .byte $13, $1c, $8e, $8b, $2d, $cd, $24, $36, $71, $da, $a2, $4f, $51, $39, $ac, $4c, $9d, $50
    // [95] "Pray which? (a-p, ESC)" (23→18 bytes)
    .byte $13, $7e, $e8, $d1, $65, $b9, $a4, $86, $ce, $3b, $54, $49, $ea, $27, $35, $89, $93, $aa
    // [96] "You have learned " (18→10 bytes)
    .byte $1e, $7a, $c9, $da, $75, $87, $3f, $f5, $c1, $aa
    // [97] "Wear which item (a-v)?" (23→16 bytes)
    .byte $8d, $f9, $ff, $45, $96, $e6, $95, $d9, $f2, $56, $71, $da, $9a, $4e, $a1, $50
    // [98] "Take off which item (a-h)?" (27→18 bytes)
    .byte $4c, $e8, $3a, $e0, $01, $45, $96, $e6, $95, $d9, $f2, $56, $71, $da, $a5, $3a, $85, $40
    // [99] "You have nothing there." (24→14 bytes)
    .byte $1e, $7a, $c9, $da, $75, $d6, $1c, $b7, $a6, $e9, $cb, $bf, $cc, $50
    // [100] "You cannot wear that." (22→12 bytes)
    .byte $1e, $7a, $cc, $fa, $d6, $1d, $17, $9f, $f4, $e4, $e6, $c5
    // [101] "Never mind." (12→8 bytes)
    .byte $4e, $e6, $9d, $fa, $96, $f4, $16, $28
    // [102] "You cannot remove it, it is cursed!" (36→21 bytes)
    .byte $1e, $7a, $cc, $fa, $d6, $1d, $ff, $25, $8d, $3a, $ec, $d3, $d7, $67, $76, $56, $6f, $7c, $b8, $33, $d4
    // [103] "You have no food." (18→10 bytes)
    .byte $1e, $7a, $c9, $da, $75, $d6, $50, $66, $05, $8a
    // [104] "You are wielding a " (20→11 bytes)
    .byte $1e, $7a, $bf, $fa, $8b, $be, $80, $77, $a6, $eb, $d5
    // [105] "You are wearing a " (19→11 bytes)
    .byte $1e, $7a, $bf, $fa, $8b, $cf, $fd, $e9, $ba, $f5, $40
    // [106] "You take off the " (18→10 bytes)
    .byte $1e, $7a, $9b, $a0, $eb, $80, $05, $39, $75, $50
    // [107] "You eat the " (13→7 bytes)
    .byte $1e, $7a, $f3, $9d, $39, $75, $50
    // [108] ". Delicious!" (13→9 bytes)
    .byte $65, $8c, $7a, $1b, $9b, $79, $e2, $9e, $a0
    // [109] ". Yuck!" (8→6 bytes)
    .byte $65, $1f, $a6, $41, $3d, $40
    // [110] "Quaff which potion (a-v)?" (26→18 bytes)
    .byte $8c, $3c, $e0, $05, $16, $5b, $9a, $56, $2c, $3d, $e6, $ac, $e3, $b5, $34, $9d, $42, $a0
    // [111] "Read which scroll (a-v)?" (25→17 bytes)
    .byte $12, $b9, $c3, $45, $96, $e6, $95, $29, $bf, $90, $85, $9c, $76, $a6, $93, $a8, $54
    // [112] "That is not a potion." (22→12 bytes)
    .byte $4d, $27, $3b, $b2, $ba, $c3, $af, $62, $c3, $de, $69, $8a
    // [113] "That is not a scroll." (22→12 bytes)
    .byte $4d, $27, $3b, $b2, $ba, $c3, $af, $4a, $6f, $e4, $20, $c5
    // [114] "You feel better." (17→10 bytes)
    .byte $1e, $7a, $83, $ba, $16, $3f, $19, $f7, $d8, $a0
    // [115] "You feel yourself moving faster." (33→19 bytes)
    .byte $1e, $7a, $83, $ba, $15, $1c, $f7, $cb, $a0, $0a, $96, $34, $de, $9b, $a0, $72, $3e, $fb, $14
    // [116] "That tasted terrible!" (22→13 bytes)
    .byte $4d, $27, $3a, $6e, $47, $c1, $a7, $df, $fe, $e3, $c3, $a7, $a8
    // [117] "Nothing seems to happen." (25→15 bytes)
    .byte $4e, $c3, $96, $f4, $dd, $2e, $e4, $8a, $9e, $59, $3c, $51, $76, $98, $a0
    // [118] "The area fills with light." (27→16 bytes)
    .byte $4d, $2e, $af, $fe, $7a, $0d, $c2, $05, $45, $d9, $ca, $c3, $6d, $c8, $d8, $a0
    // [119] "Identify which item (a-v)?" (27→18 bytes)
    .byte $11, $87, $b4, $7b, $02, $34, $59, $6e, $69, $5d, $9f, $25, $67, $1d, $a9, $a4, $ea, $15
    // [120] "This is a " (11→6 bytes)
    .byte $4d, $2d, $95, $d9, $57, $aa
    // [121] "You feel disoriented." (22→13 bytes)
    .byte $1e, $7a, $83, $ba, $14, $3b, $2c, $fe, $fb, $47, $c1, $62, $80
    // [122] "You feel much better." (22→13 bytes)
    .byte $1e, $7a, $83, $ba, $15, $2f, $4d, $2b, $1f, $8c, $fb, $ec, $50
    // [123] "Your mind feels clear." (23→13 bytes)
    .byte $1e, $7b, $f5, $2d, $e8, $34, $1d, $d0, $2b, $34, $39, $fe, $c5
    // [124] "You feel heroic!" (17→10 bytes)
    .byte $1e, $7a, $83, $ba, $16, $5d, $fc, $dc, $d3, $d4
    // [125] "You can't see!" (15→9 bytes)
    .byte $1e, $7a, $cc, $fa, $8d, $8e, $97, $74, $f5
    // [126] "You feel dizzy." (16→11 bytes)
    .byte $1e, $7a, $83, $ba, $14, $3b, $11, $08, $91, $62, $80
    // [127] "You sense nearby creatures." (28→16 bytes)
    .byte $1e, $7a, $97, $68, $ba, $eb, $9f, $f1, $d1, $b3, $7f, $9c, $fd, $fe, $26, $28
    // [128] "Your eyes tingle." (18→11 bytes)
    .byte $1e, $7b, $f7, $91, $e2, $a7, $bd, $37, $0e, $62, $80
    // [129] "The air crackles around you." (29→17 bytes)
    .byte $4d, $2e, $af, $bf, $d9, $be, $f3, $20, $87, $15, $7f, $e7, $b4, $1a, $8e, $79, $8a
    // [130] "You feel cleansed." (19→11 bytes)
    .byte $1e, $7a, $83, $ba, $16, $68, $73, $e8, $b8, $2c, $50
    // [131] "Your weapon glows briefly." (27→16 bytes)
    .byte $1e, $7b, $f4, $5e, $78, $b3, $55, $b8, $60, $a5, $63, $ff, $7c, $08, $22, $c5
    // [132] "Your armor glows briefly." (26→16 bytes)
    .byte $1e, $7b, $f5, $fe, $96, $7e, $b7, $0c, $14, $ac, $7f, $ef, $81, $04, $58, $a0
    // [133] "Your hands begin to glow." (26→15 bytes)
    .byte $1e, $7b, $f6, $4f, $a0, $95, $8f, $cd, $ef, $54, $f2, $b7, $0c, $15, $8a
    // [134] "You hear a high-pitched humming." (33→20 bytes)
    .byte $1e, $7a, $cb, $9f, $f5, $ec, $b6, $dc, $9a, $a2, $d9, $cd, $2e, $0d, $97, $92, $4b, $7a, $6d, $8a
    // [135] "You feel protected." (20→12 bytes)
    .byte $1e, $7a, $83, $ba, $16, $2f, $e1, $f4, $c7, $c1, $62, $80
    // [136] "You feel a strange vibration." (30→17 bytes)
    .byte $1e, $7a, $83, $ba, $15, $e9, $1f, $df, $4d, $f5, $69, $b8, $ff, $73, $de, $69, $8a
    // [137] "Aim which wand (a-v)?" (22→16 bytes)
    .byte $8c, $ed, $2a, $2c, $b7, $34, $a8, $af, $a0, $d9, $c7, $6a, $69, $3a, $85, $40
    // [138] "Use which staff (a-v)?" (23→16 bytes)
    .byte $4f, $f2, $ea, $2c, $b7, $34, $a9, $1b, $80, $16, $71, $da, $9a, $4e, $a1, $50
    // [139] "That is not a wand." (20→11 bytes)
    .byte $4d, $27, $3b, $b2, $ba, $c3, $af, $45, $7d, $05, $8a
    // [140] "That is not a staff." (21→12 bytes)
    .byte $4d, $27, $3b, $b2, $ba, $c3, $af, $48, $dc, $00, $62, $80
    // [141] "No charges left." (17→10 bytes)
    .byte $4e, $cb, $34, $9f, $ed, $f1, $58, $70, $0d, $8a
    // [142] "The staff is empty." (20→12 bytes)
    .byte $4d, $2e, $a4, $6e, $00, $5d, $95, $e4, $a2, $34, $58, $a0
    // [143] "A bolt of lightning shoots forth!" (34→20 bytes)
    .byte $8c, $d8, $f9, $03, $b8, $0b, $0d, $b7, $23, $d6, $f4, $dd, $29, $66, $19, $50, $67, $ce, $53, $d4
    // [144] "A bolt of frost shoots forth!" (30→17 bytes)
    .byte $8c, $d8, $f9, $03, $b8, $0a, $0f, $e1, $1d, $29, $66, $19, $50, $67, $ce, $53, $d4
    // [145] "The monster looks confused." (28→16 bytes)
    .byte $4d, $2e, $a9, $66, $88, $fb, $f6, $19, $88, $0a, $cd, $9a, $07, $8b, $82, $c5
    // [146] "The cloud dissipates." (22→13 bytes)
    .byte $4d, $2e, $b3, $43, $3c, $1a, $1d, $91, $6e, $27, $3e, $26, $28
    // [147] "You can't see to read!" (23→13 bytes)
    .byte $1e, $7a, $cc, $fa, $8d, $8e, $97, $75, $3c, $bf, $e7, $0c, $f5
    // [148] "Study which book (a-v)?" (24→17 bytes)
    .byte $6b, $3f, $05, $1a, $2c, $b7, $34, $ac, $7c, $c4, $16, $71, $da, $9a, $4e, $a1, $50
    // [149] "You cannot use magic." (22→13 bytes)
    .byte $1e, $7a, $cc, $fa, $d6, $1d, $f1, $75, $49, $db, $dc, $cc, $50
    // [150] "That is not a book." (20→12 bytes)
    .byte $4d, $27, $3b, $b2, $ba, $c3, $af, $63, $e6, $20, $62, $80
    // [151] "You cannot read that book." (27→15 bytes)
    .byte $1e, $7a, $cc, $fa, $d6, $1d, $ff, $38, $69, $c9, $ce, $c7, $cc, $40, $c5
    // [152] "You learn from the book!" (25→15 bytes)
    .byte $1e, $7a, $c3, $9f, $fa, $a0, $fe, $25, $4e, $5d, $63, $e6, $20, $9e, $a0
    // [153] "No new spells to learn." (24→14 bytes)
    .byte $4e, $cb, $ae, $16, $94, $5d, $08, $15, $3c, $b0, $e7, $fe, $98, $a0
    // [154] "Not using a lamp." (18→11 bytes)
    .byte $4e, $c3, $be, $2d, $e9, $ba, $f6, $0e, $94, $4c, $50
    // [155] "You have no oil." (17→10 bytes)
    .byte $1e, $7a, $c9, $da, $75, $d6, $5c, $dc, $18, $a0
    // [156] "Your lamp overflows." (21→13 bytes)
    .byte $1e, $7b, $f6, $0e, $94, $57, $1a, $77, $c1, $0c, $14, $98, $a0
    // [157] "Your lamp is full." (19→11 bytes)
    .byte $1e, $7b, $f6, $0e, $94, $57, $65, $41, $e8, $41, $8a
    // [158] "Your lamp is refueled." (23→13 bytes)
    .byte $1e, $7b, $f6, $0e, $94, $57, $65, $7f, $c0, $f7, $43, $82, $c5
    // [159] "Welcome to level " (18→11 bytes)
    .byte $8d, $fa, $13, $62, $5d, $4f, $2c, $39, $a7, $42, $a8
    // [160] "Gold: " (7→5 bytes)
    .byte $12, $f2, $01, $8d, $55
    // [161] ">65535" (7→9 bytes)
    .byte $4f, $e4, $fb, $12, $44, $94, $fa, $12, $54
    // [162] "B)uy  S)ell  Q)uit" (19→14 bytes)
    .byte $10, $4e, $f9, $1b, $5a, $e7, $7a, $10, $b6, $30, $9d, $f6, $cd, $40
    // [163] "Buy which item? (a-l)" (22→15 bytes)
    .byte $10, $79, $1a, $2c, $b7, $34, $ae, $cf, $92, $43, $67, $1d, $aa, $13, $aa
    // [164] "Price: " (8→6 bytes)
    .byte $13, $7f, $b9, $ba, $35, $54
    // [165] " gp. Buy? (Y/N)" (16→12 bytes)
    .byte $ad, $c4, $ca, $20, $f2, $28, $6c, $e0, $c4, $34, $e9, $d5
    // [166] "Bought!" (8→6 bytes)
    .byte $10, $67, $9b, $91, $cf, $50
    // [167] "You cannot afford that." (24→14 bytes)
    .byte $1e, $7a, $cc, $fa, $d6, $1d, $70, $03, $3e, $1a, $72, $73, $62, $80
    // [168] "Your pack is full." (19→12 bytes)
    .byte $1e, $7b, $f6, $27, $99, $05, $d9, $50, $7a, $10, $62, $80
    // [169] "Sell Items" (11→7 bytes)
    .byte $6b, $e8, $42, $88, $cf, $92, $25
    // [170] "Sell which item? (a-v)" (23→16 bytes)
    .byte $6b, $e8, $42, $8b, $2d, $cd, $2b, $b3, $e4, $90, $d9, $c7, $6a, $69, $3a, $a0
    // [171] "Offer: " (8→6 bytes)
    .byte $4f, $c0, $07, $7e, $35, $54
    // [172] " gp. Sell? (Y/N)" (17→13 bytes)
    .byte $ad, $c4, $ca, $d7, $d0, $82, $1b, $38, $31, $0d, $3a, $75, $40
    // [173] "Sold!" (6→5 bytes)
    .byte $6b, $c8, $06, $7a, $80
    // [174] "We don't buy that." (19→12 bytes)
    .byte $8d, $fa, $87, $35, $1b, $1d, $8f, $e4, $69, $c9, $cd, $8a
    // [175] "That is worthless." (19→11 bytes)
    .byte $4d, $27, $3b, $b2, $a2, $e7, $ce, $50, $e2, $26, $28
    // [176] "The store is full." (19→11 bytes)
    .byte $4d, $2e, $a4, $79, $fe, $bb, $2a, $0f, $42, $0c, $50
    // [177] "That item is cursed." (21→12 bytes)
    .byte $4d, $27, $3b, $b3, $e4, $ae, $ca, $cd, $ef, $97, $05, $8a
    // [178] "Asks " (6→4 bytes)
    .byte $8c, $92, $02, $aa
    // [179] "Offers " (8→6 bytes)
    .byte $4f, $c0, $07, $7c, $aa, $80
    // [180] " gp." (5→3 bytes)
    .byte $ad, $c4, $c5
    // [181] "Your offer? (Q=cancel)" (23→16 bytes)
    .byte $1e, $7b, $f7, $00, $0e, $fa, $1b, $39, $18, $09, $19, $9f, $53, $74, $27, $54
    // [182] "Your price? (Q=cancel)" (23→17 bytes)
    .byte $1e, $7b, $f6, $2f, $ee, $6e, $43, $67, $23, $01, $23, $33, $ea, $6e, $84, $ea, $80
    // [183] "How about " (11→7 bytes)
    .byte $13, $f0, $5a, $f1, $f3, $c7, $54
    // [184] " gp?" (5→4 bytes)
    .byte $ad, $c4, $85, $40
    // [185] "Final offer: " (14→10 bytes)
    .byte $4f, $9d, $e9, $e1, $70, $00, $ef, $c6, $aa, $80
    // [186] "Take it? (Y/N)" (15→11 bytes)
    .byte $4c, $e8, $3a, $ec, $d0, $d9, $c1, $88, $69, $d3, $aa
    // [187] "Get out of my store!" (21→12 bytes)
    .byte $12, $f8, $ee, $78, $ee, $02, $a4, $8d, $23, $cf, $f4, $f5
    // [188] "Agreed!" (8→6 bytes)
    .byte $8c, $b7, $fe, $e0, $cf, $50
    // [189] "You dig in the granite wall." (29→17 bytes)
    .byte $1e, $7a, $87, $6d, $dd, $ea, $9c, $ba, $b7, $f7, $d6, $cf, $a8, $af, $08, $31, $40
    // [190] "You dig in the magma." (22→13 bytes)
    .byte $1e, $7a, $87, $6d, $dd, $ea, $9c, $ba, $a4, $ed, $a4, $ec, $50
    // [191] "You dig in the quartz vein." (28→18 bytes)
    .byte $1e, $7a, $87, $6d, $dd, $ea, $9c, $ba, $a7, $c7, $9f, $e6, $22, $ad, $3b, $7a, $62, $80
    // [192] "You have finished the tunnel." (30→17 bytes)
    .byte $1e, $7a, $c9, $da, $75, $06, $f5, $b2, $97, $06, $9c, $ba, $9f, $b5, $ae, $83, $14
    // [193] "You have found something!" (26→16 bytes)
    .byte $1e, $7a, $c9, $da, $75, $06, $7b, $41, $a5, $89, $71, $cb, $7a, $6e, $7a, $80
    // [194] "This seems to be permanent rock." (33→19 bytes)
    .byte $4d, $2d, $95, $2e, $e4, $8a, $9e, $58, $fd, $62, $ef, $a4, $fa, $ed, $1d, $fe, $4c, $81, $8a
    // [195] "There is nothing to tunnel here." (33→19 bytes)
    .byte $4d, $2e, $ff, $5d, $95, $d6, $1c, $b7, $a6, $e9, $e5, $3f, $6b, $5d, $0b, $2e, $ff, $31, $40
    // [196] "The rubble crumbles." (21→14 bytes)
    .byte $4d, $2e, $bf, $f4, $78, $f0, $eb, $37, $fc, $94, $78, $71, $31, $40
    // [197] "You dig with your hands, making no progress." (45→27 bytes)
    .byte $1e, $7a, $87, $6d, $d1, $76, $72, $a8, $e7, $bf, $64, $fa, $09, $27, $aa, $4e, $83, $7a, $6e, $eb, $2c, $5f, $c6, $ff, $c4, $4c, $50
    // [198] "You see nothing here." (22→12 bytes)
    .byte $1e, $7a, $97, $75, $d6, $1c, $b7, $a6, $ec, $bb, $fc, $c5
    // [199] "You found " (11→6 bytes)
    .byte $1e, $7a, $83, $3d, $a0, $d5
    // [200] " gold pieces." (14→8 bytes)
    .byte $ad, $e4, $03, $62, $df, $4d, $c4, $c5
    // [201] "You picked up a " (17→10 bytes)
    .byte $1e, $7a, $c5, $b9, $90, $70, $6f, $a2, $af, $54
    // [202] "Drop which item (a-v)?" (23→16 bytes)
    .byte $8c, $7f, $91, $51, $65, $b9, $a5, $76, $7c, $95, $9c, $76, $a6, $93, $a8, $54
    // [203] "You drop a " (12→7 bytes)
    .byte $1e, $7a, $87, $f9, $15, $7a, $a0
    // [204] "No room on the floor." (22→13 bytes)
    .byte $4e, $cb, $fc, $c4, $ae, $6a, $9c, $ba, $82, $19, $9f, $62, $80
    // [205] "Sense: Terrible" (16→11 bytes)
    .byte $6b, $ed, $17, $46, $aa, $6e, $ff, $f7, $1e, $1c, $a0
    // [206] "Sense: Bad" (11→8 bytes)
    .byte $6b, $ed, $17, $46, $a8, $81, $c2, $a0
    // [207] "Sense: Average" (15→10 bytes)
    .byte $6b, $ed, $17, $46, $ac, $65, $a7, $7d, $db, $e5
    // [208] "Sense: Good" (12→8 bytes)
    .byte $6b, $ed, $17, $46, $a8, $97, $98, $15
    // [209] "Sense: Excellent" (17→12 bytes)
    .byte $6b, $ed, $17, $46, $a8, $9c, $21, $4d, $d0, $87, $68, $d4
    // [210] "You smash into the door!" (25→14 bytes)
    .byte $1e, $7a, $92, $4e, $52, $bb, $d1, $e5, $39, $75, $0e, $67, $e7, $a8
    // [211] "The door crashes open!" (23→14 bytes)
    .byte $4d, $2e, $a1, $cc, $fd, $9b, $ee, $52, $e2, $b9, $17, $6a, $7a, $80
    // [212] "The door holds firm." (21→12 bytes)
    .byte $4d, $2e, $a1, $cc, $fd, $96, $40, $25, $41, $bf, $a4, $c5
    // [213] "You are off balance." (21→12 bytes)
    .byte $1e, $7a, $bf, $fa, $e0, $01, $63, $bc, $1f, $53, $73, $14
    // [214] "Nothing interesting happens." (29→18 bytes)
    .byte $4e, $c3, $96, $f4, $dd, $de, $8f, $bf, $c4, $7b, $d3, $76, $4f, $14, $5d, $a2, $62, $80
    // [215] "You bash at empty space." (25→15 bytes)
    .byte $1e, $7a, $c7, $72, $95, $73, $bc, $94, $46, $8d, $28, $9e, $6e, $62, $80
    // [216] " appears stunned!" (18→11 bytes)
    .byte $af, $14, $5c, $ff, $2a, $47, $ed, $6b, $83, $3d, $40
    // [217] " ignores your bash!" (20→12 bytes)
    .byte $bb, $6f, $59, $fe, $2a, $8e, $7b, $f6, $3b, $94, $a7, $a8

// Huffman code table:
//   NULL   =         0101 (4 bits, freq=218)
//   a      =         0111 (4 bits, freq=247)
//   b      =      1000111 (7 bits, freq=38)
//   c      =       100110 (6 bits, freq=83)
//   d      =        00001 (5 bits, freq=96)
//   e      =         1110 (4 bits, freq=347)
//   f      =        00000 (5 bits, freq=84)
//   g      =       011011 (6 bits, freq=66)
//   h      =        10010 (5 bits, freq=152)
//   i      =        11011 (5 bits, freq=173)
//   k      =      0100000 (7 bits, freq=25)
//   l      =        10000 (5 bits, freq=142)
//   m      =       010010 (6 bits, freq=56)
//   n      =        11010 (5 bits, freq=167)
//   o      =         1100 (4 bits, freq=333)
//   p      =       100010 (6 bits, freq=71)
//   q      = 010011111000 (12 bits, freq=1)
//   r      =        11111 (5 bits, freq=178)
//   s      =         0010 (4 bits, freq=197)
//   t      =         0011 (4 bits, freq=212)
//   u      =        11110 (5 bits, freq=174)
//   v      =      0110100 (7 bits, freq=30)
//   w      =       000101 (6 bits, freq=50)
//   x      =   0001000010 (10 bits, freq=2)
//   y      =       010001 (6 bits, freq=54)
//   z      =    000100010 (9 bits, freq=6)
//   SPACE  =          101 (3 bits, freq=611)
//   $21    =      1001111 (7 bits, freq=43)
//   $27    =   1000110110 (10 bits, freq=5)
//   $28    =     10011100 (8 bits, freq=19)
//   $29    =     10011101 (8 bits, freq=22)
//   $2c    =    010011110 (9 bits, freq=7)
//   $2d    =     01101010 (8 bits, freq=15)
//   $2e    =        01100 (5 bits, freq=115)
//   $2f    =   0001000011 (10 bits, freq=3)
//   $33    = 010011111010 (12 bits, freq=1)
//   $35    =   0001001001 (10 bits, freq=3)
//   $36    = 010011111011 (12 bits, freq=1)
//   $3a    =    100011010 (9 bits, freq=9)
//   $3d    =  00010010001 (11 bits, freq=2)
//   $3e    = 010011111110 (12 bits, freq=1)
//   $3f    =      0100001 (7 bits, freq=25)
//   A      =    100011001 (9 bits, freq=9)
//   B      =    000100000 (9 bits, freq=5)
//   C      =   0001001100 (10 bits, freq=3)
//   D      =   1000110001 (10 bits, freq=4)
//   E      =   0001001110 (10 bits, freq=3)
//   F      = 010011111001 (12 bits, freq=1)
//   G      =   0001001011 (10 bits, freq=3)
//   H      =   0001001111 (10 bits, freq=3)
//   I      =    000100011 (9 bits, freq=6)
//   M      =  00010010000 (11 bits, freq=1)
//   N      =     01001110 (8 bits, freq=14)
//   O      =  01001111110 (11 bits, freq=2)
//   P      =   0001001101 (10 bits, freq=3)
//   Q      =   1000110000 (10 bits, freq=4)
//   R      =   0001001010 (10 bits, freq=3)
//   S      =     01101011 (8 bits, freq=15)
//   T      =      0100110 (7 bits, freq=28)
//   U      = 010011111111 (12 bits, freq=1)
//   W      =   1000110111 (10 bits, freq=5)
//   Y      =        00011 (5 bits, freq=98)
