// huffman_data.s — Generated by huff_encoder.py
// Source: data/huffman_strings.txt
// 222 strings, 4718 bytes uncompressed
// 2833 bytes compressed (60.0%)
// Tree: 112 bytes, Index: 444 bytes
// Total data: 3389 bytes

.const HUFF_STR_COUNT = 222
.const HSTR_INSULT_COUNT = 15

// Named string constants
.const HSTR_MAT_HITS = 15
.const HSTR_MAT_MISS = 16
.const HSTR_MAT_POISON = 17
.const HSTR_MAT_CONFUSE = 18
.const HSTR_MAT_PARALYZE = 19
.const HSTR_MAT_ACID = 20
.const HSTR_MAT_FEAR = 21
.const HSTR_MAT_SHRIEK = 22
.const HSTR_MAT_DOOR_BURST = 23
.const HSTR_MM_BOLT = 24
.const HSTR_MM_BREATH = 25
.const HSTR_MM_SUMMON = 26
.const HSTR_MM_TELEPORT = 27
.const HSTR_MM_BLIND = 28
.const HSTR_MM_CONFUSE = 29
.const HSTR_MM_HEAL = 30
.const HSTR_RF_NO_WEAPON = 31
.const HSTR_RF_NO_AMMO = 32
.const HSTR_RF_FLIES = 33
.const HSTR_RF_MISSES = 34
.const HSTR_RF_HITS = 35
.const HSTR_EB_SPELL_HITS = 36
.const HSTR_EB_FIZZLE = 37
.const HSTR_TW_PROMPT = 38
.const HSTR_TW_SHATTERS = 39
.const HSTR_EFF_POISON_END = 40
.const HSTR_EFF_BLIND_END = 41
.const HSTR_EFF_CONFUSE_END = 42
.const HSTR_EFF_PARALYZE_END = 43
.const HSTR_EFF_FEAR_END = 44
.const HSTR_EFF_HASTE_END = 45
.const HSTR_EFF_SLOW_END = 46
.const HSTR_TTL_DIM = 47
.const HSTR_TTL_OUT = 48
.const HSTR_RECALL_ARRIVE = 49
.const HSTR_DL_YOU_SEE = 50
.const HSTR_DL_OPEN_DOOR = 51
.const HSTR_DL_CLOSED_DOOR = 52
.const HSTR_DL_STAIRS_DN = 53
.const HSTR_DL_STAIRS_UP = 54
.const HSTR_DL_TRAP = 55
.const HSTR_DL_RUBBLE = 56
.const HSTR_DL_WALL = 57
.const HSTR_DL_NOTHING = 58
.const HSTR_PTM_AFRAID = 59
.const HSTR_DF_TRAP_0 = 60
.const HSTR_DF_TRAP_1 = 61
.const HSTR_DF_TRAP_2 = 62
.const HSTR_DF_TRAP_3 = 63
.const HSTR_DF_TRAP_4 = 64
.const HSTR_DF_TRAP_5 = 65
.const HSTR_DF_DEATH_ROCKFALL = 66
.const HSTR_DF_DIRECTION = 67
.const HSTR_DF_DOOR_STUCK = 68
.const HSTR_DF_FOUND_TRAP = 69
.const HSTR_DF_FOUND_SECRET = 70
.const HSTR_DF_FOUND_NOTHING = 71
.const HSTR_DF_NO_DOOR = 72
.const HSTR_DF_ALREADY_OPEN = 73
.const HSTR_DF_ALREADY_CLOSED = 74
.const HSTR_DF_DOOR_OPENED = 75
.const HSTR_DF_DOOR_CLOSED = 76
.const HSTR_DF_YOU_FELL = 77
.const HSTR_DF_ARROW_HITS = 78
.const HSTR_DF_POISON_GAS = 79
.const HSTR_DF_TELEPORTED = 80
.const HSTR_DF_DART_HITS = 81
.const HSTR_DF_ROCKFALL = 82
.const HSTR_DF_DAMAGE_PRE = 83
.const HSTR_DF_DAMAGE_POST = 84
.const HSTR_DF_CON_DRAIN = 85
.const HSTR_DF_POISONED = 86
.const HSTR_PM_NO_CAST = 87
.const HSTR_PM_NO_PRAY = 88
.const HSTR_PM_NOT_KNOWN = 89
.const HSTR_PM_NO_MANA = 90
.const HSTR_PM_NO_EXP = 91
.const HSTR_PM_FAIL = 92
.const HSTR_PM_YOU_CAST = 93
.const HSTR_PM_YOU_PRAY = 94
.const HSTR_PM_TITLE_MAGE = 95
.const HSTR_PM_TITLE_PRAY = 96
.const HSTR_PM_FOOTER_CAST = 97
.const HSTR_PM_FOOTER_PRAY = 98
.const HSTR_PIQ_LITTLE_BETTER = 99
.const HSTR_PIW_WEAR_PROMPT = 100
.const HSTR_PIW_TAKEOFF_PROMPT = 101
.const HSTR_PIW_NOTHING = 102
.const HSTR_PIW_NEVERMIND = 103
.const HSTR_PIW_CURSED = 104
.const HSTR_PIW_NO_FOOD = 105
.const HSTR_PIW_WIELD = 106
.const HSTR_PIW_WEARING = 107
.const HSTR_PIW_TAKEOFF = 108
.const HSTR_PIW_EAT = 109
.const HSTR_PIW_DELICIOUS = 110
.const HSTR_PIW_YUCK = 111
.const HSTR_PIQ_QUAFF_PROMPT = 112
.const HSTR_PIQ_READ_PROMPT = 113
.const HSTR_PMU_CREATE_FOOD = 114
.const HSTR_PIQ_SPEED = 115
.const HSTR_PIQ_TERRIBLE = 116
.const HSTR_PIQ_NOTHING = 117
.const HSTR_PIQ_LIGHT = 118
.const HSTR_PIQ_IDENTIFY_PROMPT = 119
.const HSTR_PIQ_THISIS = 120
.const HSTR_PIQ_TELEPORT = 121
.const HSTR_PIQ_MUCH_BETTER = 122
.const HSTR_PIQ_MIND_CLEAR = 123
.const HSTR_PIQ_HEROIC = 124
.const HSTR_PIQ_CANT_SEE = 125
.const HSTR_PIQ_DIZZY = 126
.const HSTR_PIQ_SENSE = 127
.const HSTR_PIQ_EYES_TINGLE = 128
.const HSTR_PIQ_AIR_CRACKLE = 129
.const HSTR_PIQ_CLEANSED = 130
.const HSTR_PMU_GLYPH_BLOCK = 131
.const HSTR_PMU_GLYPH_OK = 132
.const HSTR_PIQ_WPN_GLOW = 133
.const HSTR_PIQ_ARM_GLOW = 134
.const HSTR_PIQ_HANDS_GLOW = 135
.const HSTR_PIQ_HUMMING = 136
.const HSTR_PIQ_PROTECTED = 137
.const HSTR_PIQ_VIBRATION = 138
.const HSTR_PIW_AIM_PROMPT = 139
.const HSTR_PIW_USE_PROMPT = 140
.const HSTR_PIW_NO_CHARGES = 141
.const HSTR_PIW_STAFF_EMPTY = 142
.const HSTR_PIW_WAND_BOLT = 143
.const HSTR_PIW_WAND_FROST = 144
.const HSTR_PIW_WAND_CLOUD = 145
.const HSTR_PIW_WAND_MISS = 146
.const HSTR_PIQ_CANT_READ = 147
.const HSTR_IGS_PROMPT = 148
.const HSTR_IGS_NO_MAGIC = 149
.const HSTR_IGS_WRONG_TYPE = 150
.const HSTR_IGS_SUCCESS = 151
.const HSTR_IGS_NO_NEW = 152
.const HSTR_PIR_NOT_LAMP = 153
.const HSTR_PIR_NO_OIL = 154
.const HSTR_PIR_OVERFLOW = 155
.const HSTR_PIR_FULL = 156
.const HSTR_PIR_REFUELED = 157
.const HSTR_CMB_LVLUP = 158
.const HSTR_UIS_PACK_FULL = 159
.const HSTR_TUN_DIG_GRANITE = 160
.const HSTR_TUN_DIG_MAGMA = 161
.const HSTR_TUN_DIG_QUARTZ = 162
.const HSTR_TUN_FINISHED = 163
.const HSTR_TUN_FOUND = 164
.const HSTR_TUN_PERMANENT = 165
.const HSTR_TUN_NOTHING = 166
.const HSTR_TUN_RUBBLE = 167
.const HSTR_TUN_NO_TOOL = 168
.const HSTR_IPU_NOTHING = 169
.const HSTR_IPU_FOUND = 170
.const HSTR_IPU_GOLD = 171
.const HSTR_IPU_PICKED = 172
.const HSTR_IDR_PROMPT = 173
.const HSTR_IDR_DROP = 174
.const HSTR_IDR_FLOOR_FULL = 175
.const HSTR_SAVE_SAVING = 176
.const HSTR_SAVE_DONE = 177
.const HSTR_SAVE_LOADING = 178
.const HSTR_SAVE_NOTFOUND = 179
.const HSTR_SAVE_CORRUPT = 180
.const HSTR_SAVE_UNSUPPORTED = 181
.const HSTR_SAVE_IOERR = 182
.const HSTR_SAVE_WELCOME = 183
.const HSTR_SAVE_NEED_SAVE = 184
.const HSTR_SAVE_BAD_SAVE = 185
.const HSTR_SAVE_OVERWRITE = 186
.const HSTR_BASH_SMASH = 187
.const HSTR_BASH_CRASH = 188
.const HSTR_BASH_HOLDS = 189
.const HSTR_BASH_OFFBAL = 190
.const HSTR_BASH_EMPTY = 191
.const HSTR_BASH_STUNNED = 192
.const HSTR_BASH_IGNORES = 193
.const HSTR_PIQ_VERY_GOOD = 194
.const HSTR_PID_CARRY = 195
.const HSTR_PIQ_RESTORED = 196
.const HSTR_CHEST_FOUND_TRAP = 197
.const HSTR_CHEST_NEEDLE = 198
.const HSTR_CHEST_WEAKENED = 199
.const HSTR_CHEST_GAS = 200
.const HSTR_CHEST_UNAFFECTED = 201
.const HSTR_CHEST_CHOKE = 202
.const HSTR_CHEST_EXPLOSION = 203
.const HSTR_CHEST_PICKED = 204
.const HSTR_CHEST_PICK_CONFUSED = 205
.const HSTR_CHEST_PICK_FAIL = 206
.const HSTR_CHEST_DEATH_NEEDLE = 207
.const HSTR_CHEST_DEATH_EXPLODING = 208
.const HSTR_CHEST_DISARM_UNFOUND = 209
.const HSTR_CHEST_DISARM_NOT_TRAPPED = 210
.const HSTR_CHEST_DISARMED = 211
.const HSTR_CHEST_DISARM_FAIL = 212
.const HSTR_CHEST_DISARM_SET_OFF = 213
.const HSTR_CHEST_DESTROYED = 214
.const HSTR_CHEST_DESTROYED_CONTENTS = 215
.const HSTR_CHEST_LOCK_BREAKS = 216
.const HSTR_CHEST_HOLDS_FIRM = 217
.const HSTR_CHEST_SFX_EMPTY = 218
.const HSTR_CHEST_SFX_LOCKED = 219
.const HSTR_CHEST_SFX_TRAPPED = 220
.const HSTR_CHEST_SFX_DISARMED = 221

// Huffman tree: 56 internal nodes
// Children: $00-$7E = node index, $80+ = leaf (& $7F = screencode)
huff_tree_left:
    .byte $01, $03, $05, $07, $09, $0b, $0c, $92, $93, $80, $10, $11, $13, $14, $15, $16, $17, $8c, $18, $19, $1a, $a1, $8d, $1b, $1c, $90, $86, $1f, $21, $8b, $22, $24, $25, $a8, $bf, $d4, $c4, $29, $c1, $ce, $2c, $2e, $30, $32, $d7, $33, $34, $36, $d5, $c5, $d0, $c3, $af, $b8, $c7, $8a
huff_tree_right:
    .byte $02, $04, $06, $08, $0a, $a0, $0d, $0e, $94, $0f, $81, $12, $8f, $85, $d9, $84, $ae, $88, $8e, $89, $95, $97, $99, $87, $1d, $1e, $83, $20, $82, $96, $23, $ad, $a9, $26, $27, $28, $ac, $2a, $d3, $2b, $2d, $2f, $31, $a7, $c9, $9a, $35, $37, $c8, $cd, $d2, $98, $cf, $cc, $91, $d1

// String index: 16-bit byte offsets into huff_str_data
huff_str_index:
    .word $0000  // [0] "You will have to do better tha"
    .word $0015  // [1] "That is an insult!"
    .word $0020  // [2] "Do you wish to do business or "
    .word $0034  // [3] "Hah! Try again."
    .word $003f  // [4] "Ridiculous!"
    .word $0048  // [5] "You have got to be kidding!"
    .word $0059  // [6] "You had better be kidding!"
    .word $0069  // [7] "You try my patience."
    .word $0075  // [8] "I do not hear you."
    .word $0080  // [9] "Hmmm, nice weather we are havi"
    .word $0095  // [10] "I must have heard you wrong."
    .word $00a6  // [11] "What was that?"
    .word $00af  // [12] "I am sorry, say that again."
    .word $00c0  // [13] "What did you say?"
    .word $00cb  // [14] "Sorry, what was that again?"
    .word $00dc  // [15] @MAT_HITS " hits you."
    .word $00e2  // [16] @MAT_MISS " misses you."
    .word $00ea  // [17] @MAT_POISON " poisons you."
    .word $00f2  // [18] @MAT_CONFUSE " confuses you."
    .word $00fb  // [19] @MAT_PARALYZE " paralyzes you."
    .word $0105  // [20] @MAT_ACID " spits acid on you."
    .word $0110  // [21] @MAT_FEAR " frightens you."
    .word $011a  // [22] @MAT_SHRIEK "You hear a horrible shriek!"
    .word $012a  // [23] @MAT_DOOR_BURST "You hear a door burst open!"
    .word $0139  // [24] @MM_BOLT " casts a bolt!"
    .word $0142  // [25] @MM_BREATH " breathes fire!"
    .word $014b  // [26] @MM_SUMMON " summons help!"
    .word $0154  // [27] @MM_TELEPORT " teleports you!"
    .word $015d  // [28] @MM_BLIND " blinds you!"
    .word $0165  // [29] @MM_CONFUSE " confuses you!"
    .word $016e  // [30] @MM_HEAL " heals itself."
    .word $0177  // [31] @RF_NO_WEAPON "No ranged weapon."
    .word $0182  // [32] @RF_NO_AMMO "No ammo."
    .word $0188  // [33] @RF_FLIES " flies away."
    .word $0190  // [34] @RF_MISSES " misses"
    .word $0195  // [35] @RF_HITS " hits"
    .word $0199  // [36] @EB_SPELL_HITS "Your spell hits"
    .word $01a2  // [37] @EB_FIZZLE "Your spell fizzles out."
    .word $01b1  // [38] @TW_PROMPT "Throw which item (a-v)?"
    .word $01c2  // [39] @TW_SHATTERS " shatters!"
    .word $01c8  // [40] @EFF_POISON_END "You feel better."
    .word $01d2  // [41] @EFF_BLIND_END "You can see again."
    .word $01dd  // [42] @EFF_CONFUSE_END "You feel less confused."
    .word $01eb  // [43] @EFF_PARALYZE_END "You can move again."
    .word $01f7  // [44] @EFF_FEAR_END "You feel bolder now."
    .word $0203  // [45] @EFF_HASTE_END "You feel yourself slow down."
    .word $0214  // [46] @EFF_SLOW_END "You feel yourself speed up."
    .word $0224  // [47] @TTL_DIM "Your light is growing dim."
    .word $0234  // [48] @TTL_OUT "Your light has gone out."
    .word $0242  // [49] @RECALL_ARRIVE "You feel yourself yanked away!"
    .word $0254  // [50] @DL_YOU_SEE "You see a "
    .word $025a  // [51] @DL_OPEN_DOOR "You see an open door."
    .word $0266  // [52] @DL_CLOSED_DOOR "You see a closed door."
    .word $0272  // [53] @DL_STAIRS_DN "You see a staircase down."
    .word $0280  // [54] @DL_STAIRS_UP "You see a staircase up."
    .word $028d  // [55] @DL_TRAP "You see a trap."
    .word $0296  // [56] @DL_RUBBLE "You see rubble."
    .word $02a0  // [57] @DL_WALL "You see a wall."
    .word $02a9  // [58] @DL_NOTHING "You see nothing special."
    .word $02b7  // [59] @PTM_AFRAID "You are too afraid!"
    .word $02c2  // [60] @DF_TRAP_0 "an open pit"
    .word $02c9  // [61] @DF_TRAP_1 "an arrow trap"
    .word $02d1  // [62] @DF_TRAP_2 "a poison gas trap"
    .word $02db  // [63] @DF_TRAP_3 "a teleport trap"
    .word $02e4  // [64] @DF_TRAP_4 "a poison dart"
    .word $02ec  // [65] @DF_TRAP_5 "a rockfall trap"
    .word $02f6  // [66] @DF_DEATH_ROCKFALL "falling rock."
    .word $02ff  // [67] @DF_DIRECTION "Direction?"
    .word $0307  // [68] @DF_DOOR_STUCK "The door is stuck."
    .word $0312  // [69] @DF_FOUND_TRAP "You found a trap!"
    .word $031c  // [70] @DF_FOUND_SECRET "You found a secret door!"
    .word $032a  // [71] @DF_FOUND_NOTHING "You found nothing."
    .word $0335  // [72] @DF_NO_DOOR "No door there."
    .word $033e  // [73] @DF_ALREADY_OPEN "The door is already open."
    .word $034d  // [74] @DF_ALREADY_CLOSED "It is already closed."
    .word $035a  // [75] @DF_DOOR_OPENED "You open the door."
    .word $0365  // [76] @DF_DOOR_CLOSED "You close the door."
    .word $0370  // [77] @DF_YOU_FELL "You fell into a pit!"
    .word $037c  // [78] @DF_ARROW_HITS "An arrow hits you!"
    .word $0387  // [79] @DF_POISON_GAS "A cloud of gas surrounds you!"
    .word $0399  // [80] @DF_TELEPORTED "You are teleported!"
    .word $03a4  // [81] @DF_DART_HITS "A dart hits you!"
    .word $03ae  // [82] @DF_ROCKFALL "Rocks fall on you!"
    .word $03ba  // [83] @DF_DAMAGE_PRE "You take "
    .word $03c0  // [84] @DF_DAMAGE_POST " damage."
    .word $03c6  // [85] @DF_CON_DRAIN "You feel weakened."
    .word $03d1  // [86] @DF_POISONED "You feel poisoned."
    .word $03dc  // [87] @PM_NO_CAST "You cannot cast spells."
    .word $03ea  // [88] @PM_NO_PRAY "You cannot pray."
    .word $03f4  // [89] @PM_NOT_KNOWN "You don't know that spell."
    .word $0404  // [90] @PM_NO_MANA "You faint from fatigue."
    .word $0412  // [91] @PM_NO_EXP "You're not experienced enough."
    .word $0425  // [92] @PM_FAIL "Your spell fails."
    .word $0430  // [93] @PM_YOU_CAST "Spell book (a-v)?"
    .word $043d  // [94] @PM_YOU_PRAY "Prayer book (a-v)?"
    .word $044b  // [95] @PM_TITLE_MAGE "Monster slows."
    .word $0454  // [96] @PM_TITLE_PRAY "Type?"
    .word $0459  // [97] @PM_FOOTER_CAST "Cast which? (a-p, ESC)"
    .word $046c  // [98] @PM_FOOTER_PRAY "Pray which? (a-p, ESC)"
    .word $047f  // [99] @PIQ_LITTLE_BETTER "You feel a little better."
    .word $048d  // [100] @PIW_WEAR_PROMPT "Wear which item (a-v)?"
    .word $049d  // [101] @PIW_TAKEOFF_PROMPT "Take off which item (a-h)?"
    .word $04af  // [102] @PIW_NOTHING "You have nothing there."
    .word $04bd  // [103] @PIW_NEVERMIND "Never mind."
    .word $04c5  // [104] @PIW_CURSED "You cannot remove it, it is cu"
    .word $04da  // [105] @PIW_NO_FOOD "You have no food."
    .word $04e4  // [106] @PIW_WIELD "You are wielding a "
    .word $04ef  // [107] @PIW_WEARING "You are wearing a "
    .word $04f9  // [108] @PIW_TAKEOFF "You take off the "
    .word $0503  // [109] @PIW_EAT "You eat the "
    .word $050a  // [110] @PIW_DELICIOUS ". Delicious!"
    .word $0513  // [111] @PIW_YUCK ". Yuck!"
    .word $0519  // [112] @PIQ_QUAFF_PROMPT "Quaff which potion (a-v)?"
    .word $052b  // [113] @PIQ_READ_PROMPT "Read which scroll (a-v)?"
    .word $053c  // [114] @PMU_CREATE_FOOD "You create food."
    .word $0546  // [115] @PIQ_SPEED "You feel yourself moving faste"
    .word $0559  // [116] @PIQ_TERRIBLE "That tasted terrible!"
    .word $0566  // [117] @PIQ_NOTHING "Nothing seems to happen."
    .word $0575  // [118] @PIQ_LIGHT "The area fills with light."
    .word $0585  // [119] @PIQ_IDENTIFY_PROMPT "Identify which item (a-v)?"
    .word $0598  // [120] @PIQ_THISIS "This is a "
    .word $059e  // [121] @PIQ_TELEPORT "You feel disoriented."
    .word $05ab  // [122] @PIQ_MUCH_BETTER "You feel much better."
    .word $05b8  // [123] @PIQ_MIND_CLEAR "Your mind feels clear."
    .word $05c5  // [124] @PIQ_HEROIC "You feel heroic!"
    .word $05cf  // [125] @PIQ_CANT_SEE "You can't see!"
    .word $05d8  // [126] @PIQ_DIZZY "You feel dizzy."
    .word $05e3  // [127] @PIQ_SENSE "You sense nearby creatures."
    .word $05f3  // [128] @PIQ_EYES_TINGLE "Your eyes tingle."
    .word $05fd  // [129] @PIQ_AIR_CRACKLE "The air crackles around you."
    .word $060e  // [130] @PIQ_CLEANSED "You feel cleansed."
    .word $0619  // [131] @PMU_GLYPH_BLOCK "There is already an object und"
    .word $0630  // [132] @PMU_GLYPH_OK "You see a strange rune."
    .word $063d  // [133] @PIQ_WPN_GLOW "Your weapon glows briefly."
    .word $064d  // [134] @PIQ_ARM_GLOW "Your armor glows briefly."
    .word $065c  // [135] @PIQ_HANDS_GLOW "Your hands begin to glow."
    .word $066b  // [136] @PIQ_HUMMING "You hear a high-pitched hummin"
    .word $067f  // [137] @PIQ_PROTECTED "You feel protected."
    .word $068b  // [138] @PIQ_VIBRATION "You feel a strange vibration."
    .word $069c  // [139] @PIW_AIM_PROMPT "Aim which wand (a-v)?"
    .word $06ac  // [140] @PIW_USE_PROMPT "Use which staff (a-v)?"
    .word $06bc  // [141] @PIW_NO_CHARGES "No charges left."
    .word $06c6  // [142] @PIW_STAFF_EMPTY "The staff is empty."
    .word $06d2  // [143] @PIW_WAND_BOLT "A bolt of lightning shoots for"
    .word $06e6  // [144] @PIW_WAND_FROST "A bolt of frost shoots forth!"
    .word $06f7  // [145] @PIW_WAND_CLOUD "The monster looks confused."
    .word $0708  // [146] @PIW_WAND_MISS "The cloud dissipates."
    .word $0715  // [147] @PIQ_CANT_READ "You can't see to read!"
    .word $0722  // [148] @IGS_PROMPT "Study which book (a-v)?"
    .word $0733  // [149] @IGS_NO_MAGIC "You cannot use magic."
    .word $0740  // [150] @IGS_WRONG_TYPE "You cannot read that book."
    .word $074f  // [151] @IGS_SUCCESS "You learn from the book!"
    .word $075e  // [152] @IGS_NO_NEW "No new spells to learn."
    .word $076c  // [153] @PIR_NOT_LAMP "Not using a lamp."
    .word $0777  // [154] @PIR_NO_OIL "You have no oil."
    .word $0781  // [155] @PIR_OVERFLOW "Your lamp overflows."
    .word $078e  // [156] @PIR_FULL "Your lamp is full."
    .word $0799  // [157] @PIR_REFUELED "Your lamp is refueled."
    .word $07a6  // [158] @CMB_LVLUP "Welcome to level "
    .word $07b1  // [159] @UIS_PACK_FULL "Your pack is full."
    .word $07bd  // [160] @TUN_DIG_GRANITE "You dig in the granite wall."
    .word $07ce  // [161] @TUN_DIG_MAGMA "You dig in the magma."
    .word $07db  // [162] @TUN_DIG_QUARTZ "You dig in the quartz vein."
    .word $07ed  // [163] @TUN_FINISHED "You have finished the tunnel."
    .word $07fe  // [164] @TUN_FOUND "You have found something!"
    .word $080e  // [165] @TUN_PERMANENT "This seems to be permanent roc"
    .word $0821  // [166] @TUN_NOTHING "There is nothing to tunnel her"
    .word $0834  // [167] @TUN_RUBBLE "The rubble crumbles."
    .word $0842  // [168] @TUN_NO_TOOL "You dig with your hands, makin"
    .word $085d  // [169] @IPU_NOTHING "You see nothing here."
    .word $0869  // [170] @IPU_FOUND "You found "
    .word $0870  // [171] @IPU_GOLD " gold pieces."
    .word $0878  // [172] @IPU_PICKED "You picked up a "
    .word $0882  // [173] @IDR_PROMPT "Drop which item (a-v)?"
    .word $0892  // [174] @IDR_DROP "You drop a "
    .word $0899  // [175] @IDR_FLOOR_FULL "No room on the floor."
    .word $08a6  // [176] @SAVE_SAVING "Saving game..."
    .word $08b0  // [177] @SAVE_DONE "Game saved."
    .word $08b8  // [178] @SAVE_LOADING "Loading game..."
    .word $08c3  // [179] @SAVE_NOTFOUND "Save file not found."
    .word $08d0  // [180] @SAVE_CORRUPT "Save file corrupt!"
    .word $08dc  // [181] @SAVE_UNSUPPORTED "Unsupported save."
    .word $08e8  // [182] @SAVE_IOERR "Disk error!"
    .word $08f0  // [183] @SAVE_WELCOME "Welcome back to Moria8!"
    .word $0901  // [184] @SAVE_NEED_SAVE "Need Save Disk."
    .word $090c  // [185] @SAVE_BAD_SAVE "Wrong Save Disk."
    .word $0918  // [186] @SAVE_OVERWRITE "Overwrite? Y/N"
    .word $0924  // [187] @BASH_SMASH "You smash into the door!"
    .word $0932  // [188] @BASH_CRASH "The door crashes open!"
    .word $093f  // [189] @BASH_HOLDS "The door holds firm."
    .word $094b  // [190] @BASH_OFFBAL "You are off balance."
    .word $0957  // [191] @BASH_EMPTY "You bash at empty space."
    .word $0966  // [192] @BASH_STUNNED " appears stunned!"
    .word $0970  // [193] @BASH_IGNORES " ignores your bash!"
    .word $097c  // [194] @PIQ_VERY_GOOD "You feel very good."
    .word $0988  // [195] @PID_CARRY "You sense magik on what you ca"
    .word $099c  // [196] @PIQ_RESTORED "You feel your strength return."
    .word $09ad  // [197] @CHEST_FOUND_TRAP "You have discovered a trap on "
    .word $09c4  // [198] @CHEST_NEEDLE "A small needle has pricked you"
    .word $09d7  // [199] @CHEST_WEAKENED "You feel weakened!"
    .word $09e2  // [200] @CHEST_GAS "A puff of yellow gas surrounds"
    .word $09f8  // [201] @CHEST_UNAFFECTED "You are unaffected."
    .word $0a04  // [202] @CHEST_CHOKE "You choke and pass out."
    .word $0a12  // [203] @CHEST_EXPLOSION "There is a sudden explosion!"
    .word $0a23  // [204] @CHEST_PICKED "You have picked the lock."
    .word $0a33  // [205] @CHEST_PICK_CONFUSED "You are too confused to pick t"
    .word $0a49  // [206] @CHEST_PICK_FAIL "You failed to pick the lock."
    .word $0a5a  // [207] @CHEST_DEATH_NEEDLE "a poison needle."
    .word $0a64  // [208] @CHEST_DEATH_EXPLODING "an exploding chest."
    .word $0a71  // [209] @CHEST_DISARM_UNFOUND "I don't see a trap..."
    .word $0a7e  // [210] @CHEST_DISARM_NOT_TRAPPED "The chest was not trapped."
    .word $0a8e  // [211] @CHEST_DISARMED "You have disarmed the chest."
    .word $0a9e  // [212] @CHEST_DISARM_FAIL "You failed to disarm the chest"
    .word $0ab0  // [213] @CHEST_DISARM_SET_OFF "You set a trap off!"
    .word $0abb  // [214] @CHEST_DESTROYED "You have destroyed the chest.."
    .word $0acd  // [215] @CHEST_DESTROYED_CONTENTS "and it's contents!"
    .word $0ad9  // [216] @CHEST_LOCK_BREAKS "The lock breaks open!"
    .word $0ae7  // [217] @CHEST_HOLDS_FIRM "The chest holds firm."
    .word $0af4  // [218] @CHEST_SFX_EMPTY " (empty)"
    .word $0afb  // [219] @CHEST_SFX_LOCKED " (locked)"
    .word $0b02  // [220] @CHEST_SFX_TRAPPED " (trapped)"
    .word $0b09  // [221] @CHEST_SFX_DISARMED " (disarmed)"

// Compressed string data (2833 bytes)
huff_str_data:
    // [0] "You will have to do better than that!" (38→21 bytes)
    .byte $1e, $f6, $8b, $98, $42, $c5, $e5, $fd, $3d, $ab, $db, $27, $cc, $fc, $29, $c5, $e7, $4e, $2e, $62, $20
    // [1] "That is an insult!" (19→11 bytes)
    .byte $c6, $8b, $9d, $c9, $57, $9d, $cc, $cb, $b0, $31, $10
    // [2] "Do you wish to do business or not?" (35→20 bytes)
    .byte $60, $6d, $57, $7b, $45, $c9, $46, $9e, $d5, $ed, $93, $d2, $cc, $fc, $8a, $e8, $59, $e9, $e2, $20
    // [3] "Hah! Try again." (16→11 bytes)
    .byte $62, $af, $11, $2e, $30, $2b, $5d, $97, $cc, $da, $80
    // [4] "Ridiculous!" (12→9 bytes)
    .byte $c5, $b9, $5e, $79, $ec, $37, $a4, $22, $00
    // [5] "You have got to be kidding!" (28→17 bytes)
    .byte $1e, $f6, $c5, $e5, $fd, $67, $4e, $9e, $d9, $3f, $65, $65, $6b, $cc, $d9, $11, $00
    // [6] "You had better be kidding!" (27→16 bytes)
    .byte $1e, $f6, $c5, $d7, $64, $f9, $9f, $85, $93, $f6, $56, $56, $bc, $cd, $91, $10
    // [7] "You try my patience." (21→12 bytes)
    .byte $1e, $f6, $98, $2b, $54, $56, $e0, $e7, $9f, $9f, $3e, $d4
    // [8] "I do not hear you." (19→11 bytes)
    .byte $c7, $6a, $f6, $cf, $4e, $c7, $dc, $2a, $bb, $d6, $a0
    // [9] "Hmmm, nice weather we are having." (34→21 bytes)
    .byte $62, $aa, $28, $a3, $06, $cf, $3c, $fd, $17, $dc, $e3, $e1, $45, $fa, $e1, $f6, $2f, $2f, $33, $65, $a8
    // [10] "I must have heard you wrong." (29→17 bytes)
    .byte $c7, $6a, $9d, $23, $b1, $79, $7f, $63, $ee, $0b, $aa, $ef, $68, $a1, $b3, $65, $a8
    // [11] "What was that?" (15→9 bytes)
    .byte $c7, $22, $e7, $45, $72, $a7, $17, $3c, $44
    // [12] "I am sorry, say that again." (28→17 bytes)
    .byte $c7, $6b, $a9, $4b, $40, $15, $60, $d2, $75, $69, $c5, $ce, $bb, $2f, $99, $b5, $00
    // [13] "What did you say?" (18→11 bytes)
    .byte $c7, $22, $e7, $57, $95, $d5, $77, $b4, $9d, $5c, $44
    // [14] "Sorry, what was that again?" (28→17 bytes)
    .byte $91, $e8, $02, $ac, $1a, $2c, $5c, $e8, $ae, $54, $e2, $e7, $5d, $97, $cc, $f1, $10
    // [15] " hits you." (11→6 bytes)
    .byte $b1, $c9, $95, $57, $7a, $d4
    // [16] " misses you." (13→8 bytes)
    .byte $aa, $64, $8b, $ca, $ab, $bd, $6a, $00
    // [17] " poisons you." (14→8 bytes)
    .byte $b8, $6e, $4b, $66, $55, $5d, $eb, $50
    // [18] " confuses you." (15→9 bytes)
    .byte $bc, $ec, $f8, $e9, $79, $55, $77, $ad, $40
    // [19] " paralyzes you." (16→10 bytes)
    .byte $b8, $38, $3c, $15, $c7, $fc, $aa, $bb, $d6, $a0
    // [20] " spits acid on you." (20→11 bytes)
    .byte $a5, $86, $4c, $ab, $f3, $95, $dd, $9d, $57, $7a, $d4
    // [21] " frightens you." (16→10 bytes)
    .byte $bc, $06, $59, $89, $fc, $ca, $ab, $bd, $6a, $00
    // [22] "You hear a horrible shriek!" (28→16 bytes)
    .byte $1e, $f6, $c7, $dc, $2b, $d8, $e8, $06, $64, $c3, $e9, $44, $33, $f2, $84, $40
    // [23] "You hear a door burst open!" (28→15 bytes)
    .byte $1e, $f6, $c7, $dc, $2b, $d5, $ee, $85, $93, $d0, $23, $bb, $87, $cc, $44
    // [24] " casts a bolt!" (15→9 bytes)
    .byte $bc, $b9, $19, $57, $b2, $76, $06, $22, $00
    // [25] " breathes fire!" (16→9 bytes)
    .byte $b2, $43, $dc, $e3, $e5, $78, $c8, $78, $88
    // [26] " summons help!" (15→9 bytes)
    .byte $a5, $d5, $14, $d9, $95, $8f, $c3, $01, $10
    // [27] " teleports you!" (16→9 bytes)
    .byte $a7, $f0, $fc, $34, $0c, $aa, $bb, $d1, $10
    // [28] " blinds you!" (13→8 bytes)
    .byte $b2, $61, $99, $ac, $aa, $bb, $d1, $10
    // [29] " confuses you!" (15→9 bytes)
    .byte $bc, $ec, $f8, $e9, $79, $55, $77, $a2, $20
    // [30] " heals itself." (15→9 bytes)
    .byte $b1, $f7, $81, $5c, $99, $7c, $38, $6a, $00
    // [31] "No ranged weapon." (18→11 bytes)
    .byte $c5, $6d, $07, $9b, $3e, $ba, $2f, $be, $1b, $36, $a0
    // [32] "No ammo." (9→6 bytes)
    .byte $c5, $6d, $75, $14, $d6, $a0
    // [33] " flies away." (13→8 bytes)
    .byte $bc, $43, $3e, $55, $c5, $75, $5a, $80
    // [34] " misses" (8→5 bytes)
    .byte $aa, $64, $8b, $c9, $00
    // [35] " hits" (6→4 bytes)
    .byte $b1, $c9, $92, $00
    // [36] "Your spell hits" (16→9 bytes)
    .byte $1e, $f4, $29, $61, $f0, $85, $8e, $4c, $90
    // [37] "Your spell fizzles out." (24→15 bytes)
    .byte $1e, $f4, $29, $61, $f0, $85, $e3, $38, $fe, $3f, $0f, $2b, $bd, $36, $a0
    // [38] "Throw which item (a-v)?" (24→17 bytes)
    .byte $c6, $88, $68, $b4, $58, $e7, $98, $dc, $9f, $a9, $64, $1d, $86, $5b, $1e, $22, $00
    // [39] " shatters!" (11→6 bytes)
    .byte $a5, $17, $33, $f0, $21, $10
    // [40] "You feel better." (17→10 bytes)
    .byte $1e, $f6, $f1, $ff, $0b, $27, $cc, $fc, $1a, $80
    // [41] "You can see again." (19→11 bytes)
    .byte $1e, $f6, $f2, $f3, $a5, $ff, $5d, $97, $cc, $da, $80
    // [42] "You feel less confused." (24→14 bytes)
    .byte $1e, $f6, $f1, $ff, $0b, $0f, $22, $bc, $ec, $f8, $e9, $7a, $da, $80
    // [43] "You can move again." (20→12 bytes)
    .byte $1e, $f6, $f2, $f3, $aa, $6c, $bf, $ae, $cb, $e6, $6d, $40
    // [44] "You feel bolder now." (21→12 bytes)
    .byte $1e, $f6, $f1, $ff, $0b, $27, $60, $bf, $0b, $3d, $15, $a8
    // [45] "You feel yourself slow down." (29→17 bytes)
    .byte $1e, $f6, $f1, $ff, $0a, $ae, $f4, $0b, $e1, $c5, $28, $68, $b5, $7a, $2c, $da, $80
    // [46] "You feel yourself speed up." (28→16 bytes)
    .byte $1e, $f6, $f1, $ff, $0a, $ae, $f4, $0b, $e1, $c5, $2c, $3f, $d7, $7b, $83, $50
    // [47] "Your light is growing dim." (27→16 bytes)
    .byte $1e, $f4, $2c, $32, $cc, $4e, $e4, $ab, $21, $a2, $e6, $6c, $d5, $e5, $46, $a0
    // [48] "Your light has gone out." (25→14 bytes)
    .byte $1e, $f4, $2c, $32, $cc, $4e, $c5, $ca, $b3, $b3, $fb, $bd, $36, $a0
    // [49] "You feel yourself yanked away!" (31→18 bytes)
    .byte $1e, $f6, $f1, $ff, $0a, $ae, $f4, $0b, $e1, $c5, $55, $e7, $2b, $d7, $5c, $57, $54, $44
    // [50] "You see a " (11→6 bytes)
    .byte $1e, $f6, $97, $fd, $7a, $80
    // [51] "You see an open door." (22→12 bytes)
    .byte $1e, $f6, $97, $fd, $79, $dd, $c3, $e7, $57, $ba, $0d, $40
    // [52] "You see a closed door." (23→12 bytes)
    .byte $1e, $f6, $97, $fd, $7b, $cc, $34, $bd, $75, $7b, $a0, $d4
    // [53] "You see a staircase down." (26→14 bytes)
    .byte $1e, $f6, $97, $fd, $7a, $46, $f9, $0e, $5c, $be, $af, $45, $9b, $50
    // [54] "You see a staircase up." (24→13 bytes)
    .byte $1e, $f6, $97, $fd, $7a, $46, $f9, $0e, $5c, $be, $f7, $06, $a0
    // [55] "You see a trap." (16→9 bytes)
    .byte $1e, $f6, $97, $fd, $7a, $60, $f8, $35, $00
    // [56] "You see rubble." (16→10 bytes)
    .byte $1e, $f6, $97, $fd, $0e, $c9, $93, $0f, $6a, $00
    // [57] "You see a wall." (16→9 bytes)
    .byte $1e, $f6, $97, $fd, $7a, $2b, $c2, $0d, $40
    // [58] "You see nothing special." (25→14 bytes)
    .byte $1e, $f6, $97, $fd, $9e, $9c, $73, $36, $69, $61, $fc, $e5, $e0, $d4
    // [59] "You are too afraid!" (20→11 bytes)
    .byte $1e, $f6, $b8, $7d, $3d, $da, $fc, $03, $e5, $62, $20
    // [60] "an open pit" (12→7 bytes)
    .byte $79, $dd, $c3, $e7, $70, $c9, $a0
    // [61] "an arrow trap" (14→8 bytes)
    .byte $79, $d7, $00, $d1, $69, $83, $e0, $80
    // [62] "a poison gas trap" (18→10 bytes)
    .byte $7b, $86, $e4, $b6, $75, $97, $2a, $60, $f8, $20
    // [63] "a teleport trap" (16→9 bytes)
    .byte $7a, $7f, $0f, $c3, $40, $e9, $83, $e0, $80
    // [64] "a poison dart" (14→8 bytes)
    .byte $7b, $86, $e4, $b6, $75, $6e, $06, $80
    // [65] "a rockfall trap" (16→10 bytes)
    .byte $7a, $1b, $cc, $ae, $1e, $10, $a6, $0f, $82, $00
    // [66] "falling rock." (14→9 bytes)
    .byte $e1, $e1, $0c, $cd, $9a, $1b, $cc, $a6, $a0
    // [67] "Direction?" (11→8 bytes)
    .byte $60, $64, $3f, $93, $ce, $cf, $11, $00
    // [68] "The door is stuck." (19→11 bytes)
    .byte $c6, $8f, $d5, $ee, $85, $c9, $52, $3e, $f3, $29, $a8
    // [69] "You found a trap!" (18→10 bytes)
    .byte $1e, $f6, $f1, $bd, $9a, $eb, $d3, $07, $c0, $44
    // [70] "You found a secret door!" (25→14 bytes)
    .byte $1e, $f6, $f1, $bd, $9a, $eb, $d2, $fe, $43, $ce, $af, $74, $04, $40
    // [71] "You found nothing." (19→11 bytes)
    .byte $1e, $f6, $f1, $bd, $9a, $ec, $f4, $e3, $99, $b2, $d4
    // [72] "No door there." (15→9 bytes)
    .byte $c5, $6d, $5e, $e8, $53, $8f, $87, $b5, $00
    // [73] "The door is already open." (26→15 bytes)
    .byte $c6, $8f, $d5, $ee, $85, $c9, $57, $80, $7b, $ad, $5b, $b8, $7c, $da, $80
    // [74] "It is already closed." (22→13 bytes)
    .byte $c7, $4e, $e4, $ab, $c0, $3d, $d6, $ad, $e6, $1a, $5e, $b6, $a0
    // [75] "You open the door." (19→11 bytes)
    .byte $1e, $f6, $ee, $1f, $3a, $71, $fa, $bd, $d0, $6a, $00
    // [76] "You close the door." (20→11 bytes)
    .byte $1e, $f6, $f3, $0d, $2f, $a7, $1f, $ab, $dd, $06, $a0
    // [77] "You fell into a pit!" (21→12 bytes)
    .byte $1e, $f6, $f1, $f0, $85, $cc, $cf, $6b, $dc, $32, $62, $20
    // [78] "An arrow hits you!" (19→11 bytes)
    .byte $91, $4e, $b8, $06, $8b, $63, $93, $2a, $ae, $f4, $44
    // [79] "A cloud of gas surrounds you!" (30→18 bytes)
    .byte $91, $5e, $61, $bd, $5d, $de, $2b, $2e, $54, $ba, $01, $bd, $9a, $ca, $ab, $bd, $11, $00
    // [80] "You are teleported!" (20→11 bytes)
    .byte $1e, $f6, $b8, $7d, $3f, $87, $e1, $a0, $7e, $b1, $10
    // [81] "A dart hits you!" (17→10 bytes)
    .byte $91, $55, $b8, $1d, $8e, $4c, $aa, $bb, $d1, $10
    // [82] "Rocks fall on you!" (19→12 bytes)
    .byte $c5, $bb, $cc, $a2, $bc, $3c, $21, $76, $75, $5d, $e8, $88
    // [83] "You take " (10→6 bytes)
    .byte $1e, $f6, $9b, $ca, $fa, $80
    // [84] " damage." (9→6 bytes)
    .byte $ab, $75, $1d, $9f, $6a, $00
    // [85] "You feel weakened." (19→11 bytes)
    .byte $1e, $f6, $f1, $ff, $0a, $2f, $bc, $af, $9f, $ad, $a8
    // [86] "You feel poisoned." (19→11 bytes)
    .byte $1e, $f6, $f1, $ff, $0b, $86, $e4, $b6, $7e, $b6, $a0
    // [87] "You cannot cast spells." (24→14 bytes)
    .byte $1e, $f6, $f2, $f3, $9e, $9d, $e5, $c8, $e9, $61, $f0, $81, $35, $00
    // [88] "You cannot pray." (17→10 bytes)
    .byte $1e, $f6, $f2, $f3, $9e, $9d, $c0, $1d, $56, $a0
    // [89] "You don't know that spell." (27→16 bytes)
    .byte $1e, $f6, $af, $67, $8b, $9d, $95, $3d, $16, $9c, $5c, $e9, $61, $f0, $83, $50
    // [90] "You faint from fatigue." (24→14 bytes)
    .byte $1e, $f6, $f0, $f9, $99, $de, $03, $54, $bc, $39, $e5, $9e, $fb, $50
    // [91] "You're not experienced enough." (31→19 bytes)
    .byte $1e, $f7, $17, $0f, $b3, $d3, $bf, $8f, $70, $f0, $cf, $cf, $9f, $5d, $f9, $ef, $59, $8b, $50
    // [92] "Your spell fails." (18→11 bytes)
    .byte $1e, $f4, $29, $61, $f0, $85, $e1, $f3, $02, $6a, $00
    // [93] "Spell book (a-v)?" (18→13 bytes)
    .byte $91, $e1, $f0, $85, $93, $bb, $2a, $c8, $3b, $0c, $b6, $3c, $44
    // [94] "Prayer book (a-v)?" (19→14 bytes)
    .byte $c5, $80, $ea, $f8, $59, $3b, $b2, $ac, $83, $b0, $cb, $63, $c4, $40
    // [95] "Monster slows." (15→9 bytes)
    .byte $62, $fb, $32, $3f, $0a, $50, $d1, $49, $a8
    // [96] "Type?" (6→5 bytes)
    .byte $c6, $57, $0f, $c4, $40
    // [97] "Cast which? (a-p, ESC)" (23→19 bytes)
    .byte $c7, $8e, $47, $45, $8e, $79, $8e, $25, $90, $76, $1c, $18, $35, $8b, $48, $f1, $e3, $1a, $00
    // [98] "Pray which? (a-p, ESC)" (23→19 bytes)
    .byte $c5, $80, $ea, $d1, $63, $9e, $63, $89, $64, $1d, $87, $06, $0d, $62, $d2, $3c, $78, $c6, $80
    // [99] "You feel a little better." (26→14 bytes)
    .byte $1e, $f6, $f1, $ff, $0a, $f6, $19, $33, $87, $d9, $3e, $67, $e0, $d4
    // [100] "Wear which item (a-v)?" (23→16 bytes)
    .byte $c7, $3d, $c2, $8b, $1c, $f3, $1b, $93, $f5, $2c, $83, $b0, $cb, $63, $c4, $40
    // [101] "Take off which item (a-h)?" (27→18 bytes)
    .byte $c6, $79, $5f, $77, $8e, $28, $b1, $cf, $31, $b9, $3f, $52, $c8, $3b, $0c, $58, $f1, $10
    // [102] "You have nothing there." (24→14 bytes)
    .byte $1e, $f6, $c5, $e5, $fd, $9e, $9c, $73, $36, $69, $c7, $c3, $da, $80
    // [103] "Never mind." (12→8 bytes)
    .byte $c5, $7c, $bf, $0a, $a6, $66, $b6, $a0
    // [104] "You cannot remove it, it is cursed!" (36→21 bytes)
    .byte $1e, $f6, $f2, $f3, $9e, $9d, $0f, $53, $65, $fd, $c9, $b0, $6e, $4e, $e4, $af, $3d, $02, $f5, $88, $80
    // [105] "You have no food." (18→10 bytes)
    .byte $1e, $f6, $c5, $e5, $fd, $9e, $de, $37, $56, $d4
    // [106] "You are wielding a " (20→11 bytes)
    .byte $1e, $f6, $b8, $7d, $17, $3f, $05, $e6, $6c, $d7, $a8
    // [107] "You are wearing a " (19→10 bytes)
    .byte $1e, $f6, $b8, $7d, $17, $dc, $33, $36, $6b, $d4
    // [108] "You take off the " (18→10 bytes)
    .byte $1e, $f6, $9b, $ca, $fb, $bc, $71, $4e, $3f, $50
    // [109] "You eat the " (13→7 bytes)
    .byte $1e, $f6, $fb, $9d, $38, $fd, $40
    // [110] ". Delicious!" (13→9 bytes)
    .byte $6d, $60, $7c, $33, $ce, $77, $a4, $22, $00
    // [111] ". Yuck!" (8→6 bytes)
    .byte $6d, $1f, $79, $94, $22, $00
    // [112] "Quaff which potion (a-v)?" (26→18 bytes)
    .byte $62, $7e, $bf, $1c, $51, $63, $9e, $63, $70, $d3, $ce, $ce, $c8, $3b, $0c, $b6, $3c, $44
    // [113] "Read which scroll (a-v)?" (25→17 bytes)
    .byte $c5, $be, $eb, $a2, $c7, $3c, $c6, $97, $21, $b0, $85, $90, $76, $19, $6c, $78, $88
    // [114] "You create food." (17→10 bytes)
    .byte $1e, $f6, $f2, $1e, $e7, $f7, $8d, $d5, $b5, $00
    // [115] "You feel yourself moving faster." (33→19 bytes)
    .byte $1e, $f6, $f1, $ff, $0a, $ae, $f4, $0b, $e1, $c5, $53, $65, $e6, $6c, $de, $1c, $8f, $c1, $a8
    // [116] "That tasted terrible!" (22→13 bytes)
    .byte $c6, $8b, $9d, $37, $23, $f5, $d3, $f0, $0c, $c9, $87, $88, $80
    // [117] "Nothing seems to happen." (25→15 bytes)
    .byte $c5, $69, $c7, $33, $66, $97, $fa, $85, $4f, $6c, $5f, $0c, $3e, $6d, $40
    // [118] "The area fills with light." (27→16 bytes)
    .byte $c6, $8f, $d7, $0f, $7b, $c6, $61, $02, $a2, $e4, $e3, $61, $96, $62, $6d, $40
    // [119] "Identify which item (a-v)?" (27→19 bytes)
    .byte $c7, $57, $f3, $3c, $f0, $ad, $16, $39, $e6, $37, $27, $ea, $59, $07, $61, $96, $c7, $88, $80
    // [120] "This is a " (11→6 bytes)
    .byte $c6, $8e, $4a, $e4, $ab, $d4
    // [121] "You feel disoriented." (22→13 bytes)
    .byte $1e, $f6, $f1, $ff, $0a, $bc, $96, $86, $7e, $67, $eb, $6a, $00
    // [122] "You feel much better." (22→13 bytes)
    .byte $1e, $f6, $f1, $ff, $0a, $a7, $79, $8d, $93, $e6, $7e, $0d, $40
    // [123] "Your mind feels clear." (23→13 bytes)
    .byte $1e, $f4, $2a, $99, $9a, $ef, $1f, $f0, $2b, $cc, $3d, $c1, $a8
    // [124] "You feel heroic!" (17→10 bytes)
    .byte $1e, $f6, $f1, $ff, $0b, $1f, $0d, $cf, $22, $20
    // [125] "You can't see!" (15→9 bytes)
    .byte $1e, $f6, $f2, $f3, $c5, $ce, $97, $f8, $88
    // [126] "You feel dizzy." (16→11 bytes)
    .byte $1e, $f6, $f1, $ff, $0a, $bc, $e3, $f8, $fa, $ad, $40
    // [127] "You sense nearby creatures." (28→16 bytes)
    .byte $1e, $f6, $97, $cc, $be, $cf, $dc, $24, $ab, $79, $0f, $73, $e8, $79, $35, $00
    // [128] "Your eyes tingle." (18→10 bytes)
    .byte $1e, $f4, $2f, $ab, $e5, $4f, $33, $66, $1e, $d4
    // [129] "The air crackles around you." (29→17 bytes)
    .byte $c6, $8f, $d7, $c8, $5e, $41, $f9, $95, $0f, $2a, $e1, $bd, $9a, $ea, $bb, $d6, $a0
    // [130] "You feel cleansed." (19→11 bytes)
    .byte $1e, $f6, $f1, $ff, $0b, $cc, $3d, $e6, $5e, $b6, $a0
    // [131] "There is already an object under you." (38→23 bytes)
    .byte $c6, $8f, $87, $dc, $95, $78, $07, $ba, $d5, $af, $3b, $b2, $58, $9b, $f9, $3b, $d9, $af, $c2, $ab, $bd, $6a, $00
    // [132] "You see a strange rune." (24→13 bytes)
    .byte $1e, $f6, $97, $fd, $7a, $46, $0f, $36, $7e, $87, $67, $ed, $40
    // [133] "Your weapon glows briefly." (27→16 bytes)
    .byte $1e, $f4, $28, $be, $f8, $6c, $eb, $30, $d1, $4a, $c9, $0c, $ff, $10, $55, $a8
    // [134] "Your armor glows briefly." (26→15 bytes)
    .byte $1e, $f4, $2b, $82, $9a, $15, $98, $68, $a5, $64, $86, $7f, $88, $2a, $d4
    // [135] "Your hands begin to glow." (26→15 bytes)
    .byte $1e, $f4, $2c, $5e, $6b, $2b, $27, $d9, $cc, $e9, $ed, $66, $1a, $2b, $50
    // [136] "You hear a high-pitched humming." (33→20 bytes)
    .byte $1e, $f6, $c7, $dc, $2b, $d8, $e5, $98, $b0, $e1, $93, $e6, $3e, $bb, $1e, $a8, $a6, $66, $cb, $50
    // [137] "You feel protected." (20→12 bytes)
    .byte $1e, $f6, $f1, $ff, $0b, $80, $69, $ff, $27, $eb, $6a, $00
    // [138] "You feel a strange vibration." (30→17 bytes)
    .byte $1e, $f6, $f1, $ff, $0a, $f4, $8c, $1e, $6c, $fd, $97, $99, $20, $e7, $9d, $9b, $50
    // [139] "Aim which wand (a-v)?" (22→16 bytes)
    .byte $91, $65, $4a, $2c, $73, $cc, $68, $af, $35, $d9, $07, $61, $96, $c7, $88, $80
    // [140] "Use which staff (a-v)?" (23→16 bytes)
    .byte $62, $85, $f4, $58, $e7, $98, $d2, $37, $e3, $8b, $20, $ec, $32, $d8, $f1, $10
    // [141] "No charges left." (17→10 bytes)
    .byte $c5, $6d, $e6, $2e, $0c, $f9, $58, $7f, $06, $d4
    // [142] "The staff is empty." (20→12 bytes)
    .byte $c6, $8f, $d2, $37, $e3, $8b, $92, $be, $a6, $06, $ab, $50
    // [143] "A bolt of lightning shoots forth!" (34→20 bytes)
    .byte $91, $59, $3b, $03, $bb, $c5, $86, $59, $89, $cf, $33, $66, $94, $77, $4c, $af, $1a, $07, $11, $10
    // [144] "A bolt of frost shoots forth!" (30→17 bytes)
    .byte $91, $59, $3b, $03, $bb, $c5, $e0, $34, $8e, $94, $77, $4c, $af, $1a, $07, $11, $10
    // [145] "The monster looks confused." (28→17 bytes)
    .byte $c6, $8f, $d5, $36, $64, $7e, $16, $1b, $b2, $8a, $f3, $b3, $e3, $a5, $eb, $6a, $00
    // [146] "The cloud dissipates." (22→13 bytes)
    .byte $c6, $8f, $de, $61, $bd, $5d, $5e, $48, $b3, $83, $9f, $93, $50
    // [147] "You can't see to read!" (23→13 bytes)
    .byte $1e, $f6, $f2, $f3, $c5, $ce, $97, $fd, $3d, $a1, $ee, $b1, $10
    // [148] "Study which book (a-v)?" (24→17 bytes)
    .byte $91, $9f, $56, $ad, $16, $39, $e6, $36, $4e, $ec, $ab, $20, $ec, $32, $d8, $f1, $10
    // [149] "You cannot use magic." (22→13 bytes)
    .byte $1e, $f6, $f2, $f3, $9e, $9d, $e9, $7d, $51, $d9, $cf, $2d, $40
    // [150] "You cannot read that book." (27→15 bytes)
    .byte $1e, $f6, $f2, $f3, $9e, $9d, $0f, $75, $d3, $8b, $9d, $93, $bb, $29, $a8
    // [151] "You learn from the book!" (25→15 bytes)
    .byte $1e, $f6, $c3, $dc, $27, $78, $0d, $52, $9c, $7e, $c9, $dd, $94, $22, $00
    // [152] "No new spells to learn." (24→14 bytes)
    .byte $c5, $6d, $9f, $8b, $4b, $0f, $84, $0a, $9e, $d8, $7b, $84, $da, $80
    // [153] "Not using a lamp." (18→11 bytes)
    .byte $c5, $69, $de, $96, $66, $cd, $7b, $07, $53, $06, $a0
    // [154] "You have no oil." (17→10 bytes)
    .byte $1e, $f6, $c5, $e5, $fd, $9e, $dd, $cc, $1a, $80
    // [155] "Your lamp overflows." (21→13 bytes)
    .byte $1e, $f4, $2c, $1d, $4c, $2e, $cb, $f0, $e2, $1a, $29, $35, $00
    // [156] "Your lamp is full." (19→11 bytes)
    .byte $1e, $f4, $2c, $1d, $4c, $2e, $4a, $f1, $d8, $41, $a8
    // [157] "Your lamp is refueled." (23→13 bytes)
    .byte $1e, $f4, $2c, $1d, $4c, $2e, $4a, $87, $f1, $df, $87, $ad, $a8
    // [158] "Welcome to level " (18→11 bytes)
    .byte $c7, $3e, $1c, $ea, $9f, $4f, $6c, $3e, $5f, $c2, $a0
    // [159] "Your pack is full." (19→12 bytes)
    .byte $1e, $f4, $2e, $0f, $cc, $ab, $92, $bc, $76, $10, $6a, $00
    // [160] "You dig in the granite wall." (29→17 bytes)
    .byte $1e, $f6, $af, $2c, $dc, $ce, $9c, $7e, $b2, $0f, $3c, $9f, $d1, $5e, $10, $6a, $00
    // [161] "You dig in the magma." (22→13 bytes)
    .byte $1e, $f6, $af, $2c, $dc, $ce, $9c, $7e, $a8, $ec, $a8, $ed, $40
    // [162] "You dig in the quartz vein." (28→18 bytes)
    .byte $1e, $f6, $af, $2c, $dc, $ce, $9c, $7e, $b1, $2f, $5c, $0f, $1f, $b2, $ff, $33, $6a, $00
    // [163] "You have finished the tunnel." (30→17 bytes)
    .byte $1e, $f6, $c5, $e5, $fd, $e3, $33, $c9, $47, $d7, $4e, $3f, $4f, $b3, $9f, $c1, $a8
    // [164] "You have found something!" (26→16 bytes)
    .byte $1e, $f6, $c5, $e5, $fd, $e3, $7b, $35, $d2, $d5, $3c, $e3, $99, $b2, $22, $00
    // [165] "This seems to be permanent rock." (33→19 bytes)
    .byte $c6, $8e, $4a, $97, $fa, $85, $4f, $6c, $9f, $b8, $78, $28, $f3, $f9, $9d, $0d, $e6, $53, $50
    // [166] "There is nothing to tunnel here." (33→19 bytes)
    .byte $c6, $8f, $87, $dc, $95, $9e, $9c, $73, $36, $69, $ed, $3e, $ce, $7f, $0b, $1f, $0f, $6a, $00
    // [167] "The rubble crumbles." (21→14 bytes)
    .byte $c6, $8f, $d0, $ec, $99, $30, $fb, $c8, $75, $49, $30, $f2, $6a, $00
    // [168] "You dig with your hands, making no progress." (45→27 bytes)
    .byte $1e, $f6, $af, $2c, $d1, $72, $71, $aa, $ef, $42, $c5, $e6, $b2, $60, $d5, $1e, $56, $66, $cd, $9e, $dc, $03, $59, $0f, $22, $6a, $00
    // [169] "You see nothing here." (22→12 bytes)
    .byte $1e, $f6, $97, $fd, $9e, $9c, $73, $36, $6c, $7c, $3d, $a8
    // [170] "You found " (11→7 bytes)
    .byte $1e, $f6, $f1, $bd, $9a, $ea, $00
    // [171] " gold pieces." (14→8 bytes)
    .byte $ac, $ec, $17, $70, $cf, $f3, $e4, $d4
    // [172] "You picked up a " (17→10 bytes)
    .byte $1e, $f6, $e1, $9e, $65, $7a, $ef, $70, $af, $50
    // [173] "Drop which item (a-v)?" (23→16 bytes)
    .byte $60, $06, $e1, $45, $8e, $79, $8d, $c9, $fa, $96, $41, $d8, $65, $b1, $e2, $20
    // [174] "You drop a " (12→7 bytes)
    .byte $1e, $f6, $ac, $37, $0a, $f5, $00
    // [175] "No room on the floor." (22→13 bytes)
    .byte $c5, $6d, $0d, $d5, $2e, $ce, $9c, $7e, $f1, $0d, $d0, $6a, $00
    // [176] "Saving game..." (15→10 bytes)
    .byte $91, $bc, $bc, $cd, $9a, $cb, $a9, $ed, $6b, $50
    // [177] "Game saved." (12→8 bytes)
    .byte $62, $47, $53, $e9, $3c, $bf, $5b, $50
    // [178] "Loading game..." (16→11 bytes)
    .byte $62, $3d, $75, $e6, $6c, $d6, $5d, $4f, $6b, $5a, $80
    // [179] "Save file not found." (21→13 bytes)
    .byte $91, $bc, $bf, $bc, $66, $1f, $67, $a7, $78, $de, $cd, $6d, $40
    // [180] "Save file corrupt!" (19→12 bytes)
    .byte $91, $bc, $bf, $bc, $66, $1f, $79, $d0, $0e, $e0, $62, $20
    // [181] "Unsupported save." (18→12 bytes)
    .byte $62, $93, $2e, $e1, $86, $81, $fa, $e9, $3c, $bf, $6a, $00
    // [182] "Disk error!" (12→8 bytes)
    .byte $60, $64, $a5, $5f, $00, $d0, $11, $00
    // [183] "Welcome back to Moria8!" (24→17 bytes)
    .byte $c7, $3e, $1c, $ea, $9f, $64, $bf, $32, $a9, $ed, $62, $fa, $19, $76, $22, $11, $00
    // [184] "Need Save Disk." (16→11 bytes)
    .byte $c5, $7f, $ae, $c8, $de, $5f, $d6, $06, $4a, $53, $50
    // [185] "Wrong Save Disk." (17→12 bytes)
    .byte $c7, $03, $66, $cd, $91, $bc, $bf, $ac, $0c, $94, $a6, $a0
    // [186] "Overwrite? Y/N" (15→12 bytes)
    .byte $62, $19, $7e, $02, $86, $4f, $f1, $28, $d8, $83, $14, $80
    // [187] "You smash into the door!" (25→14 bytes)
    .byte $1e, $f6, $92, $8e, $51, $b9, $99, $ed, $38, $fd, $5e, $e8, $08, $80
    // [188] "The door crashes open!" (23→13 bytes)
    .byte $c6, $8f, $d5, $ee, $85, $e4, $1c, $a3, $e5, $77, $0f, $98, $88
    // [189] "The door holds firm." (21→12 bytes)
    .byte $c6, $8f, $d5, $ee, $85, $8e, $c1, $65, $78, $c8, $28, $d4
    // [190] "You are off balance." (21→12 bytes)
    .byte $1e, $f6, $b8, $7d, $de, $38, $b2, $5e, $0f, $3e, $7d, $a8
    // [191] "You bash at empty space." (25→15 bytes)
    .byte $1e, $f6, $c9, $72, $8d, $73, $be, $a6, $06, $ad, $2c, $1f, $9f, $6a, $00
    // [192] " appears stunned!" (18→10 bytes)
    .byte $af, $86, $1e, $e0, $54, $8f, $b3, $9f, $ac, $44
    // [193] " ignores your bash!" (20→12 bytes)
    .byte $b9, $66, $7a, $1e, $55, $5d, $e8, $59, $2e, $51, $11, $00
    // [194] "You feel very good." (20→12 bytes)
    .byte $1e, $f6, $f1, $ff, $0b, $2f, $c1, $5a, $ce, $ea, $da, $80
    // [195] "You sense magik on what you carry." (35→20 bytes)
    .byte $1e, $f6, $97, $cc, $be, $a8, $ec, $e6, $55, $d9, $d1, $62, $e7, $55, $de, $de, $5c, $01, $56, $a0
    // [196] "You feel your strength return." (31→17 bytes)
    .byte $1e, $f6, $f1, $ff, $0a, $ae, $f4, $29, $18, $7c, $d9, $38, $d0, $f3, $e8, $4d, $a8
    // [197] "You have discovered a trap on the chest!" (41→23 bytes)
    .byte $1e, $f6, $c5, $e5, $fd, $5e, $4b, $9d, $97, $e1, $eb, $af, $4c, $1f, $0b, $b3, $a7, $1f, $bc, $c7, $c8, $c4, $40
    // [198] "A small needle has pricked you!" (32→19 bytes)
    .byte $91, $52, $51, $e1, $0b, $3f, $f5, $c3, $ec, $5c, $ae, $01, $9e, $65, $7a, $ea, $bb, $d1, $10
    // [199] "You feel weakened!" (19→11 bytes)
    .byte $1e, $f6, $f1, $ff, $0a, $2f, $bc, $af, $9f, $ac, $44
    // [200] "A puff of yellow gas surrounds you!" (36→22 bytes)
    .byte $91, $5c, $3b, $c7, $17, $78, $aa, $fc, $21, $a2, $d6, $5c, $a9, $74, $03, $7b, $35, $95, $57, $7a, $22, $00
    // [201] "You are unaffected." (20→12 bytes)
    .byte $1e, $f6, $b8, $7d, $ec, $df, $8e, $3f, $93, $f5, $b5, $00
    // [202] "You choke and pass out." (24→14 bytes)
    .byte $1e, $f6, $f3, $1d, $95, $f5, $e6, $bb, $83, $91, $5d, $e9, $b5, $00
    // [203] "There is a sudden explosion!" (29→17 bytes)
    .byte $c6, $8f, $87, $dc, $95, $7a, $5d, $5a, $fe, $77, $f1, $ee, $10, $d2, $ce, $cc, $44
    // [204] "You have picked the lock." (26→16 bytes)
    .byte $1e, $f6, $c5, $e5, $fd, $c3, $3c, $ca, $f5, $d3, $8f, $d8, $6f, $32, $9a, $80
    // [205] "You are too confused to pick the lock." (39→22 bytes)
    .byte $1e, $f6, $b8, $7d, $3d, $db, $ce, $cf, $8e, $97, $ae, $9e, $dc, $33, $cc, $aa, $71, $fb, $0d, $e6, $53, $50
    // [206] "You failed to pick the lock." (29→17 bytes)
    .byte $1e, $f6, $f0, $f9, $87, $ae, $9e, $dc, $33, $cc, $aa, $71, $fb, $0d, $e6, $53, $50
    // [207] "a poison needle." (17→10 bytes)
    .byte $7b, $86, $e4, $b6, $76, $7f, $eb, $87, $b5, $00
    // [208] "an exploding chest." (20→13 bytes)
    .byte $79, $df, $c7, $b8, $43, $57, $99, $b3, $79, $8f, $91, $b5, $00
    // [209] "I don't see a trap..." (22→13 bytes)
    .byte $c7, $6a, $f6, $78, $b9, $d2, $ff, $af, $4c, $1f, $06, $b5, $a8
    // [210] "The chest was not trapped." (27→16 bytes)
    .byte $c6, $8f, $de, $63, $e4, $74, $57, $2b, $3d, $3a, $60, $f8, $61, $eb, $6a, $00
    // [211] "You have disarmed the chest." (29→16 bytes)
    .byte $1e, $f6, $c5, $e5, $fd, $5e, $49, $c1, $4f, $5d, $38, $fd, $e6, $3e, $46, $d4
    // [212] "You failed to disarm the chest." (32→18 bytes)
    .byte $1e, $f6, $f0, $f9, $87, $ae, $9e, $d5, $e4, $9c, $14, $a7, $1f, $bc, $c7, $c8, $da, $80
    // [213] "You set a trap off!" (20→11 bytes)
    .byte $1e, $f6, $97, $9d, $7a, $60, $f8, $5d, $e3, $81, $10
    // [214] "You have destroyed the chest..." (32→18 bytes)
    .byte $1e, $f6, $c5, $e5, $fd, $5f, $91, $86, $ab, $eb, $a7, $1f, $bc, $c7, $c8, $da, $d6, $a0
    // [215] "and it's contents!" (19→12 bytes)
    .byte $79, $ae, $e4, $f1, $72, $bc, $ec, $cf, $e6, $64, $22, $00
    // [216] "The lock breaks open!" (22→14 bytes)
    .byte $c6, $8f, $d8, $6f, $32, $ac, $90, $f7, $94, $57, $70, $f9, $88, $80
    // [217] "The chest holds firm." (22→13 bytes)
    .byte $c6, $8f, $de, $63, $e4, $76, $3b, $05, $95, $e3, $20, $a3, $50
    // [218] " (empty)" (9→7 bytes)
    .byte $b2, $1e, $a6, $06, $ab, $1a, $00
    // [219] " (locked)" (10→7 bytes)
    .byte $b2, $10, $de, $65, $7a, $d8, $d0
    // [220] " (trapped)" (11→7 bytes)
    .byte $b2, $06, $0f, $86, $1e, $b6, $34
    // [221] " (disarmed)" (12→8 bytes)
    .byte $b2, $0b, $c9, $38, $29, $eb, $63, $40

// Huffman code table:
//   NULL   =         0100 (4 bits, freq=222)
//   a      =         0111 (4 bits, freq=269)
//   b      =      1001001 (7 bits, freq=39)
//   c      =       111001 (6 bits, freq=97)
//   d      =        01011 (5 bits, freq=127)
//   e      =         1111 (4 bits, freq=410)
//   f      =       111000 (6 bits, freq=96)
//   g      =       011001 (6 bits, freq=68)
//   h      =        10001 (5 bits, freq=159)
//   i      =        11001 (5 bits, freq=180)
//   j      = 011000100110 (12 bits, freq=1)
//   k      =      1001010 (7 bits, freq=42)
//   l      =        10000 (5 bits, freq=151)
//   m      =       010100 (6 bits, freq=62)
//   n      =        10011 (5 bits, freq=175)
//   o      =         1101 (4 bits, freq=380)
//   p      =       110000 (6 bits, freq=87)
//   q      = 011000100101 (12 bits, freq=1)
//   r      =         0000 (4 bits, freq=205)
//   s      =         0010 (4 bits, freq=218)
//   t      =         0011 (4 bits, freq=221)
//   u      =        11101 (5 bits, freq=198)
//   v      =      1001011 (7 bits, freq=42)
//   w      =       000101 (6 bits, freq=52)
//   x      =  11000111101 (11 bits, freq=3)
//   y      =       010101 (6 bits, freq=62)
//   z      =   1100011111 (10 bits, freq=6)
//   SPACE  =          101 (3 bits, freq=670)
//   $21    =       000100 (6 bits, freq=51)
//   $27    =   1100010111 (10 bits, freq=6)
//   $28    =     10010000 (8 bits, freq=18)
//   $29    =     01100011 (8 bits, freq=18)
//   $2c    =    011000001 (9 bits, freq=7)
//   $2d    =     01100001 (8 bits, freq=15)
//   $2e    =        01101 (5 bits, freq=137)
//   $2f    = 011000100000 (12 bits, freq=1)
//   $38    = 011000100010 (12 bits, freq=1)
//   $3f    =     11000100 (8 bits, freq=21)
//   A      =    100100010 (9 bits, freq=8)
//   C      =  11000111100 (11 bits, freq=3)
//   D      =    011000000 (9 bits, freq=7)
//   E      =  01100010110 (11 bits, freq=2)
//   G      = 011000100100 (12 bits, freq=1)
//   H      =  01100010101 (11 bits, freq=2)
//   I      =   1100011101 (10 bits, freq=6)
//   L      = 011000100011 (12 bits, freq=1)
//   M      =  01100010111 (11 bits, freq=2)
//   N      =    110001010 (9 bits, freq=11)
//   O      = 011000100001 (12 bits, freq=1)
//   P      =  11000101100 (11 bits, freq=2)
//   Q      = 011000100111 (12 bits, freq=1)
//   R      =  11000101101 (11 bits, freq=3)
//   S      =    100100011 (9 bits, freq=10)
//   T      =     11000110 (8 bits, freq=24)
//   U      =  01100010100 (11 bits, freq=2)
//   W      =   1100011100 (10 bits, freq=6)
//   Y      =        00011 (5 bits, freq=108)
