// huffman_data.s — Generated by huff_encoder.py
// Source: data/huffman_strings.txt
// 209 strings, 4445 bytes uncompressed
// 2671 bytes compressed (60.1%)
// Tree: 112 bytes, Index: 418 bytes
// Total data: 3201 bytes

.const HUFF_STR_COUNT = 209
.const HSTR_INSULT_COUNT = 15

// Named string constants
.const HSTR_MAT_HITS = 15
.const HSTR_MAT_MISS = 16
.const HSTR_MAT_POISON = 17
.const HSTR_MAT_CONFUSE = 18
.const HSTR_MAT_PARALYZE = 19
.const HSTR_MAT_ACID = 20
.const HSTR_MAT_FEAR = 21
.const HSTR_MAT_SHRIEK = 22
.const HSTR_MM_BOLT = 23
.const HSTR_MM_BREATH = 24
.const HSTR_MM_SUMMON = 25
.const HSTR_MM_TELEPORT = 26
.const HSTR_MM_BLIND = 27
.const HSTR_MM_CONFUSE = 28
.const HSTR_MM_HEAL = 29
.const HSTR_RF_NO_WEAPON = 30
.const HSTR_RF_NO_AMMO = 31
.const HSTR_RF_FLIES = 32
.const HSTR_RF_MISSES = 33
.const HSTR_RF_HITS = 34
.const HSTR_EB_SPELL_HITS = 35
.const HSTR_EB_FIZZLE = 36
.const HSTR_TW_PROMPT = 37
.const HSTR_TW_SHATTERS = 38
.const HSTR_EFF_POISON_END = 39
.const HSTR_EFF_BLIND_END = 40
.const HSTR_EFF_CONFUSE_END = 41
.const HSTR_EFF_PARALYZE_END = 42
.const HSTR_EFF_FEAR_END = 43
.const HSTR_EFF_HASTE_END = 44
.const HSTR_EFF_SLOW_END = 45
.const HSTR_TTL_DIM = 46
.const HSTR_TTL_OUT = 47
.const HSTR_RECALL_ARRIVE = 48
.const HSTR_DL_YOU_SEE = 49
.const HSTR_DL_OPEN_DOOR = 50
.const HSTR_DL_CLOSED_DOOR = 51
.const HSTR_DL_STAIRS_DN = 52
.const HSTR_DL_STAIRS_UP = 53
.const HSTR_DL_TRAP = 54
.const HSTR_DL_RUBBLE = 55
.const HSTR_DL_WALL = 56
.const HSTR_DL_NOTHING = 57
.const HSTR_PTM_AFRAID = 58
.const HSTR_DF_TRAP_0 = 59
.const HSTR_DF_TRAP_1 = 60
.const HSTR_DF_TRAP_2 = 61
.const HSTR_DF_TRAP_3 = 62
.const HSTR_DF_TRAP_4 = 63
.const HSTR_DF_TRAP_5 = 64
.const HSTR_DF_DEATH_ROCKFALL = 65
.const HSTR_DF_DIRECTION = 66
.const HSTR_DF_DOOR_STUCK = 67
.const HSTR_DF_FOUND_TRAP = 68
.const HSTR_DF_FOUND_SECRET = 69
.const HSTR_DF_FOUND_NOTHING = 70
.const HSTR_DF_NO_DOOR = 71
.const HSTR_DF_ALREADY_OPEN = 72
.const HSTR_DF_ALREADY_CLOSED = 73
.const HSTR_DF_DOOR_OPENED = 74
.const HSTR_DF_DOOR_CLOSED = 75
.const HSTR_DF_YOU_FELL = 76
.const HSTR_DF_ARROW_HITS = 77
.const HSTR_DF_POISON_GAS = 78
.const HSTR_DF_TELEPORTED = 79
.const HSTR_DF_DART_HITS = 80
.const HSTR_DF_ROCKFALL = 81
.const HSTR_DF_DAMAGE_PRE = 82
.const HSTR_DF_DAMAGE_POST = 83
.const HSTR_DF_CON_DRAIN = 84
.const HSTR_DF_POISONED = 85
.const HSTR_PM_NO_CAST = 86
.const HSTR_PM_NO_PRAY = 87
.const HSTR_PM_NOT_KNOWN = 88
.const HSTR_PM_NO_MANA = 89
.const HSTR_PM_NO_EXP = 90
.const HSTR_PM_FAIL = 91
.const HSTR_PM_YOU_CAST = 92
.const HSTR_PM_YOU_PRAY = 93
.const HSTR_PM_TITLE_MAGE = 94
.const HSTR_PM_TITLE_PRAY = 95
.const HSTR_PM_FOOTER_CAST = 96
.const HSTR_PM_FOOTER_PRAY = 97
.const HSTR_PIQ_LITTLE_BETTER = 98
.const HSTR_PIW_WEAR_PROMPT = 99
.const HSTR_PIW_TAKEOFF_PROMPT = 100
.const HSTR_PIW_NOTHING = 101
.const HSTR_PIW_NEVERMIND = 102
.const HSTR_PIW_CURSED = 103
.const HSTR_PIW_NO_FOOD = 104
.const HSTR_PIW_WIELD = 105
.const HSTR_PIW_WEARING = 106
.const HSTR_PIW_TAKEOFF = 107
.const HSTR_PIW_EAT = 108
.const HSTR_PIW_DELICIOUS = 109
.const HSTR_PIW_YUCK = 110
.const HSTR_PIQ_QUAFF_PROMPT = 111
.const HSTR_PIQ_READ_PROMPT = 112
.const HSTR_PMU_CREATE_FOOD = 113
.const HSTR_PIQ_SPEED = 114
.const HSTR_PIQ_TERRIBLE = 115
.const HSTR_PIQ_NOTHING = 116
.const HSTR_PIQ_LIGHT = 117
.const HSTR_PIQ_IDENTIFY_PROMPT = 118
.const HSTR_PIQ_THISIS = 119
.const HSTR_PIQ_TELEPORT = 120
.const HSTR_PIQ_MUCH_BETTER = 121
.const HSTR_PIQ_MIND_CLEAR = 122
.const HSTR_PIQ_HEROIC = 123
.const HSTR_PIQ_CANT_SEE = 124
.const HSTR_PIQ_DIZZY = 125
.const HSTR_PIQ_SENSE = 126
.const HSTR_PIQ_EYES_TINGLE = 127
.const HSTR_PIQ_AIR_CRACKLE = 128
.const HSTR_PIQ_CLEANSED = 129
.const HSTR_PMU_GLYPH_BLOCK = 130
.const HSTR_PMU_GLYPH_OK = 131
.const HSTR_PIQ_WPN_GLOW = 132
.const HSTR_PIQ_ARM_GLOW = 133
.const HSTR_PIQ_HANDS_GLOW = 134
.const HSTR_PIQ_HUMMING = 135
.const HSTR_PIQ_PROTECTED = 136
.const HSTR_PIQ_VIBRATION = 137
.const HSTR_PIW_AIM_PROMPT = 138
.const HSTR_PIW_USE_PROMPT = 139
.const HSTR_PIW_NO_CHARGES = 140
.const HSTR_PIW_STAFF_EMPTY = 141
.const HSTR_PIW_WAND_BOLT = 142
.const HSTR_PIW_WAND_FROST = 143
.const HSTR_PIW_WAND_CLOUD = 144
.const HSTR_PIW_WAND_MISS = 145
.const HSTR_PIQ_CANT_READ = 146
.const HSTR_IGS_PROMPT = 147
.const HSTR_IGS_NO_MAGIC = 148
.const HSTR_IGS_WRONG_TYPE = 149
.const HSTR_IGS_SUCCESS = 150
.const HSTR_IGS_NO_NEW = 151
.const HSTR_PIR_NOT_LAMP = 152
.const HSTR_PIR_NO_OIL = 153
.const HSTR_PIR_OVERFLOW = 154
.const HSTR_PIR_FULL = 155
.const HSTR_PIR_REFUELED = 156
.const HSTR_CMB_LVLUP = 157
.const HSTR_UIS_PACK_FULL = 158
.const HSTR_TUN_DIG_GRANITE = 159
.const HSTR_TUN_DIG_MAGMA = 160
.const HSTR_TUN_DIG_QUARTZ = 161
.const HSTR_TUN_FINISHED = 162
.const HSTR_TUN_FOUND = 163
.const HSTR_TUN_PERMANENT = 164
.const HSTR_TUN_NOTHING = 165
.const HSTR_TUN_RUBBLE = 166
.const HSTR_TUN_NO_TOOL = 167
.const HSTR_IPU_NOTHING = 168
.const HSTR_IPU_FOUND = 169
.const HSTR_IPU_GOLD = 170
.const HSTR_IPU_PICKED = 171
.const HSTR_IDR_PROMPT = 172
.const HSTR_IDR_DROP = 173
.const HSTR_IDR_FLOOR_FULL = 174
.const HSTR_SAVE_SAVING = 175
.const HSTR_SAVE_DONE = 176
.const HSTR_SAVE_LOADING = 177
.const HSTR_SAVE_NOTFOUND = 178
.const HSTR_SAVE_CORRUPT = 179
.const HSTR_SAVE_UNSUPPORTED = 180
.const HSTR_SAVE_IOERR = 181
.const HSTR_SAVE_WELCOME = 182
.const HSTR_SAVE_NEED_SAVE = 183
.const HSTR_SAVE_BAD_SAVE = 184
.const HSTR_SAVE_OVERWRITE = 185
.const HSTR_BASH_SMASH = 186
.const HSTR_BASH_CRASH = 187
.const HSTR_BASH_HOLDS = 188
.const HSTR_BASH_OFFBAL = 189
.const HSTR_BASH_EMPTY = 190
.const HSTR_BASH_STUNNED = 191
.const HSTR_BASH_IGNORES = 192
.const HSTR_PIQ_VERY_GOOD = 193
.const HSTR_PID_CARRY = 194
.const HSTR_PIQ_RESTORED = 195
.const HSTR_CHEST_FOUND_TRAP = 196
.const HSTR_CHEST_TRAPPED = 197
.const HSTR_CHEST_NEEDLE = 198
.const HSTR_CHEST_WEAKENED = 199
.const HSTR_CHEST_GAS = 200
.const HSTR_CHEST_UNAFFECTED = 201
.const HSTR_CHEST_CHOKE = 202
.const HSTR_CHEST_EXPLOSION = 203
.const HSTR_CHEST_PICKED = 204
.const HSTR_CHEST_PICK_CONFUSED = 205
.const HSTR_CHEST_PICK_FAIL = 206
.const HSTR_CHEST_DEATH_NEEDLE = 207
.const HSTR_CHEST_DEATH_EXPLODING = 208

// Huffman tree: 56 internal nodes
// Children: $00-$7E = node index, $80+ = leaf (& $7F = screencode)
huff_tree_left:
    .byte $01, $03, $05, $07, $09, $0b, $0c, $92, $0e, $80, $81, $11, $13, $14, $15, $84, $ae, $88, $18, $8e, $1a, $a1, $8d, $99, $1c, $90, $83, $1f, $21, $8b, $22, $a9, $a8, $25, $bf, $d4, $c4, $29, $c1, $d3, $ce, $2e, $30, $a7, $c9, $9a, $34, $36, $d5, $c5, $d0, $c3, $af, $b8, $c7, $8a
huff_tree_right:
    .byte $02, $04, $06, $08, $0a, $a0, $0d, $94, $93, $0f, $10, $12, $8f, $85, $d9, $16, $17, $8c, $19, $89, $95, $97, $1b, $87, $1d, $1e, $86, $20, $82, $96, $23, $24, $ad, $26, $27, $28, $ac, $2a, $2b, $2c, $2d, $2f, $31, $32, $33, $d7, $35, $37, $c8, $cd, $d2, $98, $cf, $cc, $91, $d1

// String index: 16-bit byte offsets into huff_str_data
huff_str_index:
    .word $0000  // [0] "You will have to do better tha"
    .word $0015  // [1] "That is an insult!"
    .word $0020  // [2] "Do you wish to do business or "
    .word $0034  // [3] "Hah! Try again."
    .word $003f  // [4] "Ridiculous!"
    .word $0048  // [5] "You have got to be kidding!"
    .word $0059  // [6] "You had better be kidding!"
    .word $0069  // [7] "You try my patience."
    .word $0075  // [8] "I do not hear you."
    .word $0080  // [9] "Hmmm, nice weather we are havi"
    .word $0095  // [10] "I must have heard you wrong."
    .word $00a6  // [11] "What was that?"
    .word $00af  // [12] "I am sorry, say that again."
    .word $00c0  // [13] "What did you say?"
    .word $00cb  // [14] "Sorry, what was that again?"
    .word $00dc  // [15] @MAT_HITS " hits you."
    .word $00e2  // [16] @MAT_MISS " misses you."
    .word $00ea  // [17] @MAT_POISON " poisons you."
    .word $00f2  // [18] @MAT_CONFUSE " confuses you."
    .word $00fb  // [19] @MAT_PARALYZE " paralyzes you."
    .word $0105  // [20] @MAT_ACID " spits acid on you."
    .word $0110  // [21] @MAT_FEAR " frightens you."
    .word $011a  // [22] @MAT_SHRIEK "You hear a horrible shriek!"
    .word $012a  // [23] @MM_BOLT " casts a bolt!"
    .word $0133  // [24] @MM_BREATH " breathes fire!"
    .word $013c  // [25] @MM_SUMMON " summons help!"
    .word $0145  // [26] @MM_TELEPORT " teleports you!"
    .word $014e  // [27] @MM_BLIND " blinds you!"
    .word $0156  // [28] @MM_CONFUSE " confuses you!"
    .word $015f  // [29] @MM_HEAL " heals itself."
    .word $0168  // [30] @RF_NO_WEAPON "No ranged weapon."
    .word $0173  // [31] @RF_NO_AMMO "No ammo."
    .word $0179  // [32] @RF_FLIES " flies away."
    .word $0181  // [33] @RF_MISSES " misses"
    .word $0186  // [34] @RF_HITS " hits"
    .word $018a  // [35] @EB_SPELL_HITS "Your spell hits"
    .word $0193  // [36] @EB_FIZZLE "Your spell fizzles out."
    .word $01a2  // [37] @TW_PROMPT "Throw which item (a-v)?"
    .word $01b3  // [38] @TW_SHATTERS " shatters!"
    .word $01b9  // [39] @EFF_POISON_END "You feel better."
    .word $01c3  // [40] @EFF_BLIND_END "You can see again."
    .word $01ce  // [41] @EFF_CONFUSE_END "You feel less confused."
    .word $01dc  // [42] @EFF_PARALYZE_END "You can move again."
    .word $01e8  // [43] @EFF_FEAR_END "You feel bolder now."
    .word $01f4  // [44] @EFF_HASTE_END "You feel yourself slow down."
    .word $0205  // [45] @EFF_SLOW_END "You feel yourself speed up."
    .word $0215  // [46] @TTL_DIM "Your light is growing dim."
    .word $0225  // [47] @TTL_OUT "Your light has gone out."
    .word $0233  // [48] @RECALL_ARRIVE "You feel yourself yanked away!"
    .word $0245  // [49] @DL_YOU_SEE "You see a "
    .word $024b  // [50] @DL_OPEN_DOOR "You see an open door."
    .word $0257  // [51] @DL_CLOSED_DOOR "You see a closed door."
    .word $0263  // [52] @DL_STAIRS_DN "You see a staircase down."
    .word $0271  // [53] @DL_STAIRS_UP "You see a staircase up."
    .word $027e  // [54] @DL_TRAP "You see a trap."
    .word $0287  // [55] @DL_RUBBLE "You see rubble."
    .word $0291  // [56] @DL_WALL "You see a wall."
    .word $029a  // [57] @DL_NOTHING "You see nothing special."
    .word $02a8  // [58] @PTM_AFRAID "You are too afraid!"
    .word $02b3  // [59] @DF_TRAP_0 "an open pit"
    .word $02ba  // [60] @DF_TRAP_1 "an arrow trap"
    .word $02c2  // [61] @DF_TRAP_2 "a poison gas trap"
    .word $02cc  // [62] @DF_TRAP_3 "a teleport trap"
    .word $02d5  // [63] @DF_TRAP_4 "a poison dart"
    .word $02dd  // [64] @DF_TRAP_5 "a rockfall trap"
    .word $02e7  // [65] @DF_DEATH_ROCKFALL "falling rock."
    .word $02f0  // [66] @DF_DIRECTION "Direction?"
    .word $02f8  // [67] @DF_DOOR_STUCK "The door is stuck."
    .word $0303  // [68] @DF_FOUND_TRAP "You found a trap!"
    .word $030d  // [69] @DF_FOUND_SECRET "You found a secret door!"
    .word $031b  // [70] @DF_FOUND_NOTHING "You found nothing."
    .word $0326  // [71] @DF_NO_DOOR "No door there."
    .word $032f  // [72] @DF_ALREADY_OPEN "The door is already open."
    .word $033e  // [73] @DF_ALREADY_CLOSED "It is already closed."
    .word $034b  // [74] @DF_DOOR_OPENED "You open the door."
    .word $0356  // [75] @DF_DOOR_CLOSED "You close the door."
    .word $0361  // [76] @DF_YOU_FELL "You fell into a pit!"
    .word $036d  // [77] @DF_ARROW_HITS "An arrow hits you!"
    .word $0378  // [78] @DF_POISON_GAS "A cloud of gas surrounds you!"
    .word $038a  // [79] @DF_TELEPORTED "You are teleported!"
    .word $0395  // [80] @DF_DART_HITS "A dart hits you!"
    .word $039f  // [81] @DF_ROCKFALL "Rocks fall on you!"
    .word $03ab  // [82] @DF_DAMAGE_PRE "You take "
    .word $03b1  // [83] @DF_DAMAGE_POST " damage."
    .word $03b7  // [84] @DF_CON_DRAIN "You feel weakened."
    .word $03c2  // [85] @DF_POISONED "You feel poisoned."
    .word $03cd  // [86] @PM_NO_CAST "You cannot cast spells."
    .word $03db  // [87] @PM_NO_PRAY "You cannot pray."
    .word $03e5  // [88] @PM_NOT_KNOWN "You don't know that spell."
    .word $03f5  // [89] @PM_NO_MANA "You faint from fatigue."
    .word $0403  // [90] @PM_NO_EXP "You're not experienced enough."
    .word $0416  // [91] @PM_FAIL "Your spell fails."
    .word $0421  // [92] @PM_YOU_CAST "Spell book (a-v)?"
    .word $042e  // [93] @PM_YOU_PRAY "Prayer book (a-v)?"
    .word $043c  // [94] @PM_TITLE_MAGE "Monster slows."
    .word $0445  // [95] @PM_TITLE_PRAY "Type?"
    .word $044a  // [96] @PM_FOOTER_CAST "Cast which? (a-p, ESC)"
    .word $045d  // [97] @PM_FOOTER_PRAY "Pray which? (a-p, ESC)"
    .word $0470  // [98] @PIQ_LITTLE_BETTER "You feel a little better."
    .word $047e  // [99] @PIW_WEAR_PROMPT "Wear which item (a-v)?"
    .word $048e  // [100] @PIW_TAKEOFF_PROMPT "Take off which item (a-h)?"
    .word $04a0  // [101] @PIW_NOTHING "You have nothing there."
    .word $04ae  // [102] @PIW_NEVERMIND "Never mind."
    .word $04b6  // [103] @PIW_CURSED "You cannot remove it, it is cu"
    .word $04cb  // [104] @PIW_NO_FOOD "You have no food."
    .word $04d5  // [105] @PIW_WIELD "You are wielding a "
    .word $04e0  // [106] @PIW_WEARING "You are wearing a "
    .word $04ea  // [107] @PIW_TAKEOFF "You take off the "
    .word $04f4  // [108] @PIW_EAT "You eat the "
    .word $04fb  // [109] @PIW_DELICIOUS ". Delicious!"
    .word $0504  // [110] @PIW_YUCK ". Yuck!"
    .word $050a  // [111] @PIQ_QUAFF_PROMPT "Quaff which potion (a-v)?"
    .word $051c  // [112] @PIQ_READ_PROMPT "Read which scroll (a-v)?"
    .word $052d  // [113] @PMU_CREATE_FOOD "You create food."
    .word $0537  // [114] @PIQ_SPEED "You feel yourself moving faste"
    .word $054a  // [115] @PIQ_TERRIBLE "That tasted terrible!"
    .word $0557  // [116] @PIQ_NOTHING "Nothing seems to happen."
    .word $0566  // [117] @PIQ_LIGHT "The area fills with light."
    .word $0576  // [118] @PIQ_IDENTIFY_PROMPT "Identify which item (a-v)?"
    .word $0589  // [119] @PIQ_THISIS "This is a "
    .word $058f  // [120] @PIQ_TELEPORT "You feel disoriented."
    .word $059c  // [121] @PIQ_MUCH_BETTER "You feel much better."
    .word $05a9  // [122] @PIQ_MIND_CLEAR "Your mind feels clear."
    .word $05b6  // [123] @PIQ_HEROIC "You feel heroic!"
    .word $05c0  // [124] @PIQ_CANT_SEE "You can't see!"
    .word $05c9  // [125] @PIQ_DIZZY "You feel dizzy."
    .word $05d4  // [126] @PIQ_SENSE "You sense nearby creatures."
    .word $05e4  // [127] @PIQ_EYES_TINGLE "Your eyes tingle."
    .word $05ee  // [128] @PIQ_AIR_CRACKLE "The air crackles around you."
    .word $05ff  // [129] @PIQ_CLEANSED "You feel cleansed."
    .word $060a  // [130] @PMU_GLYPH_BLOCK "There is already an object und"
    .word $0621  // [131] @PMU_GLYPH_OK "You see a strange rune."
    .word $062e  // [132] @PIQ_WPN_GLOW "Your weapon glows briefly."
    .word $063e  // [133] @PIQ_ARM_GLOW "Your armor glows briefly."
    .word $064d  // [134] @PIQ_HANDS_GLOW "Your hands begin to glow."
    .word $065c  // [135] @PIQ_HUMMING "You hear a high-pitched hummin"
    .word $0670  // [136] @PIQ_PROTECTED "You feel protected."
    .word $067c  // [137] @PIQ_VIBRATION "You feel a strange vibration."
    .word $068d  // [138] @PIW_AIM_PROMPT "Aim which wand (a-v)?"
    .word $069d  // [139] @PIW_USE_PROMPT "Use which staff (a-v)?"
    .word $06ad  // [140] @PIW_NO_CHARGES "No charges left."
    .word $06b7  // [141] @PIW_STAFF_EMPTY "The staff is empty."
    .word $06c3  // [142] @PIW_WAND_BOLT "A bolt of lightning shoots for"
    .word $06d7  // [143] @PIW_WAND_FROST "A bolt of frost shoots forth!"
    .word $06e8  // [144] @PIW_WAND_CLOUD "The monster looks confused."
    .word $06f9  // [145] @PIW_WAND_MISS "The cloud dissipates."
    .word $0706  // [146] @PIQ_CANT_READ "You can't see to read!"
    .word $0713  // [147] @IGS_PROMPT "Study which book (a-v)?"
    .word $0724  // [148] @IGS_NO_MAGIC "You cannot use magic."
    .word $0731  // [149] @IGS_WRONG_TYPE "You cannot read that book."
    .word $0740  // [150] @IGS_SUCCESS "You learn from the book!"
    .word $074f  // [151] @IGS_NO_NEW "No new spells to learn."
    .word $075d  // [152] @PIR_NOT_LAMP "Not using a lamp."
    .word $0768  // [153] @PIR_NO_OIL "You have no oil."
    .word $0772  // [154] @PIR_OVERFLOW "Your lamp overflows."
    .word $077f  // [155] @PIR_FULL "Your lamp is full."
    .word $078a  // [156] @PIR_REFUELED "Your lamp is refueled."
    .word $0797  // [157] @CMB_LVLUP "Welcome to level "
    .word $07a2  // [158] @UIS_PACK_FULL "Your pack is full."
    .word $07ae  // [159] @TUN_DIG_GRANITE "You dig in the granite wall."
    .word $07bf  // [160] @TUN_DIG_MAGMA "You dig in the magma."
    .word $07cc  // [161] @TUN_DIG_QUARTZ "You dig in the quartz vein."
    .word $07de  // [162] @TUN_FINISHED "You have finished the tunnel."
    .word $07ef  // [163] @TUN_FOUND "You have found something!"
    .word $07ff  // [164] @TUN_PERMANENT "This seems to be permanent roc"
    .word $0812  // [165] @TUN_NOTHING "There is nothing to tunnel her"
    .word $0825  // [166] @TUN_RUBBLE "The rubble crumbles."
    .word $0833  // [167] @TUN_NO_TOOL "You dig with your hands, makin"
    .word $084e  // [168] @IPU_NOTHING "You see nothing here."
    .word $085a  // [169] @IPU_FOUND "You found "
    .word $0861  // [170] @IPU_GOLD " gold pieces."
    .word $0869  // [171] @IPU_PICKED "You picked up a "
    .word $0873  // [172] @IDR_PROMPT "Drop which item (a-v)?"
    .word $0883  // [173] @IDR_DROP "You drop a "
    .word $088a  // [174] @IDR_FLOOR_FULL "No room on the floor."
    .word $0897  // [175] @SAVE_SAVING "Saving game..."
    .word $08a1  // [176] @SAVE_DONE "Game saved."
    .word $08a9  // [177] @SAVE_LOADING "Loading game..."
    .word $08b4  // [178] @SAVE_NOTFOUND "Save file not found."
    .word $08c1  // [179] @SAVE_CORRUPT "Save file corrupt!"
    .word $08cd  // [180] @SAVE_UNSUPPORTED "Unsupported save."
    .word $08d9  // [181] @SAVE_IOERR "Disk error!"
    .word $08e1  // [182] @SAVE_WELCOME "Welcome back to Moria8!"
    .word $08f2  // [183] @SAVE_NEED_SAVE "Need Save Disk."
    .word $08fd  // [184] @SAVE_BAD_SAVE "Wrong Save Disk."
    .word $0909  // [185] @SAVE_OVERWRITE "Overwrite? Y/N"
    .word $0915  // [186] @BASH_SMASH "You smash into the door!"
    .word $0923  // [187] @BASH_CRASH "The door crashes open!"
    .word $0930  // [188] @BASH_HOLDS "The door holds firm."
    .word $093c  // [189] @BASH_OFFBAL "You are off balance."
    .word $0948  // [190] @BASH_EMPTY "You bash at empty space."
    .word $0957  // [191] @BASH_STUNNED " appears stunned!"
    .word $0961  // [192] @BASH_IGNORES " ignores your bash!"
    .word $096d  // [193] @PIQ_VERY_GOOD "You feel very good."
    .word $0979  // [194] @PID_CARRY "You sense magik on what you ca"
    .word $098d  // [195] @PIQ_RESTORED "You feel your strength return."
    .word $099e  // [196] @CHEST_FOUND_TRAP "You have discovered a trap on "
    .word $09b5  // [197] @CHEST_TRAPPED "The chest is trapped!"
    .word $09c2  // [198] @CHEST_NEEDLE "A small needle has pricked you"
    .word $09d5  // [199] @CHEST_WEAKENED "You feel weakened!"
    .word $09e0  // [200] @CHEST_GAS "A puff of yellow gas surrounds"
    .word $09f6  // [201] @CHEST_UNAFFECTED "You are unaffected."
    .word $0a02  // [202] @CHEST_CHOKE "You choke and pass out."
    .word $0a10  // [203] @CHEST_EXPLOSION "There is a sudden explosion!"
    .word $0a21  // [204] @CHEST_PICKED "You have picked the lock."
    .word $0a31  // [205] @CHEST_PICK_CONFUSED "You are too confused to pick t"
    .word $0a47  // [206] @CHEST_PICK_FAIL "You failed to pick the lock."
    .word $0a58  // [207] @CHEST_DEATH_NEEDLE "a poison needle."
    .word $0a62  // [208] @CHEST_DEATH_EXPLODING "an exploding chest."

// Compressed string data (2671 bytes)
huff_str_data:
    // [0] "You will have to do better than that!" (38→21 bytes)
    .byte $2e, $f6, $93, $98, $c6, $c1, $a5, $fd, $1d, $aa, $db, $27, $c4, $7c, $28, $c1, $b1, $46, $0c, $24, $20
    // [1] "That is an insult!" (19→11 bytes)
    .byte $9e, $83, $0d, $c9, $d6, $c5, $ce, $0f, $b1, $12, $10
    // [2] "Do you wish to do business or not?" (35→20 bytes)
    .byte $5d, $6d, $7b, $7b, $49, $c9, $c2, $8e, $d5, $6d, $93, $d3, $ce, $3c, $ce, $e8, $5c, $68, $ce, $20
    // [3] "Hah! Try again." (16→11 bytes)
    .byte $90, $ad, $02, $2c, $f0, $3d, $59, $f6, $ce, $1c, $80
    // [4] "Ridiculous!" (12→9 bytes)
    .byte $91, $f9, $56, $78, $ec, $77, $a6, $42, $00
    // [5] "You have got to be kidding!" (28→17 bytes)
    .byte $2e, $f6, $c1, $a5, $fd, $7f, $46, $8e, $d9, $3f, $65, $65, $4a, $ce, $1f, $21, $00
    // [6] "You had better be kidding!" (27→16 bytes)
    .byte $2e, $f6, $c1, $95, $64, $f8, $8f, $85, $93, $f6, $56, $54, $ac, $e1, $f2, $10
    // [7] "You try my patience." (21→12 bytes)
    .byte $2e, $f6, $88, $3d, $56, $7a, $cc, $c3, $9f, $c7, $1e, $e4
    // [8] "I do not hear you." (19→11 bytes)
    .byte $9d, $aa, $b6, $e3, $46, $c3, $d8, $2b, $db, $d7, $20
    // [9] "Hmmm, nice weather we are having." (34→21 bytes)
    .byte $90, $ab, $2c, $b2, $ee, $e3, $3c, $7d, $27, $d8, $61, $e1, $49, $fa, $c1, $f6, $0d, $2f, $38, $7d, $c8
    // [10] "I must have heard you wrong." (29→17 bytes)
    .byte $9d, $aa, $dd, $31, $b0, $69, $7f, $61, $ec, $0a, $af, $6f, $69, $21, $b8, $7d, $c8
    // [11] "What was that?" (15→9 bytes)
    .byte $9f, $e0, $c3, $49, $63, $a3, $06, $19, $c4
    // [12] "I am sorry, say that again." (28→17 bytes)
    .byte $9d, $ab, $2d, $4f, $40, $1e, $5d, $d3, $67, $a8, $c1, $86, $b3, $ed, $9c, $39, $00
    // [13] "What did you say?" (18→11 bytes)
    .byte $9f, $e0, $c3, $55, $95, $57, $b7, $b4, $d9, $e9, $c4
    // [14] "Sorry, what was that again?" (28→17 bytes)
    .byte $9d, $68, $03, $cb, $ba, $4c, $18, $69, $2c, $74, $60, $c3, $59, $f6, $ce, $27, $10
    // [15] " hits you." (11→6 bytes)
    .byte $b0, $c8, $9d, $7b, $7a, $e4
    // [16] " misses you." (13→8 bytes)
    .byte $ab, $64, $cf, $ce, $bd, $bd, $72, $00
    // [17] " poisons you." (14→8 bytes)
    .byte $b3, $6e, $4f, $70, $75, $ed, $eb, $90
    // [18] " confuses you." (15→9 bytes)
    .byte $bc, $6e, $39, $e9, $f9, $d7, $b7, $ae, $40
    // [19] " paralyzes you." (16→10 bytes)
    .byte $b3, $30, $34, $5e, $9f, $bc, $eb, $db, $d7, $20
    // [20] " spits acid on you." (20→11 bytes)
    .byte $a7, $36, $44, $eb, $71, $95, $5d, $c5, $7b, $7a, $e4
    // [21] " frightens you." (16→10 bytes)
    .byte $bc, $86, $5f, $80, $fe, $0e, $bd, $bd, $72, $00
    // [22] "You hear a horrible shriek!" (28→16 bytes)
    .byte $2e, $f6, $c3, $d8, $2b, $58, $68, $06, $64, $c7, $e9, $c0, $33, $f2, $88, $40
    // [23] " casts a bolt!" (15→9 bytes)
    .byte $bc, $31, $89, $d6, $b2, $76, $22, $42, $00
    // [24] " breathes fire!" (16→9 bytes)
    .byte $b2, $43, $d8, $61, $e7, $79, $c8, $79, $08
    // [25] " summons help!" (15→9 bytes)
    .byte $a7, $d5, $96, $dc, $1d, $87, $c6, $62, $10
    // [26] " teleports you!" (16→9 bytes)
    .byte $a3, $f1, $f9, $b4, $04, $eb, $db, $d2, $10
    // [27] " blinds you!" (13→8 bytes)
    .byte $b2, $63, $9c, $28, $eb, $db, $d2, $10
    // [28] " confuses you!" (15→9 bytes)
    .byte $bc, $6e, $39, $e9, $f9, $d7, $b7, $a4, $20
    // [29] " heals itself." (15→9 bytes)
    .byte $b0, $f6, $89, $dc, $89, $fc, $79, $72, $00
    // [30] "No ranged weapon." (18→11 bytes)
    .byte $9f, $6d, $06, $c3, $fe, $aa, $4f, $b4, $db, $87, $20
    // [31] "No ammo." (9→6 bytes)
    .byte $9f, $6d, $65, $96, $d7, $20
    // [32] " flies away." (13→8 bytes)
    .byte $bc, $c7, $3e, $75, $89, $67, $9c, $80
    // [33] " misses" (8→5 bytes)
    .byte $ab, $64, $cf, $cd, $00
    // [34] " hits" (6→4 bytes)
    .byte $b0, $c8, $9a, $00
    // [35] "Your spell hits" (16→9 bytes)
    .byte $2e, $f4, $29, $cd, $f1, $8d, $86, $44, $d0
    // [36] "Your spell fizzles out." (24→15 bytes)
    .byte $2e, $f4, $29, $cd, $f1, $8d, $e7, $33, $f4, $fd, $1f, $3b, $bd, $17, $20
    // [37] "Throw which item (a-v)?" (24→17 bytes)
    .byte $9e, $80, $69, $34, $98, $67, $88, $5c, $8f, $ad, $57, $99, $7e, $5a, $e4, $e2, $00
    // [38] " shatters!" (11→6 bytes)
    .byte $a7, $06, $11, $f0, $32, $10
    // [39] "You feel better." (17→10 bytes)
    .byte $2e, $f6, $f3, $ff, $1b, $27, $c4, $7c, $1c, $80
    // [40] "You can see again." (19→11 bytes)
    .byte $2e, $f6, $f0, $d8, $a7, $ff, $59, $f6, $ce, $1c, $80
    // [41] "You feel less confused." (24→14 bytes)
    .byte $2e, $f6, $f3, $ff, $1b, $1f, $33, $bc, $6e, $39, $e9, $fa, $9c, $80
    // [42] "You can move again." (20→12 bytes)
    .byte $2e, $f6, $f0, $d8, $ab, $6c, $bf, $ac, $fb, $67, $0e, $40
    // [43] "You feel bolder now." (21→12 bytes)
    .byte $2e, $f6, $f3, $ff, $1b, $27, $62, $af, $0b, $8d, $25, $c8
    // [44] "You feel yourself slow down." (29→17 bytes)
    .byte $2e, $f6, $f3, $ff, $1a, $f6, $f4, $0f, $e3, $cd, $38, $e9, $35, $5a, $4e, $1c, $80
    // [45] "You feel yourself speed up." (28→16 bytes)
    .byte $2e, $f6, $f3, $ff, $1a, $f6, $f4, $0f, $e3, $cd, $39, $bf, $d5, $7b, $33, $90
    // [46] "Your light is growing dim." (27→16 bytes)
    .byte $2e, $f4, $2c, $72, $fc, $06, $e4, $eb, $e1, $a4, $e7, $0f, $d5, $65, $67, $20
    // [47] "Your light has gone out." (25→14 bytes)
    .byte $2e, $f4, $2c, $72, $fc, $06, $c1, $8e, $bf, $b8, $fb, $bd, $17, $20
    // [48] "You feel yourself yanked away!" (31→18 bytes)
    .byte $2e, $f6, $f3, $ff, $1a, $f6, $f4, $0f, $e3, $cd, $79, $b1, $2b, $d5, $58, $96, $78, $84
    // [49] "You see a " (11→6 bytes)
    .byte $2e, $f6, $9f, $fd, $6a, $80
    // [50] "You see an open door." (22→12 bytes)
    .byte $2e, $f6, $9f, $fd, $6c, $5d, $9b, $f1, $55, $ba, $0e, $40
    // [51] "You see a closed door." (23→12 bytes)
    .byte $2e, $f6, $9f, $fd, $6b, $c4, $74, $fd, $55, $5b, $a0, $e4
    // [52] "You see a staircase down." (26→14 bytes)
    .byte $2e, $f6, $9f, $fd, $6a, $62, $d9, $0e, $18, $fe, $ab, $49, $c3, $90
    // [53] "You see a staircase up." (24→13 bytes)
    .byte $2e, $f6, $9f, $fd, $6a, $62, $d9, $0e, $18, $fe, $f6, $67, $20
    // [54] "You see a trap." (16→9 bytes)
    .byte $2e, $f6, $9f, $fd, $6a, $20, $d3, $39, $00
    // [55] "You see rubble." (16→10 bytes)
    .byte $2e, $f6, $9f, $fd, $0e, $c9, $93, $1f, $72, $00
    // [56] "You see a wall." (16→9 bytes)
    .byte $2e, $f6, $9f, $fd, $6a, $4b, $46, $2e, $40
    // [57] "You see nothing special." (25→14 bytes)
    .byte $2e, $f6, $9f, $fd, $c6, $8c, $33, $87, $e9, $cd, $fc, $65, $a2, $e4
    // [58] "You are too afraid!" (20→11 bytes)
    .byte $2e, $f6, $b0, $7d, $1d, $da, $dc, $83, $65, $44, $20
    // [59] "an open pit" (12→7 bytes)
    .byte $6c, $5d, $9b, $f1, $66, $c8, $a0
    // [60] "an arrow trap" (14→8 bytes)
    .byte $6c, $56, $00, $d2, $68, $83, $4c, $80
    // [61] "a poison gas trap" (18→10 bytes)
    .byte $6b, $36, $e4, $f7, $15, $f6, $3a, $20, $d3, $20
    // [62] "a teleport trap" (16→9 bytes)
    .byte $6a, $3f, $1f, $9b, $40, $68, $83, $4c, $80
    // [63] "a poison dart" (14→8 bytes)
    .byte $6b, $36, $e4, $f7, $15, $4c, $02, $80
    // [64] "a rockfall trap" (16→10 bytes)
    .byte $6a, $1b, $c4, $ae, $5a, $31, $a2, $0d, $32, $00
    // [65] "falling rock." (14→9 bytes)
    .byte $e5, $a3, $1c, $e1, $fa, $1b, $c4, $a7, $20
    // [66] "Direction?" (11→8 bytes)
    .byte $5d, $64, $3f, $81, $ce, $e2, $71, $00
    // [67] "The door is stuck." (19→11 bytes)
    .byte $9e, $87, $d5, $6e, $85, $c9, $d3, $1e, $f1, $29, $c8
    // [68] "You found a trap!" (18→10 bytes)
    .byte $2e, $f6, $f3, $bd, $c2, $ab, $51, $06, $98, $84
    // [69] "You found a secret door!" (25→14 bytes)
    .byte $2e, $f6, $f3, $bd, $c2, $ab, $53, $fe, $03, $c6, $ab, $74, $08, $40
    // [70] "You found nothing." (19→11 bytes)
    .byte $2e, $f6, $f3, $bd, $c2, $ae, $34, $61, $9c, $3e, $e4
    // [71] "No door there." (15→9 bytes)
    .byte $9f, $6d, $56, $e8, $51, $87, $87, $b9, $00
    // [72] "The door is already open." (26→15 bytes)
    .byte $9e, $87, $d5, $6e, $85, $c9, $d6, $88, $7b, $29, $eb, $b3, $7e, $1c, $80
    // [73] "It is already closed." (22→13 bytes)
    .byte $9d, $86, $e4, $eb, $44, $3d, $94, $f5, $e2, $3a, $7e, $a7, $20
    // [74] "You open the door." (19→11 bytes)
    .byte $2e, $f6, $ec, $df, $8a, $30, $fa, $ad, $d0, $72, $00
    // [75] "You close the door." (20→11 bytes)
    .byte $2e, $f6, $f1, $1d, $3f, $a3, $0f, $aa, $dd, $07, $20
    // [76] "You fell into a pit!" (21→12 bytes)
    .byte $2e, $f6, $f3, $f1, $8d, $ce, $07, $6b, $59, $b2, $24, $20
    // [77] "An arrow hits you!" (19→11 bytes)
    .byte $91, $62, $b0, $06, $93, $61, $91, $3a, $f6, $f4, $84
    // [78] "A cloud of gas surrounds you!" (30→18 bytes)
    .byte $91, $5e, $23, $bd, $55, $de, $6b, $ec, $74, $fa, $01, $bd, $c2, $8e, $bd, $bd, $21, $00
    // [79] "You are teleported!" (20→11 bytes)
    .byte $2e, $f6, $b0, $7d, $1f, $8f, $cd, $a0, $3e, $a2, $10
    // [80] "A dart hits you!" (17→10 bytes)
    .byte $91, $55, $30, $0d, $86, $44, $eb, $db, $d2, $10
    // [81] "Rocks fall on you!" (19→12 bytes)
    .byte $91, $fb, $c4, $a3, $bc, $b4, $63, $77, $15, $ed, $e9, $08
    // [82] "You take " (10→6 bytes)
    .byte $2e, $f6, $8b, $4a, $fa, $80
    // [83] " damage." (9→6 bytes)
    .byte $aa, $65, $99, $ff, $72, $00
    // [84] "You feel weakened." (19→11 bytes)
    .byte $2e, $f6, $f3, $ff, $1a, $4f, $b4, $af, $c7, $a9, $c8
    // [85] "You feel poisoned." (19→11 bytes)
    .byte $2e, $f6, $f3, $ff, $1b, $36, $e4, $f7, $1e, $a7, $20
    // [86] "You cannot cast spells." (24→14 bytes)
    .byte $2e, $f6, $f0, $d8, $c6, $8d, $e1, $8c, $69, $cd, $f1, $89, $b9, $00
    // [87] "You cannot pray." (17→10 bytes)
    .byte $2e, $f6, $f0, $d8, $c6, $8d, $98, $19, $e7, $20
    // [88] "You don't know that spell." (27→16 bytes)
    .byte $2e, $f6, $ab, $71, $23, $0d, $95, $8d, $26, $8c, $18, $69, $cd, $f1, $8b, $90
    // [89] "You faint from fatigue." (24→14 bytes)
    .byte $2e, $f6, $f2, $d9, $c0, $de, $43, $56, $bc, $b0, $e5, $fe, $fb, $90
    // [90] "You're not experienced enough." (31→19 bytes)
    .byte $2e, $f6, $46, $0f, $b8, $d1, $bf, $3b, $e6, $f0, $cf, $e3, $8f, $55, $fc, $6f, $5f, $83, $90
    // [91] "Your spell fails." (18→11 bytes)
    .byte $2e, $f4, $29, $cd, $f1, $8d, $e5, $b3, $13, $72, $00
    // [92] "Spell book (a-v)?" (18→13 bytes)
    .byte $9d, $4d, $f1, $8d, $93, $bb, $2a, $af, $32, $fc, $b5, $c9, $c4
    // [93] "Prayer book (a-v)?" (19→14 bytes)
    .byte $91, $c0, $cf, $78, $59, $3b, $b2, $aa, $f3, $2f, $cb, $5c, $9c, $40
    // [94] "Monster slows." (15→9 bytes)
    .byte $90, $fb, $83, $1f, $0a, $71, $d2, $4d, $c8
    // [95] "Type?" (6→5 bytes)
    .byte $9e, $7a, $6f, $9c, $40
    // [96] "Cast which? (a-p, ESC)" (23→19 bytes)
    .byte $9d, $cc, $63, $49, $86, $78, $84, $e5, $5e, $65, $f9, $97, $76, $43, $4e, $a7, $72, $e2, $00
    // [97] "Pray which? (a-p, ESC)" (23→19 bytes)
    .byte $91, $c0, $cf, $52, $61, $9e, $21, $39, $57, $99, $7e, $65, $dd, $90, $d3, $a9, $dc, $b8, $80
    // [98] "You feel a little better." (26→14 bytes)
    .byte $2e, $f6, $f3, $ff, $1a, $d6, $39, $11, $8f, $d9, $3e, $23, $e0, $e4
    // [99] "Wear which item (a-v)?" (23→16 bytes)
    .byte $9f, $fd, $82, $93, $0c, $f1, $0b, $91, $f5, $aa, $f3, $2f, $cb, $5c, $9c, $40
    // [100] "Take off which item (a-h)?" (27→18 bytes)
    .byte $9e, $69, $5f, $77, $9e, $69, $30, $cf, $10, $b9, $1f, $5a, $af, $32, $fc, $17, $27, $10
    // [101] "You have nothing there." (24→14 bytes)
    .byte $2e, $f6, $c1, $a5, $fd, $c6, $8c, $33, $87, $e8, $c3, $c3, $dc, $80
    // [102] "Never mind." (12→8 bytes)
    .byte $9f, $7c, $bf, $0a, $b6, $70, $a7, $20
    // [103] "You cannot remove it, it is cursed!" (36→21 bytes)
    .byte $2e, $f6, $f0, $d8, $c6, $8d, $0f, $5b, $65, $fd, $c8, $ae, $ee, $46, $e4, $ef, $1d, $03, $f5, $10, $80
    // [104] "You have no food." (18→10 bytes)
    .byte $2e, $f6, $c1, $a5, $fd, $c6, $de, $77, $54, $e4
    // [105] "You are wielding a " (20→11 bytes)
    .byte $2e, $f6, $b0, $7d, $27, $3f, $15, $67, $0f, $d6, $a8
    // [106] "You are wearing a " (19→10 bytes)
    .byte $2e, $f6, $b0, $7d, $27, $d8, $33, $87, $eb, $54
    // [107] "You take off the " (18→10 bytes)
    .byte $2e, $f6, $8b, $4a, $fb, $bc, $f3, $46, $1f, $50
    // [108] "You eat the " (13→7 bytes)
    .byte $2e, $f6, $fb, $0d, $18, $7d, $40
    // [109] ". Delicious!" (13→9 bytes)
    .byte $75, $5d, $7c, $73, $c6, $77, $a6, $42, $00
    // [110] ". Yuck!" (8→6 bytes)
    .byte $75, $2f, $78, $94, $42, $00
    // [111] "Quaff which potion (a-v)?" (26→18 bytes)
    .byte $90, $7e, $b7, $3c, $d2, $61, $9e, $21, $66, $d1, $ce, $e2, $af, $32, $fc, $b5, $c9, $c4
    // [112] "Read which scroll (a-v)?" (25→17 bytes)
    .byte $91, $fe, $ca, $a4, $c3, $3c, $42, $9f, $01, $b1, $8d, $5e, $65, $f9, $6b, $93, $88
    // [113] "You create food." (17→10 bytes)
    .byte $2e, $f6, $f0, $1e, $c3, $f7, $9d, $d5, $39, $00
    // [114] "You feel yourself moving faster." (33→19 bytes)
    .byte $2e, $f6, $f3, $ff, $1a, $f6, $f4, $0f, $e3, $cd, $5b, $65, $e7, $0f, $de, $58, $c7, $c1, $c8
    // [115] "That tasted terrible!" (22→13 bytes)
    .byte $9e, $83, $0d, $16, $31, $f5, $51, $f0, $0c, $c9, $8f, $90, $80
    // [116] "Nothing seems to happen." (25→15 bytes)
    .byte $9f, $68, $c3, $38, $7e, $9f, $fa, $c7, $47, $6c, $1a, $69, $bf, $0e, $40
    // [117] "The area fills with light." (27→16 bytes)
    .byte $9e, $87, $d6, $0f, $6b, $ce, $63, $13, $a4, $e4, $61, $63, $97, $e0, $2e, $40
    // [118] "Identify which item (a-v)?" (27→19 bytes)
    .byte $9d, $95, $f8, $1c, $f2, $f5, $26, $19, $e2, $17, $23, $eb, $55, $e6, $5f, $96, $b9, $38, $80
    // [119] "This is a " (11→6 bytes)
    .byte $9e, $86, $4e, $e4, $eb, $54
    // [120] "You feel disoriented." (22→13 bytes)
    .byte $2e, $f6, $f3, $ff, $1a, $ac, $9e, $86, $7f, $03, $ea, $72, $00
    // [121] "You feel much better." (22→13 bytes)
    .byte $2e, $f6, $f3, $ff, $1a, $b7, $78, $85, $93, $e2, $3e, $0e, $40
    // [122] "Your mind feels clear." (23→13 bytes)
    .byte $2e, $f4, $2a, $d9, $c2, $af, $3f, $f1, $3b, $c4, $7d, $81, $c8
    // [123] "You feel heroic!" (17→10 bytes)
    .byte $2e, $f6, $f3, $ff, $1b, $0f, $0d, $cf, $04, $20
    // [124] "You can't see!" (15→9 bytes)
    .byte $2e, $f6, $f0, $d8, $91, $86, $9f, $f9, $08
    // [125] "You feel dizzy." (16→11 bytes)
    .byte $2e, $f6, $f3, $ff, $1a, $ac, $cf, $d3, $f3, $ce, $40
    // [126] "You sense nearby creatures." (28→16 bytes)
    .byte $2e, $f6, $9f, $e0, $fe, $e3, $d8, $24, $bd, $78, $0f, $61, $e8, $79, $b9, $00
    // [127] "Your eyes tingle." (18→10 bytes)
    .byte $2e, $f4, $2f, $bd, $e7, $47, $38, $7e, $3e, $e4
    // [128] "The air crackles around you." (29→17 bytes)
    .byte $9e, $87, $d6, $c8, $5e, $01, $b8, $95, $1f, $3a, $c1, $bd, $c2, $ab, $db, $d7, $20
    // [129] "You feel cleansed." (19→11 bytes)
    .byte $2e, $f6, $f3, $ff, $1b, $c4, $7d, $b0, $7e, $a7, $20
    // [130] "There is already an object under you." (38→23 bytes)
    .byte $9e, $87, $87, $dc, $9d, $68, $87, $b2, $9e, $ad, $8b, $b2, $64, $1b, $f8, $1b, $dc, $2b, $c2, $bd, $bd, $72, $00
    // [131] "You see a strange rune." (24→13 bytes)
    .byte $2e, $f6, $9f, $fd, $6a, $62, $0d, $87, $fe, $87, $71, $ee, $40
    // [132] "Your weapon glows briefly." (27→16 bytes)
    .byte $2e, $f4, $29, $3e, $d3, $6e, $2b, $f1, $d2, $4e, $c9, $0c, $ff, $31, $79, $c8
    // [133] "Your armor glows briefly." (26→15 bytes)
    .byte $2e, $f4, $2b, $02, $da, $15, $f8, $e9, $27, $64, $86, $7f, $98, $bc, $e4
    // [134] "Your hands begin to glow." (26→15 bytes)
    .byte $2e, $f4, $2c, $1b, $0a, $3b, $27, $df, $ce, $28, $ed, $7e, $3a, $4b, $90
    // [135] "You hear a high-pitched humming." (33→20 bytes)
    .byte $2e, $f6, $c3, $d8, $2b, $58, $65, $f8, $2f, $cd, $91, $e2, $1e, $ab, $0e, $ac, $b6, $70, $fb, $90
    // [136] "You feel protected." (20→12 bytes)
    .byte $2e, $f6, $f3, $ff, $1b, $30, $68, $ff, $03, $ea, $72, $00
    // [137] "You feel a strange vibration." (30→17 bytes)
    .byte $2e, $f6, $f3, $ff, $1a, $d4, $c4, $1b, $0f, $fd, $97, $99, $20, $c3, $9d, $c3, $90
    // [138] "Aim which wand (a-v)?" (22→16 bytes)
    .byte $91, $65, $6a, $4c, $33, $c4, $29, $2d, $85, $55, $e6, $5f, $96, $b9, $38, $80
    // [139] "Use which staff (a-v)?" (23→16 bytes)
    .byte $90, $87, $f4, $98, $67, $88, $53, $16, $e7, $9a, $bc, $cb, $f2, $d7, $27, $10
    // [140] "No charges left." (17→10 bytes)
    .byte $9f, $6d, $e2, $0c, $0f, $f9, $d8, $ff, $22, $e4
    // [141] "The staff is empty." (20→12 bytes)
    .byte $9e, $87, $d3, $16, $e7, $9b, $93, $be, $b4, $c2, $f3, $90
    // [142] "A bolt of lightning shoots forth!" (34→20 bytes)
    .byte $91, $59, $3b, $11, $bb, $cd, $8e, $5f, $80, $e3, $38, $7e, $9c, $37, $44, $ef, $3a, $03, $02, $10
    // [143] "A bolt of frost shoots forth!" (30→17 bytes)
    .byte $91, $59, $3b, $11, $bb, $cd, $e4, $34, $c6, $9c, $37, $44, $ef, $3a, $03, $02, $10
    // [144] "The monster looks confused." (28→17 bytes)
    .byte $9e, $87, $d5, $b7, $06, $3e, $16, $3b, $b2, $8e, $f1, $b8, $e7, $a7, $ea, $72, $00
    // [145] "The cloud dissipates." (22→13 bytes)
    .byte $9e, $87, $de, $23, $bd, $55, $56, $4c, $f3, $33, $0f, $9b, $90
    // [146] "You can't see to read!" (23→13 bytes)
    .byte $2e, $f6, $f0, $d8, $91, $86, $9f, $fd, $1d, $a1, $ec, $a2, $10
    // [147] "Study which book (a-v)?" (24→17 bytes)
    .byte $9d, $0f, $54, $f5, $26, $19, $e2, $16, $4e, $ec, $aa, $bc, $cb, $f2, $d7, $27, $10
    // [148] "You cannot use magic." (22→13 bytes)
    .byte $2e, $f6, $f0, $d8, $c6, $8d, $e9, $fd, $59, $9f, $cf, $0e, $40
    // [149] "You cannot read that book." (27→15 bytes)
    .byte $2e, $f6, $f0, $d8, $c6, $8d, $0f, $65, $51, $83, $0d, $93, $bb, $29, $c8
    // [150] "You learn from the book!" (25→15 bytes)
    .byte $2e, $f6, $c7, $d8, $31, $79, $0d, $5a, $8c, $3e, $c9, $dd, $94, $42, $00
    // [151] "No new spells to learn." (24→14 bytes)
    .byte $9f, $6d, $c7, $93, $4e, $6f, $8c, $4e, $8e, $d8, $fb, $06, $1c, $80
    // [152] "Not using a lamp." (18→11 bytes)
    .byte $9f, $68, $de, $9e, $70, $fd, $6b, $16, $5a, $67, $20
    // [153] "You have no oil." (17→10 bytes)
    .byte $2e, $f6, $c1, $a5, $fd, $c6, $dd, $cc, $5c, $80
    // [154] "Your lamp overflows." (21→13 bytes)
    .byte $2e, $f4, $2c, $59, $69, $ae, $cb, $f0, $e6, $3a, $49, $b9, $00
    // [155] "Your lamp is full." (19→11 bytes)
    .byte $2e, $f4, $2c, $59, $69, $ae, $4e, $f3, $d8, $c5, $c8
    // [156] "Your lamp is refueled." (23→13 bytes)
    .byte $2e, $f4, $2c, $59, $69, $ae, $4e, $87, $f3, $df, $8f, $a9, $c8
    // [157] "Welcome to level " (18→11 bytes)
    .byte $9f, $fe, $3c, $6a, $df, $47, $6c, $7e, $5f, $c6, $a0
    // [158] "Your pack is full." (19→12 bytes)
    .byte $2e, $f4, $2c, $cd, $c4, $ab, $93, $bc, $f6, $31, $72, $00
    // [159] "You dig in the granite wall." (29→17 bytes)
    .byte $2e, $f6, $ab, $2f, $dc, $e2, $8c, $3e, $be, $0d, $8c, $8f, $d2, $5a, $31, $72, $00
    // [160] "You dig in the magma." (22→13 bytes)
    .byte $2e, $f6, $ab, $2f, $dc, $e2, $8c, $3e, $ac, $cf, $ac, $ce, $40
    // [161] "You dig in the quartz vein." (28→18 bytes)
    .byte $2e, $f6, $ab, $2f, $dc, $e2, $8c, $3e, $c8, $2f, $58, $06, $7e, $b2, $ff, $38, $72, $00
    // [162] "You have finished the tunnel." (30→17 bytes)
    .byte $2e, $f6, $c1, $a5, $fd, $e7, $38, $c9, $c3, $d5, $46, $1f, $47, $b8, $c7, $c5, $c8
    // [163] "You have found something!" (26→16 bytes)
    .byte $2e, $f6, $c1, $a5, $fd, $e7, $7b, $85, $53, $d5, $bc, $61, $9c, $3e, $42, $00
    // [164] "This seems to be permanent rock." (33→19 bytes)
    .byte $9e, $86, $4e, $9f, $fa, $c7, $47, $6c, $9f, $b3, $78, $2c, $d8, $fc, $0d, $0d, $e2, $53, $90
    // [165] "There is nothing to tunnel here." (33→19 bytes)
    .byte $9e, $87, $87, $dc, $9d, $c6, $8c, $33, $87, $e8, $ed, $1e, $e3, $1f, $1b, $0f, $0f, $72, $00
    // [166] "The rubble crumbles." (21→14 bytes)
    .byte $9e, $87, $d0, $ec, $99, $31, $fb, $c0, $75, $69, $31, $f3, $72, $00
    // [167] "You dig with your hands, making no progress." (45→27 bytes)
    .byte $2e, $f6, $ab, $2f, $d2, $72, $30, $af, $6f, $42, $c1, $b0, $a3, $5d, $d5, $9a, $56, $70, $fd, $c6, $d9, $83, $5f, $0f, $33, $72, $00
    // [168] "You see nothing here." (22→12 bytes)
    .byte $2e, $f6, $9f, $fd, $c6, $8c, $33, $87, $ec, $3c, $3d, $c8
    // [169] "You found " (11→7 bytes)
    .byte $2e, $f6, $f3, $bd, $c2, $aa, $00
    // [170] " gold pieces." (14→8 bytes)
    .byte $af, $ec, $55, $66, $cf, $f1, $e6, $e4
    // [171] "You picked up a " (17→10 bytes)
    .byte $2e, $f6, $cd, $9e, $25, $7a, $af, $66, $ad, $50
    // [172] "Drop which item (a-v)?" (23→16 bytes)
    .byte $5d, $06, $cd, $49, $86, $78, $85, $c8, $fa, $d5, $79, $97, $e5, $ae, $4e, $20
    // [173] "You drop a " (12→7 bytes)
    .byte $2e, $f6, $a8, $36, $6a, $d5, $00
    // [174] "No room on the floor." (22→13 bytes)
    .byte $9f, $6d, $0d, $d5, $ae, $e2, $8c, $3e, $f3, $1d, $d0, $72, $00
    // [175] "Saving game..." (15→10 bytes)
    .byte $9d, $34, $bc, $e1, $fa, $fb, $2d, $ee, $73, $90
    // [176] "Game saved." (12→8 bytes)
    .byte $90, $46, $5b, $e9, $b4, $bf, $53, $90
    // [177] "Loading game..." (16→11 bytes)
    .byte $90, $3d, $65, $67, $0f, $d7, $d9, $6f, $73, $9c, $80
    // [178] "Save file not found." (21→13 bytes)
    .byte $9d, $34, $bf, $bc, $e6, $3f, $71, $a3, $79, $de, $e1, $4e, $40
    // [179] "Save file corrupt!" (19→12 bytes)
    .byte $9d, $34, $bf, $bc, $e6, $3f, $78, $d0, $0e, $cc, $24, $20
    // [180] "Unsupported save." (18→12 bytes)
    .byte $90, $98, $3e, $cd, $36, $80, $fa, $a9, $b4, $bf, $72, $00
    // [181] "Disk error!" (12→8 bytes)
    .byte $5d, $64, $e5, $5f, $00, $d0, $21, $00
    // [182] "Welcome back to Moria8!" (24→17 bytes)
    .byte $9f, $fe, $3c, $6a, $df, $64, $b7, $12, $a8, $ed, $90, $fa, $19, $69, $02, $21, $00
    // [183] "Need Save Disk." (16→11 bytes)
    .byte $9f, $7f, $aa, $ce, $9a, $5f, $d5, $d6, $4e, $53, $90
    // [184] "Wrong Save Disk." (17→12 bytes)
    .byte $9f, $c3, $70, $fd, $9d, $34, $bf, $ab, $ac, $9c, $a7, $20
    // [185] "Overwrite? Y/N" (15→12 bytes)
    .byte $90, $19, $7e, $04, $86, $47, $e7, $29, $64, $02, $7c, $80
    // [186] "You smash into the door!" (25→14 bytes)
    .byte $2e, $f6, $9a, $cc, $70, $b9, $c0, $ed, $18, $7d, $56, $e8, $10, $80
    // [187] "The door crashes open!" (23→13 bytes)
    .byte $9e, $87, $d5, $6e, $85, $e0, $18, $e1, $e7, $76, $6f, $c1, $08
    // [188] "The door holds firm." (21→12 bytes)
    .byte $9e, $87, $d5, $6e, $85, $86, $c5, $47, $79, $c8, $2c, $e4
    // [189] "You are off balance." (21→12 bytes)
    .byte $2e, $f6, $b0, $7d, $de, $79, $b2, $5a, $2d, $8e, $3d, $c8
    // [190] "You bash at empty space." (25→15 bytes)
    .byte $2e, $f6, $c9, $63, $85, $61, $be, $b4, $c2, $f5, $39, $9b, $8f, $72, $00
    // [191] " appears stunned!" (18→10 bytes)
    .byte $ad, $34, $de, $c0, $74, $c7, $b8, $c7, $a8, $84
    // [192] " ignores your bash!" (20→12 bytes)
    .byte $b9, $7f, $1a, $1e, $75, $ed, $e8, $59, $2c, $70, $21, $00
    // [193] "You feel very good." (20→12 bytes)
    .byte $2e, $f6, $f3, $ff, $1b, $2f, $c1, $ea, $fe, $ea, $9c, $80
    // [194] "You sense magik on what you carry." (35→20 bytes)
    .byte $2e, $f6, $9f, $e0, $fe, $ac, $cf, $e6, $55, $dc, $52, $60, $c3, $5e, $de, $de, $18, $01, $e7, $20
    // [195] "You feel your strength return." (31→17 bytes)
    .byte $2e, $f6, $f3, $ff, $1a, $f6, $f4, $29, $88, $7e, $1f, $18, $50, $f1, $e8, $61, $c8
    // [196] "You have discovered a trap on the chest!" (41→23 bytes)
    .byte $2e, $f6, $c1, $a5, $fd, $56, $4f, $8d, $97, $e1, $ea, $ad, $44, $1a, $6b, $b8, $a3, $0f, $bc, $43, $cc, $48, $40
    // [197] "The chest is trapped!" (22→13 bytes)
    .byte $9e, $87, $de, $21, $e6, $37, $27, $44, $1a, $69, $bd, $44, $20
    // [198] "A small needle has pricked you!" (32→19 bytes)
    .byte $91, $53, $59, $a3, $1b, $8f, $f5, $47, $ec, $18, $ec, $c1, $9e, $25, $7a, $ab, $db, $d2, $10
    // [199] "You feel weakened!" (19→11 bytes)
    .byte $2e, $f6, $f3, $ff, $1a, $4f, $b4, $af, $c7, $a8, $84
    // [200] "A puff of yellow gas surrounds you!" (36→22 bytes)
    .byte $91, $59, $bb, $cf, $37, $79, $af, $7c, $63, $a4, $d7, $d8, $e9, $f4, $03, $7b, $85, $1d, $7b, $7a, $42, $00
    // [201] "You are unaffected." (20→12 bytes)
    .byte $2e, $f6, $b0, $7d, $ee, $1b, $9e, $7f, $81, $f5, $39, $00
    // [202] "You choke and pass out." (24→14 bytes)
    .byte $2e, $f6, $f1, $0d, $95, $f5, $b0, $ab, $33, $19, $dd, $e8, $b9, $00
    // [203] "There is a sudden explosion!" (29→17 bytes)
    .byte $9e, $87, $87, $dc, $9d, $6a, $7d, $52, $bf, $17, $e7, $7c, $d1, $d3, $ce, $e0, $84
    // [204] "You have picked the lock." (26→16 bytes)
    .byte $2e, $f6, $c1, $a5, $fd, $9b, $3c, $4a, $f5, $51, $87, $d8, $ef, $12, $9c, $80
    // [205] "You are too confused to pick the lock." (39→22 bytes)
    .byte $2e, $f6, $b0, $7d, $1d, $db, $c6, $e3, $9e, $9f, $aa, $8e, $d9, $b3, $c4, $aa, $30, $fb, $1d, $e2, $53, $90
    // [206] "You failed to pick the lock." (29→17 bytes)
    .byte $2e, $f6, $f2, $d9, $8f, $aa, $8e, $d9, $b3, $c4, $aa, $30, $fb, $1d, $e2, $53, $90
    // [207] "a poison needle." (17→10 bytes)
    .byte $6b, $36, $e4, $f7, $17, $1f, $ea, $8f, $b9, $00
    // [208] "an exploding chest." (20→13 bytes)
    .byte $6c, $5f, $9d, $f3, $47, $55, $9c, $3f, $78, $87, $98, $b9, $00

// Huffman code table:
//   NULL   =         0100 (4 bits, freq=209)
//   a      =         0110 (4 bits, freq=253)
//   b      =      1001001 (7 bits, freq=37)
//   c      =       111000 (6 bits, freq=90)
//   d      =        01010 (5 bits, freq=113)
//   e      =         1111 (4 bits, freq=383)
//   f      =       111001 (6 bits, freq=92)
//   g      =       011111 (6 bits, freq=68)
//   h      =        10000 (5 bits, freq=146)
//   i      =        11001 (5 bits, freq=175)
//   j      = 100100000110 (12 bits, freq=1)
//   k      =      1001010 (7 bits, freq=39)
//   l      =        10001 (5 bits, freq=147)
//   m      =       010110 (6 bits, freq=57)
//   n      =        11000 (5 bits, freq=168)
//   o      =         1101 (4 bits, freq=362)
//   p      =       100110 (6 bits, freq=80)
//   q      = 100100000101 (12 bits, freq=1)
//   r      =         0000 (4 bits, freq=193)
//   s      =         0011 (4 bits, freq=203)
//   t      =         0001 (4 bits, freq=201)
//   u      =        11101 (5 bits, freq=192)
//   v      =      1001011 (7 bits, freq=40)
//   w      =       001001 (6 bits, freq=51)
//   x      =  10011101111 (11 bits, freq=3)
//   y      =       011110 (6 bits, freq=60)
//   z      =   1001111110 (10 bits, freq=6)
//   SPACE  =          101 (3 bits, freq=631)
//   $21    =       001000 (6 bits, freq=48)
//   $27    =   1001000110 (10 bits, freq=4)
//   $28    =     01011110 (8 bits, freq=14)
//   $29    =     01011100 (8 bits, freq=14)
//   $2c    =    010111011 (9 bits, freq=7)
//   $2d    =     01011111 (8 bits, freq=15)
//   $2e    =        01110 (5 bits, freq=127)
//   $2f    = 100100000000 (12 bits, freq=1)
//   $38    = 100100000010 (12 bits, freq=1)
//   $3f    =     10011100 (8 bits, freq=21)
//   A      =    100100010 (9 bits, freq=8)
//   C      =  10011101110 (11 bits, freq=3)
//   D      =    010111010 (9 bits, freq=7)
//   E      =  10010000110 (11 bits, freq=2)
//   G      = 100100000100 (12 bits, freq=1)
//   H      =  10010000101 (11 bits, freq=2)
//   I      =   1001110110 (10 bits, freq=5)
//   L      = 100100000011 (12 bits, freq=1)
//   M      =  10010000111 (11 bits, freq=2)
//   N      =    100111110 (9 bits, freq=11)
//   O      = 100100000001 (12 bits, freq=1)
//   P      =  10010001110 (11 bits, freq=2)
//   Q      = 100100000111 (12 bits, freq=1)
//   R      =  10010001111 (11 bits, freq=3)
//   S      =    100111010 (9 bits, freq=10)
//   T      =     10011110 (8 bits, freq=22)
//   U      =  10010000100 (11 bits, freq=2)
//   W      =   1001111111 (10 bits, freq=6)
//   Y      =        00101 (5 bits, freq=103)
