// huffman_data.s — Generated by huff_encoder.py
// Source: data/huffman_strings.txt
// 218 strings, 4670 bytes uncompressed
// 2802 bytes compressed (60.0%)
// Tree: 112 bytes, Index: 436 bytes
// Total data: 3350 bytes

.const HUFF_STR_COUNT = 218
.const HSTR_INSULT_COUNT = 15

// Named string constants
.const HSTR_MAT_HITS = 15
.const HSTR_MAT_MISS = 16
.const HSTR_MAT_POISON = 17
.const HSTR_MAT_CONFUSE = 18
.const HSTR_MAT_PARALYZE = 19
.const HSTR_MAT_ACID = 20
.const HSTR_MAT_FEAR = 21
.const HSTR_MAT_SHRIEK = 22
.const HSTR_MM_BOLT = 23
.const HSTR_MM_BREATH = 24
.const HSTR_MM_SUMMON = 25
.const HSTR_MM_TELEPORT = 26
.const HSTR_MM_BLIND = 27
.const HSTR_MM_CONFUSE = 28
.const HSTR_MM_HEAL = 29
.const HSTR_RF_NO_WEAPON = 30
.const HSTR_RF_NO_AMMO = 31
.const HSTR_RF_FLIES = 32
.const HSTR_RF_MISSES = 33
.const HSTR_RF_HITS = 34
.const HSTR_EB_SPELL_HITS = 35
.const HSTR_EB_FIZZLE = 36
.const HSTR_TW_PROMPT = 37
.const HSTR_TW_SHATTERS = 38
.const HSTR_EFF_POISON_END = 39
.const HSTR_EFF_BLIND_END = 40
.const HSTR_EFF_CONFUSE_END = 41
.const HSTR_EFF_PARALYZE_END = 42
.const HSTR_EFF_FEAR_END = 43
.const HSTR_EFF_HASTE_END = 44
.const HSTR_EFF_SLOW_END = 45
.const HSTR_TTL_DIM = 46
.const HSTR_TTL_OUT = 47
.const HSTR_RECALL_ARRIVE = 48
.const HSTR_DL_YOU_SEE = 49
.const HSTR_DL_OPEN_DOOR = 50
.const HSTR_DL_CLOSED_DOOR = 51
.const HSTR_DL_STAIRS_DN = 52
.const HSTR_DL_STAIRS_UP = 53
.const HSTR_DL_TRAP = 54
.const HSTR_DL_RUBBLE = 55
.const HSTR_DL_WALL = 56
.const HSTR_DL_NOTHING = 57
.const HSTR_PTM_AFRAID = 58
.const HSTR_DF_TRAP_0 = 59
.const HSTR_DF_TRAP_1 = 60
.const HSTR_DF_TRAP_2 = 61
.const HSTR_DF_TRAP_3 = 62
.const HSTR_DF_TRAP_4 = 63
.const HSTR_DF_TRAP_5 = 64
.const HSTR_DF_DEATH_ROCKFALL = 65
.const HSTR_DF_DIRECTION = 66
.const HSTR_DF_DOOR_STUCK = 67
.const HSTR_DF_FOUND_TRAP = 68
.const HSTR_DF_FOUND_SECRET = 69
.const HSTR_DF_FOUND_NOTHING = 70
.const HSTR_DF_NO_DOOR = 71
.const HSTR_DF_ALREADY_OPEN = 72
.const HSTR_DF_ALREADY_CLOSED = 73
.const HSTR_DF_DOOR_OPENED = 74
.const HSTR_DF_DOOR_CLOSED = 75
.const HSTR_DF_YOU_FELL = 76
.const HSTR_DF_ARROW_HITS = 77
.const HSTR_DF_POISON_GAS = 78
.const HSTR_DF_TELEPORTED = 79
.const HSTR_DF_DART_HITS = 80
.const HSTR_DF_ROCKFALL = 81
.const HSTR_DF_DAMAGE_PRE = 82
.const HSTR_DF_DAMAGE_POST = 83
.const HSTR_DF_CON_DRAIN = 84
.const HSTR_DF_POISONED = 85
.const HSTR_PM_NO_CAST = 86
.const HSTR_PM_NO_PRAY = 87
.const HSTR_PM_NOT_KNOWN = 88
.const HSTR_PM_NO_MANA = 89
.const HSTR_PM_NO_EXP = 90
.const HSTR_PM_FAIL = 91
.const HSTR_PM_YOU_CAST = 92
.const HSTR_PM_YOU_PRAY = 93
.const HSTR_PM_TITLE_MAGE = 94
.const HSTR_PM_TITLE_PRAY = 95
.const HSTR_PM_FOOTER_CAST = 96
.const HSTR_PM_FOOTER_PRAY = 97
.const HSTR_PIQ_LITTLE_BETTER = 98
.const HSTR_PIW_WEAR_PROMPT = 99
.const HSTR_PIW_TAKEOFF_PROMPT = 100
.const HSTR_PIW_NOTHING = 101
.const HSTR_PIW_NEVERMIND = 102
.const HSTR_PIW_CURSED = 103
.const HSTR_PIW_NO_FOOD = 104
.const HSTR_PIW_WIELD = 105
.const HSTR_PIW_WEARING = 106
.const HSTR_PIW_TAKEOFF = 107
.const HSTR_PIW_EAT = 108
.const HSTR_PIW_DELICIOUS = 109
.const HSTR_PIW_YUCK = 110
.const HSTR_PIQ_QUAFF_PROMPT = 111
.const HSTR_PIQ_READ_PROMPT = 112
.const HSTR_PMU_CREATE_FOOD = 113
.const HSTR_PIQ_SPEED = 114
.const HSTR_PIQ_TERRIBLE = 115
.const HSTR_PIQ_NOTHING = 116
.const HSTR_PIQ_LIGHT = 117
.const HSTR_PIQ_IDENTIFY_PROMPT = 118
.const HSTR_PIQ_THISIS = 119
.const HSTR_PIQ_TELEPORT = 120
.const HSTR_PIQ_MUCH_BETTER = 121
.const HSTR_PIQ_MIND_CLEAR = 122
.const HSTR_PIQ_HEROIC = 123
.const HSTR_PIQ_CANT_SEE = 124
.const HSTR_PIQ_DIZZY = 125
.const HSTR_PIQ_SENSE = 126
.const HSTR_PIQ_EYES_TINGLE = 127
.const HSTR_PIQ_AIR_CRACKLE = 128
.const HSTR_PIQ_CLEANSED = 129
.const HSTR_PMU_GLYPH_BLOCK = 130
.const HSTR_PMU_GLYPH_OK = 131
.const HSTR_PIQ_WPN_GLOW = 132
.const HSTR_PIQ_ARM_GLOW = 133
.const HSTR_PIQ_HANDS_GLOW = 134
.const HSTR_PIQ_HUMMING = 135
.const HSTR_PIQ_PROTECTED = 136
.const HSTR_PIQ_VIBRATION = 137
.const HSTR_PIW_AIM_PROMPT = 138
.const HSTR_PIW_USE_PROMPT = 139
.const HSTR_PIW_NO_CHARGES = 140
.const HSTR_PIW_STAFF_EMPTY = 141
.const HSTR_PIW_WAND_BOLT = 142
.const HSTR_PIW_WAND_FROST = 143
.const HSTR_PIW_WAND_CLOUD = 144
.const HSTR_PIW_WAND_MISS = 145
.const HSTR_PIQ_CANT_READ = 146
.const HSTR_IGS_PROMPT = 147
.const HSTR_IGS_NO_MAGIC = 148
.const HSTR_IGS_WRONG_TYPE = 149
.const HSTR_IGS_SUCCESS = 150
.const HSTR_IGS_NO_NEW = 151
.const HSTR_PIR_NOT_LAMP = 152
.const HSTR_PIR_NO_OIL = 153
.const HSTR_PIR_OVERFLOW = 154
.const HSTR_PIR_FULL = 155
.const HSTR_PIR_REFUELED = 156
.const HSTR_CMB_LVLUP = 157
.const HSTR_UIS_PACK_FULL = 158
.const HSTR_TUN_DIG_GRANITE = 159
.const HSTR_TUN_DIG_MAGMA = 160
.const HSTR_TUN_DIG_QUARTZ = 161
.const HSTR_TUN_FINISHED = 162
.const HSTR_TUN_FOUND = 163
.const HSTR_TUN_PERMANENT = 164
.const HSTR_TUN_NOTHING = 165
.const HSTR_TUN_RUBBLE = 166
.const HSTR_TUN_NO_TOOL = 167
.const HSTR_IPU_NOTHING = 168
.const HSTR_IPU_FOUND = 169
.const HSTR_IPU_GOLD = 170
.const HSTR_IPU_PICKED = 171
.const HSTR_IDR_PROMPT = 172
.const HSTR_IDR_DROP = 173
.const HSTR_IDR_FLOOR_FULL = 174
.const HSTR_SAVE_SAVING = 175
.const HSTR_SAVE_DONE = 176
.const HSTR_SAVE_LOADING = 177
.const HSTR_SAVE_NOTFOUND = 178
.const HSTR_SAVE_CORRUPT = 179
.const HSTR_SAVE_UNSUPPORTED = 180
.const HSTR_SAVE_IOERR = 181
.const HSTR_SAVE_WELCOME = 182
.const HSTR_SAVE_NEED_SAVE = 183
.const HSTR_SAVE_BAD_SAVE = 184
.const HSTR_SAVE_OVERWRITE = 185
.const HSTR_BASH_SMASH = 186
.const HSTR_BASH_CRASH = 187
.const HSTR_BASH_HOLDS = 188
.const HSTR_BASH_OFFBAL = 189
.const HSTR_BASH_EMPTY = 190
.const HSTR_BASH_STUNNED = 191
.const HSTR_BASH_IGNORES = 192
.const HSTR_PIQ_VERY_GOOD = 193
.const HSTR_PID_CARRY = 194
.const HSTR_PIQ_RESTORED = 195
.const HSTR_CHEST_FOUND_TRAP = 196
.const HSTR_CHEST_TRAPPED = 197
.const HSTR_CHEST_NEEDLE = 198
.const HSTR_CHEST_WEAKENED = 199
.const HSTR_CHEST_GAS = 200
.const HSTR_CHEST_UNAFFECTED = 201
.const HSTR_CHEST_CHOKE = 202
.const HSTR_CHEST_EXPLOSION = 203
.const HSTR_CHEST_PICKED = 204
.const HSTR_CHEST_PICK_CONFUSED = 205
.const HSTR_CHEST_PICK_FAIL = 206
.const HSTR_CHEST_DEATH_NEEDLE = 207
.const HSTR_CHEST_DEATH_EXPLODING = 208
.const HSTR_CHEST_DISARM_UNFOUND = 209
.const HSTR_CHEST_DISARM_NOT_TRAPPED = 210
.const HSTR_CHEST_DISARMED = 211
.const HSTR_CHEST_DISARM_FAIL = 212
.const HSTR_CHEST_DISARM_SET_OFF = 213
.const HSTR_CHEST_DESTROYED = 214
.const HSTR_CHEST_DESTROYED_CONTENTS = 215
.const HSTR_CHEST_LOCK_BREAKS = 216
.const HSTR_CHEST_HOLDS_FIRM = 217

// Huffman tree: 56 internal nodes
// Children: $00-$7E = node index, $80+ = leaf (& $7F = screencode)
huff_tree_left:
    .byte $01, $03, $05, $07, $09, $0b, $0c, $92, $80, $94, $81, $11, $13, $14, $15, $16, $17, $8c, $88, $19, $1a, $a1, $1b, $99, $1c, $90, $86, $1f, $21, $8b, $22, $24, $a8, $25, $bf, $28, $c4, $29, $c1, $ce, $2c, $2e, $30, $32, $d7, $33, $34, $36, $d5, $c5, $d0, $c3, $af, $b8, $c7, $8a
huff_tree_right:
    .byte $02, $04, $06, $08, $0a, $a0, $0d, $0e, $93, $0f, $10, $12, $8f, $85, $d9, $84, $ae, $18, $8e, $89, $95, $97, $8d, $87, $1d, $1e, $83, $20, $82, $96, $23, $a9, $ad, $26, $27, $d4, $ac, $2a, $d3, $2b, $2d, $2f, $31, $a7, $c9, $9a, $35, $37, $c8, $cd, $d2, $98, $cf, $cc, $91, $d1

// String index: 16-bit byte offsets into huff_str_data
huff_str_index:
    .word $0000  // [0] "You will have to do better tha"
    .word $0015  // [1] "That is an insult!"
    .word $0020  // [2] "Do you wish to do business or "
    .word $0034  // [3] "Hah! Try again."
    .word $003f  // [4] "Ridiculous!"
    .word $0048  // [5] "You have got to be kidding!"
    .word $0059  // [6] "You had better be kidding!"
    .word $0069  // [7] "You try my patience."
    .word $0075  // [8] "I do not hear you."
    .word $0080  // [9] "Hmmm, nice weather we are havi"
    .word $0095  // [10] "I must have heard you wrong."
    .word $00a6  // [11] "What was that?"
    .word $00af  // [12] "I am sorry, say that again."
    .word $00c0  // [13] "What did you say?"
    .word $00cb  // [14] "Sorry, what was that again?"
    .word $00dc  // [15] @MAT_HITS " hits you."
    .word $00e2  // [16] @MAT_MISS " misses you."
    .word $00ea  // [17] @MAT_POISON " poisons you."
    .word $00f2  // [18] @MAT_CONFUSE " confuses you."
    .word $00fb  // [19] @MAT_PARALYZE " paralyzes you."
    .word $0105  // [20] @MAT_ACID " spits acid on you."
    .word $0110  // [21] @MAT_FEAR " frightens you."
    .word $011a  // [22] @MAT_SHRIEK "You hear a horrible shriek!"
    .word $012a  // [23] @MM_BOLT " casts a bolt!"
    .word $0133  // [24] @MM_BREATH " breathes fire!"
    .word $013c  // [25] @MM_SUMMON " summons help!"
    .word $0145  // [26] @MM_TELEPORT " teleports you!"
    .word $014e  // [27] @MM_BLIND " blinds you!"
    .word $0156  // [28] @MM_CONFUSE " confuses you!"
    .word $015f  // [29] @MM_HEAL " heals itself."
    .word $0168  // [30] @RF_NO_WEAPON "No ranged weapon."
    .word $0173  // [31] @RF_NO_AMMO "No ammo."
    .word $0179  // [32] @RF_FLIES " flies away."
    .word $0181  // [33] @RF_MISSES " misses"
    .word $0186  // [34] @RF_HITS " hits"
    .word $018a  // [35] @EB_SPELL_HITS "Your spell hits"
    .word $0193  // [36] @EB_FIZZLE "Your spell fizzles out."
    .word $01a2  // [37] @TW_PROMPT "Throw which item (a-v)?"
    .word $01b3  // [38] @TW_SHATTERS " shatters!"
    .word $01b9  // [39] @EFF_POISON_END "You feel better."
    .word $01c3  // [40] @EFF_BLIND_END "You can see again."
    .word $01ce  // [41] @EFF_CONFUSE_END "You feel less confused."
    .word $01dc  // [42] @EFF_PARALYZE_END "You can move again."
    .word $01e8  // [43] @EFF_FEAR_END "You feel bolder now."
    .word $01f4  // [44] @EFF_HASTE_END "You feel yourself slow down."
    .word $0205  // [45] @EFF_SLOW_END "You feel yourself speed up."
    .word $0215  // [46] @TTL_DIM "Your light is growing dim."
    .word $0225  // [47] @TTL_OUT "Your light has gone out."
    .word $0233  // [48] @RECALL_ARRIVE "You feel yourself yanked away!"
    .word $0245  // [49] @DL_YOU_SEE "You see a "
    .word $024b  // [50] @DL_OPEN_DOOR "You see an open door."
    .word $0257  // [51] @DL_CLOSED_DOOR "You see a closed door."
    .word $0263  // [52] @DL_STAIRS_DN "You see a staircase down."
    .word $0271  // [53] @DL_STAIRS_UP "You see a staircase up."
    .word $027e  // [54] @DL_TRAP "You see a trap."
    .word $0287  // [55] @DL_RUBBLE "You see rubble."
    .word $0291  // [56] @DL_WALL "You see a wall."
    .word $029a  // [57] @DL_NOTHING "You see nothing special."
    .word $02a8  // [58] @PTM_AFRAID "You are too afraid!"
    .word $02b3  // [59] @DF_TRAP_0 "an open pit"
    .word $02ba  // [60] @DF_TRAP_1 "an arrow trap"
    .word $02c2  // [61] @DF_TRAP_2 "a poison gas trap"
    .word $02cc  // [62] @DF_TRAP_3 "a teleport trap"
    .word $02d5  // [63] @DF_TRAP_4 "a poison dart"
    .word $02dd  // [64] @DF_TRAP_5 "a rockfall trap"
    .word $02e7  // [65] @DF_DEATH_ROCKFALL "falling rock."
    .word $02f0  // [66] @DF_DIRECTION "Direction?"
    .word $02f8  // [67] @DF_DOOR_STUCK "The door is stuck."
    .word $0303  // [68] @DF_FOUND_TRAP "You found a trap!"
    .word $030d  // [69] @DF_FOUND_SECRET "You found a secret door!"
    .word $031b  // [70] @DF_FOUND_NOTHING "You found nothing."
    .word $0326  // [71] @DF_NO_DOOR "No door there."
    .word $032f  // [72] @DF_ALREADY_OPEN "The door is already open."
    .word $033e  // [73] @DF_ALREADY_CLOSED "It is already closed."
    .word $034b  // [74] @DF_DOOR_OPENED "You open the door."
    .word $0356  // [75] @DF_DOOR_CLOSED "You close the door."
    .word $0361  // [76] @DF_YOU_FELL "You fell into a pit!"
    .word $036d  // [77] @DF_ARROW_HITS "An arrow hits you!"
    .word $0378  // [78] @DF_POISON_GAS "A cloud of gas surrounds you!"
    .word $038a  // [79] @DF_TELEPORTED "You are teleported!"
    .word $0395  // [80] @DF_DART_HITS "A dart hits you!"
    .word $039f  // [81] @DF_ROCKFALL "Rocks fall on you!"
    .word $03ab  // [82] @DF_DAMAGE_PRE "You take "
    .word $03b1  // [83] @DF_DAMAGE_POST " damage."
    .word $03b7  // [84] @DF_CON_DRAIN "You feel weakened."
    .word $03c2  // [85] @DF_POISONED "You feel poisoned."
    .word $03cd  // [86] @PM_NO_CAST "You cannot cast spells."
    .word $03db  // [87] @PM_NO_PRAY "You cannot pray."
    .word $03e5  // [88] @PM_NOT_KNOWN "You don't know that spell."
    .word $03f5  // [89] @PM_NO_MANA "You faint from fatigue."
    .word $0403  // [90] @PM_NO_EXP "You're not experienced enough."
    .word $0416  // [91] @PM_FAIL "Your spell fails."
    .word $0421  // [92] @PM_YOU_CAST "Spell book (a-v)?"
    .word $042e  // [93] @PM_YOU_PRAY "Prayer book (a-v)?"
    .word $043c  // [94] @PM_TITLE_MAGE "Monster slows."
    .word $0445  // [95] @PM_TITLE_PRAY "Type?"
    .word $044a  // [96] @PM_FOOTER_CAST "Cast which? (a-p, ESC)"
    .word $045d  // [97] @PM_FOOTER_PRAY "Pray which? (a-p, ESC)"
    .word $0470  // [98] @PIQ_LITTLE_BETTER "You feel a little better."
    .word $047e  // [99] @PIW_WEAR_PROMPT "Wear which item (a-v)?"
    .word $048e  // [100] @PIW_TAKEOFF_PROMPT "Take off which item (a-h)?"
    .word $04a0  // [101] @PIW_NOTHING "You have nothing there."
    .word $04ae  // [102] @PIW_NEVERMIND "Never mind."
    .word $04b6  // [103] @PIW_CURSED "You cannot remove it, it is cu"
    .word $04cb  // [104] @PIW_NO_FOOD "You have no food."
    .word $04d5  // [105] @PIW_WIELD "You are wielding a "
    .word $04e0  // [106] @PIW_WEARING "You are wearing a "
    .word $04ea  // [107] @PIW_TAKEOFF "You take off the "
    .word $04f4  // [108] @PIW_EAT "You eat the "
    .word $04fb  // [109] @PIW_DELICIOUS ". Delicious!"
    .word $0504  // [110] @PIW_YUCK ". Yuck!"
    .word $050a  // [111] @PIQ_QUAFF_PROMPT "Quaff which potion (a-v)?"
    .word $051c  // [112] @PIQ_READ_PROMPT "Read which scroll (a-v)?"
    .word $052d  // [113] @PMU_CREATE_FOOD "You create food."
    .word $0537  // [114] @PIQ_SPEED "You feel yourself moving faste"
    .word $054a  // [115] @PIQ_TERRIBLE "That tasted terrible!"
    .word $0557  // [116] @PIQ_NOTHING "Nothing seems to happen."
    .word $0566  // [117] @PIQ_LIGHT "The area fills with light."
    .word $0576  // [118] @PIQ_IDENTIFY_PROMPT "Identify which item (a-v)?"
    .word $0589  // [119] @PIQ_THISIS "This is a "
    .word $058f  // [120] @PIQ_TELEPORT "You feel disoriented."
    .word $059c  // [121] @PIQ_MUCH_BETTER "You feel much better."
    .word $05a9  // [122] @PIQ_MIND_CLEAR "Your mind feels clear."
    .word $05b6  // [123] @PIQ_HEROIC "You feel heroic!"
    .word $05c0  // [124] @PIQ_CANT_SEE "You can't see!"
    .word $05c9  // [125] @PIQ_DIZZY "You feel dizzy."
    .word $05d4  // [126] @PIQ_SENSE "You sense nearby creatures."
    .word $05e4  // [127] @PIQ_EYES_TINGLE "Your eyes tingle."
    .word $05ee  // [128] @PIQ_AIR_CRACKLE "The air crackles around you."
    .word $05ff  // [129] @PIQ_CLEANSED "You feel cleansed."
    .word $060a  // [130] @PMU_GLYPH_BLOCK "There is already an object und"
    .word $0621  // [131] @PMU_GLYPH_OK "You see a strange rune."
    .word $062e  // [132] @PIQ_WPN_GLOW "Your weapon glows briefly."
    .word $063e  // [133] @PIQ_ARM_GLOW "Your armor glows briefly."
    .word $064d  // [134] @PIQ_HANDS_GLOW "Your hands begin to glow."
    .word $065c  // [135] @PIQ_HUMMING "You hear a high-pitched hummin"
    .word $0670  // [136] @PIQ_PROTECTED "You feel protected."
    .word $067c  // [137] @PIQ_VIBRATION "You feel a strange vibration."
    .word $068d  // [138] @PIW_AIM_PROMPT "Aim which wand (a-v)?"
    .word $069d  // [139] @PIW_USE_PROMPT "Use which staff (a-v)?"
    .word $06ad  // [140] @PIW_NO_CHARGES "No charges left."
    .word $06b7  // [141] @PIW_STAFF_EMPTY "The staff is empty."
    .word $06c3  // [142] @PIW_WAND_BOLT "A bolt of lightning shoots for"
    .word $06d7  // [143] @PIW_WAND_FROST "A bolt of frost shoots forth!"
    .word $06e8  // [144] @PIW_WAND_CLOUD "The monster looks confused."
    .word $06f9  // [145] @PIW_WAND_MISS "The cloud dissipates."
    .word $0706  // [146] @PIQ_CANT_READ "You can't see to read!"
    .word $0713  // [147] @IGS_PROMPT "Study which book (a-v)?"
    .word $0724  // [148] @IGS_NO_MAGIC "You cannot use magic."
    .word $0731  // [149] @IGS_WRONG_TYPE "You cannot read that book."
    .word $0740  // [150] @IGS_SUCCESS "You learn from the book!"
    .word $074f  // [151] @IGS_NO_NEW "No new spells to learn."
    .word $075d  // [152] @PIR_NOT_LAMP "Not using a lamp."
    .word $0768  // [153] @PIR_NO_OIL "You have no oil."
    .word $0772  // [154] @PIR_OVERFLOW "Your lamp overflows."
    .word $077f  // [155] @PIR_FULL "Your lamp is full."
    .word $078a  // [156] @PIR_REFUELED "Your lamp is refueled."
    .word $0797  // [157] @CMB_LVLUP "Welcome to level "
    .word $07a2  // [158] @UIS_PACK_FULL "Your pack is full."
    .word $07ae  // [159] @TUN_DIG_GRANITE "You dig in the granite wall."
    .word $07bf  // [160] @TUN_DIG_MAGMA "You dig in the magma."
    .word $07cc  // [161] @TUN_DIG_QUARTZ "You dig in the quartz vein."
    .word $07de  // [162] @TUN_FINISHED "You have finished the tunnel."
    .word $07ef  // [163] @TUN_FOUND "You have found something!"
    .word $07ff  // [164] @TUN_PERMANENT "This seems to be permanent roc"
    .word $0812  // [165] @TUN_NOTHING "There is nothing to tunnel her"
    .word $0825  // [166] @TUN_RUBBLE "The rubble crumbles."
    .word $0833  // [167] @TUN_NO_TOOL "You dig with your hands, makin"
    .word $084e  // [168] @IPU_NOTHING "You see nothing here."
    .word $085a  // [169] @IPU_FOUND "You found "
    .word $0861  // [170] @IPU_GOLD " gold pieces."
    .word $0869  // [171] @IPU_PICKED "You picked up a "
    .word $0873  // [172] @IDR_PROMPT "Drop which item (a-v)?"
    .word $0883  // [173] @IDR_DROP "You drop a "
    .word $088a  // [174] @IDR_FLOOR_FULL "No room on the floor."
    .word $0897  // [175] @SAVE_SAVING "Saving game..."
    .word $08a1  // [176] @SAVE_DONE "Game saved."
    .word $08a9  // [177] @SAVE_LOADING "Loading game..."
    .word $08b4  // [178] @SAVE_NOTFOUND "Save file not found."
    .word $08c1  // [179] @SAVE_CORRUPT "Save file corrupt!"
    .word $08cd  // [180] @SAVE_UNSUPPORTED "Unsupported save."
    .word $08d9  // [181] @SAVE_IOERR "Disk error!"
    .word $08e1  // [182] @SAVE_WELCOME "Welcome back to Moria8!"
    .word $08f2  // [183] @SAVE_NEED_SAVE "Need Save Disk."
    .word $08fd  // [184] @SAVE_BAD_SAVE "Wrong Save Disk."
    .word $0909  // [185] @SAVE_OVERWRITE "Overwrite? Y/N"
    .word $0915  // [186] @BASH_SMASH "You smash into the door!"
    .word $0923  // [187] @BASH_CRASH "The door crashes open!"
    .word $0930  // [188] @BASH_HOLDS "The door holds firm."
    .word $093c  // [189] @BASH_OFFBAL "You are off balance."
    .word $0948  // [190] @BASH_EMPTY "You bash at empty space."
    .word $0957  // [191] @BASH_STUNNED " appears stunned!"
    .word $0961  // [192] @BASH_IGNORES " ignores your bash!"
    .word $096d  // [193] @PIQ_VERY_GOOD "You feel very good."
    .word $0979  // [194] @PID_CARRY "You sense magik on what you ca"
    .word $098d  // [195] @PIQ_RESTORED "You feel your strength return."
    .word $099e  // [196] @CHEST_FOUND_TRAP "You have discovered a trap on "
    .word $09b5  // [197] @CHEST_TRAPPED "The chest is trapped!"
    .word $09c2  // [198] @CHEST_NEEDLE "A small needle has pricked you"
    .word $09d5  // [199] @CHEST_WEAKENED "You feel weakened!"
    .word $09e0  // [200] @CHEST_GAS "A puff of yellow gas surrounds"
    .word $09f6  // [201] @CHEST_UNAFFECTED "You are unaffected."
    .word $0a02  // [202] @CHEST_CHOKE "You choke and pass out."
    .word $0a10  // [203] @CHEST_EXPLOSION "There is a sudden explosion!"
    .word $0a21  // [204] @CHEST_PICKED "You have picked the lock."
    .word $0a31  // [205] @CHEST_PICK_CONFUSED "You are too confused to pick t"
    .word $0a47  // [206] @CHEST_PICK_FAIL "You failed to pick the lock."
    .word $0a58  // [207] @CHEST_DEATH_NEEDLE "a poison needle."
    .word $0a62  // [208] @CHEST_DEATH_EXPLODING "an exploding chest."
    .word $0a6f  // [209] @CHEST_DISARM_UNFOUND "I don't see a trap..."
    .word $0a7c  // [210] @CHEST_DISARM_NOT_TRAPPED "The chest was not trapped."
    .word $0a8c  // [211] @CHEST_DISARMED "You have disarmed the chest."
    .word $0a9c  // [212] @CHEST_DISARM_FAIL "You failed to disarm the chest"
    .word $0aae  // [213] @CHEST_DISARM_SET_OFF "You set a trap off!"
    .word $0ab9  // [214] @CHEST_DESTROYED "You have destroyed the chest.."
    .word $0acb  // [215] @CHEST_DESTROYED_CONTENTS "and it's contents!"
    .word $0ad7  // [216] @CHEST_LOCK_BREAKS "The lock breaks open!"
    .word $0ae5  // [217] @CHEST_HOLDS_FIRM "The chest holds firm."

// Compressed string data (2802 bytes)
huff_str_data:
    // [0] "You will have to do better than that!" (38→21 bytes)
    .byte $1e, $f6, $8b, $98, $42, $c9, $a3, $fd, $4d, $ab, $db, $17, $d1, $3c, $2a, $49, $a7, $52, $4c, $82, $10
    // [1] "That is an insult!" (19→11 bytes)
    .byte $c7, $93, $25, $c9, $d6, $9d, $cc, $cf, $b0, $41, $08
    // [2] "Do you wish to do business or not?" (35→20 bytes)
    .byte $50, $6d, $73, $7b, $45, $c9, $ca, $a6, $d5, $ed, $8b, $d3, $cc, $fc, $ce, $e8, $59, $ea, $62, $10
    // [3] "Hah! Try again." (16→11 bytes)
    .byte $88, $ad, $21, $2e, $38, $39, $59, $d6, $cc, $de, $40
    // [4] "Ridiculous!" (12→9 bytes)
    .byte $c5, $b9, $5e, $79, $ec, $37, $a6, $21, $00
    // [5] "You have got to be kidding!" (28→17 bytes)
    .byte $1e, $f6, $c9, $a3, $fd, $77, $52, $a6, $d8, $bf, $63, $65, $6b, $cc, $dd, $10, $80
    // [6] "You had better be kidding!" (27→16 bytes)
    .byte $1e, $f6, $c9, $97, $62, $fa, $27, $85, $8b, $f6, $36, $56, $bc, $cd, $d1, $08
    // [7] "You try my patience." (21→12 bytes)
    .byte $1e, $f6, $a0, $39, $55, $72, $e0, $c9, $9f, $9f, $3e, $f2
    // [8] "I do not hear you." (19→11 bytes)
    .byte $c6, $6a, $f6, $cf, $52, $cb, $d8, $2b, $9b, $d7, $90
    // [9] "Hmmm, nice weather we are having." (34→21 bytes)
    .byte $88, $aa, $aa, $aa, $86, $cf, $3c, $fd, $17, $d9, $25, $e1, $45, $fa, $c1, $f6, $4d, $1f, $33, $75, $e4
    // [10] "I must have heard you wrong." (29→17 bytes)
    .byte $c6, $6a, $bd, $34, $b2, $68, $ff, $65, $ec, $0b, $ae, $6f, $68, $a1, $b3, $75, $e4
    // [11] "What was that?" (15→9 bytes)
    .byte $c6, $24, $c9, $45, $63, $a9, $26, $4c, $42
    // [12] "I am sorry, say that again." (28→17 bytes)
    .byte $c6, $6b, $2b, $4f, $40, $1c, $50, $d3, $67, $2a, $49, $92, $b3, $ad, $99, $bc, $80
    // [13] "What did you say?" (18→11 bytes)
    .byte $c6, $24, $c9, $57, $95, $d7, $37, $b4, $d9, $cc, $42
    // [14] "Sorry, what was that again?" (28→17 bytes)
    .byte $89, $e8, $03, $8a, $1a, $2c, $99, $28, $ac, $75, $24, $c9, $59, $d6, $cc, $f1, $08
    // [15] " hits you." (11→6 bytes)
    .byte $b2, $ca, $1d, $73, $7a, $f2
    // [16] " misses you." (13→8 bytes)
    .byte $aa, $e4, $cf, $ce, $b9, $bd, $79, $00
    // [17] " poisons you." (14→8 bytes)
    .byte $b8, $6e, $4f, $66, $75, $cd, $eb, $c8
    // [18] " confuses you." (15→9 bytes)
    .byte $bc, $ec, $f8, $e9, $f9, $d7, $37, $af, $20
    // [19] " paralyzes you." (16→10 bytes)
    .byte $b8, $30, $34, $1c, $c6, $fc, $eb, $9b, $d7, $90
    // [20] " spits acid on you." (20→11 bytes)
    .byte $a7, $86, $50, $eb, $73, $95, $dd, $9d, $73, $7a, $f2
    // [21] " frightens you." (16→10 bytes)
    .byte $bc, $06, $5d, $92, $7c, $ce, $b9, $bd, $79, $00
    // [22] "You hear a horrible shriek!" (28→16 bytes)
    .byte $1e, $f6, $cb, $d8, $2b, $59, $68, $06, $62, $c3, $e9, $c8, $33, $f1, $84, $20
    // [23] " casts a bolt!" (15→9 bytes)
    .byte $bc, $b1, $a1, $d6, $b1, $76, $08, $21, $00
    // [24] " breathes fire!" (16→9 bytes)
    .byte $b1, $43, $d9, $25, $e7, $78, $c8, $78, $84
    // [25] " summons help!" (15→9 bytes)
    .byte $a7, $d5, $55, $d9, $9d, $97, $c3, $01, $08
    // [26] " teleports you!" (16→9 bytes)
    .byte $a9, $f0, $fc, $34, $10, $eb, $9b, $d1, $08
    // [27] " blinds you!" (13→8 bytes)
    .byte $b1, $61, $99, $ac, $eb, $9b, $d1, $08
    // [28] " confuses you!" (15→9 bytes)
    .byte $bc, $ec, $f8, $e9, $f9, $d7, $37, $a2, $10
    // [29] " heals itself." (15→9 bytes)
    .byte $b2, $f6, $81, $dc, $a1, $fc, $38, $79, $00
    // [30] "No ranged weapon." (18→11 bytes)
    .byte $c5, $6d, $06, $9b, $be, $ba, $2f, $b6, $1b, $37, $90
    // [31] "No ammo." (9→6 bytes)
    .byte $c5, $6d, $65, $55, $d7, $90
    // [32] " flies away." (13→8 bytes)
    .byte $bc, $43, $3e, $75, $85, $67, $1e, $40
    // [33] " misses" (8→5 bytes)
    .byte $aa, $e4, $cf, $cc, $80
    // [34] " hits" (6→4 bytes)
    .byte $b2, $ca, $19, $00
    // [35] "Your spell hits" (16→9 bytes)
    .byte $1e, $f4, $29, $e1, $f0, $85, $96, $50, $c8
    // [36] "Your spell fizzles out." (24→15 bytes)
    .byte $1e, $f4, $29, $e1, $f0, $85, $e3, $38, $de, $37, $0f, $3b, $bd, $47, $90
    // [37] "Throw which item (a-v)?" (24→17 bytes)
    .byte $c7, $90, $68, $b4, $59, $67, $99, $5c, $a7, $ab, $54, $99, $4e, $3a, $8e, $21, $00
    // [38] " shatters!" (11→6 bytes)
    .byte $a7, $26, $44, $f0, $31, $08
    // [39] "You feel better." (17→10 bytes)
    .byte $1e, $f6, $f1, $ff, $0b, $17, $d1, $3c, $1e, $40
    // [40] "You can see again." (19→11 bytes)
    .byte $1e, $f6, $f2, $d3, $a7, $ff, $59, $d6, $cc, $de, $40
    // [41] "You feel less confused." (24→14 bytes)
    .byte $1e, $f6, $f1, $ff, $0b, $0f, $33, $bc, $ec, $f8, $e9, $fa, $de, $40
    // [42] "You can move again." (20→12 bytes)
    .byte $1e, $f6, $f2, $d3, $aa, $ec, $7f, $ac, $eb, $66, $6f, $20
    // [43] "You feel bolder now." (21→12 bytes)
    .byte $1e, $f6, $f1, $ff, $0b, $17, $60, $bf, $0b, $3d, $15, $e4
    // [44] "You feel yourself slow down." (29→17 bytes)
    .byte $1e, $f6, $f1, $ff, $0a, $e6, $f4, $0f, $e1, $c5, $38, $68, $b5, $7a, $2c, $de, $40
    // [45] "You feel yourself speed up." (28→16 bytes)
    .byte $1e, $f6, $f1, $ff, $0a, $e6, $f4, $0f, $e1, $c5, $3c, $3f, $d7, $7b, $83, $c8
    // [46] "Your light is growing dim." (27→16 bytes)
    .byte $1e, $f4, $2c, $32, $ec, $92, $e4, $eb, $a1, $a2, $e6, $6e, $d5, $e5, $57, $90
    // [47] "Your light has gone out." (25→14 bytes)
    .byte $1e, $f4, $2c, $32, $ec, $92, $c9, $8e, $bb, $b3, $fb, $bd, $47, $90
    // [48] "You feel yourself yanked away!" (31→18 bytes)
    .byte $1e, $f6, $f1, $ff, $0a, $e6, $f4, $0f, $e1, $c5, $71, $a7, $1b, $d7, $58, $56, $70, $42
    // [49] "You see a " (11→6 bytes)
    .byte $1e, $f6, $9f, $fd, $6a, $40
    // [50] "You see an open door." (22→12 bytes)
    .byte $1e, $f6, $9f, $fd, $69, $dd, $c3, $e7, $57, $ba, $0f, $20
    // [51] "You see a closed door." (23→12 bytes)
    .byte $1e, $f6, $9f, $fd, $6b, $cc, $34, $fd, $75, $7b, $a0, $f2
    // [52] "You see a staircase down." (26→14 bytes)
    .byte $1e, $f6, $9f, $fd, $6a, $68, $d9, $0e, $58, $fe, $af, $45, $9b, $c8
    // [53] "You see a staircase up." (24→13 bytes)
    .byte $1e, $f6, $9f, $fd, $6a, $68, $d9, $0e, $58, $fe, $f7, $07, $90
    // [54] "You see a trap." (16→9 bytes)
    .byte $1e, $f6, $9f, $fd, $6a, $80, $d8, $3c, $80
    // [55] "You see rubble." (16→10 bytes)
    .byte $1e, $f6, $9f, $fd, $0e, $c5, $8b, $0f, $79, $00
    // [56] "You see a wall." (16→9 bytes)
    .byte $1e, $f6, $9f, $fd, $6a, $2b, $42, $0f, $20
    // [57] "You see nothing special." (25→14 bytes)
    .byte $1e, $f6, $9f, $fd, $9e, $a4, $b3, $37, $69, $e1, $fc, $e5, $a0, $f2
    // [58] "You are too afraid!" (20→11 bytes)
    .byte $1e, $f6, $b0, $7d, $4d, $da, $dc, $03, $65, $62, $10
    // [59] "an open pit" (12→7 bytes)
    .byte $69, $dd, $c3, $e7, $70, $ca, $10
    // [60] "an arrow trap" (14→8 bytes)
    .byte $69, $d6, $00, $d1, $6a, $03, $60, $40
    // [61] "a poison gas trap" (18→10 bytes)
    .byte $6b, $86, $e4, $f6, $75, $d6, $3a, $80, $d8, $10
    // [62] "a teleport trap" (16→9 bytes)
    .byte $6a, $9f, $0f, $c3, $41, $2a, $03, $60, $40
    // [63] "a poison dart" (14→8 bytes)
    .byte $6b, $86, $e4, $f6, $75, $6c, $08, $40
    // [64] "a rockfall trap" (16→10 bytes)
    .byte $6a, $1b, $cc, $6e, $1a, $10, $a8, $0d, $81, $00
    // [65] "falling rock." (14→9 bytes)
    .byte $e1, $a1, $0c, $cd, $da, $1b, $cc, $67, $90
    // [66] "Direction?" (11→8 bytes)
    .byte $50, $64, $3f, $94, $ce, $cf, $10, $80
    // [67] "The door is stuck." (19→11 bytes)
    .byte $c7, $97, $d5, $ee, $85, $c9, $d3, $4e, $f3, $19, $e4
    // [68] "You found a trap!" (18→10 bytes)
    .byte $1e, $f6, $f1, $bd, $9a, $eb, $54, $06, $c0, $42
    // [69] "You found a secret door!" (25→14 bytes)
    .byte $1e, $f6, $f1, $bd, $9a, $eb, $53, $fe, $43, $d2, $af, $74, $04, $20
    // [70] "You found nothing." (19→11 bytes)
    .byte $1e, $f6, $f1, $bd, $9a, $ec, $f5, $25, $99, $ba, $f2
    // [71] "No door there." (15→9 bytes)
    .byte $c5, $6d, $5e, $e8, $54, $97, $87, $bc, $80
    // [72] "The door is already open." (26→15 bytes)
    .byte $c7, $97, $d5, $ee, $85, $c9, $d6, $80, $7b, $2d, $cb, $b8, $7c, $de, $40
    // [73] "It is already closed." (22→13 bytes)
    .byte $c6, $52, $e4, $eb, $40, $3d, $96, $e5, $e6, $1a, $7e, $b7, $90
    // [74] "You open the door." (19→11 bytes)
    .byte $1e, $f6, $ee, $1f, $3a, $92, $fa, $bd, $d0, $79, $00
    // [75] "You close the door." (20→11 bytes)
    .byte $1e, $f6, $f3, $0d, $3f, $a9, $2f, $ab, $dd, $07, $90
    // [76] "You fell into a pit!" (21→12 bytes)
    .byte $1e, $f6, $f1, $f0, $85, $cc, $d3, $6b, $5c, $32, $82, $10
    // [77] "An arrow hits you!" (19→11 bytes)
    .byte $89, $4e, $b0, $06, $8b, $65, $94, $3a, $e6, $f4, $42
    // [78] "A cloud of gas surrounds you!" (30→18 bytes)
    .byte $89, $5e, $61, $bd, $5d, $de, $2b, $ac, $74, $fa, $01, $bd, $9a, $ce, $b9, $bd, $10, $80
    // [79] "You are teleported!" (20→11 bytes)
    .byte $1e, $f6, $b0, $7d, $4f, $87, $e1, $a0, $9e, $b1, $08
    // [80] "A dart hits you!" (17→10 bytes)
    .byte $89, $55, $b0, $25, $96, $50, $eb, $9b, $d1, $08
    // [81] "Rocks fall on you!" (19→12 bytes)
    .byte $c5, $bb, $cc, $63, $bc, $34, $21, $76, $75, $cd, $e8, $84
    // [82] "You take " (10→6 bytes)
    .byte $1e, $f6, $a3, $46, $fa, $40
    // [83] " damage." (9→6 bytes)
    .byte $ab, $65, $59, $df, $79, $00
    // [84] "You feel weakened." (19→11 bytes)
    .byte $1e, $f6, $f1, $ff, $0a, $2f, $b4, $6f, $9f, $ad, $e4
    // [85] "You feel poisoned." (19→11 bytes)
    .byte $1e, $f6, $f1, $ff, $0b, $86, $e4, $f6, $7e, $b7, $90
    // [86] "You cannot cast spells." (24→14 bytes)
    .byte $1e, $f6, $f2, $d3, $9e, $a5, $e5, $8d, $29, $e1, $f0, $81, $bc, $80
    // [87] "You cannot pray." (17→10 bytes)
    .byte $1e, $f6, $f2, $d3, $9e, $a5, $c0, $19, $c7, $90
    // [88] "You don't know that spell." (27→16 bytes)
    .byte $1e, $f6, $af, $67, $8b, $a5, $8d, $3d, $16, $a4, $99, $29, $e1, $f0, $83, $c8
    // [89] "You faint from fatigue." (24→14 bytes)
    .byte $1e, $f6, $f0, $d9, $9a, $5e, $03, $55, $bc, $32, $65, $de, $fb, $c8
    // [90] "You're not experienced enough." (31→19 bytes)
    .byte $1e, $f7, $17, $0f, $b3, $d4, $bf, $8d, $70, $f0, $cf, $cf, $9f, $5d, $f9, $ef, $5d, $93, $c8
    // [91] "Your spell fails." (18→11 bytes)
    .byte $1e, $f4, $29, $e1, $f0, $85, $e1, $b3, $03, $79, $00
    // [92] "Spell book (a-v)?" (18→13 bytes)
    .byte $89, $e1, $f0, $85, $8b, $bb, $1a, $a9, $32, $9c, $75, $1c, $42
    // [93] "Prayer book (a-v)?" (19→14 bytes)
    .byte $c5, $80, $ce, $78, $58, $bb, $b1, $aa, $93, $29, $c7, $51, $c4, $20
    // [94] "Monster slows." (15→9 bytes)
    .byte $88, $fb, $33, $4f, $0a, $70, $d1, $4d, $e4
    // [95] "Type?" (6→5 bytes)
    .byte $c7, $73, $0f, $c4, $20
    // [96] "Cast which? (a-p, ESC)" (23→19 bytes)
    .byte $c6, $8c, $69, $45, $96, $79, $96, $25, $52, $65, $3c, $14, $36, $23, $44, $f1, $a2, $89, $00
    // [97] "Pray which? (a-p, ESC)" (23→19 bytes)
    .byte $c5, $80, $ce, $51, $65, $9e, $65, $89, $54, $99, $4f, $05, $0d, $88, $d1, $3c, $68, $a2, $40
    // [98] "You feel a little better." (26→14 bytes)
    .byte $1e, $f6, $f1, $ff, $0a, $d6, $19, $44, $87, $d8, $be, $89, $e0, $f2
    // [99] "Wear which item (a-v)?" (23→16 bytes)
    .byte $c6, $3d, $82, $8b, $2c, $f3, $2b, $94, $f5, $6a, $93, $29, $c7, $51, $c4, $20
    // [100] "Take off which item (a-h)?" (27→18 bytes)
    .byte $c7, $68, $df, $77, $8e, $28, $b2, $cf, $32, $b9, $4f, $56, $a9, $32, $9c, $94, $71, $08
    // [101] "You have nothing there." (24→14 bytes)
    .byte $1e, $f6, $c9, $a3, $fd, $9e, $a4, $b3, $37, $6a, $4b, $c3, $de, $40
    // [102] "Never mind." (12→8 bytes)
    .byte $c5, $7c, $7f, $0a, $ae, $66, $b7, $90
    // [103] "You cannot remove it, it is cursed!" (36→21 bytes)
    .byte $1e, $f6, $f2, $d3, $9e, $a5, $0f, $57, $63, $fd, $ca, $28, $6e, $52, $e4, $ef, $3d, $03, $f5, $88, $40
    // [104] "You have no food." (18→10 bytes)
    .byte $1e, $f6, $c9, $a3, $fd, $9e, $de, $37, $56, $f2
    // [105] "You are wielding a " (20→11 bytes)
    .byte $1e, $f6, $b0, $7d, $17, $3f, $05, $e6, $6e, $d6, $a4
    // [106] "You are wearing a " (19→10 bytes)
    .byte $1e, $f6, $b0, $7d, $17, $d8, $33, $37, $6b, $52
    // [107] "You take off the " (18→10 bytes)
    .byte $1e, $f6, $a3, $46, $fb, $bc, $71, $52, $5f, $48
    // [108] "You eat the " (13→7 bytes)
    .byte $1e, $f6, $fb, $25, $49, $7d, $20
    // [109] ". Delicious!" (13→9 bytes)
    .byte $7d, $50, $7c, $33, $ce, $77, $a6, $21, $00
    // [110] ". Yuck!" (8→6 bytes)
    .byte $7d, $1f, $79, $8c, $21, $00
    // [111] "Quaff which potion (a-v)?" (26→18 bytes)
    .byte $88, $7e, $b7, $1c, $51, $65, $9e, $65, $70, $d4, $ce, $ce, $a9, $32, $9c, $75, $1c, $42
    // [112] "Read which scroll (a-v)?" (25→17 bytes)
    .byte $c5, $be, $cb, $a2, $cb, $3c, $ca, $9f, $21, $b0, $85, $52, $65, $38, $ea, $38, $84
    // [113] "You create food." (17→10 bytes)
    .byte $1e, $f6, $f2, $1e, $c9, $f7, $8d, $d5, $bc, $80
    // [114] "You feel yourself moving faster." (33→19 bytes)
    .byte $1e, $f6, $f1, $ff, $0a, $e6, $f4, $0f, $e1, $c5, $57, $63, $e6, $6e, $de, $18, $d3, $c1, $e4
    // [115] "That tasted terrible!" (22→13 bytes)
    .byte $c7, $93, $25, $46, $34, $f5, $d4, $f0, $0c, $c5, $87, $88, $40
    // [116] "Nothing seems to happen." (25→15 bytes)
    .byte $c5, $6a, $4b, $33, $76, $9f, $fa, $a7, $53, $6c, $9b, $0c, $3e, $6f, $20
    // [117] "The area fills with light." (27→16 bytes)
    .byte $c7, $97, $d6, $0f, $6b, $c6, $61, $03, $a2, $e5, $25, $61, $97, $64, $8f, $20
    // [118] "Identify which item (a-v)?" (27→19 bytes)
    .byte $c6, $57, $f3, $4c, $f0, $e5, $16, $59, $e6, $57, $29, $ea, $d5, $26, $53, $8e, $a3, $88, $40
    // [119] "This is a " (11→6 bytes)
    .byte $c7, $96, $4e, $e4, $eb, $52
    // [120] "You feel disoriented." (22→13 bytes)
    .byte $1e, $f6, $f1, $ff, $0a, $bc, $9e, $86, $7e, $69, $eb, $79, $00
    // [121] "You feel much better." (22→13 bytes)
    .byte $1e, $f6, $f1, $ff, $0a, $af, $79, $95, $8b, $e8, $9e, $0f, $20
    // [122] "Your mind feels clear." (23→13 bytes)
    .byte $1e, $f4, $2a, $b9, $9a, $ef, $1f, $f0, $3b, $cc, $3d, $81, $e4
    // [123] "You feel heroic!" (17→10 bytes)
    .byte $1e, $f6, $f1, $ff, $0b, $2f, $0d, $cf, $22, $10
    // [124] "You can't see!" (15→9 bytes)
    .byte $1e, $f6, $f2, $d3, $c5, $d2, $9f, $f8, $84
    // [125] "You feel dizzy." (16→11 bytes)
    .byte $1e, $f6, $f1, $ff, $0a, $bc, $e3, $78, $db, $8f, $20
    // [126] "You sense nearby creatures." (28→16 bytes)
    .byte $1e, $f6, $9f, $cc, $fe, $cf, $d8, $22, $b9, $79, $0f, $64, $e8, $79, $bc, $80
    // [127] "Your eyes tingle." (18→10 bytes)
    .byte $1e, $f4, $2f, $b9, $e7, $53, $33, $76, $1e, $f2
    // [128] "The air crackles around you." (29→17 bytes)
    .byte $c7, $97, $d6, $c8, $5e, $41, $b9, $8d, $0f, $3a, $c1, $bd, $9a, $eb, $9b, $d7, $90
    // [129] "You feel cleansed." (19→11 bytes)
    .byte $1e, $f6, $f1, $ff, $0b, $cc, $3d, $a6, $7e, $b7, $90
    // [130] "There is already an object under you." (38→23 bytes)
    .byte $c7, $97, $87, $dc, $9d, $68, $07, $b2, $dc, $ad, $3b, $b1, $62, $1b, $f9, $4b, $d9, $af, $c2, $b9, $bd, $79, $00
    // [131] "You see a strange rune." (24→13 bytes)
    .byte $1e, $f6, $9f, $fd, $6a, $68, $0d, $37, $7e, $87, $67, $ef, $20
    // [132] "Your weapon glows briefly." (27→16 bytes)
    .byte $1e, $f4, $28, $be, $d8, $6c, $eb, $b0, $d1, $4e, $c5, $0c, $ff, $10, $71, $e4
    // [133] "Your armor glows briefly." (26→15 bytes)
    .byte $1e, $f4, $2b, $02, $ba, $15, $d8, $68, $a7, $62, $86, $7f, $88, $38, $f2
    // [134] "Your hands begin to glow." (26→15 bytes)
    .byte $1e, $f4, $2c, $9a, $6b, $3b, $17, $dd, $cc, $ea, $6d, $76, $1a, $2b, $c8
    // [135] "You hear a high-pitched humming." (33→20 bytes)
    .byte $1e, $f6, $cb, $d8, $2b, $59, $65, $d9, $29, $e1, $94, $e6, $5e, $bb, $2e, $aa, $ae, $66, $eb, $c8
    // [136] "You feel protected." (20→12 bytes)
    .byte $1e, $f6, $f1, $ff, $0b, $80, $6a, $7f, $29, $eb, $79, $00
    // [137] "You feel a strange vibration." (30→17 bytes)
    .byte $1e, $f6, $f1, $ff, $0a, $d4, $d0, $1a, $6e, $fd, $8f, $98, $a0, $c9, $9d, $9b, $c8
    // [138] "Aim which wand (a-v)?" (22→16 bytes)
    .byte $89, $65, $5a, $2c, $b3, $cc, $a8, $ad, $35, $d5, $26, $53, $8e, $a3, $88, $40
    // [139] "Use which staff (a-v)?" (23→16 bytes)
    .byte $88, $87, $f4, $59, $67, $99, $53, $46, $e3, $8a, $a4, $ca, $71, $d4, $71, $08
    // [140] "No charges left." (17→10 bytes)
    .byte $c5, $6d, $e6, $4c, $0e, $f9, $d8, $7f, $08, $f2
    // [141] "The staff is empty." (20→12 bytes)
    .byte $c7, $97, $d3, $46, $e3, $8b, $93, $be, $ae, $08, $e3, $c8
    // [142] "A bolt of lightning shoots forth!" (34→20 bytes)
    .byte $89, $58, $bb, $04, $bb, $c5, $86, $5d, $92, $4f, $33, $76, $9c, $b7, $50, $ef, $1a, $09, $21, $08
    // [143] "A bolt of frost shoots forth!" (30→17 bytes)
    .byte $89, $58, $bb, $04, $bb, $c5, $e0, $34, $d2, $9c, $b7, $50, $ef, $1a, $09, $21, $08
    // [144] "The monster looks confused." (28→17 bytes)
    .byte $c7, $97, $d5, $76, $66, $9e, $16, $1b, $b1, $8e, $f3, $b3, $e3, $a7, $eb, $79, $00
    // [145] "The cloud dissipates." (22→13 bytes)
    .byte $c7, $97, $de, $61, $bd, $5d, $5e, $4c, $f3, $83, $27, $9b, $c8
    // [146] "You can't see to read!" (23→13 bytes)
    .byte $1e, $f6, $f2, $d3, $c5, $d2, $9f, $fd, $4d, $a1, $ec, $b1, $08
    // [147] "Study which book (a-v)?" (24→17 bytes)
    .byte $89, $a7, $56, $e5, $16, $59, $e6, $56, $2e, $ec, $6a, $a4, $ca, $71, $d4, $71, $08
    // [148] "You cannot use magic." (22→13 bytes)
    .byte $1e, $f6, $f2, $d3, $9e, $a5, $e9, $fd, $55, $9d, $cf, $2f, $20
    // [149] "You cannot read that book." (27→15 bytes)
    .byte $1e, $f6, $f2, $d3, $9e, $a5, $0f, $65, $d4, $93, $25, $8b, $bb, $19, $e4
    // [150] "You learn from the book!" (25→15 bytes)
    .byte $1e, $f6, $c3, $d8, $27, $78, $0d, $56, $a4, $be, $c5, $dd, $8c, $21, $00
    // [151] "No new spells to learn." (24→14 bytes)
    .byte $c5, $6d, $9f, $8b, $4f, $0f, $84, $0e, $a6, $d8, $7b, $04, $de, $40
    // [152] "Not using a lamp." (18→11 bytes)
    .byte $c5, $6a, $5e, $9e, $66, $ed, $6b, $06, $57, $07, $90
    // [153] "You have no oil." (17→10 bytes)
    .byte $1e, $f6, $c9, $a3, $fd, $9e, $dd, $cc, $1e, $40
    // [154] "Your lamp overflows." (21→13 bytes)
    .byte $1e, $f4, $2c, $19, $5c, $2e, $c7, $f0, $e2, $1a, $29, $bc, $80
    // [155] "Your lamp is full." (19→11 bytes)
    .byte $1e, $f4, $2c, $19, $5c, $2e, $4e, $f1, $d8, $41, $e4
    // [156] "Your lamp is refueled." (23→13 bytes)
    .byte $1e, $f4, $2c, $19, $5c, $2e, $4e, $87, $f1, $df, $87, $ad, $e4
    // [157] "Welcome to level " (18→11 bytes)
    .byte $c6, $3e, $1c, $ea, $bf, $53, $6c, $3e, $3f, $c2, $90
    // [158] "Your pack is full." (19→12 bytes)
    .byte $1e, $f4, $2e, $0d, $cc, $6b, $93, $bc, $76, $10, $79, $00
    // [159] "You dig in the granite wall." (29→17 bytes)
    .byte $1e, $f6, $af, $2e, $dc, $ce, $a4, $be, $ba, $0d, $3c, $a7, $d1, $5a, $10, $79, $00
    // [160] "You dig in the magma." (22→13 bytes)
    .byte $1e, $f6, $af, $2e, $dc, $ce, $a4, $be, $aa, $ce, $aa, $cf, $20
    // [161] "You dig in the quartz vein." (28→18 bytes)
    .byte $1e, $f6, $af, $2e, $dc, $ce, $a4, $be, $c4, $2f, $58, $13, $1b, $b1, $ff, $33, $79, $00
    // [162] "You have finished the tunnel." (30→17 bytes)
    .byte $1e, $f6, $c9, $a3, $fd, $e3, $33, $c9, $cb, $d7, $52, $5f, $53, $b3, $9f, $c1, $e4
    // [163] "You have found something!" (26→16 bytes)
    .byte $1e, $f6, $c9, $a3, $fd, $e3, $7b, $35, $d3, $d5, $7d, $25, $99, $ba, $21, $00
    // [164] "This seems to be permanent rock." (33→19 bytes)
    .byte $c7, $96, $4e, $9f, $fa, $a7, $53, $6c, $5f, $b8, $78, $2a, $d3, $f9, $a5, $0d, $e6, $33, $c8
    // [165] "There is nothing to tunnel here." (33→19 bytes)
    .byte $c7, $97, $87, $dc, $9d, $9e, $a4, $b3, $37, $6a, $6d, $4e, $ce, $7f, $0b, $2f, $0f, $79, $00
    // [166] "The rubble crumbles." (21→14 bytes)
    .byte $c7, $97, $d0, $ec, $58, $b0, $fb, $c8, $75, $58, $b0, $f3, $79, $00
    // [167] "You dig with your hands, making no progress." (45→27 bytes)
    .byte $1e, $f6, $af, $2e, $d1, $72, $92, $ae, $6f, $42, $c9, $a6, $b3, $50, $d5, $5a, $36, $66, $ed, $9e, $dc, $03, $5d, $0f, $33, $79, $00
    // [168] "You see nothing here." (22→12 bytes)
    .byte $1e, $f6, $9f, $fd, $9e, $a4, $b3, $37, $6c, $bc, $3d, $e4
    // [169] "You found " (11→7 bytes)
    .byte $1e, $f6, $f1, $bd, $9a, $e9, $00
    // [170] " gold pieces." (14→8 bytes)
    .byte $ae, $ec, $17, $70, $cf, $f3, $e6, $f2
    // [171] "You picked up a " (17→10 bytes)
    .byte $1e, $f6, $e1, $9e, $63, $7a, $ef, $70, $ad, $48
    // [172] "Drop which item (a-v)?" (23→16 bytes)
    .byte $50, $06, $e1, $45, $96, $79, $95, $ca, $7a, $b5, $49, $94, $e3, $a8, $e2, $10
    // [173] "You drop a " (12→7 bytes)
    .byte $1e, $f6, $ac, $37, $0a, $d4, $80
    // [174] "No room on the floor." (22→13 bytes)
    .byte $c5, $6d, $0d, $d5, $6e, $ce, $a4, $be, $f1, $0d, $d0, $79, $00
    // [175] "Saving game..." (15→10 bytes)
    .byte $89, $b4, $7c, $cd, $da, $eb, $2b, $ef, $7b, $c8
    // [176] "Game saved." (12→8 bytes)
    .byte $88, $46, $57, $e9, $b4, $7f, $5b, $c8
    // [177] "Loading game..." (16→11 bytes)
    .byte $88, $3d, $65, $e6, $6e, $d7, $59, $5f, $7b, $de, $40
    // [178] "Save file not found." (21→13 bytes)
    .byte $89, $b4, $7f, $bc, $66, $1f, $67, $a9, $78, $de, $cd, $6f, $20
    // [179] "Save file corrupt!" (19→12 bytes)
    .byte $89, $b4, $7f, $bc, $66, $1f, $79, $d0, $0e, $e0, $82, $10
    // [180] "Unsupported save." (18→12 bytes)
    .byte $88, $93, $3e, $e1, $86, $82, $7a, $e9, $b4, $7f, $79, $00
    // [181] "Disk error!" (12→8 bytes)
    .byte $50, $64, $e3, $5f, $00, $d0, $10, $80
    // [182] "Welcome back to Moria8!" (24→17 bytes)
    .byte $c6, $3e, $1c, $ea, $bf, $62, $b7, $31, $aa, $6d, $88, $fa, $19, $68, $82, $10, $80
    // [183] "Need Save Disk." (16→11 bytes)
    .byte $c5, $7f, $ae, $c4, $da, $3f, $d5, $06, $4e, $33, $c8
    // [184] "Wrong Save Disk." (17→12 bytes)
    .byte $c6, $03, $66, $ed, $89, $b4, $7f, $aa, $0c, $9c, $67, $90
    // [185] "Overwrite? Y/N" (15→12 bytes)
    .byte $88, $18, $fe, $02, $86, $53, $f1, $28, $e2, $03, $14, $40
    // [186] "You smash into the door!" (25→14 bytes)
    .byte $1e, $f6, $9a, $ac, $72, $b9, $9a, $6d, $49, $7d, $5e, $e8, $08, $40
    // [187] "The door crashes open!" (23→13 bytes)
    .byte $c7, $97, $d5, $ee, $85, $e4, $18, $e5, $e7, $77, $0f, $98, $84
    // [188] "The door holds firm." (21→12 bytes)
    .byte $c7, $97, $d5, $ee, $85, $96, $c1, $67, $78, $c8, $2a, $f2
    // [189] "You are off balance." (21→12 bytes)
    .byte $1e, $f6, $b0, $7d, $de, $38, $b1, $5a, $0d, $3e, $7d, $e4
    // [190] "You bash at empty space." (25→15 bytes)
    .byte $1e, $f6, $c5, $63, $95, $64, $be, $ae, $08, $e5, $3c, $1b, $9f, $79, $00
    // [191] " appears stunned!" (18→10 bytes)
    .byte $ad, $86, $1e, $c0, $74, $d3, $b3, $9f, $ac, $42
    // [192] " ignores your bash!" (20→12 bytes)
    .byte $b9, $76, $7a, $1e, $75, $cd, $e8, $58, $ac, $72, $10, $80
    // [193] "You feel very good." (20→12 bytes)
    .byte $1e, $f6, $f1, $ff, $0b, $1f, $c1, $ca, $ee, $ea, $de, $40
    // [194] "You sense magik on what you carry." (35→20 bytes)
    .byte $1e, $f6, $9f, $cc, $fe, $aa, $ce, $e6, $35, $d9, $d1, $64, $c9, $5c, $de, $de, $58, $01, $c7, $90
    // [195] "You feel your strength return." (31→17 bytes)
    .byte $1e, $f6, $f1, $ff, $0a, $e6, $f4, $29, $a0, $7c, $dd, $49, $50, $f4, $e8, $4d, $e4
    // [196] "You have discovered a trap on the chest!" (41→23 bytes)
    .byte $1e, $f6, $c9, $a3, $fd, $5e, $4f, $9d, $8f, $e1, $eb, $ad, $50, $1b, $0b, $b3, $a9, $2f, $bc, $cb, $cd, $04, $20
    // [197] "The chest is trapped!" (22→13 bytes)
    .byte $c7, $97, $de, $65, $e6, $97, $27, $50, $1b, $0c, $3d, $62, $10
    // [198] "A small needle has pricked you!" (32→19 bytes)
    .byte $89, $53, $55, $a1, $0b, $3f, $f5, $c3, $ec, $98, $ee, $01, $9e, $63, $7a, $eb, $9b, $d1, $08
    // [199] "You feel weakened!" (19→11 bytes)
    .byte $1e, $f6, $f1, $ff, $0a, $2f, $b4, $6f, $9f, $ac, $42
    // [200] "A puff of yellow gas surrounds you!" (36→22 bytes)
    .byte $89, $5c, $3b, $c7, $17, $78, $ae, $7c, $21, $a2, $d7, $58, $e9, $f4, $03, $7b, $35, $9d, $73, $7a, $21, $00
    // [201] "You are unaffected." (20→12 bytes)
    .byte $1e, $f6, $b0, $7d, $ec, $db, $8e, $3f, $94, $f5, $bc, $80
    // [202] "You choke and pass out." (24→14 bytes)
    .byte $1e, $f6, $f3, $2d, $8d, $f5, $a6, $bb, $83, $19, $dd, $ea, $3c, $80
    // [203] "There is a sudden explosion!" (29→17 bytes)
    .byte $c7, $97, $87, $dc, $9d, $6a, $7d, $5a, $fe, $77, $f1, $ae, $10, $d3, $ce, $cc, $42
    // [204] "You have picked the lock." (26→16 bytes)
    .byte $1e, $f6, $c9, $a3, $fd, $c3, $3c, $c6, $f5, $d4, $97, $d8, $6f, $31, $9e, $40
    // [205] "You are too confused to pick the lock." (39→22 bytes)
    .byte $1e, $f6, $b0, $7d, $4d, $db, $ce, $cf, $8e, $9f, $ae, $a6, $dc, $33, $cc, $6a, $92, $fb, $0d, $e6, $33, $c8
    // [206] "You failed to pick the lock." (29→17 bytes)
    .byte $1e, $f6, $f0, $d9, $87, $ae, $a6, $dc, $33, $cc, $6a, $92, $fb, $0d, $e6, $33, $c8
    // [207] "a poison needle." (17→10 bytes)
    .byte $6b, $86, $e4, $f6, $76, $7f, $eb, $87, $bc, $80
    // [208] "an exploding chest." (20→13 bytes)
    .byte $69, $df, $c6, $b8, $43, $57, $99, $bb, $79, $97, $9a, $3c, $80
    // [209] "I don't see a trap..." (22→13 bytes)
    .byte $c6, $6a, $f6, $78, $ba, $53, $ff, $ad, $50, $1b, $07, $bd, $e4
    // [210] "The chest was not trapped." (27→16 bytes)
    .byte $c7, $97, $de, $65, $e6, $94, $56, $3b, $3d, $4a, $80, $d8, $61, $eb, $79, $00
    // [211] "You have disarmed the chest." (29→16 bytes)
    .byte $1e, $f6, $c9, $a3, $fd, $5e, $4d, $81, $5f, $5d, $49, $7d, $e6, $5e, $68, $f2
    // [212] "You failed to disarm the chest." (32→18 bytes)
    .byte $1e, $f6, $f0, $d9, $87, $ae, $a6, $d5, $e4, $d8, $15, $a9, $2f, $bc, $cb, $cd, $1e, $40
    // [213] "You set a trap off!" (20→11 bytes)
    .byte $1e, $f6, $9f, $a5, $6a, $80, $d8, $5d, $e3, $81, $08
    // [214] "You have destroyed the chest..." (32→18 bytes)
    .byte $1e, $f6, $c9, $a3, $fd, $5f, $9a, $06, $b9, $eb, $a9, $2f, $bc, $cb, $cd, $1e, $f7, $90
    // [215] "and it's contents!" (19→12 bytes)
    .byte $69, $ae, $e5, $31, $73, $bc, $ec, $d3, $e6, $86, $21, $00
    // [216] "The lock breaks open!" (22→14 bytes)
    .byte $c7, $97, $d8, $6f, $31, $ac, $50, $f6, $8c, $77, $70, $f9, $88, $40
    // [217] "The chest holds firm." (22→13 bytes)
    .byte $c7, $97, $de, $65, $e6, $96, $5b, $05, $9d, $e3, $20, $ab, $c8

// Huffman code table:
//   NULL   =         0010 (4 bits, freq=218)
//   a      =         0110 (4 bits, freq=266)
//   b      =      1000101 (7 bits, freq=38)
//   c      =       111001 (6 bits, freq=97)
//   d      =        01011 (5 bits, freq=123)
//   e      =         1111 (4 bits, freq=407)
//   f      =       111000 (6 bits, freq=96)
//   g      =       011101 (6 bits, freq=68)
//   h      =        10010 (5 bits, freq=160)
//   i      =        11001 (5 bits, freq=180)
//   j      = 100010000110 (12 bits, freq=1)
//   k      =      1000110 (7 bits, freq=41)
//   l      =        10000 (5 bits, freq=150)
//   m      =       010101 (6 bits, freq=60)
//   n      =        10011 (5 bits, freq=174)
//   o      =         1101 (4 bits, freq=375)
//   p      =       110000 (6 bits, freq=85)
//   q      = 100010000101 (12 bits, freq=1)
//   r      =         0000 (4 bits, freq=201)
//   s      =         0011 (4 bits, freq=218)
//   t      =         0100 (4 bits, freq=220)
//   u      =        11101 (5 bits, freq=196)
//   v      =      1000111 (7 bits, freq=42)
//   w      =       000101 (6 bits, freq=52)
//   x      =  11000110101 (11 bits, freq=3)
//   y      =       011100 (6 bits, freq=61)
//   z      =   1100011011 (10 bits, freq=6)
//   SPACE  =          101 (3 bits, freq=664)
//   $21    =       000100 (6 bits, freq=51)
//   $27    =   1100010111 (10 bits, freq=6)
//   $28    =     01010010 (8 bits, freq=14)
//   $29    =     01010001 (8 bits, freq=14)
//   $2c    =    010100001 (9 bits, freq=7)
//   $2d    =     01010011 (8 bits, freq=15)
//   $2e    =        01111 (5 bits, freq=137)
//   $2f    = 100010000000 (12 bits, freq=1)
//   $38    = 100010000010 (12 bits, freq=1)
//   $3f    =     11000100 (8 bits, freq=21)
//   A      =    100010010 (9 bits, freq=8)
//   C      =  11000110100 (11 bits, freq=3)
//   D      =    010100000 (9 bits, freq=7)
//   E      =  10001000110 (11 bits, freq=2)
//   G      = 100010000100 (12 bits, freq=1)
//   H      =  10001000101 (11 bits, freq=2)
//   I      =   1100011001 (10 bits, freq=6)
//   L      = 100010000011 (12 bits, freq=1)
//   M      =  10001000111 (11 bits, freq=2)
//   N      =    110001010 (9 bits, freq=11)
//   O      = 100010000001 (12 bits, freq=1)
//   P      =  11000101100 (11 bits, freq=2)
//   Q      = 100010000111 (12 bits, freq=1)
//   R      =  11000101101 (11 bits, freq=3)
//   S      =    100010011 (9 bits, freq=10)
//   T      =     11000111 (8 bits, freq=25)
//   U      =  10001000100 (11 bits, freq=2)
//   W      =   1100011000 (10 bits, freq=6)
//   Y      =        00011 (5 bits, freq=107)
